### ISSUE TITLE
Cannot fork on github

### ISSUE THREAD

**Issue by adlbtt** [git/git-scm.com#1000]
Hej,

I am unable to fork repository on the Github. Whne I press the "Fork"button nothing happen. Could you please help about that? Is it a technical problem with Github?

MVH
Adl

**Comment by sxlijin** [comment]
Perhaps you have Javascript disabled? Or you've already forked the repo (although in that case a window appears showing you where you've forked the repo already).

No matter what the issue, though, we can't help you with that; that's an issue for GitHub itself.

**Comment by adlbtt** [comment]
I checked, neither JavaScript was disabled nor I can see the that repo is forked.

Could you tell me how I gonna contact to Gtihub to solve the issue?

**Comment by sxlijin** [comment]
https://github.com/contact
