### ISSUE TITLE
Rails does not complain if no ElasticSearch instance is running

### ISSUE THREAD

**Issue by sxlijin** [git/git-scm.com#1001]
It just silently 200's out, even if there's nothing responding.

**Comment by pedrorijo91** [comment]
can you just clarify/give some more details, in case some external contributor wants to pick this issue? (what is ES? the spanish locale? ES6?)

**Comment by dscho** [comment]
After #1804 was merged, this ticket can be closed, correct?

**Comment by To1ne** [comment]
> After https://github.com/git/git-scm.com/pull/1804 was merged, this ticket can be closed, correct?

@dscho I'd say we can!
