### ISSUE TITLE
Error while git commit

### ISSUE THREAD

**Issue by ari7it** [git/git-scm.com#1002]
Hello,
I am trying to commit few files after adding them in git, but am getting an error I have not seen before. Everybody else have been able to use the same git clone link but it isnt working on my laptop.

The error is : Your machine is not correctly configured to use GIT - please contact SCS team for further instructions

Any help is appreciated. Thanks.

**Comment by pedrorijo91** [comment]
Hey @ari7it,

As you can see through the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this is not the repository to report problems using git. You should try to find help through the [dedicated channels](https://git-scm.com/community)

Hint: provide information if you can run other git commands, the platform you are using (windows, mac, some linux distro?), and the output of `git --version`
