### ISSUE TITLE
git-stash - misleading examples

### ISSUE THREAD

**Issue by Solder-Soldier** [git/git-scm.com#1003]
Some of the example commands in git-stash documentation should be written as comments rather than actual commands:
![2017-05-25 21_15_55-git - git-stash documentation](https://cloud.githubusercontent.com/assets/24915363/26444394/5cf6a754-4190-11e7-845e-135288c8916e.png)

For example, `$ edit emergency fix` should be `# ... edit emergency fix ...` like the other comments in the section.

More like this:
![2017-05-25` 21_14_37-git - git-stash documentation fixed](https://cloud.githubusercontent.com/assets/24915363/26444395/5cf6db7a-4190-11e7-97fd-8981c5a90542.png)

It could be misleading for novices.

**Comment by pedrorijo91** [comment]
Hey @Solder-Soldier,

While I do agree with your suggestion, those pages are extracted from the git documentation itself (type `git stash --help` and you'll see the same issue). 

As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), these kind of issues should be raised with the [community](https://git-scm.com/community). Can I ask you to report on the appropriate channel (the mailing list)?

Thanks for the contribution nevertheless!

**Comment by Solder-Soldier** [comment]
I see. Sorry for the bother.
Will do.
