### ISSUE TITLE
git rm submodule section seems to be inconsistent with current behavior

### ISSUE THREAD

**Issue by daixtrose** [git/git-scm.com#1009]
The [section about submodules](https://git-scm.com/docs/git-rm#_submodules) states
> Only submodules using a gitfile (which means they were cloned with a Git version 1.7.8 or newer) will be removed from the work tree, as their repository lives inside the .git directory of the superproject. If a submodule [...] still uses a .git directory, ...

I am using newer git versions like e.g. `git version 2.10.2.windows.1` and find that I cannot see any gitfile, but the submodules still use `.git` directories. I understand the cited text such that git versions beyond 1.7.8 rather use gitfile that `.git`. So I am confused. 

In general `git submodules` has undergone so much changes by now that any decent Google search points to outdated information and probably unnecessary command sequences, especially for removing a submodule. Both, book and website might profit from some clarification.

**Comment by pedrorijo91** [comment]
Hey @daixtrose 

Thanks for the time to reporting your issue. Nevertheless I think the issue doesn't fit in this repository: As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), issues in the docs pages should be raised in the [community](https://git-scm.com/community) as they are generated from git man pages itself.

If you think it's a git-windows problem, try to report the problem in the [git-for-windows/git](https://github.com/git-for-windows/git) repository

**Comment by daixtrose** [comment]
Oops! I overlooked that line in the template. I Should have read the template more carefully. Close here.
