### ISSUE TITLE
App down

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#1010]
Application seems to be down at this moment on https://git-scm.com/docs/git-tree, with heroku message:

"Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details."

Not sure if @peff is doing any maintenance or how to debug the problem

**Comment by pedrorijo91** [comment]
![image](https://user-images.githubusercontent.com/1999050/28273415-413c585c-6b06-11e7-821a-faf6e128a890.png)

**Comment by pedrorijo91** [comment]
On https://git-scm.com/docs/git-tree

**Comment by peff** [comment]
Seems fine now? There is no `git-tree`, of course, so it redirects back to the original page. I wasn't doing any maintenance and haven't touche the site recently. Heroku blip, maybe?

**Comment by pedrorijo91** [comment]
Sorry, it was https://git-scm.com/docs/git-commit-tree which was having the problem. Maybe it was just heroku, since it seems to be working just fine now

**Comment by peff** [comment]
We're often running close to the memory limits of the Heroku VM. I think that mostly just pushes us into swap, but it's possible that it resulted in a page request failing (especially a page that wasn't likely to be in the cloudflare cache, like `commit-tree`). I suspect we could do some work to reduce memory usage in the VM. I've poked at it but I'm not familiar enough with ruby/rails to have made much headway.
