### ISSUE TITLE
git clone failed and give me that error

### ISSUE THREAD

**Issue by yehia67** [git/git-scm.com#1015]
while cloning any repo it give me that error:"
Cloning into 'checker-framework'...
remote: Counting objects: 143085, done.
remote: Compressing objects: 100% (19/19), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by yehia67** [comment]
![screenshot from 2017-08-08 15-34-01](https://user-images.githubusercontent.com/21314724/29079153-ae2a1618-7c5c-11e7-93a1-bb9868e4a7f1.png)

**Comment by pedrorijo91** [comment]
Hey @yehia67,

As you can see from the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md) this is probably not the best place to report your problem. 

You should try to raise the issue with the [community](https://git-scm.com/community)

Thanks for your contribution!

Let us know if you need any help reporting it
