### ISSUE TITLE
Chinese typo

### ISSUE THREAD

**Issue by ljporljp** [git/git-scm.com#1017]
the url  :
https://git-scm.com/book/zh/v2/Git-%E5%B7%A5%E5%85%B7-%E5%AD%90%E6%A8%A1%E5%9D%97

![1503630247 1](https://user-images.githubusercontent.com/5728237/29698031-36ab24b6-8985-11e7-90df-5369b367382b.jpg)

should be "该配置文件"

**Comment by sxlijin** [comment]
Thanks for mentioning this!

Unfortunately this is not the right repo to fix that: the correct repo is
progit/progit2-zh (https://github.com/progit/progit2-zh). Glancing at it, I
think you should be able to submit a PR that directly fixes this (:

**Comment by ljporljp** [comment]
Oh,sorry,but thank you to point the real repo,I can submit a PR to that.
