### ISSUE TITLE
Git-2.14.1-64-bit.exe Git Bash link incorrect

### ISSUE THREAD

**Issue by DevinCook** [git/git-scm.com#1021]
The Git Bash link in Windows 10 is pointing to "C:\Program Files\Git\git-bash.exe" which doesn't exist.  I believe the path should be "C:\Program Files\Git\bin\bash,exe".  

Same issue in the registry for "Git Bash Here".

**Comment by sxlijin** [comment]
This sounds like an issue that should be opened with the [Git for Windows](https://github.com/git-for-windows/git/issues) project, as the issue template stated. Closed unless I'm wrong.
