### ISSUE TITLE
read-tree documentation incorrectly compiled

### ISSUE THREAD

**Issue by me-and** [git/git-scm.com#1023]
This __is__ a problem with the documentation, but the problem is specific to git-scm.com's compiled man pages, and doesn't appear in the upstream compiled man pages, so I'm reporting it here since I assume upstream can't fix the compilation processes used for this site.

Specifically, the first `<pre>` formatted block in the "Two Tree Merge" section of the [git-scm.com read-tree man page](https://git-scm.com/docs/git-read-tree#_two_tree_merge) has lost the whitespace at the start of the string.  The whitespace appears correctly in my locally compiled version of the HTML man pages.

Compare the below from git-scm.com, where the headers are misaligned:

![git-scm bad table](https://user-images.githubusercontent.com/1397507/30741862-897bcc62-9f8e-11e7-9263-e5b8b6faaabf.png)

with the below from my local compiled version of the HTML man page:

![correct read-tree](https://user-images.githubusercontent.com/1397507/30741902-b1681f1e-9f8e-11e7-910c-bf6fd9956580.png)

Both versions of this man page are from Git v2.13.1, and I'm seeing this behaviour with Google Chrome 60.0.3112.113.

**Comment by jnavila** [comment]
Ah. This is a case where asciidoc and asciidoctor diverge in the interpretation of the formatting of the verbatim paragraph.

asciidoc realigns all the lines of the paragraph to the lines where the indentation is the smallest, whereas asciidoctor seems to specialize the first line. Is this a case for #928 ?

**Comment by peff** [comment]
@jnavila No, #928 won't fix it. We're already in compat mode because of the way the top-level title is formatted (but I also double-checked that setting compat-mode explicitly doesn't help).

**Comment by peff** [comment]
@me-and Thanks for the report. This definitely _is_ the right place to report formatting hiccups with the upstream manpages.

I think in this case the best workaround is fixing the source. I just sent [a patch](https://public-inbox.org/git/20170923055526.audcysedpxdst6tm@sigill.intra.peff.net/) to the list that should improve things.

The site won't be updated until upstream picks up the patch, of course. But I'm going to close this out as I don't think there's anything to be done here. I'd love some asciidoctor compat workaround in the meantime, as I wouldn't be surprised if there are other instances of the same problem. But I don't see any solution on the git-scm.com side short of munging the imported text (and I'm not sure how to recognize this situation, which leaves us with basically applying the upstream patch on the fly -- we could do that but it's a road I'd prefer not to go down if we know the real fix is coming eventually).
