### ISSUE TITLE
banners should be dismissable

### ISSUE THREAD

**Issue by peff** [git/git-scm.com#1028]
We sometimes put temporary banners at the top of git-scm.com pages (e.g., the survey banner in #846, the Conservancy banner in #641). After you've seen them for the millionth time, they can be visually annoying. It would be nice if there was a way to dismiss them (and optionally in a way that would persist between browser sessions).

More discussion in https://github.com/git/git-scm.com/issues/863.

**Comment by andrewhayward** [comment]
Assuming nobody's picked this issue up, I'm happy to tackle it.

**Comment by sxlijin** [comment]
Please feel free to! Pull requests are always welcome :)
