### ISSUE TITLE
Create rake task for populating man pages locally faster (picking just a few)

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#1032]
Following the [setup instructions](https://github.com/git/git-scm.com#setup) there's a rake task to populate the man pages. This task (`rake local_index`) will populate the man pages for **all** git versions, taking a lot of time (it's running for 20 mints and it's still on version 1.6.1.1).

Using `git branch` as an example, under https://git-scm.com/docs/git-branch/, there's not even an easy way to go to versions prior to 2.4.0 (I got to 1.5.1.1 version by replacing in the url)

Wouldn't make sense to make `rake local_index` just fetch a few versions to be faster, and create a new `rake local_index_full` that would fetch all the versions? Note that the `local_index_full` would probably need to know how to handle the case were the developer ran `local_index` previously but now it would need all the versions (probably replacing already existing versions)

I'm not fully aware, but I would say that omitting some versions shouldn't cause any major app problems, besides 404 eventually (and rarely I would say)

My suggestion would be to pick a few (let's say, latest 10/20 versions for git 2.x), and a few more to git 1.9.x

**Comment by pedrorijo91** [comment]
doesn't seem very hard, it may be a good Hacktoberfest candidate

**Comment by jnavila** [comment]
You can already select the version you want: 
```
$ GIT_REPO=<path to git repo> REBUILD_DOC=$VERSION rake local_index
```
This is more a matter of documenting this feature.
Plus, I'm actually rewriting this stuff, see #1027
