### ISSUE TITLE
‘Companies & Projects Using Git’ doesn’t make much sense any more

### ISSUE THREAD

**Issue by robinwhittleton** [git/git-scm.com#1059]
Maybe the ‘Companies & Projects Using Git’ section should just be removed? Everyone uses Git in some capacity or another at this point I would assume.

According to Fx dev tools on a fresh load this would save 178Kb of images from the total site size.

I’ll happily do a PR, but this feels like potentially a good first bug for someone else?

**Comment by sxlijin** [comment]
I would disagree. For us in the bubble, Git is nearly universal, but
outside it there are still far too many people relying on SVN. If these
people are ever to convince their management to switch to Git, I imagine
having a list such as that on our website would be a relatively persuasive
element.

**Comment by iyedb** [comment]
Hi! How can I get the company I work to appear in the ‘Companies & Projects Using Git' section? Can I do pull request for that?

**Comment by pedrorijo91** [comment]
yes @iyedb. I don't know what's your company, but all the companies present currently are companies very well recognized.

**Comment by iyedb** [comment]
Thanks! The company I work for is a hugely popular (in France) tech French company and we use huge fans of git there. Can I make a pull request and have it appear on the web site for a while maybe?

**Comment by sxlijin** [comment]
Sure!

There isn't really any policy about what companies we list, mostly because
it's never been an issue :)

**Comment by iyedb** [comment]
Thanks guys. I will be submitting a pull request and link it to this issue then.

**Comment by pedrorijo91** [comment]
closing the issue as removing the section is not intended (can open again if it makes sense)
