### ISSUE TITLE
Use of symbol "|" in filepath causes error

### ISSUE THREAD

**Issue by jas99** [git/git-scm.com#1063]
Getting following error
OS: Windows 10
```
jas@LAPTOP-6909QVFH MINGW64 /d/repo/gist.github.com/93419be812de5782819b0c5939c18a5e (master)
$ git reset --hard
error: unable to create file snippets|javascript.json: Invalid argument
fatal: Could not reset index file to revision 'HEAD'.
```

**Comment by pedrorijo91** [comment]
Hey @jas99. Thanks for reporting the issue, but as [described in the issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md) this is not the repository to report git bugs. This repository is only for [git-scm.com website](https://git-scm.com/) related problems.

you probably want to report the issue at https://github.com/git-for-windows/git
