### ISSUE TITLE
You are fucking idiots !!!! 

### ISSUE THREAD

**Issue by kaizer1** [git/git-scm.com#1066]
git commit and how to dooooo ?????? 

 
![screen shot 2017-11-02 at 17 06 22](https://user-images.githubusercontent.com/5073933/32330158-4e72a992-bff0-11e7-9bfe-9e1f772c0f4a.png)

HOOWWWWW ?????  
How can I code the simplest example

**Comment by pedrorijo91** [comment]
Please, respect other developers @kaizer1

**Comment by kaizer1** [comment]
Fucked program ! 
  I'm typing in your tutorials 
 git init 
 git add . 
 git commit 
I get such a window and whore what's next? Disconnection
  THAT I did not click - everything is reset and everything can only be repeated at first !!!!

**Comment by kaizer1** [comment]
Thanks to everyone who will help me.

**Comment by kaizer1** [comment]
Ни одного нормально туторилала - который можно повторить чтобы всё получилось
