### ISSUE TITLE
submodule revision

### ISSUE THREAD

**Issue by ror6ax** [git/git-scm.com#1067]
Hi guys.

Currently git submodule only works with branch of the submodule in question. Adding a functionality to work with a revision would be great from my point of view.

Proposed syntax is as follows:
```git submodule add -r commit_sha git://some_repository.git```

Not raised this to the bug mailing list as this is not a bug, unsure is feature requests go in the same list or not.

Thanks!

**Comment by pedrorijo91** [comment]
Hey @ror6ax. Thanks for reporting the issue, but as described in the issue template this is not the repository to report git bugs. This repository is only for git-scm.com website related problems.

you probably want to report the issue with [the community](https://git-scm.com/community)

let us know if you need any other help

**Comment by sxlijin** [comment]
And to answer your original concern, yes, the git@vger.kernel.org mailing
list is the right place to raise feature requests (although if memory
serves me correctly, there should be a way to do what you're asking about).
