### ISSUE TITLE
Git consumes all memory - Mac

### ISSUE THREAD

**Issue by alancpazetto** [git/git-scm.com#1069]
Hi everyone.

I'm having a problem with Git in my computer, sometimes (about 2 in a day) that my computer sleep and wake up, the three git process consume all computer memory.

Anybody knows what happens?

```
git version 2.13.6 (Apple Git-96)
```

![screen shot 2017-11-06 at 09 19 53](https://user-images.githubusercontent.com/180714/32454543-ab918c60-c306-11e7-8180-a37926fd30a0.png)

**Comment by pedrorijo91** [comment]
Hey @alancpazetto,

Thanks for reporting your issue, but as you may see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), issues about git should be reported to the [community](https://git-scm.com/community).

Nevertheless, you shouldn't have git processes running if you are not doing git commands.
