### ISSUE TITLE
Context menu not working on Windows

### ISSUE THREAD

**Issue by ivanjaros** [git/git-scm.com#1073]
About a year ago the context menu for "git gui here" and "git bash here" here stopped working. I thought it will get fixed but everytime I download new version it is still not working. So I have resorted to try and edit the windows registry manually but no matter what, I was not able to make it work.

So is this some weird bug only on my work station or is there a quickfix for it?

**Comment by pedrorijo91** [comment]
Hey @ivanjaros,

Thanks for reporting your issue, but as you may see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), issues about git on windows should be reported on the repository: https://github.com/git-for-windows/git
