### ISSUE TITLE
Adding GitDrive in gui section

### ISSUE THREAD

**Issue by iossoft** [git/git-scm.com#1074]
Hi, 
I am the author of GitDrive, I am very glad to see there will have a GUI section for mobile apps as [issue #694 ](https://github.com/git/git-scm.com/issues/694) suggested. GItDrive is an embedded git server and powerful git client specially designed for iOS, it implements Git smart transport protocol. Could you include this App in GUI section?  Thanks a lot!

Below are some description for the App:

The repository pushed from your PC to GitDrive will be automatically synced to iCloud. As a result, it turns the iOS device already in the palm of your hand into a Git-enabled mobile hard drive!

GitDrive also has powerful Git client functionality; whether you need to trace file versions, view branches and tags, or apply syntax coloring to source code; from viewing Markdown files, to checking PDF, Word, or the various types of image and audio-video files; it can get the job done! 

Main Features:
- Powerful Git Server supports Git Smart transfer protocol; supports access by 5-10 users concurrently (using iPad will increase concurrent user accessibility).
- Support for repository-based user authorization control.
- Shallow updates and cloning operations for the repository.
- Repository management; every repository update operation will be controlled by transaction; if the operation is interrupted, all data will be immediately rolled back, or automatically rolled back when App is re-started, reliable and dependable!
- iCloud repository syncing; no need to worry about data loss, because all repositories are backed up on the cloud!
- Graphical commit record; all branches are available at a glance.
- High-speed syntax coloring engine; supports syntax coloring for over 100 programming languages; will be updated periodically.
- GitHub integration; simple to search and clone GitHub repositories.

Link from Apple Store: https://itunes.apple.com/us/app/git-drive/id1215974700?ls=1&mt=8

**Comment by pedrorijo91** [comment]
Hey @iossoft,

I would recommend you to open a PR to this repository including your GUI client. There's already a PR waiting to be merged that adds the mobile sections at https://github.com/git/git-scm.com/pull/1072. You can use it to understand which changes you need to do in order to include the client

**Comment by iossoft** [comment]
Thanks, I will do that.

**Comment by iossoft** [comment]
I think I just need to change the content in file "resources/guis.yml" and add corresponding image files into the folder "images/guis/", I think I could only do that after you merge PR #1072 into the master branch, right?

**Comment by pedrorijo91** [comment]
yes, it should be something like that :) I also created an issue to create documentation for this at #1075 

you can start your PR from my branch also

**Comment by iossoft** [comment]
Ok, got it.

**Comment by pedrorijo91** [comment]
Made a draft of the instructions at https://github.com/pedrorijo91/git-scm.com/blob/66e2591f9637cf58d32102fcd0e230d23a6690a9/README.md#adding-new-gui @iossoft 

would love you to try following them and provide any feedback :)

**Comment by iossoft** [comment]
Sure, very detail document, working on that !

**Comment by pedrorijo91** [comment]
closing this issue @iossoft. Feel free to open a PR if you want. And let me know any feedback on the instructions
