### ISSUE TITLE
Error starting GIT - libcrypto.so not found

### ISSUE THREAD

**Issue by sollysj** [git/git-scm.com#1076]
-I’ve just installed git-2.3.7.15 for TNS/E on HP NonStop in OSS. When we try to start it up to configure it we get the following error:

/user/sollys: git
*** RLD ERROR ***: FileSystem Error 11: File /G/SYSTEM/ZDLL/libcrypto.so NOT Fou
nd
/bin/-sh: /bin/git: tdm_execve(): failed with unexpected error
pr_errno=(4022) pr_TPCerror=(75) pr_TPCdetail=(11)

I’m assuming this is due to the version I’ve installed being hardcoded to use OPENSSL. Is this the case?

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.

**Comment by peff** [comment]
It's actually HP NonStop. Most of the discussion for that port happens on the mailing list. See https://git-scm.com/community.
