### ISSUE TITLE
''git commit" and "git checkout -b" will block and no response with OS X 10.13.1 

### ISSUE THREAD

**Issue by seagull112373** [git/git-scm.com#1096]
When I run the command "git commit" and "git checkout -b xx" on OS X 10.13.1, it will block there and no response forever. But the other commands can run well on my machine, for example, git log, git pull, etc.  My git version is 2.15.0.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

If you need help with using git, you can ask the [community](https://git-scm.com/community)

**Comment by seagull112373** [comment]
Ok, Thanks!
