### ISSUE TITLE
new wiki

### ISSUE THREAD

**Issue by schacon** [git/git-scm.com#11]
the previous wiki was OK and a lot of people used it, but it's now dead due to k.org biting the bullet.

implement a new wiki interface and way to contribute super easily.

import the old wiki, too.

**Comment by sxlijin** [comment]
The current wiki isn't terribly active (and there's definitely outdated stuff there), but I think it does see periodic updates - last year's Git User survey is up there, for example. I think it's safe to mark this as closed.

**Comment by maxlazio** [comment]
Let's close it, enough time has passed :)
