### ISSUE TITLE
Navigation circles displayed incorrectly on devices with low pixel density

### ISSUE THREAD

**Issue by siliconforks** [git/git-scm.com#1103]
See the navigation section just above the main content in the screenshot below:

![non-retina](https://user-images.githubusercontent.com/1156399/34456750-91bc453e-ed75-11e7-9522-dda9f27f60f5.png)

This is presumably what they are supposed to look like (taken on an iPad with "Retina" display):

![retina](https://user-images.githubusercontent.com/1156399/34456756-c83af88a-ed75-11e7-81d2-fa49a188e0be.png)

**Comment by pedrorijo91** [comment]
reopen due to #1107
