### ISSUE TITLE
search covers only dynamic content

### ISSUE THREAD

**Issue by peff** [git/git-scm.com#1109]
We index the [book and manpage content](https://github.com/git/git-scm.com/blob/fef621c3762f65326b838943cbd58fc5109311f7/lib/tasks/search.rake#L9-L21) for the search feature, but not any of the static content. So searching for "trademark", for example, will not turn up the trademark page (nor will "downoad" find the download page, etc).

We probably could feed the static pages into the index, but I'm not sure of the details.

**Comment by pedrorijo91** [comment]
There are a few search related topics from a deprecated TODO file that should be considered when addressing this issue (https://github.com/git/git-scm.com/blob/2c4281d6bfd1fab54cf6f1c8a47318f3c49607f1/TODO.txt) :

  * weighting
    - weigh porcelain over plumbing
    - weigh by total views
  * add book content to search
  * add video shownotes to search
  * add stackoverflow to search
  * search internal pages, too


Probably a few can be discarded (adding stackoverflow to search seems an overkill for instance), but let's reflect on them when implementing

**Comment by cornel001** [comment]
Hi. What does the search in the upper right of the site? It always returns Sorry, no search matches no matter the browser used and what I search. It is a bug ? Thanks.

**Comment by pedrorijo91** [comment]
thanks for reporting @cornel001 , it seems like a bug. 

@peff I have a vague memory of we having a similar problem due to the ES instance being down?

**Comment by peff** [comment]
I never figured out the exact reason, but yes, a year or so ago the search database stopped working, which was solved by doing a `rake search_clear && rake search_index && rake search_index_book`. Unfortunately, that doesn't seem to work anymore, as the `tire` gem depends on an outdated `rest-client` (I get `KeyError: key not found: :ciphers`; some searching reveals that this is fixed in more recent versions).

The `tire` gem itself is deprecated. I suspect the right path forward is moving to a better supported elasticsearch client gem.

**Comment by pedrorijo91** [comment]
on the Tire [README](https://github.com/karmi/retire#tire) file they recommend to look at https://github.com/elastic/elasticsearch-rails

**Comment by dscho** [comment]
With the switch to Pagefind in #1804, this seems to be addressed. [Searching for "trademark"](https://git-scm.com/search/results?search=trademark&language=en) finds the "About - Trademark" page first.
