### ISSUE TITLE
The problem of wording

### ISSUE THREAD

**Issue by KiiTheSpark** [git/git-scm.com#1127]
There is a wording issue of the languages setting. Traditional Chinese, which is named as 正體中文 in the website，might be regarded as a word about ideology. The suggestion is to replace it with 繁體中文.

**Comment by sxlijin** [comment]
Thanks for pointing this out. As best as I can tell, 正體中文 only appears in the "Full translations available in" list - @KiiTheSpark, is that consistent with your observation?

There are two places to fix this:
* https://github.com/git/git-scm.com/blob/master/app/views/doc/_translations.html.erb#L9
* https://github.com/git/git-scm.com/blob/master/app/views/books/_translations.html.erb#L9

Feel free to submit a PR to fix this.

**Comment by jnavila** [comment]
Not sure about this one. It seems highly political.

https://en.wikipedia.org/wiki/Traditional_Chinese_characters#Chinese_names

This is the translation for zh-tw, and they call it as it is written now.

**Comment by bigbuger** [comment]
I find the repository of translation for zh-tw.
https://github.com/progit/progit2-zh-tw
They use 繁體中文 in  README.

**Comment by peff** [comment]
I don't know enough to have an educated opinion, but it seems like we should follow whatever is preferred by the people doing the translation in progit/progit2-zh-tw (which implies making the change to match their README).
