### ISSUE TITLE
Unable to find update message again

### ISSUE THREAD

**Issue by gemal** [git/git-scm.com#1145]
On Windows I suddenly got a "Update available" message which is nice.
But I didn't click on it and then it just disappeared. Now it's impossible to find/see this message again.
The only way for me to update is to go to the website and download.

Cant these notification be added to the Windows 10 notification or somehow add a Check for Updates inthe Git GUI?

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

If you need help with using git, you can ask the [community](https://git-scm.com/community)

**Comment by pedrorijo91** [comment]
I would add that since this seems to be git for windows related, you should reach out https://github.com/git-for-windows/git as described in [the issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md)
