### ISSUE TITLE
Drop Git Book ed 1

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#1149]
as per discussed on #1140

**Comment by jasonlong** [comment]
I'm currently planning on ignoring v1 of the book with the new site design. Would someone else like to :fire: that version in a separate PR?

**Comment by pedrorijo91** [comment]
will try to look into this next week @jasonlong , but until there is certainly impossible

**Comment by peff** [comment]
There are a few translations that are _only_ done for v1, I think. But it has been long enough since v2 came out that I am OK with declaring those as stale and unmaintained. In particular, v1 does not receive any updates at this point.

**Comment by jnavila** [comment]
That needs to be reflected in the list of languages. Will submit a PR.

**Comment by jnavila** [comment]
How a PR would interact with other ongoing works?

**Comment by jasonlong** [comment]
@jnavila Do you mean in regards to the redesign work? If so, I wouldn't worry about that as I'll just merge in whatever changes you make and then figure out what differences exist w/ the new design to account for v2 being the only version.

**Comment by jnavila** [comment]
In fact the translations in V1 were already dropped. There is just the Slovene missing.

**Comment by dscho** [comment]
I believe that this has been addressed via #1274, almost 6 years ago.
