### ISSUE TITLE
Git pull would can change the world

### ISSUE THREAD

**Issue by codificate** [git/git-scm.com#1155]
This is **not** an issue about, it could be a new feature or the future:

I take this opportunity to share my idea with you, may be it is a ridiculous idea but is mine hahaha. I did been was thinking something that may be would be relative but so useful, and is it the following:

Think that when you execute a git pull or git fetch command, that will save in git server, the complete information about: who did that command request, and time when the request was executed, allowing keep all register between the times of work over repository, and that information would justify your hours worked for each task that you do. And be able to show metrics on the different tasks performed. Etc..

I understand that my idea would can be a misused tool, but it just an idea, and when someone of you taken it, would can work around fix it and improve it.

It is my humble idea for now. I hope you like it.

Regards,

**Comment by sxlijin** [comment]
@codificate thanks for the suggestion, but as the issue template shown to you when you opened this issue makes explicitly clear, this is not the appropriate forum for discussion of core Git. Please use the mailing list git@vger.kernel.org for that.
