### ISSUE TITLE
Doc about update hook must contain remark

### ISSUE THREAD

**Issue by ivanbogomoloff** [git/git-scm.com#1158]
Here https://git-scm.com/book/en/v2/Customizing-Git-An-Example-Git-Enforced-Policy

I think it must contain remark about git hook update when it is new branch.
oldrev will be 0 and hook will not work. And all commits will be passed.

https://stackoverflow.com/questions/3511057/git-receive-update-hooks-and-new-branches look at "right answer"

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the book [Pro Git](https://github.com/progit/progit2). Could you open an issue there?

Thanks.
