### ISSUE TITLE
git里运行node

### ISSUE THREAD

**Issue by yimidy** [git/git-scm.com#1161]
在git bash里运行node出错
![-1](https://user-images.githubusercontent.com/36751760/36930262-1e40a0ca-1ed8-11e8-9db0-ffddffd552e6.png)

1.git命令与C:\Users\用户名\AppDate\Rosming\npm里的uer文件有什么关系，而且该路径下并没有这个文件，它是在安装好的Git文件下有，
2.在git里运行node，出现error：cannot start node.exe:not found in PATH,可是我明明已经添加
3.环境变量path，PATH，有区别吗？

**Comment by pornpailin0328** [comment]
On issue

**Comment by pornpailin0328** [comment]
closed this issue 1 day ago

**Comment by pornpailin0328** [comment]
AppDate\Rosming\npm

**Comment by pornpailin0328** [comment]
error：cannot start node.exe:not found

**Comment by pornpailin0328** [comment]
path，PATH，

**Comment by pornpailin0328** [comment]
You’re receiving notifications because you commented.

**Comment by pedrorijo91** [comment]
if you have any problem be make sure you provide a detailed explanation @pornpailin0328 @yimidy, and please write it in english
