### ISSUE TITLE
Redesign individual manual pages

### ISSUE THREAD

**Issue by jasonlong** [git/git-scm.com#1162]

**Comment by jasonlong** [comment]
This should fix #1048 by not allowing the version dropdown to grow endlessly. New design has a `max-height` on the dropdown's contents and you can scroll to earlier versions if you like.

![dropdown](https://user-images.githubusercontent.com/6104/36992195-3454702a-2078-11e8-9d2a-90dda4cdf514.gif)

**Comment by pedrorijo91** [comment]
Feel free to close the other issue in favor of this one then :)

**Comment by jasonlong** [comment]
I've renamed this issue to refer to the individual manual pages themselves and not the top level landing page.

I'm marking this one complete. The layout should be responsive, all version dropdown has a `max-height` w/ scrollable contents, and `aria-labels` have been added (via JS for now) to all of the permalink anchors.

Example: https://git-scm-pr-1179.herokuapp.com/manuals/git-commit
