### ISSUE TITLE
Redesign homepage

### ISSUE THREAD

**Issue by jasonlong** [git/git-scm.com#1167]
Placeholder issue.

Probably remove company/project logos. /cc #595

**Comment by Meghana-12** [comment]
I'd like to be part of site modernization, if possible. Could you let me know if there is something I can contribute to? @jasonlong

**Comment by jasonlong** [comment]
@Meghana-12 The site redesign work hasn't really progressed since I haven't been able to allocate enough time to it. If/when this work picks back up, I can let you know about possible places to help.

**Comment by Meghana-12** [comment]
Sure, thank you so much!

**Comment by dscho** [comment]
With that 👍 I feel confident to close this issue.
