### ISSUE TITLE
Implement responsive search

### ISSUE THREAD

**Issue by jasonlong** [git/git-scm.com#1169]

**Comment by ABHINAV-JHA-27** [comment]
hey @jasonlong, is this issue still open?

**Comment by jasonlong** [comment]
@ABHINAV-JHA-27 I've been out of the loop for a while, but it looks like this was addressed in #1644. I'll leave it to @pedrorijo91 or @peff to confirm closing.

**Comment by pedrorijo91** [comment]
there's a major PR currently on-going, so i guess we should wait for it. see #1804

**Comment by dscho** [comment]
> it looks like this was addressed in [#1644](https://github.com/git/git-scm.com/pull/1644).

I am neither of the aforementioned people but I dare to confirm and close.
