### ISSUE TITLE
Don't run a node command in the git bash

### ISSUE THREAD

**Issue by yimidy** [git/git-scm.com#1170]
![-1](https://user-images.githubusercontent.com/36751760/37025722-6edf3be0-2167-11e8-8c61-f52d1bb42fc9.png)

1. The git command with the "C: \ Users \ username \ AppDate \ Rosming \ NPM" what is the relationship between usr file under this path, and this file is not present in the path, it is under the git installed files have
2. Run the node in the git, appear error: always start node. Exe: not found in the PATH, but I have been added, and restart the computer
3. The environment variable :path&&PATH, is there a difference?

**Comment by sxlijin** [comment]
It's very unclear what you're asking, but if you have questions about how to use Node with the MINGW/MSYS2 distro shipped with Git for Windows, you should probably either file an issue on git-for-windows/git or reach out to the MSYS2 community. This repo is for the Git *website*, not for anything else.
