### ISSUE TITLE
Add contribute link to ProGit translations

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#1178]
I was navigating through the site and on the book section I noticed there's no easy way to find how to contribute to translations.

For instance, imagine I know portuguese and I want to help translating https://git-scm.com/book/pt-br/v2. I have to find the link to https://github.com/progit/progit2 on the left bar, where it says `The source of this book is hosted on GitHub. Patches, suggestions and comments are welcome.` and then find on the organization the book for the language I want to help (and most repos don't even have a description to aid on this).

If we had (at the top?) something like "Want to help translating this book?" with the link to the correct repository, maybe we see an increasing number of contributions.

What do you think about including this one on the redesign @jasonlong ?

**Comment by jnavila** [comment]
The list of the languages for Progit is available at https://github.com/git/git-scm.com/blob/master/lib/tasks/book2.rake. With some changes, it could be used to generate the corresponding link for each language.

**Comment by jasonlong** [comment]
I haven't started the book section yet, but I was thinking it could be laid out similarly to the Manual. With that structure, we'd have a right sidebar with links to the various chapters so maybe we could have a link in the sidebar saying something like "Want to help with this Portuguese translation?".

**Comment by peff** [comment]
It may also be worth adding a mention of translations to the "About this site" page.

**Comment by antdog1982** [comment]
https://github.com/git/git-scm.com/pull/1265

**Comment by dscho** [comment]
Let's just close this, there has not been enough activity to merit keeping this ticket open.
