### ISSUE TITLE
gitk GUI doens't show diff view at bottom.

### ISSUE THREAD

**Issue by indigo-sam** [git/git-scm.com#1182]
Git: 2.16.2
Windows 64
It suppose to have the highlighted section but I don't see it in my GUI anymore. Anyone know if this is  a bug or an option that I can enable somewhere?

![image](https://user-images.githubusercontent.com/20443379/37419099-fa74a8d4-2770-11e8-9074-a41dcc61a21f.png)

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
