### ISSUE TITLE
Redesign book pages

### ISSUE THREAD

**Issue by jasonlong** [git/git-scm.com#1185]

**Comment by jasonlong** [comment]
This is mostly done in #1179. The one remaining task I'd like to do is update the styling of the navigation at the bottom of each page.

![image](https://user-images.githubusercontent.com/6104/48445386-7629d900-e764-11e8-876d-229d1965c1ae.png)

But this unfortunately requires a change to a rake task and regeneration of all books.
https://github.com/git/git-scm.com/blob/master/lib/tasks/book2.rake#L35

![screen shot 2018-11-13 at 4 48 45 pm](https://user-images.githubusercontent.com/6104/48445247-192e2300-e764-11e8-96df-541a6a5f36d5.png)

![screen shot 2018-11-13 at 4 50 00 pm](https://user-images.githubusercontent.com/6104/48445276-2e0ab680-e764-11e8-9a39-c2e2cac9dede.png)

**Comment by jasonlong** [comment]
I'm wondering if it would make sense to make a copy of the production db and point this branch to that one. Then we could make these sorts of generated content changes w/o worrying about prod and then we could just make the new copy the production db when we ship this redesign. Thoughts?

**Comment by jasonlong** [comment]
Also, note that the design for the [book landing page](https://git-scm-pr-1179.herokuapp.com/book/en/v2.) has not been updated yet.

**Comment by peff** [comment]
I'm not opposed to copying the production db, though right now it really only matters for test deploys to Heroku, I guess. I don't really know what that entails on the Heroku side, as far as configuring the review apps to use the alternate database.

What's our end-game deployment plan here? I had figured that we'd mostly be viewing it locally (and freely blowing away and rebuilding the database content), and then we'd eventually have a flag day where we merge and deploy #1179 and just rebuild everything from scratch.

**Comment by jasonlong** [comment]
@peff My main reasoning for having a db for the redesign is so that we are free to update the generated content w/o affecting production. For example, the nav at the bottom of each page [has been updated](https://github.com/git/git-scm.com/blob/50be18d10ed9af6ece5d688fc2b1c211692fb642/lib/tasks/book2.rake#L35-L49) in the `.rake` file but that part of the design won't be visible until we regenerate all of the books.

**Comment by jasonlong** [comment]
I'm going to close this as the work is done, but I'd still be interested in exploring using a staging db where we can have regenerated book content with the new nav links at the bottom.

**Comment by peff** [comment]
Right, I guess my question was: how often are we using the staging environment? It seems like I usually have to kick it to even get it to run. If we're going to have a test period where we run both, then for sure I think we should have an alternate db. But I'm not sure it's a high priority right now.

**Comment by jasonlong** [comment]
@peff We're already running both environments aren't we? With #1179, we're back to updating the staging URL with every push to that branch. The staging env dies off if the pushes don't happen enough, but it's still the known URL where anyone can go to see the progress until we're finished with the updates.
