### ISSUE TITLE
Redesign Manual landing page

### ISSUE THREAD

**Issue by jasonlong** [git/git-scm.com#1186]
I'm hoping we can keep this simple and expose all of the man pages plus some useful jumping off links.

Placeholder here: https://git-scm-pr-1179.herokuapp.com/manual

**Comment by sxlijin** [comment]
We've got analytics floating around somewhere that I bet would be super helpful for this.

**Comment by sxlijin** [comment]
Hmmmm. Maybe it might make sense to categorize the commands?

I feel like in addition to basic workflow, rebase/reset/diff/log kinda fall into a "have a repo, trying to do X" category (and submodule/stash/fetch *kinda* fit here too).

Also worth noting, an alphabetic sort might be useful. Not sure if it's the best idea, but the first time I looked at that list I wasn't really sure how to browse it.

**Comment by jasonlong** [comment]
I started brainstorming ways of grouping the commands and kept coming back to the fact that we already have the commands organized in categories.

Here's another idea. We could expand out the existing categories w/ their one-line summaries (responsive version TBD) and then indicate the more popular pages with a star or something.

![screen shot 2018-03-19 at 4 16 28 pm](https://user-images.githubusercontent.com/6104/37619948-426d1666-2b91-11e8-9e1d-3015f401bbaf.png)

**Comment by peff** [comment]
I like that direction. You can still use the categories to find what you're looking for, or if you don't know the category, you can skim for stars.

It would probably make sense to keep the stars for each category grouped at the top, and probably make the non-starred ones smaller (e.g., by not including their one-line summaries).

**Comment by pedrorijo91** [comment]
just as @peff, I really like this version. But I would prefer to keep the one-line summaries in all the commands just for consistency. I think the star icon is enough to give the headlight

**Comment by peff** [comment]
My concern with the one-line summaries for all is just that it becomes hard to scan the list looking for "starred" entries. But I'm happy to punt on that until we see the final design and live with it for a while.

**Comment by jnavila** [comment]
Wouldn't the stars be more useful if put on categories where all the commands are common? Here it seems like despite their commonness, they are scattered in the page.

**Comment by jasonlong** [comment]
FWIW, based on the list from GA [above](https://github.com/git/git-scm.com/issues/1186#issuecomment-373373897), the most-frequented pages are indeed scattered over the page. I imagine this is from a mix of newer users looking at basic commands + more experienced users referring to harder to remember commands.

**Comment by sxlijin** [comment]
This kind of ties into an idea that's been bouncing around my head: it would be great to announce this somewhere and collect user feedback, e.g. /r/git, maybe /r/programming, lobste.rs, HN, etc., so that we have opinions from people who *aren't* Git contributors.

**Comment by peff** [comment]
I do think it's a good idea to get some outside feedback. I'm a little worried about having to sort through an influx of input with low signal/noise ratio (I don't mean to imply that the feedback will be low quality, but that we'll get a lot of "you should do this one specific thing" without very much overlap, some of which are bound to conflict, and sorting and organizing the suggestions will be a task in itself).

**Comment by dscho** [comment]
Since nobody has been working on thi, in over three years, maybe we should close this ticket?

Should someone show up willing to drive this improvement, we could easily reopen it.

**Comment by dscho** [comment]
Let's just close this.
