### ISSUE TITLE
make progit in text-format accessible on the site?

### ISSUE THREAD

**Issue by utonsal** [git/git-scm.com#1189]
I read following notice:
"
   - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
"

I miss a non-graphical version of the ProGit -book on the site. Would you upload such a version, if there was one?
greetings,
utonsal

**Comment by pedrorijo91** [comment]
hey @utonsal.

At https://git-scm.com/book/en/v2 there are many book formats available (pdf, epub, mobi) and the HTML version (by clicking on the chapters). None of these versions work for you?

Still, I guess we could include the non-graphical version. This should be considered in #1185

**Comment by utonsal** [comment]
well,
i don't want to be forced having graphics on my computer. Even if i at
the moment do have it and could read pdf.

html could be alright.


Am 20.03.2018 um 11:33 schrieb Pedro Rijo:
> hey @utonsal.
> 
> At https://git-scm.com/book/en/v2 there are many book formats available (pdf, epub, mobi) and the HTML version (by clicking on the chapters). None of these versions work for you?
> 
> Still, I guess we could include the non-graphical version. This should be considered in #1185 
>

**Comment by utonsal** [comment]
a related question:
who actually does the job of building the actual progit-formats, and by
whom are they then uploaded on git-scm.com?

**Comment by jnavila** [comment]
"I miss a non-graphical version of the ProGit -book on the site": What do you mean by "non-graphical"?

The books are compiled automatically from the source projects on GitHub and uploaded in the release section of projects.

**Comment by utonsal** [comment]
Am 20.03.2018 um 15:06 schrieb Jean-Noël Avila:
> "I miss a non-graphical version of the ProGit -book on the site": What do you mean by "non-graphical"?

I mean, that you are able to read the book without having X or something
graphical like this installed.

> 
> The books are compiled automatically from the source projects on GitHub and uploaded in the release section of projects.
> 
The text format from the sources is '.asc'. It would associate 'ascii'
with this ending, but it looks formatted.

Does somebody know how to transform these different chapters in
.asc-format into one single text-file?

greetings,
kalle

**Comment by jnavila** [comment]
Ok, this is more a question to be asked at https://github.com/progit/progit2 .

The source text is in fact in [asciidoc format](http://www.methods.co.nz/asciidoc/) and we're using [asciidoctor](https://www.asciidoctor.org) to make the conversion to other formats. The asciidoc format is supposedly quite readable as is.

What we have more approaching is to target a pure html output that you could render in text using w3m or links. See https://github.com/asciidoctor/asciidoctor/issues/1636 for a discussion about your options. As for Pro Git, apart from the text, I'm not sure the text replacement for the images are helpful.

**Comment by utonsal** [comment]
Am 23.03.2018 um 23:01 schrieb Jean-Noël Avila:
> What we have more approaching is to target a pure html output that you could render in text using w3m or links. See https://github.com/asciidoctor/asciidoctor/issues/1636 for a discussion about your options. As for Pro Git, apart from the text, I'm not sure the text replacement for the images are helpful.

that would be fine.

**Comment by pedrorijo91** [comment]
I think this issue can be closed as it is being followed on https://github.com/progit/progit2/issues/1030 @jnavila ?

**Comment by jnavila** [comment]
Yes, let's close it. Even a progit/progit2, I don't think anybody will pour effort in it.
