### ISSUE TITLE
Download link for version 2.17.0?

### ISSUE THREAD

**Issue by ItsPugle** [git/git-scm.com#1193]
Since the release of Git 2.17.0, how come [git-scm.com](https://git-scm.com) still advertises the 2.16.3 download for macOS? Especially since you can update to 2.17.0.

Is their some sort of hold up in having this released? 

![Advertising An Old Version](https://rpl.cat/uploads/KhVSewfBRKYCCSd_iWwUUOZq3a6hllGewoLkr8_MisM/public.png)

- [x] This is **not** an issue about 
     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).

**Comment by ItsPugle** [comment]
Hey @pedrorijo91, thanks for the reply! That all makes sense 😄 Any idea when the new bundle will be deployed, allowing the website to update?

**Comment by Tonchi** [comment]
[FILE.STENCIL]

**Comment by pedrorijo91** [comment]
no clue TBH @ItsPugle. You may try to open an issue on the repository associated (https://github.com/timcharper/git_osx_installer/issues), but it seems issues don't usually have a quick answer...
