### ISSUE TITLE
Git-Windows download page still points to 2.16.2

### ISSUE THREAD

**Issue by lll000111** [git/git-scm.com#1194]
The download page still lists 2.16.2 as the binary, but the 2.17 (Windows) git binary version has been available for quite some time now:

![image](https://user-images.githubusercontent.com/25476357/38979547-bf8d9418-43ba-11e8-8595-de86f126d38e.png)

**Comment by pedrorijo91** [comment]
I ran the rake task locally (as described at https://github.com/git/git-scm.com/blob/master/ARCHITECTURE.md#heroku) and the latest win version is 2.17.0

on heroku we have as last run: Apr 19, 7:31 UTC

**Comment by lll000111** [comment]
https://git-scm.com/download/win still offers 2.16.2 :-)

**Comment by pedrorijo91** [comment]
Been looking at this today. The versions and downloads were in the database, but there was some problem.

The query being executed to get the download url is:

```
SELECT  "versions".* FROM "versions"  ORDER BY versions.vorder DESC LIMIT 1
  SQL (2.4ms)  SELECT  "downloads"."id" AS t0_r0, "downloads"."url" AS t0_r1, "downloads"."filename" AS t0_r2, "downloads"."platform" AS t0_r3, "downloads"."version_id" AS t0_r4, "downloads"."created_at" AS t0_r5, "downloads"."updated_at" AS t0_r6, "downloads"."release_date" AS t0_r7, "versions"."id" AS t1_r0, "versions"."name" AS t1_r1, "versions"."commit_sha" AS t1_r2, "versions"."tree_sha" AS t1_r3, "versions"."committed" AS t1_r4, "versions"."created_at" AS t1_r5, "versions"."updated_at" AS t1_r6, "versions"."vorder" AS t1_r7 FROM "downloads" LEFT OUTER JOIN "versions" ON "versions"."id" = "downloads"."version_id" WHERE (platform='mac')  ORDER BY versions.vorder DESC, downloads.release_date DESC LIMIT 1
```

so probably some of the records had some corrupt/missing data that lead to the LEFT OUTER JOIN failing. 

I'm not proud of the solution, but the fastest way was to delete the downloads and versions table content and run the `rake downloads` task again. 

everything seems to be working now @lll000111
