### ISSUE TITLE
`iconv` should have the encoding `ISO646-SE2`

### ISSUE THREAD

**Issue by mobluse** [git/git-scm.com#1199]
I installed from `Git-2.16.2-64-bit.exe` from git-scm.com. I think `iconv` should have the encoding `ISO646-SE2`. Ubuntu 16.04 has this encoding. I use it to read old Swedish text files, e.g.: 
`curl -s https://www.abc.se/programbanken/abc/abc80/asmkod/basicii.txt | dos2unix | iconv -f ISO646-SE2 -t UTF8 | less`
`ISO646-SE2` is used by e.g. the computers Luxor [ABC80](https://en.wikipedia.org/wiki/ABC_80) and [ABC800](https://en.wikipedia.org/wiki/ABC_800)-series. At my university we only have Git Bash and not Ubuntu for WSL.

(Not clear where I should report this, but one should be able to report issues with the configuration of the other programs than `git` in the package somewhere. If there is a better place, please let me know.)

**Comment by pedrorijo91** [comment]
Hey @mobluse,

Thanks for reporting your issue.

As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

From what I understood from your description, I would say this fits into 'Git specific issues', which should be raised with the community (https://git-scm.com/community).

Let us know if we can help in anything else

**Comment by stefanbeller** [comment]
I think https://github.com/git-for-windows/git/issues/new is the correct place to report this as the bug report affects packaging in Git-for-windows, not directly core git?
