### ISSUE TITLE
Documentation links stuck in a recursive loop

### ISSUE THREAD

**Issue by hollenberry** [git/git-scm.com#1201]
Hey there!

It looks like specific documentation pages are broken:
![image](https://user-images.githubusercontent.com/13326548/39334574-089fda72-4964-11e8-817d-860de5c5cf29.png)

Example: https://git-scm.com/docs/git-reflog

I've tested this on:
- Chrome
- Brave
- Safari
- >5 of the links from the docs page
- A friend's machine

**Please make sure you are NOT reporting a problem about git itself**

- [x] This is **not** an issue about 
     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).

**Comment by hollenberry** [comment]
Looks like it works now! 

Thank you @pedrorijo91 !

**Comment by pedrorijo91** [comment]
you may not see the most current version of the docs yet, still running

**Comment by pedrorijo91** [comment]
everything should be working fine now
