### ISSUE TITLE
Incorrect PowerShell Syntax

### ISSUE THREAD

**Issue by danstur** [git/git-scm.com#1205]
At https://git-scm.com/book/en/v2/Git-Internals-Git-Objects there is a note stating that:

> In PowerShell or CMD on Windows, the ^ character is used for escaping, so you have to double it to avoid this: git cat-file -p master^^{tree}.

This is (presumably? no idea honestly) correct for CMD but is incorrect for PowerShell. ^ is not an escape character in PowerShell, \` is. What happens (to the best of my understanding) is that `{` causes PowerShell to interpret everything following until the closing `}` as a script block. Passing that script block to a executable causes the script block to be evaluated. Instead of getting a single parameter "master^{tree}", the executable receives two parameters "master^" and "tree". 

Consequently the proposed solution doesn't work:
```
> git cat-file -p master^{tree}
error: switch `e' : incompatible with -p
[...]
> git cat-file -p master^^{tree}
error: switch `e' : incompatible with -p
[...]
```

Two possible solutions to make the command work in PowerShell would be to pass the argument as a string (imo the preferred solution):
`> git cat-file -p 'master^{tree}' `
or to escape the {} characters:
```> git cat-file -p 'master^`{tree`}' ```

My proposed fix for the documentation would be something along the lines:

> In CMD on Windows, the ^ character is used for escaping, so you have to double it to avoid this: git cat-file -p master^^{tree}.
> 
> When using PowerShell parameters using {} characters have to be quoted to avoid the parameter being parsed incorrectly: git cat-file -p 'master^{tree}'

**Comment by pedrorijo91** [comment]
Hey @danstur,

Thanks for reporting this detail!

But as you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

book related issues (i.e. anything with a URL starting with https://git-scm.com/book or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).

Can you open the issue in the proper repository?  (https://github.com/progit/progit2/issues)

Thanks a lot!

**Comment by danstur** [comment]
My apologies for ignoring the template.. [Issue in proper repo](https://github.com/progit/progit2/issues/1047)

**Comment by pedrorijo91** [comment]
thanks a lot! :D @danstur
