### ISSUE TITLE
Windows Download Button Text Discrepancy

### ISSUE THREAD

**Issue by noahleigh** [git/git-scm.com#1206]
**Please make sure you are NOT reporting a problem about git itself**

- [x] This is **not** an issue about 
     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).

Currently, the button shown for downloading the latest Windows release is showing the filename rather than the version has it has previously:

Previous (from archive.org) | Current | Expected
------------------------------|------------|--------
![web archive org_web_20180105024757_https___git-scm com_](https://user-images.githubusercontent.com/5957867/39665419-eb2fd2b2-5061-11e8-8493-34b1eb9c8d8f.png) | ![git-scm com_](https://user-images.githubusercontent.com/5957867/39665421-f02431be-5061-11e8-859e-a3dae36e646a.png) | ![git-scm com_ 1](https://user-images.githubusercontent.com/5957867/39665487-4659f496-5063-11e8-8423-cd7089a03323.png)

The DOM element where this information is stored shows a discrepancy between the format of the macOS version (semver) and the Windows version (filename):
```html
<span data-mac="2.16.3" data-win="Git-2.17.0-32-bit.exe" id="installer-version"></span>
```

Here is the Javascript that updates the button text based on that element:
https://github.com/git/git-scm.com/blob/7df7712cbe6970ca8a1f29c7cf70b0a6256dbf92/app/assets/javascripts/application.js#L58-L66
I believe the issue lies in this section of the `downloads_controller`, but I don't have a development version of this site to test changes:
https://github.com/git/git-scm.com/blob/0892d28ef34e03c9d4df20ac33f9c8d037a456ca/app/helpers/application_helper.rb#L32-L40

**Comment by pedrorijo91** [comment]
thanks a lot for the detailed report @noahleigh !

would you like to submit a PR with the fix? :)

**Comment by pedrorijo91** [comment]
I had a look on this. It seems the name of the git for windows released are extracted from the assets on the repository releases. For instance: https://github.com/git-for-windows/git/releases/tag/v2.17.0.windows.1

I think this issue was introduced a while ago when migrating the rake task logic into a rails service: https://github.com/git/git-scm.com/commit/0f4974ec4cfbf3c5c897b2c7e2357d23f1002fa0#diff-2426dabc6613c25dd009ffe7b4a91788
