### ISSUE TITLE
fast-export system requirements

### ISSUE THREAD

**Issue by rinu** [git/git-scm.com#1208]
https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git

In the section about migration from mercurial, it's asking me to use a tool called fast-export. This tool requires python 2.7.
Also, that tool is made for UNIX-like systems. It may work under Windows but it's not supported.

Both facts should be documented.

**Comment by pedrorijo91** [comment]
hey @rinu, and thanks for reporting the issue!

But as you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

book related issues (i.e. anything with a URL starting with https://git-scm.com/book or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
