### ISSUE TITLE
More GUI tools

### ISSUE THREAD

**Issue by inducer** [git/git-scm.com#121]
- [qgit](http://digilander.libero.it/mcostalba/)
- [giggle](https://live.gnome.org/giggle)

**Comment by sxlijin** [comment]
Bump @peff.

**Comment by peff** [comment]
I'm happy to add more GUI tools (and we've done so several times in the intervening years). It would need somebody to make sure that the projects are still active, and then open a PR. I'm going to close this as it sounds like these particular projects probably _aren't_ really active these days.
