### ISSUE TITLE
code injection with download from git-scm.com under link: 64-bit Git for Windows Setup

### ISSUE THREAD

**Issue by somestuff** [git/git-scm.com#1211]
Running windows 10 64-bit and firefox

Trying to download git from page https://git-scm.com/downloads link to windows and the file may or may not start downloading or I click the link on the following page, 64-bit Git for Windows Setup, in either case this issue is present. This issue seems not to exist with the portable version for windows.

There is an unexpected file that installs while the expected file downloads. This unexpected file installs to a location other than the customary downloads location. That unexpected file installs in firefox folder at location:
C:\Users\username\AppData\Local\Mozilla\Firefox\Profiles########.default\cache2\entries

The expected file, Git-2.17.0-64-bit.exe, downloads to the expected downloads location.

This unexpected file is in bit format and is named with a key that is unique every download.
This unexpected file installs regardless, whether or not I proceed with the download or cancel the download through the dialog box associated with the download. This observation I made on may 23 2018 while attempting to document this questionable download behavior.

Steps To Reproduce:
Using windows 10 64-bit and firefox latest version as of this writing, version firefox 60.0.1 (64-bit)

Document the contents of folder
C:\Users\username\AppData\Local\Mozilla\Firefox\Profiles########.default\cache2\entries

go to https://git-scm.com/download/win click link: 64-bit Git for Windows Setup

go back to folder
C:\Users\username\AppData\Local\Mozilla\Firefox\Profiles########.default\cache2\entries
and note the addition of the latest file by date entry or a comparison of the contents of this folder as it exist after the download against the contents of the folder prior to the download.

Impact

Possible the unexpected file runs on next start-up of the firefox browser.

**Comment by pedrorijo91** [comment]
Hey @somestuff !

Thanks for reporting this issue. But that location seems to be where firefox stores cached data to possibly speed up navigation. A quick google search led me to this post: https://support.mozilla.org/pt-BR/questions/1169456
