### ISSUE TITLE
Bug when cloning from ssh: 'remote-SSH' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by forReason** [git/git-scm.com#1219]
when trying a git clone through ssh such as: `git clone SSH://user@server/repository` the error appears:

![image](https://user-images.githubusercontent.com/12736950/41808971-0ec79b2e-76e6-11e8-9e43-38136369139e.png)

when trying to use `git --help remote-SSH` the following error appears:
![image](https://user-images.githubusercontent.com/12736950/41809003-82c88312-76e6-11e8-8761-65d14c8d8a10.png)

after a lot of trial and error I found out, that the command `git clone` was not working because I spelled the ´SSH´ in capital.
to show that the same command works with small letters:
![image](https://user-images.githubusercontent.com/12736950/41809298-9110477a-76eb-11e8-8d52-1a6da4a28e52.png)

For me as a ´normal user´ there was no visibility at all on why the command failed. The errormessage made it more confusing to me since i expected a module to be missing. A google search helped neither.

please make it work with capital letters too.

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

book related issues (i.e. anything with a URL starting with https://git-scm.com/book or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)

**Comment by peff** [comment]
I passed along the report to the mailing list. See https://public-inbox.org/git/20180624085622.GA28575@sigill.intra.peff.net/
