### ISSUE TITLE
Error of "Failed-Forbidden" while downloading GIT

### ISSUE THREAD

**Issue by Zaima6659** [git/git-scm.com#1222]
When i download the progit book or the Git itself, the download starts and after sometime it stops and its written under the download tab "Failed-Forbidden". Can anyone tell me how i can sort out this issue? I am using Win 10, 64 bit. Waiting for the solution asap.

**Comment by Zaima6659** [comment]
When i download the progit book or the Git itself, the download starts and after sometime it stops and its written under the download tab "Failed-Forbidden". Can anyone tell me how i can sort out this issue? I am using Win 10, 6 bit.

**Comment by Sicaine** [comment]
I tried and downloaded the book without issues;

What link do you exactly click?

**Comment by pedrorijo91** [comment]
it also works for me. can you try with another browser, another machine, and/or using incognito mode?

**Comment by Zaima6659** [comment]
I tried with Microsoft Edge browser, issue resolved. Thanks to both of you :)
