### ISSUE TITLE
git-2.18 win7 and win10 bug

### ISSUE THREAD

**Issue by EricBatty** [git/git-scm.com#1227]
hello,
    I found a memory leak bug in git-2.18.0 under windows7 and windows10.
   When I downloaded and installed git and started it, my memory would fill up instantly, causing my computer to crash.
  I hope the author can see the problem and respond to it.
 please!

**Comment by pedrorijo91** [comment]
Hey @EricBatty,

As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)

**Comment by EricBatty** [comment]
@pedrorijo91 Ok, I see.Thank you for your reply
