### ISSUE TITLE
Linux/Unix on the Download page

### ISSUE THREAD

**Issue by BracketMaster** [git/git-scm.com#1228]
Mac OS is Unix and should be included in the Linux/Unix download section in the Git Downloads page. In fact, git can be installed on MacOS via "$port install git". Port is a BSD based, Apple approved package manager for MacOs.

**Comment by pedrorijo91** [comment]
hey @BracketMaster,

Thanks for reporting this. This is very similar to a previous discussion:  https://github.com/git/git-scm.com/issues/377

I think the goal of that page is not to be 100% precise, but more to group the SO in relevant and useful groups for users navigating to that page. In that reasoning, there are 3 main/major groups: Windows, Linux/Unix, and Mac OS X (that could be grouped into Linux/Unix mas has so many users that it makes sense to make it a 'top group')

So, while not 100% technical correct, I think it's the best UX decision. Any thoughts you'd like to add on this decision @peff ?

**Comment by peff** [comment]
Right, I think the goal is not about deciding "what's unix", but about pointing people in the right direction. So the real question is: do people end up on the wrong page looking for information, and if so, can we point them from there to the right page?

I.e., it would make sense to me to do one or both of:

 - from the macOS page, mention other install mechanisms than the binary package. The main ones I know of are `brew`, and getting it bundled with XCode (I hadn't heard of `port`, but I am not a mac user, so if that's a common solution, it makes sense to mention it, too)

 - from the Linux/Unix page, mention macOS specifically as a platform that gets its own page. I think it's probably already there in the navbar, but it doesn't hurt to put it in the main list.

**Comment by pedrorijo91** [comment]
I think that may be something to consider on #1179 cc @jasonlong

**Comment by BracketMaster** [comment]
Alright. Alright. I hear you. I would like to mention that Mac OS comes with the latest version of git installed as of the OS release which is yearly, as most Linux distros do the same. I figure since the target audience of git users is developers of some sort, perhaps it is appropriate to at least point them to a package manager method of installation. I can add that in the future and make a pull request?

**Comment by pedrorijo91** [comment]
Hey @BracketMaster, are you still interested in contributing on this through a PR? :)

**Comment by BracketMaster** [comment]
Real busy rn with other stuff. But eventually yes. Thanks for asking.

**Comment by phil-blain** [comment]
I thought I'd add to the conversation just to mention that using [conda](https://conda.io/en/latest/index.html) is another great way to install Git, and works cross-platform, so I don't know if we want to feature that in the Downloads section...

 It's also very useful to install different, isolated versions of Git, e.g. to test for bugs and fixes across different versions, although that's not what the main audience of the Downloads page does I guess.
