### ISSUE TITLE
stash documentation issue.

### ISSUE THREAD

**Issue by nkrishnawat** [git/git-scm.com#1231]
The documentation of stash on git-scm.com says "Calling git stash without any arguments is equivalent to git stash push" which is not true and not same as what git documentation says when I use terminal help:
>git help stash

**Comment by pedrorijo91** [comment]
Hey @nkrishnawat 

thanks for reporting your issue, but it seems weird. The documentation on the git-scm website, it's extracted from the git man pages, so the information on https://git-scm.com/docs/git-stash should be the same that shows when you write `$ git stash --help`.

On my machine, both have the same content. Which git version are you using?

```
$ git --version
git version 2.17.0
```

**Comment by peff** [comment]
The manpages found on the site are built directly from the text in the main git repository, which is also what you see from `git help stash`. Presumably you have an older version of git locally; `git stash save` was deprecated in favor of `git stash push` in v2.16.

You can view the documentation for older versions of `git` by clicking the `Version X.Y.Z` link at the top of each manpage on git-scm.com. That will show you all the places where this particular page changed, and you can click through to a specific version (e.g., https://git-scm.com/docs/git-stash/2.14.0).
