### ISSUE TITLE
Cannot parse Git version string

### ISSUE THREAD

**Issue by whotired** [git/git-scm.com#1232]
I install git 2.18.0 and 64 bit for Windows 7. While clicking "Gig GUI here" and getting error: 
git-gui:fatal error
Cannot parse Git version string
The path in environment virable is "C:\Program Files\Git\cmd" as default.
![git-gui-error](https://user-images.githubusercontent.com/15623105/44123925-24ec5c32-a05d-11e8-88f8-50a51c8d208a.jpg)

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
