### ISSUE TITLE
Git binaries on Windows don't have a version number

### ISSUE THREAD

**Issue by JJClements** [git/git-scm.com#1233]
Bit of a strange one, we've noticed that the git binaries on Windows don't seem to have a build version (at all) that presumably matches the release version of the application? Is there a reason for this? It's the only one of many applications that we use that doesn't seem to add the tags to the binaries when they are compiled for some reason?

This would also really help with our patching/maintenance to ensure the application is always kept up to date ;-)

Thanks

**Comment by pedrorijo91** [comment]
Hey @JJClements! 

Thanks for reporting your issue, but as you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
