### ISSUE TITLE
Customize the sort of "git diff --stat" output

### ISSUE THREAD

**Issue by frozar** [git/git-scm.com#1235]
I was looking for the possibility of sorting the output of the command `git diff --stat` by the number of modifications. Currently, the output of this command show the modified files by alphabetic order.  
I didn't find a "builtin" option which allows to sort the files by number of modifications.

It is possible to do it with a `| sort "good_option"` but you may lose the coloration and it's not desirable.  
If this option already exist, please send me a link to it and I apologize by advance.

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
