### ISSUE TITLE
MacOS installer installs Malware

### ISSUE THREAD

**Issue by Rohitkrops** [git/git-scm.com#1238]
Yesterday I tried to update Git. Visited download page on the site but the automatic download didn't start. 

Then I clicked the link below which took me to Sourceforge site. The installed provided by it tried to install several third-party applications without prior notice. Additionally, it tried to change my search engine preferences. 

![screen shot 2018-09-06 at 8 55 47 pm](https://user-images.githubusercontent.com/20735862/45167963-dc035d00-b217-11e8-9551-1473553975aa.png)

Thanks to Malwarebytes, it saved me by blocking it.

**Comment by pedrorijo91** [comment]
Hey @Rohitkrops. Thanks for reporting the issue.

I reported the issue on the proper repo (https://github.com/timcharper/git_osx_installer/issues/121) as it may be an important problem. Can you please follow up there?

**Comment by Rohitkrops** [comment]
@peff I downloaded that image as it was flagged. 

Downloaded fresh Image through Incognito tab with all extensions disabled. 
```
9c8aebb6a3f0eadcd903683c24f307c33f8bb557  git-2.18.0-intel-universal-mavericks.dmg
``` 
Installed and it's ok this time. 🤯  [18 threads that day but 0 today] 🤔
![screen shot 2018-09-06 at 10 07 09 pm](https://user-images.githubusercontent.com/20735862/45172004-8fbd1a80-b221-11e8-8cb4-2e594cd0ecc1.png)


One thing I noticed was that on that day I saw a pop when download started but not today. Maybe an extension causing it.

**Comment by peff** [comment]
@Rohitkrops Thanks for following up.

I think we should take the link down temporarily if we think it's serving malware. However, I can't seem to find any problem now, and it's possible it was from some other vector (e.g., an http proxy). So it seems just as likely to me that it's not a problem.

**Comment by Rohitkrops** [comment]
Sure we can declare it clean. Closing the issue.
