### ISSUE TITLE
Try Git tutorial is gone

### ISSUE THREAD

**Issue by liffiton** [git/git-scm.com#1239]
The front page prominently links to Try Git at https://try.github.com/, but the interactive tutorial is no longer available there.  See Try-Git/try_git#24.

**Comment by pedrorijo91** [comment]
Thanks for reporting the issue @liffiton ! It seems https://try.github.com/ was integrated on Pluralsight as part of the acquisition of codeschool by Pluralsight.

I've found a few quick alternatives:

* http://gitready.com/
* https://www.katacoda.com/courses/git
* https://www.codecademy.com/courses/learn-git/lessons/git-workflow/exercises/hello-git
* https://learngitbranching.js.org/

**Comment by peff** [comment]
The page you end up at looks like a GitHub Services page, so I'll ask those folks if they have any more details, or whether the site is coming back.

If not, then we should drop both the tutorial link, as well as the one on the front page.

**Comment by liffiton** [comment]
Of those alternatives, I think gitready.com is too confusing for a beginner, and codecademy requires signing up or logging in, which seems like a bigger barrier than you'd want for a quick "try git out" link.  Katacoda looks the most friendly of those to me.

**Comment by peff** [comment]
Another alternative I came across: https://play.instruqt.com/public/topics/getting-started-with-git

My understanding is that try.github.io is gone for good. GitHub Services has https://lab.github.com/ these days, but there's not a pure-Git course there as of yet (and even if there were, I don't think we'd want something that requires a GitHub login to play with).

I don't think any of these options rises to the level of so simple that the front page should point people to it. So IMHO we can just drop that content entirely from the front page. On the tutorial page, it would make more sense to link to some of these, and drop the trygit entry.

**Comment by aespielberg** [comment]
@pedrorijo91  But pluralsight costs $45 per month.  Does git really have no interest in having a free tutorial for beginners for their core product?  I'm having a hard time finding a tutorial for someone who is not a computer programmer but still wants good tracking of files.

It seems weird that github would remove the onramp of its core service for new users.

**Comment by pedrorijo91** [comment]
@aespielberg this repo is about git-scm website, which basically pulls info from many different sources to get an easier UI to users. We pull data from the pro git book, git man pages, and a few external resources.

if git itself has any interest in having a free tutorial is a question to ask in the official mailing list (see https://git-scm.com/community)

github it a totally independent company from git. whatever their goals are, git has nothing to say about that
