### ISSUE TITLE
git gui commit message window can't input chinese

### ISSUE THREAD

**Issue by yajw** [git/git-scm.com#1247]
I have the same problem as #795 . Commit message window can't input Chinese.

environment:
git version 2.19.1
OS X

**Comment by pedrorijo91** [comment]
as you can see in #795:

> This issue tracker is dedicated to the git-scm.com website.
>
> The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org
