### ISSUE TITLE
Please link to https not http git-scm.com

### ISSUE THREAD

**Issue by avar** [git/git-scm.com#1250]
@peff : Seems only you can change this (and couldn't find a better way to report this bug). The description at https://github.com/git/ should link to https://git-scm.com, not http://git-scm.com

**Comment by peff** [comment]
Good idea. I've switched it. @gitster also has admin permissions on that repo, but I'm not sure how often he reads GitHub notifications. ;)

**Comment by peff** [comment]
By the way, I also tidied up the team and admin list a bit, so people may have seen some notifications related to that. Permissions should be the same before and after, as it was mostly dropping duplicates (in particular there was a legacy "Team Gitcscm" that duplicated the more modern "gitscm" team that actually grants access to this repository.
