### ISSUE TITLE
Manual: Small Suggestion: Chapter: 3.6 Git Branching - Rebasing

### ISSUE THREAD

**Issue by schittli** [git/git-scm.com#1258]
Good evening
git-scm.com says _Patches, suggestions, and comments are welcome_, unfortunately _About git-scm.com_ does not say how and where we could send comments.

Therefore, I hope that I'm right here to suggest a small clarification for the manual:

In [3.6 Git Branching - Rebasing](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) I suggest to replace this sentence:

- Original: **Do not rebase commits that exist outside your repository.**
- New: **Do not rebase commits that exist outside your _own local working_ repository.**

I **guess** the original sentence means the local working repository - if this is true, then this is the key to understand it right :-)

The background is, that I have a lot of repositories.
But some are on servers, others are local...

Kind regards, Tom

**Comment by peff** [comment]
Thanks for your suggestion! I agree that it makes the meaning more clear. That content comes from the Pro Git2; you can open a pull request there (see https://git-scm.com/site for more discussion of what comes from where).
