### ISSUE TITLE
check-ignore fails to find bracket patterns

### ISSUE THREAD

**Issue by mcandre** [git/git-scm.com#1259]
I was using the gitignore.io recommended pattern for Python:

https://www.gitignore.io/api/python

When I noticed that my `bin/` directory was being excluded from version control by Atom, as a result of being excluded from git. Eventually I determined that the assorted parts of the git toolset react completely differently from each other.

`git add -f <path>` insisted that the path was forcibly added to version control, but in fact `git status` showed that the path was *not* in version control. And `git check-ignore` was no help, as it skipped over the `[Bb]in` pattern in the .gitignore file.

git 2.19.1, macOS 10.14.1 Mojave.

**Comment by pedrorijo91** [comment]
Hey @mcandre, 

As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
