### ISSUE TITLE
remote_genbook2 produces "can't modify frozen String" error

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#1272]
while running `$ rake remote_genbook2`  I get a lot of messages on the output:

```
$ rake remote_genbook2
** Invoke remote_genbook2 (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute remote_genbook2
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
can't modify frozen String
```

I thought it wouldn't be a problem, but books were not added to my local storage. I had never seen this error (ruby noob here), but google is our friend (https://stackoverflow.com/questions/2204945/ruby-cant-modify-frozen-string-typeerror).

I couldn't really understand where are we changing some String, but by changing `lib/tasks/book2.rake` first line into `# frozen_string_literal: false`, it now works. 

I'm not sure this is a good solution, but I saw you did the same on #1261 @tarebyte. Is this acceptable or a huge hack?

**Comment by jnavila** [comment]
It's time I update my setup, it seems.

**Comment by tarebyte** [comment]
@pedrorijo91 that's my bad I'll open a PR to fix it.

**Comment by pedrorijo91** [comment]
no problem @tarebyte , easily solved :D
