### ISSUE TITLE
merge not work 

### ISSUE THREAD

**Issue by lakshmankashyap** [git/git-scm.com#1276]
hi team,

some one solve my  query 

my query is i have two branch 

dev 
​dev​2

when i merge dev to dev2 then not show conflict  at same file in my file on line 71 both branch have diff code

error that when i dev to dev2 then dev2 have no change and when i do dev to dev2 merge then dev2 have no change show but when i use git diff dev2 then show diff .

i use most of time git merge its work but that time face many problem

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
