### ISSUE TITLE
Git for Windows 2.19.2 was marked pre-release after the fact, contains "breaking changes"

### ISSUE THREAD

**Issue by dakotahawkins** [git/git-scm.com#1278]
From the [release page:](https://github.com/git-for-windows/git/releases/tag/v2.19.2.windows.1)

> **EDIT November 26th 2018:** marking as pre-release because of [two major breakages in this version](https://github.com/git-for-windows/build-extra/blob/6d8ce0cb3bf27425a491718319016303fe6a9a5e/ReleaseNotes.md#bug-fixes); Git for Windows v2.20.0 (which is slated for December 3rd) will fix them both.]

It may be prudent to change windows download links to point at the 2.19.1 release until 2.20 is released.

**Comment by pedrorijo91** [comment]
hey @dakotahawkins,

thanks for reporting this issue.

TBH, and this is totally my single opinion, I'm not sure if it would compensate the work of changing the links:

0.  Probably the fix would be to delete the DB entry for the latest windows version (https://github.com/git/git-scm.com/blob/master/app/controllers/downloads_controller.rb#L39) 
0.5. We would need to stop the daily task that updates the Downloads table
1. The new release is a couple of days ahead
2. Breaking change for already existing git-for-windows users right? If I had to bet (totally NOT based in facts), I would say the major number of users going to that link would be installing git-for-windows for the first time, and not updating

WDYT @peff ?

**Comment by dakotahawkins** [comment]
> Breaking change for already existing git-for-windows users right? If I had to bet (totally NOT based in facts), I would say the major number of users going to that link would be installing git-for-windows for the first time, and not updating

I only realized this after I told my coworker to update his install to fix something else and he installed this version and had some issues.

I don't personally get my updates that way, so I asked him where he got it and he got it from here. I think this is where people who google it usually wind up, which is exactly what he did.

> I'm not sure if it would compensate the work of changing the links

You may be right! I took a look and couldn't figure out how that worked, so I just filed an issue in case you find it worthwhile.

Thanks!

**Comment by JTBrinkmann** [comment]
I do not think it would be a breaking change for users who already installed the 2.19.2, as the git-for-windows updater automatically suggests "updating" to 2.19.1

Because the 2.19.2 tag "was demoted to 'pre-release' status" in the git-for-windows repository, maybe the daily task would not automatically pick it up again, and thus does not have to be stopped?

**Comment by dakotahawkins** [comment]
@JTBrinkmann 

That's good, but the updater (at least automatically checking for updates) is optional. When initially released the updater didn't work in our work environment (normal user is not an Administrator) so I never choose to install/use it.

**Comment by pedrorijo91** [comment]
> Because the 2.19.2 tag "was demoted to 'pre-release' status" in the git-for-windows repository, maybe the daily task would not automatically pick it up again, and thus does not have to be stopped?

From what I can see, we do not filter out pre-releases, but we could, without much work I think, we would just need to look at the `prerelease` and/or `draft` field from the release object: https://developer.github.com/v3/repos/releases/#response

**Comment by dakotahawkins** [comment]
@pedrorijo91 

You must filter when you usually update, GFW releases a lot of pre-releases.

If that the case, would re-running whatever pulls the versions get a previous version or not because what you currently have is the latest version or later than the latest official release?

**Comment by pedrorijo91** [comment]
solved on #1281 + https://github.com/git/git-scm.com/pull/1281#issuecomment-445159894
