### ISSUE TITLE
Text entered into search box lags

### ISSUE THREAD

**Issue by henniss** [git/git-scm.com#1279]
If one types quickly into the search box and immediately hits enter, the query text will be truncated. 

For example, if I rapidly type "quick\n", I get search results for "qu": 

![image](https://user-images.githubusercontent.com/17056237/49251014-4968f900-f3d5-11e8-9bd0-272a4fb5336d.png)
(The xhr request is triggered during typing; the document request is triggered when text is entered. In this example, the document request is made before "qui", "quic", or "quick" xhr requests are made.)

If I wait before entering my query... the search is still broken (#822 ?), but the query text is at least correct. 

Observed in Chrome 70.0.3538.110.

**Comment by pedrorijo91** [comment]
@jasonlong good one for the site redesign? :)

thanks for the report @henniss. We really need to fix the search. Will try to look on the weekend

**Comment by pedrorijo91** [comment]
still happens after fixing search on #1282
