### ISSUE TITLE
Git Bash Spacing

### ISSUE THREAD

**Issue by Mxdi** [git/git-scm.com#1291]
I run the following commands, It looks like this.

![image](https://user-images.githubusercontent.com/43386840/50667165-037bf380-0f86-11e9-8ce8-cf3887b0896a.png)

In a normal powershell , it looks like;

![image](https://user-images.githubusercontent.com/43386840/50667191-1a224a80-0f86-11e9-8b40-e967ab8342cd.png)

Ive deleted the .config , along with the other files in hopes that it was a cache issue, Deleting all of the files and resetting the looks oif my terminal have not solved anything, any ideas?

**Comment by pedrorijo91** [comment]
this seems totally unrelated with https://git-scm.com/
