### ISSUE TITLE
503 No Backend Servers Available

### ISSUE THREAD

**Issue by bmontana-edu** [git/git-scm.com#1297]
Received this message...

> ### 503 No Backend Servers Available
> No backend servers were available to answer your request. Please notify the site admins.

...when trying to download 2.20.1 for Mac.

**Comment by pedrorijo91** [comment]
this project only has a link to an external site which is responsible by the download, so probably this may be a problem for https://github.com/timcharper/git_osx_installer/issues (actually it may be a sourceforge problem, in which case there's not much to do besides retry I guess)

**Comment by bmontana-edu** [comment]
I did the same thing as you. That's when I got the error. After reporting the issue, I tried again and it worked.

Thanks for your quick response.
