### ISSUE TITLE
After update,  default ~  is /x/    No longer seeing my .bashrc

### ISSUE THREAD

**Issue by audetcameron** [git/git-scm.com#1310]
Hello All,
 I recently updated gitbash for windows.    Before updating I had been given administrator access on my work pc.  After updating git opens to ~   /x/    and the pwd is /x/  which does not exist on this system. However if I run gitbash as and Administrator it sees my .bashrc profile and my aliases work.
Is there a way to configure default non admin gitbash to use my C:\Users\Cameron   profile?

**Comment by tarebyte** [comment]
@audetcameron 👋 

This is actually the site for the documentation, if you're having an issue with Git for Windows you'd have better luck asking here: https://github.com/microsoft/git

Thanks!

**Comment by peff** [comment]
>  if you're having an issue with Git for Windows you'd have better luck asking here: https://github.com/microsoft/git

That's actually Microsoft's fork where they're porting VFS for Git patches to upstream. The Git for Windows project is at https://github.com/git-for-windows/git.
