### ISSUE TITLE
Git Unable to create .lock file on WINDOWS,Because branch name contains '>'

### ISSUE THREAD

**Issue by LongQingRox** [git/git-scm.com#1313]
Branch api>18 wasn't deleted
        cannot lock ref 'refs/heads/api>18': Unable to create 'C:/Users/Roxas/Documents/StudioProjects/ProjectName/.git/refs/heads/api>18.lock': Invalid argument
        Error deleting branch 'api>18'
I can't rename or delete this branch, please help.

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)

**Comment by meysam101** [comment]
`okoko`
