### ISSUE TITLE
0xc0000017 with phpstorm or Git Extensions

### ISSUE THREAD

**Issue by mrusklon** [git/git-scm.com#1319]
when I run phpstorm, I come across an error 0xc0000017, I tried to install Git Extensions, there is a similar situation. From the console, git is working properly, what should I do?

$ git --version    
git version 2.20.1.windows.1

reinstalling windows did not produce results

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
