### ISSUE TITLE
Making Website Completely Responsive.

### ISSUE THREAD

**Issue by prasadgujar** [git/git-scm.com#1321]
Hello Everyone,
while visiting https://git-scm.com/ and checking whether the website is completely responsive or not.
if the browser is resized completely, then the website is not completely responsive.

**Comment by HonkingGoose** [comment]
A responsive layout is coming, it's being worked at here: https://github.com/git/git-scm.com/pull/1179

**Comment by pedrorijo91** [comment]
as @HonkingGoose explained, the responsiveness is being under control. As such, we'll close this issue
