### ISSUE TITLE
Can't close window git-bash console

### ISSUE THREAD

**Issue by Eskander88** [git/git-scm.com#1323]
I create file `%userprofile\.bashrc` and added some alias

Several times I open `C:\Program Files\Git\git-bash.exe` for testing and don't close previous applications.

And I have several git-bash's are opened.  When I click `Close all window` on taskbar (status bar) Windows some windows git-bash don't close.

To close this windows of application I need press `CTRL` + `SHIFT` + `ESC` and taskkill `git-bash.exe` and `bash.exe` from proccesses. 

Other standard methods don't work in this situation.

**GIT:** version 2.21.0.windows.1
**OS:** WIN 10 x64

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.

**Comment by Eskander88** [comment]
I am talking about distributive which was downloaded from git-scm.com
![изображение](https://user-images.githubusercontent.com/24587938/54076802-8d1aab00-42c0-11e9-9c7e-1860e66b59cc.png)

**Comment by peff** [comment]
Yes, but git-scm.com is just linking to the software that is written and distributed elsewhere. People watching issues on this repo are not likely to have the answer to your question, but people on the Git for Windows project will. I.e., https://github.com/git-for-windows/git/issues.
