### ISSUE TITLE
GitHub Cheat Sheet link update

### ISSUE THREAD

**Issue by 990094523** [git/git-scm.com#1324]
![1](https://user-images.githubusercontent.com/27407218/54343395-a4b7b200-4679-11e9-8110-55691e19a418.png)

https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf  => https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdf

**Comment by pedrorijo91** [comment]
hey @990094523 , thanks for reporting the issue! would you like to contribute with a PR since you already found the correct link? You only need to update the file at https://github.com/git/git-scm.com/blob/master/app/views/doc/index.html.erb#L24 with the correct link :)

**Comment by 990094523** [comment]
👌

**Comment by pedrorijo91** [comment]
closed by #1325
