### ISSUE TITLE
Git Extensions dropped linux support

### ISSUE THREAD

**Issue by eliocamp** [git/git-scm.com#1326]
I was trying to install Git Extensions on linux and it seems that it's no longer compatible. Their "how to install on linux" [page](https://github.com/gitextensions/gitextensions/wiki/How-To:-run-Git-Extensions-on-Linux) asks the user to download the Mono version, but Mono support was deprecated in [version 3](https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00) last december. 

If all it takes to make the change is remove "linux" from Git Extension's entry in guis.yml I can send a PR if you'd like.

**Comment by pedrorijo91** [comment]
@eliocamp thanks for raising the issue! :)

from what I can see, there's still a version that supports linux  (https://github.com/gitextensions/gitextensions#version-25x) and that will receive security updates. So it still provides a linux version (even if not 100% updated) right ?

**Comment by eliocamp** [comment]
Oh, ok. I missed that as I was only looking at the latest release. 

Sorry, then!
