### ISSUE TITLE
Mistake in gitignore pattern documentation?

### ISSUE THREAD

**Issue by iwasherefirst2** [git/git-scm.com#1332]
I think that the rule in the [documentation][1] is not correct:

> If the pattern does not contain a slash /, Git treats it as a shell
> glob pattern and checks for a match against the pathname relative to
> the location of the .gitignore file (relative to the toplevel of the
> work tree if not from a .gitignore file).

I tested it and it seems that this is not true. Instead, it looks to me like this is true:

> If the pattern does ***<strike>not</strike>*** contain a slash /, **other than a trailing slash**, Git treats it as a shell
> glob pattern and checks for a match against the pathname relative to
> the location of the .gitignore file (relative to the toplevel of the
> work tree if not from a .gitignore file).

Example:

For this folder:

    .
    ├── foo
    │   └── bar
    │       └── New Document
    └── test
        └── foo
            └── bar
                └── New Document

and this `.gitignore` file

    foo/bar

the folder `/foo/bar` is ignored and the folder `/test/foo/bar` not. 

On the other side, if one changes `.gitignore` file to
 
    bar 

or

    bar/ 

then bar is ignored everywhere and not only relative to the .gitignore file. 

  [1]: https://git-scm.com/docs/gitignore

**Comment by pedrorijo91** [comment]
hey @iwasherefirst2 

As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community). The documentation you refer to is imported from git man pages

**Comment by iwasherefirst2** [comment]
hi @pedrorijo91 

I think this is a problem found on the git-scm website. The information on the page https://git-scm.com/docs/gitignore is not true and the paragraph should be changed there?

**Comment by pedrorijo91** [comment]
although it appears on the git-scm website, the content is imported from the git man pages, meaning that if there's a problem, it should be fixed on the git man pages, and git-scm will pick up the changes afterwards

**Comment by iwasherefirst2** [comment]
Oh I see. I will write to the mailing list then. Thank you for that info.

**Comment by pedrorijo91** [comment]
no problem! thanks for reporting @iwasherefirst2 :)
