### ISSUE TITLE
Increase text contrast on website by using full black instead of grey text.

### ISSUE THREAD

**Issue by HonkingGoose** [git/git-scm.com#1334]
**Please make sure you are NOT reporting a problem about git itself**

- [x] This is **not** an issue about 
     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).

### Issue description:

Some text on the website is harder to read, because it uses a grey text instead of a full black text.

#### Examples of grey text:
https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control the text of the Pro Git 2 book is rendered in grey.

https://git-scm.com/ The text that's under the "About", "Documentation", "Downloads", and "Community" sections. The text next to the Pro Git book thumbnail.

### Suggested improvement:

Change the markup/html/css/JS/whatever so that it uses a full black color for all text.

**Comment by pedrorijo91** [comment]
@tarebyte another one to have into account on the redesign #1179

@HonkingGoose thanks for reporting the issue. There's currently an effort to re-design the website (#1179) so this will be considered on that probably. 

But if you are able to work on a quick solution and submit a PR I think we may be able to land it in the meanwhile

**Comment by HonkingGoose** [comment]
Hi @pedrorijo91 thanks for your comment. :smile:

It would be very nice indeed to have a solid black color. So I do hope it will be considered in the re-design of the site.

As for me helping out with a quick-fix for the text: I don't know HTML/CSS/JS yet, and I don't know how this website is structured yet. So I'm not able to help on this issue. But thanks for the offer of letting me help. I'll keep that in mind for when I do know how those things work. :+1:

**Comment by jasonlong** [comment]
Thanks for the issue @HonkingGoose. Full black text definitely isn't necessary or even [desirable normally](https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/). 

The text you mention already far exceeds the recommended [contrast ratio](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) for accessibility standards. For example, the book content (and all other similarly formatted pages) [has a contrast ratio of 9.12](http://jxnblk.com/colorable/demos/text/?background=%23fcfcfa&foreground=%234e453d) which is a AAA rating.

The new design will, of course, also be mindful of these a11y recommendations.

**Comment by HonkingGoose** [comment]
Hi @jasonlong Thanks for the detailed comment, I'm learning new stuff here. :smile: I didn't know that full black is not desirable. And having seen the examples, it makes more sense to use a dark grey.

I'll take your word on the fact the current text already has a good contrast ratio.

I'm making the assumption here that https://a11yproject.com/ uses the recommended color and contrast for their text. Their text is easy for me to read. So it must be something else apart from color/contrast that is causing issues with reading the smaller text on the git-scm site.
