### ISSUE TITLE
public/javascripts selectivizr-min.js source code formatting/indenting

### ISSUE THREAD

**Issue by HonkingGoose** [git/git-scm.com#1335]
**Please make sure you are NOT reporting a problem about git itself**

- [x] This is **not** an issue about 
     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).

## Description of problem:
The selectivizr script located at https://github.com/git/git-scm.com/blob/master/public/javascripts/selectivizr-min.js is very hard to read, because it is not formatted in any way.

## Discussion:
Usually source code is formatted in nice blocks/indents for ease of reading. This code is not formatted/indented in any way. Is this intended?

**Comment by pedrorijo91** [comment]
that's intended @HonkingGoose :) it's called assets minification, for performance purposes. There are tons of resources online where you can explore the subject. Here's a quick example: https://blog.stackpath.com/glossary/minification/

**Comment by HonkingGoose** [comment]
Ah okay, I read the link you provided. Thanks for the link! :+1: 

If I understand correctly:

- minifiying is something you do *after* writing the code, but *before* deploying. 
- The benefit of minifying is not sending whitespace and formatting to the end-user (saves bandwidth).

The selectivizr script itself is already minified it seems. How is this intended to be maintained then? Do you just copy+paste a new script when the old one breaks/needs updating?

**Comment by jasonlong** [comment]
@HonkingGoose You're correct on both points. Normally JS scripts are minified as part of a pre-deployment build process. The developer will make their updates to a normally formatted JS file and then have the minifier do its thing prior to deploying.

If you're looking to un-minify a JS script, you can do this in your browser's web inspector. For example, Chrome has this "pretty print" button in the bottom left:

<img width="251" alt="Screen Shot 2019-04-01 at 8 42 58 PM" src="https://user-images.githubusercontent.com/6104/55355111-58fd6900-54bf-11e9-9934-75fbe598ddb4.png">
