### ISSUE TITLE
Git commit malfunction with Atom

### ISSUE THREAD

**Issue by JasLieb** [git/git-scm.com#1336]
Hello,

I have noticed a problem while an commit attempt, with Atom as default editor :

`
git commit 
hint: Waiting for your editor to close the file...
`

// Atom opened and I write my commit
// Save and I close the tab (nothing happened) or the app

`
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: Object.<anonymous> (C:\Users\Jason\AppData\Local\atom\app-1.35.1\resources\app.asar\node_modules\github\lib\worker.js:61:22
Remote event names: destroyed, crashed
`

I thank you in advance for your return.

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

**Comment by Cristishor201** [comment]
I get this error even if my editor is not opened. :(

is this a git or atom issue ?

**Comment by tanzer253** [comment]
> Hello,
> 
> I have noticed a problem while an commit attempt, with Atom as default editor :
> 
> `git commit hint: Waiting for your editor to close the file...`
> 
> // Atom opened and I write my commit
> // Save and I close the tab (nothing happened) or the app
> 
> `Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\Jason\AppData\Local\atom\app-1.35.1\resources\app.asar\node_modules\github\lib\worker.js:61:22 Remote event names: destroyed, crashed`
> 
> I thank you in advance for your return.

**Comment by Cristishor201** [comment]
when I work with atom in windows 7, it works just fine, but when I tried to use it on windows 10, I get this error, with --wait.
Now I resolved this but for some reason I cannot open the atom editor any longer, within the cmd. it open but the lines of code is blank.

**Comment by pedrorijo91** [comment]
> As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/).
> 
> Git specific issues should be raised with the community (https://git-scm.com/community).


hello @Cristishor201 , please raise the issue on the correct channel, but it may be a Atom related issue
