### ISSUE TITLE
rewrite commit, but push "everything up-to-date"

### ISSUE THREAD

**Issue by SnailDev** [git/git-scm.com#1341]
![image](https://user-images.githubusercontent.com/30819423/56495623-f0873200-6528-11e9-96f5-ceeffa695ff4.png)

![image](https://user-images.githubusercontent.com/30819423/56495655-0694f280-6529-11e9-839f-15cff66ba5e2.png)

I just want to delete big  file in the record and some one has the same problem on the comment at [this article](https://www.hollischuang.com/archives/1708).

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
