### ISSUE TITLE
git-check-ref-format: Not clear on international characters

### ISSUE THREAD

**Issue by SetTrend** [git/git-scm.com#1342]
[`https://git-scm.com/docs/git-check-ref-format`](https://git-scm.com/docs/git-check-ref-format) isn't clear about using international characters for branch names.

When we use branch names including umlauts or apostrophes, `git fetch` is getting into trouble with these.

**Comment by peff** [comment]
They're allowed and should work from the Git side. However, note that refs may be stored in the filesystem with names matching the refname, and some filesystems may convert case or normalize unicode behind the scenes (e.g., HFS+). That can result in confusing results.

All that said, this question should be taken to the [mailing list](https://git-scm.com/community). This repository is just about the web site itself. The actual contents of the manpages (and the behavior of Git, of course) are discussed on the list.
