### ISSUE TITLE
Add links to the External Links page.

### ISSUE THREAD

**Issue by amishscientist** [git/git-scm.com#1343]
I would like to add the following links to the External Links Page

- https://www.youtube.com/c/DanGitschoolDude   Is a great channel with videos that I find very helpful and short that cover a rage of git tops. Most of the time I can watch them while I'm eating lunch at my desk. 

- http://sethrobertson.github.io/GitFixUm/fixup.html  is a site I found super helpful when I was first started out.  It's git help done in a chose your own adventure style. 

I guess I'm looking for approval of the links before going off and making code updates followed by the pull request. 

**Please make sure you are NOT reporting a problem about git itself**

- [x] This is **not** an issue about 
     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).

**Comment by peff** [comment]
I skimmed over the content in both of them, and they look pretty reasonable. I think the only real downside to adding links to new resources is that they would turn out to be misleading or wrong, and our link would endorse them and provide extra confusion. But as a general rule, if a third party thinks the content is useful and nobody has complained otherwise, I think it's worth linking and giving the benefit of the doubt (that's certainly what we've done for books).

And in both of these cases, the material seems to be presented in different ways than what's already linked on the site.

So yes, a PR would be welcome. Thanks!

**Comment by pedrorijo91** [comment]
thanks for the raising this @amishscientist .

we would love to have you doing a PR adding those links. In case you need some guidance, the files you'd need to change are under https://github.com/git/git-scm.com/tree/master/app/views/doc

**Comment by adsingh14** [comment]
@pedrorijo91 it seems that issue author has not added the links.

**Comment by pedrorijo91** [comment]
true. would you be interested in doing it @adsingh14 ? (or were you planning but forgot @amishscientist ?)

**Comment by amishscientist** [comment]
Well the computer I was using at the time was a raspberry pi 3.  When I
tried to set up the project it would crash so I never got around to it.  If
someone else would like to do it, go ahead.  While I have a raspberry pi 4
now it is still very slow.

**Comment by adsingh14** [comment]
> true. would you be interested in doing it @adsingh14 ? (or were you planning but forgot @amishscientist ?)

I would like to pass it to the author. I supposed that several stale issues needs to be 'closed'. :)

**Comment by amishscientist** [comment]
If someone else wants to do it is fine with me.

**Comment by amishscientist** [comment]
Is there a link to awesome-git then?

**Comment by dscho** [comment]
> Is there a link to awesome-git then?

[Yes](https://github.com/git/git-scm.com/issues/1343#issuecomment-2343807240): https://github.com/dictcp/awesome-git

**Comment by dscho** [comment]
Let's just close this, there is not enough concrete, actionable idea to merit keeping this ticket open.
