### ISSUE TITLE
Carbon Ads Integration

### ISSUE THREAD

**Issue by sayzlim** [git/git-scm.com#1344]
Hi Git website maintainers,

I reached out to @peff asking for permission to share some details about https://www.carbonads.net/ with the core contributors of the website and he told me to create an issue here so others can vote on the invitation.

Carbon is an ad network that helps open source projects to generate ad revenue through  relevant dev/code ads. Some of the sites we work with are:

- https://getbootstrap.com/
- https://en.cppreference.com/
- https://githowto.com/
- https://laravel.com/docs/5.8

I understand that the decision is made by the community, so before I share more details, I would like to ask  the core maintainers of the website to vote whether you’re interested in learning more about it. Do you mind if I share more details for the team to evaluate whether Carbon is the right choice for the project?

_P.S. Please vote up or down to this issue. I’m aware that creating issue here is not the right place, but I also want to avoid sending email to the mailing list with this invitation. It’s ideal to  seek feedbacks for the core members before I ask the community._

**Comment by pedrorijo91** [comment]
Hey @sayzlim,

From my point of view, no ads is always better than having adds on any website :)

Ads bring some financial return, but it would be for the sfconservancy foundation so I would say it's their call if the money is important or not (cc @peff ) .

Can we have an estimation of the expected return for the foundation by adding the ads?

**Comment by jasonlong** [comment]
I concur w/ @pedrorijo91. I'd be apprehensive about adding ads since I think a userbase like this is especially against them. However, I don't think it's my call since I'm not involved in the financial side of anything related to the site.

**Comment by peff** [comment]
My feelings are similar to @pedrorijo91 and @jasonlong's. However, I felt it was important to have this conversation in the open, rather than just me giving a "yes" or "no" in private. I'll also ping the Git PLC at Conservancy so they're aware and can give input.

**Comment by avar** [comment]
[Disclosure: I'm on the Git PLC]

Let's assume for the sake of argument that we're all in agreement that serving ads on git-scm.com is a good idea.

My own opinion on the matter is that I'm not principally opposed to it, but it would need to take into account what we'd be getting out of it, say enough money make a dent in funding student devs working on git, sponsored travel to conferences etc.

There's also the trade-off of the project's landing & git's reputation being "cheapened" by such a move, and I'm told there's concerns that it would impact our non-profit tax status in the US. I have a strong bias in the direction of this sort of thing not being worth it overall, but I'm fully open to discussing it.

Anyway, let's say that's all past us, we agree that ads are a great idea on git-scm.com, and now we really just want to make that happen.

I think even then we should definitely not start such a conversation with what amounts to a pitch led by a specific advertising agency. So I think what we should do here is thank @sayzlim for his time and say "thanks, but no thanks".

**Comment by chriscool** [comment]
Yeah, according to the Conservancy, it looks like it would impact our non-profit tax status in the US.

And anyway I think that there are other ways to get money that we should try first, if we would like, or would need, more money in the first place. (For example we could ask big companies interested in Git for sponsorship.)

So I also think that we should politely reject this proposal. [Disclosure: I'm on the Git PLC too]

**Comment by sayzlim** [comment]
Thanks for the reply everyone! I’m glad this proposal opens up discussion among the foundation and the members.

I respect the decision made by the team. The invitation remains open whenever the team decides to use Carbon as one of the options. We also work with https://opencollective.com/ where we can deposit the earnings to the project collective (if you have one).

I’ll close this issue for now. Let me know whenever the team wishes to try out Carbon.

Cheers!

**Comment by sayzlim** [comment]
Hi everyone, just want to circle back the conversation to see if it makes sense to explore advertising revenue to fund the project at the current stage. You can use ESLint as a reference by setting up a collective at https://opencollective.com/eslint

We can also send the earnings to Software Freedom Conservancy through PayPal or Wire. Based on the current site traffic, the amount of **potential revenue is more than $15k per year**. There are many choices when it comes to fund the project — sponsorship is one of the examples you Chris mentioned, but Carbon can be a solid choice if you don't have the time/resouces to approach companies for sponsorship.

The ad will also take up a small space in the sidebar.

![Carbon on git-scm](https://cln.sh/CZ8zOQ+)

Happy to address any concerns the team members have when it comes to using Carbon. Let me know if there is anything that I can do to make the process easy for the team if you decide to try it out.

**Comment by sayzlim** [comment]
Hi @peff @chriscool, just wondering if anything has changed in the past year on the advertising or sponsorship in general? We've been helping MDN with their sponsorship placement that you can see on https://developer.mozilla.org/en-US/docs/Web/HTML — think we can explore to do something similar here?
