### ISSUE TITLE
Email to git@vger.kernel.org gets rejected

### ISSUE THREAD

**Issue by clisc** [git/git-scm.com#1345]
I looked at the ones already closed and I don't see anything that applies to my case.

As far as I can tell, there is no HTML in my email, but I'm not sure exactly how to verify that.

On second glance, it looks like I did trip the HTML filter... how do I know if my email has HTML in it?  I did have a hyperlink but I removed that and sent again.  

I'm using Outlook 365 as a mail client.

Original Message   Details
--
Created Date:               5/30/2019 9:58:27 PM                       Sender Address:               clisc@microsoft.com                       Recipient Address:               git@vger.kernel.org                       Subject:               Simple shortcut for "git     push --set-upstream origin newBranchName" | Created Date: | 5/30/2019 9:58:27 PM | Sender Address: | clisc@microsoft.com | Recipient Address: | git@vger.kernel.org | Subject: | Simple shortcut for "git     push --set-upstream origin newBranchName"
Created Date: | 5/30/2019 9:58:27 PM
Sender Address: | clisc@microsoft.com
Recipient Address: | git@vger.kernel.org
Subject: | Simple shortcut for "git     push --set-upstream origin newBranchName"
Error Details
Reported error:               550 5.7.350 Remote server     returned message detected as spam -> 550 5.7.1 Content-Policy reject     msg: The message contains HTML subpart, therefore we consider it SPAM or     Outlook Virus. TEXT/PLAIN is accepted.! BF:<U 0.499996>;     S1726307AbfE3V6d                        DSN generated by:               BN8PR21MB1218.namprd21.prod.outlook.com                       Remote server:               vger.kernel.org | Reported error: | 550 5.7.350 Remote server     returned message detected as spam -> 550 5.7.1 Content-Policy reject     msg: The message contains HTML subpart, therefore we consider it SPAM or     Outlook Virus. TEXT/PLAIN is accepted.! BF:<U 0.499996>;     S1726307AbfE3V6d | DSN generated by: | BN8PR21MB1218.namprd21.prod.outlook.com | Remote server: | vger.kernel.org
Reported error: | 550 5.7.350 Remote server     returned message detected as spam -> 550 5.7.1 Content-Policy reject     msg: The message contains HTML subpart, therefore we consider it SPAM or     Outlook Virus. TEXT/PLAIN is accepted.! BF:<U 0.499996>;     S1726307AbfE3V6d
DSN generated by: | BN8PR21MB1218.namprd21.prod.outlook.com
Remote server: | vger.kernel.org

**Comment by pedrorijo91** [comment]
well, that depends on your email client. A quick googling "office 365 send email as plain text" led me to this link: https://support.office.com/en-ie/article/change-the-message-format-to-html-rich-text-format-or-plain-text-338a389d-11da-47fe-b693-cf41f792fefa

**Comment by clisc** [comment]
Thanks!  I kept finding links to changing it to HTML but not plain text.  That should help.
