### ISSUE TITLE
Git Bash Window Is Blank On Windows

### ISSUE THREAD

**Issue by zh1010880729** [git/git-scm.com#1352]
When I use git bash here .it will like this
![微信截图_20190604185847](https://user-images.githubusercontent.com/30980981/58874234-d0878880-86fa-11e9-82d9-e1c71d3a7a33.png)

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

book related issues (i.e. anything with a URL starting with https://git-scm.com/book or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
