### ISSUE TITLE
Re-enabled a folder set as untracked

### ISSUE THREAD

**Issue by samuelrabini** [git/git-scm.com#1355]
Using SourceTree I issue the Stop Tracking command (I think it executed the _add untracked_ https://git-scm.com/docs/git-add#Documentation/git-add.txt-adduntracked). Is there anyway to revert this command and re-enable the folder? I was able to re-add to the index all files into the folder by the _git add -f pathtofolder_ command, but new files are not asked to be committed and pushed.

Thanks in advance,
Samuel

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

Nevertheless, that's something specific to sourcetree (I've personally never used it). But maybe you should check the .gitignore folder (or look into sourcetree specific foruns/stackoverflow): https://git-scm.com/docs/gitignore
