### ISSUE TITLE
Highlight subsection of book which user currently reading at

### ISSUE THREAD

**Issue by etanot** [git/git-scm.com#1359]
Properly highlight which section+subsection book which user currently reading at. For example if I'm at URL https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Hooks  so, highlight **Customizing Git** -> **Git Hooks** when user clicks on chapters drop-down.

![git](https://user-images.githubusercontent.com/28824347/61434625-110e2f00-a954-11e9-9e43-8013cd27aaef.png)

**Comment by pedrorijo91** [comment]
thanks for reporting the issue @finn0 

Would you be interested in helping fixing it? :)

**Comment by pedrorijo91** [comment]
thanks for reporting the issue @finn0 !

would you be interested in helping fixing it? :)

**Comment by finn0** [comment]
@pedrorijo91, yes. But, first I need to see code-base to understand how website works and which modules do I have to look into it. And I need your help in it. Is there any documentation available for getting started quickly?

**Comment by pedrorijo91** [comment]
so, the website is a simples Ruby On Rails app. You can see on the README file how to setup the site locally. Under https://github.com/git/git-scm.com/tree/master/app you'll see the site source code.

I think this is the general picture. Feel free to explore a bit and come back with any questions that arise
