### ISSUE TITLE
Git will not finish downloading

### ISSUE THREAD

**Issue by petitt0** [git/git-scm.com#1368]
I am trying to download Git 2.23.0 64 bit and am able to start the download and the progress bar gets to the very end, but never completes. No error messages or anything.
Info: Windows 10; 64 bit
![Screenshot_44](https://user-images.githubusercontent.com/54504283/63725074-56f9c500-c827-11e9-9dae-443e02469a87.png)

**Comment by pedrorijo91** [comment]
Hey @petitt0. This issue seems to be related with the git for windows installer itself right? If that's the case we recommend you to report the issue at  [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)

**Comment by adsingh14** [comment]
@pedrorijo91  I think this issue should be **closed**.
