### ISSUE TITLE
git version 2.20.1.windows.1 - name-only behaviour not as expected

### ISSUE THREAD

**Issue by cahe** [git/git-scm.com#1369]
I'm trying to generate a file list containing all modified files between two tags. Lately I've done some unification of endlines (conversion of all files from Unix to Windows CRLF) and I'm getting as a result all files in the repository when generating a diff between two latest tags.

The command I'm using:

git diff --ignore-space-at-eol -b -w --ignore-blank-lines --name-only TAG1 TAG2

Git Log in Tortoise Git shows 0 added 0 removed lines and kdiff shows no difference between two revisions if you ignore whitespace changes.

Is there a way for me to generate this file list excluding the files that have only the endlines converted? Is this the expected behaviour?

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
