### ISSUE TITLE
git config credential.helper 'cache [<options>]' should have store option

### ISSUE THREAD

**Issue by yehonadav** [git/git-scm.com#1370]
This is a feature suggestion,
that can help tremendously with package management tools taking advantage of git and its capabilities.

If one can store credentials safely and avoid the credential prompt, 
crossplatform automation solutions can easily make a better ci cd pipeline.

Please consider as this will make a major impact and save a lot of time on a custom credential cache that won't work for every platform or require big effort for something that should be simple and easy to use

Suggested Usage:
   git config credential.helper 'cache --timeout=300 --store username=nightwing password=gitisawsome'

**Comment by peff** [comment]
This repository just tracks the git-scm.com site itself; questions about Git should generally go to the [mailing list](https://git-scm.com/community).

However, I think what you want already exists. Either:

  - you want the config in your `.gitconfig` file, in which case you can put a short shell snippet in the config which returns the password (e.g., `git config credential.helper '!f() { test $1 = get && echo password=whatever; }; f`

  - you want to prime the cache with an automated process, in which case you can run `git credential approve` (e.g., `echo url=https://user:pass@example.com | git credential approve`).

You can find more about how credential helpers work in [the technical documentation](https://git-scm.com/docs/api-credentials#_credential_helpers).

**Comment by yehonadav** [comment]
thank you!! 

after reading a bit more on git approve:
```
git config credential.helper 'cache --timeout=300'
echo "username=xxx" | git credential approve
echo "password=xxx" | git credential approve
echo "email=xxx" | git credential approve
```
seems to do the job with a warning:
```
git credential-'cache store: -c: line 0: unexpected EOF while looking for matching `''
git credential-'cache store: -c: line 1: syntax error: unexpected end of file
```
hopefully this might help others as this is not as clear/documented as other git concepts.

**Comment by peff** [comment]
That warning implies to me you have a broken config entry with an extra single-quote in it. Try looking at `.git/config` in an editor.

When you are seeding, you'll need to provide not just the password, but also some context (so it knows which URL to associate the password with). You can do that as broken down fields:

```
git credential approve <<\EOF
host=example.com
protocol=https
username=xxx
password=yyy
```

Or you can use `echo url=https://xxx:yyy@example.com | git credential approve`, which Git will automatically break down into those fields for you.
