### ISSUE TITLE
Focus on more content (increase width of box)

### ISSUE THREAD

**Issue by etanot** [git/git-scm.com#1373]
Move left hand side content to either top or bottom of the page.

![git1](https://user-images.githubusercontent.com/28824347/65386667-596c1380-dd2e-11e9-8e88-c0ad9313b4a2.png)

and increase the width of box so, more content (text) could fit in a line.

![git2](https://user-images.githubusercontent.com/28824347/65386731-f464ed80-dd2e-11e9-95eb-aecc1d5fcf52.png)

For some git sub-commands, their documentation is very long which requires lots of scrolling to finish the reading and lots of space wastes in both left and right hand side of box which can be utilize by documentation content.

**Comment by jasonlong** [comment]
The (admittedly stalled out) site redesign does indeed move the navigation to the top of the page. This would make the content area somewhat wider, but we'd always have some sort of max-width because extremely long line lengths are terrible for readability.

**Comment by finn0** [comment]
> site redesign does indeed move the navigation to the top of the page.

For now, we can move side content to the top and increase width of box until new design is not ready. And this shouldn't require much changes in the code.

> extremely long line lengths are terrible for readability.

Indeed, if users want long line lengths, they should read documentation either on [Kernel.org wiki](https://git.wiki.kernel.org/index.php/GitDocumentation) or man page.

**Comment by dscho** [comment]
Let's just close this, there has not been enough activity to merit keeping this ticket open.
