### ISSUE TITLE
Output of `--pretty=raw` misses date of annotated tags

### ISSUE THREAD

**Issue by Bachsau** [git/git-scm.com#1379]

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
