### ISSUE TITLE
Rendering of localised manpages: broken links

### ISSUE THREAD

**Issue by rimrul** [git/git-scm.com#1382]
To see this issue in action, please compare the "further documentation" section on the [English git(1) page](https://git-scm.com/docs/git#_further_documentation) with the [German one](https://git-scm.com/docs/git/de#_weitere_dokumentation).

You'll find 1 of 6 links broken (API documentation) on the English version and 3 of 6 broken (user manual, howto and API documentation)on the German version. Those broken links are generated from Asciidoc(tor) `link` macros (the working links are generated from linkgit macros).

The API documentation is broken for two reaseons. A) git-scm.com doesn't host the corresponding file. B) When rendering the folder structure in the link gets dropped, i.e. a link to `technical/api-index.html` turns into a href of `api-index`.

The other two links are broken because of the language structure. The asciidoc source for both languages is

````
link:howto-index.html[howto]
````

The English document links to https://git-scm.com/docs/howto-index.html (href `howto-index.html`)

The German document links to https://git-scm.com/docs/git/howto-index.html  (href `howto-index.html`)

**Comment by pedrorijo91** [comment]
Thanks for reporting the issue @rimrul  :) I don't think anyone was aware of it. I saw @jnavila self-assigned the issue, so he may be able to come up with an ideia or a fix in the near future

If you do have the time and availability to help, I'm sure your help we'd be most welcomed

**Comment by rimrul** [comment]
In [lib/tasks/index.rake#L80](lib/tasks/index.rake#L80) there's a gsub call that changes link macros for files in the technical folder. I think we can add a second gsub call bellow, that adds in a "../" to all relative links from a link macro.

**Comment by jnavila** [comment]
I'm not an expert in rails, but IIUC, routes don't work with subpaths. That's why all sub-path are brought back at level 0.

There is a bug where link assumes paths at same level. But a level is inserted when requesting a specific version or a translation, in which case this assumption fails. For instance, [this does not work either](https://git-scm.com/docs/git/2.22.1#_further_documentation).

The fix is to rewrite all the docs with correct sub-paths.

**Comment by peff** [comment]
I rebuilt the manpages on the production site (all translated, but also v2.23.0 in case it turns up any weird regressions). You may see an old version for a few hours due to CDN caching, but the user-manual link should work after that.

**Comment by rimrul** [comment]
The links to the user manual are working on git-scm.com/docs/git/de. The others at least look like they should work, if we had the docs available.
