### ISSUE TITLE
GIT Partial Clone feature is not working as expected

### ISSUE THREAD

**Issue by aristocrat-vijay** [git/git-scm.com#1385]
Hi Team, 

Based on below reference, we were trying to evaluate git partial clone feature with git version 2.23.0 but its not working as expected. 

https://git-scm.com/docs/partial-clone

If we try to clone one of our repos using it, we are getting: “warning: filtering not recognized by server, ignoring”

Also tried by enabling below configurations. 

git config --global uploadpack.allowFilter true
git config --local uploadpack.allowAnySHA1InWant true

Please help…

Thanks & Regards
Vijay Kumar
Team Lead – DevOps, Systems |Aristocrat Technologies India Pvt. Ltd.
ETT-1, FC 15/16, 7th Floor,Sector-16A |Noida - 201 301
email – vijay.kumar@aristocrat.com|  +91-120-4669755  || 91-8588840638

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

If you need help with using git, you can ask the [community](https://git-scm.com/community)

**Comment by aristocrat-vijay** [comment]
Hi, 
Got email delivery failure for git@vger.kernel.org. 

This is a delivery failure notification message indicating that an email you addressed to email address :
-- git@vger.kernel.org

**Comment by jnavila** [comment]
The mailing list is picky about the format of emails: no attachments, no html.
