### ISSUE TITLE
include git tag or SHA1 of gitscm-next repo in published pages 

### ISSUE THREAD

**Issue by SethMilliken** [git/git-scm.com#140]
For folks reporting issues and checking whether committed fixes are actually reflected in the published site, it would be handy to have the tag or SHA1 available somewhere in the footer or in a `<meta>` tag.

**Comment by pedrorijo91** [comment]
@jasonlong do you want to think about this for the redesign? IMHO it is not needed: the site deploys on merge. If an deploy error occurs, heroku members (me and peff at this moment), get an email.

besides all of these, our agressive caching policy may not display the latest version immediately, but I can't imagine any urgent fix we need to have it deployed ASAP. 

If you agree, please close this issue

**Comment by jasonlong** [comment]
@pedrorijo91 :thumbsup: agreed
