### ISSUE TITLE
/site (About git-scm.com) conflicts with progit2 repository about issue report target

### ISSUE THREAD

**Issue by Chealer** [git/git-scm.com#1400]
According to [the About git-scm.com page](https://git-scm.com/site):

> Content from the ProGit book is imported from the progit/progit2 repository, which is available under a Creative Commons CC-BY-NC-SA license, as specified in the progit2 repository. Bug reports and suggestions may be made in the progit2 repository.

This contradicts progit2. When reporting an issue to progit2, the template contains:

> Before filing a bug please check the following:
> [...]
> * This bug is about the Pro Git book, version 2, English language.

I assume this is a bug in git-scm.com, since there are indeed different repositories for the book's translations (such as https://github.com/progit/progit2-fr/ for French).

- [X] This is **not** an issue about 
     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).

**Comment by peff** [comment]
Yeah, it would be nice to point that to the correct repository for each translation, but this message isn't even on a translated page. It also applies only if the problem is actually about the translation. If it's a technical problem that also applies to the English language version, it probably should be submitted there.

So I wonder if we should just clarify it with something like "...in the progit2 repository (or in the language-specific repository if it is an issue with the translation)." Is there a page we can link to that has the list of translation repos (@jnavila might know)?

**Comment by jnavila** [comment]
We have a list of translations of Progit [here](https://github.com/progit/progit2/blob/master/TRANSLATING.md) . The links in the Progit pages can be generated according to the translation list as [we already have them in the feeding script](https://github.com/git/git-scm.com/blob/b5f35141adf1b82b6d0c321a6c593383788c842a/lib/tasks/book2.rake#L188-L217)

It's just a matter of extending generation of manpage in a way similar to what was already done in #1364 for manpages.

**Comment by peff** [comment]
@jnavila Thanks, that's exactly the list I was looking for. I opened https://github.com/git/git-scm.com/pull/1401 which I think improves the situation. We could _also_ link to the project repo for the translation somebody is currently viewing, but the page in question isn't a book page. And we don't currently have a direct "report a problem" link from the book pages, I don't think.

**Comment by Chealer** [comment]
The proposed change is surely an improvement, but note that at least French is on version 1 of the book.

**Comment by peff** [comment]
Ah, yeah, that complicates things a bit. I think the new text is still probably the best we can do there. If it's a technical issue then it may exist in v2 as well, and could be reported in the main issue.

**Comment by jnavila** [comment]
@Chealer on git-scm.com French is in version 2. Version 1 has been removed from accessible links for a while now. If you get to the french translation via the navigation from the landing page, you get the v2.

**Comment by Chealer** [comment]
Thank you @jnavila, I hadn't realized the website hosted both versions and that Google web search had brought me to an old version.

Sorry for the noise. I suppose it may help to add a warning about that version of the book being deprecated.

**Comment by jnavila** [comment]
To prevent any future wondering, the solution is simple: remove v1. Will do.
