### ISSUE TITLE
Recommended text for no tracking information for the current branch

### ISSUE THREAD

**Issue by indiestream** [git/git-scm.com#1406]
I believe the upstream tracking information text that outputs when you don't have anything configured is wrong. Below is what is outputted for the recommended settings.

```
If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> develop
```

However that throws and error when used. I believe it used to be:

git branch --set-upstream-to=origin/develop

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
