### ISSUE TITLE
:(exclude) feature seems to be no longer supported 

### ISSUE THREAD

**Issue by SchlauFuchs** [git/git-scm.com#1407]
In our project build I noticed the following command no longer being supported after upgrading git from V2.17:

`git diff 607cba022eaba65809db049dc1f0f26f6315039a --name-only  --cached -- . ':(exclude)C:\projects\ourproject\common' `

The environment is Windows 10, 64bit. This has been tested on two developer boxes.
In V2.17 this command passes without errors, both running git.exe from _Git for Windows_ as well as cygwin git V2.17.
In V2.21 and V2.24 an error is reported:

`fatal: Invalid path '':/(exclude)C:': No such file or directory`

Is this a regression or do we have to update our build workflow?

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
