### ISSUE TITLE
Mintty.exe is a dialog instead of a terminal

### ISSUE THREAD

**Issue by mschroen** [git/git-scm.com#1416]
Git usually brings the mintty terminal, which can be found at `Git/usr/bin/mintty.exe`.
Today I updated Git for Windows (for a long time I didn't), and I found that executing mintty does not open a terminal anymore. Instead, it opens a dialog offering msys2 and mingw variants: 
![grafik](https://user-images.githubusercontent.com/7942719/72140578-5ce4e280-3391-11ea-9a88-f5093b6f2feb.png)

How can mintty (i.e., msys2) be opened directly without the dialog?
(msys2 seems not to have a single executable, the folder `Git/usr/bin/` only contains dlls...)

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)

**Comment by mschroen** [comment]
> 
> 
> Hey @mschroen
> 
> As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/).
> 
> Git for windows problems should be raised in https://github.com/git-for-windows/git

Thanks, I read only the first lines of the template, while the most important info is the last bullet point. To improve the template, I'd suggest to put in the first line: "Please only submit issues related to the Git-SCM Website!". Second line: your statement about what this issue tracker is NOT about, then followed by the items.

**Comment by pedrorijo91** [comment]
thanks for the suggestion @mschroen ! We will try to improve the template :)
