### ISSUE TITLE
Report a bug about this command "git reset head^".

### ISSUE THREAD

**Issue by wxdut** [git/git-scm.com#1420]
Git Verson: git version 2.24.1
Platform: macOS Mojave 10.14.6
Functions: git worktree.

I use the worktree to avoid checkout too many repos.
But When I execute this command: git reset head^, Terriable thing happenes:
您的分支和 'origin/xxx' 出现了偏离，
并且分别有 14517 和 18976 处不同的提交。

Anyone can help me ?

**Comment by pedrorijo91** [comment]
Hey @wxdut ,

As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
