### ISSUE TITLE
Responsive web site

### ISSUE THREAD

**Issue by agdod** [git/git-scm.com#1421]
- the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with https://git-scm.com/docs), which
 Please make the site responsive to it scale nivel on tablet and phones. Reading the documentaion on iPad would ne lot nivel if it was responsive. Having just completed my web design responsive  course i would be intrested on looking into this

**Comment by pedrorijo91** [comment]
hello @agdod.

There's a work in progress effort for this by @tarebyte on #1179 

Thanks for showing availably to help!! tarebyte has been a bit busy, but maybe you could help him

**Comment by adsingh14** [comment]
Hi there! I would also like to contribute.

**Comment by adsingh14** [comment]
> Please read the README file to know how to feed and index the manpages and update the downloads. Everything is described in it.
> 

I've followed all steps and downloaded only 'en' locale book. I ignored after 'OR' commands because those were slower.

**Comment by adsingh14** [comment]
@jnavila  I've re-run commands. Only 'Complete list of all commands' page is now working which is enough for making the website responsive. Now, I just want to know how to run search offline ?

**Comment by adsingh14** [comment]
Shall I upload responsive layout of current website ?

**Comment by adsingh14** [comment]
I got an issue, `media-query` is not working after I continue to code on local space.

**Comment by peff** [comment]
You probably need to run `rake search_index` to build the index (you'll want to make sure you've imported book and manpages (`local_index`, etc) so you have something to put in the search index.

**Comment by adsingh14** [comment]
@peff  I think this issue has been resolved.
