### ISSUE TITLE
"Git - SVN Crash Course" unreachable from the home page

### ISSUE THREAD

**Issue by phil-blain** [git/git-scm.com#1424]
### URL for broken page
Probably https://git-scm.com/doc ?

### Problem

The "Git - SVN Crash Course" page, available at https://git-scm.com/course/svn, and in the repo at [app/views/site/svn.html.erb](../blob/master/app/views/site/svn.html.erb), cannot be reached from the site home page.

### Context
I found this page via an unrelated Google search and was surprised because I know the website pretty well and hadn't seen that page before!

### Other details

Should some page of the site link to it ?

**Comment by pedrorijo91** [comment]
wow :) thanks for finding that one @phil-blain . I'm not sure, if git-svn it's still important as git became the standard nowadays. 

Furthermore, it seems the only legacy page under /course (https://github.com/git/git-scm.com/blob/master/config/routes.rb#L103), and there are plenty of tutorials of git-svn

should we simply delete it @peff ?

**Comment by peff** [comment]
My inclination is to delete it. None of us even knew it was there, and who knows how stale the content is.

**Comment by pedrorijo91** [comment]
closed by #1426
