### ISSUE TITLE
docs: link to https://github.github.com/training-kit/ instead of the PDF cheat sheet ?

### ISSUE THREAD

**Issue by phil-blain** [git/git-scm.com#1425]
### URL for affected page

https://git-scm.com/docs/

### Problem (not really a problem)

The "Reference" page links to the GitHub Git cheat sheet PDF at https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdf, which is in English. However, the website https://github.github.com/training-kit/ has versions of this cheat sheet in several other langages, as well as a cheat sheet on using submodule vs subtrees and another on SVN Migration. 

I think it could maybe be good to link to https://github.github.com/training-kit/ directly instead of linking to the English PDF cheat sheet. What do you think ? @peff @pedrorijo91

**Comment by pedrorijo91** [comment]
@phil-blain thanks for reporting this issue as well. 

I think this website is new. They had a previous version of this, which became dead, so we linked to the PDF directly IIRC. 

But it sounds good to update the link on my side. Are you open to contribute? :)

**Comment by peff** [comment]
Yeah, I think linking to the translated list of sheets would be great. If the HTML version of the English one mentioned the translations, I'd perhaps suggest linking there to save people reading in English a click. But it doesn't seem to, so the full list seems like the best bet.
