### ISSUE TITLE
Missing branch name in git pre-push hook (especially for remote delete)

### ISSUE THREAD

**Issue by zeleznypa** [git/git-scm.com#1429]
There are two different topics, that can be done by the `git push` command.

- when I push the data into the remote branch/tag  (`git push origin branch`)
- when I delete the remote branch (`git push origin :branch`)

I want to start automatical code-check when I "push data into the remote branch", but I really don't want to wait for code-check, when I decide to delete the remote branch.

I have found a workaround with [`ps` command](https://gist.github.com/lyoshenka/158cfff41d09e1dcf029#file-pre-push-sh-L17) but it is not 100% working, because of the docker containers sometimes don't have the `ps` command available.

Will it is possible please, to add the "branch name" (or `:branch`) as the third parameter for `pre-push` hook to work with?

**Comment by zeleznypa** [comment]
It will be also useful to convert `git push origin -d branch` or `git push origin --delete branch` or `git push origin :branch` to the same `:branch` value as a `pre-push` parameter.

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
