### ISSUE TITLE
Feature: git gui should run commands in "visualise master history"

### ISSUE THREAD

**Issue by mufti11** [git/git-scm.com#1433]
It would be very helpful, if the git gui "visualise master history" window would
be able to run a configable command for earch versioned file.

When you are working with data files (e.g. X3D files), a diff output is not much useful, instead a the start of a viewer for each file would be great.

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
