### ISSUE TITLE
git p4 unshelve command issue

### ISSUE THREAD

**Issue by GitForMike** [git/git-scm.com#1440]
Hi.
I got problem when using ‘git p4 unshelve [shelve id]’.

Usually it works fine. 
But when handling some shelves it returns error with below msg.
[file path]#none -no file(s) at that revision

But direct perforce command is working well in same environment.
‘p4 unshelve [shelve id]’

Could you help me solve this issue?

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
