### ISSUE TITLE
Some man pages still show Git 2.25 version

### ISSUE THREAD

**Issue by phil-blain** [git/git-scm.com#1445]
### URLs for broken pages
https://git-scm.com/docs/git-clone/
https://git-scm.com/docs/git-restore
https://git-scm.com/docs/git-help
https://git-scm.com/docs/git-init
https://git-scm.com/docs/git-add
https://git-scm.com/docs/git-status
(probably others as well) ...

### Problem

It's the Git 2.25.0 version of the man page. Navigating directly to https://git-scm.com/docs/git-clone/2.26.0 still lands me on 2.25.0

### Context

macOS 10.11.6 - Chrome

### Other details
This might be the same issue as happened before:
https://github.com/git/git-scm.com/issues/1153

~Note that it's not just an issue of the page displaying "2.25" but showing the 2.26 content (at least for `git clone`), it's really showing the 2.25 content (I noticed because the `git clone` page doesn't mention the new `--filter` argument)~.
**EDIT**: I'm not sure of that anymore since `git clone --help` does not talk about `--filter` either, so maybe this is a bad example...

**Comment by peff** [comment]
I don't think any of those pages have changes between v2.25.0 and v2.26.0:

```
$ cd /path/to/git.git
$ cd Documentation
$ git diff v2.25.0 v2.26.0 git-{clone,restore,help,init,add,status}.txt
[no output]
```

It's a quirk of the versioning code and schema that it doesn't recognize the newer version in that case (patches welcome, of course; it just hasn't been a big enough priority for anyone to tackle).

#1153 was a caching issue where there really were changes that didn't show up. I don't think it has been fixed either. If you find a page where there actually is a diff between versions that isn't showing, I can try flushing the redis cache.

**Comment by phil-blain** [comment]
OK. Sorry for the noise. I'll try to write to the list as to why `--filter` is not in the man page for git clone then.

**Comment by peff** [comment]
It was added in git/git@4a465443a6ce51bd6e1d4ffef56d3f2e8d45f506, which is in `pu` but not yet in `next`.

**Comment by peff** [comment]
Closing this out, but please reopen if you find any pages that do have differences that aren't being reflected.
