### ISSUE TITLE
Latest macOS Download Pulls 2.23 instead of 2.26

### ISSUE THREAD

**Issue by say25** [git/git-scm.com#1446]
### Problem

Latest download points to wrong location

### Context

macOS, Chrome

**Comment by ttaylorr** [comment]
The macOS installer is built by a volunteer, so it can lag behind the latest upstream from time to time. When a new version is published, the site will automatically update.

**Comment by peff** [comment]
This is a frequently asked question, so I opened #1449 to help address it.
