### ISSUE TITLE
How to uninstall this or upgrade it to git 2.26 ?

### ISSUE THREAD

**Issue by paulgureghian** [git/git-scm.com#1448]
![git](https://user-images.githubusercontent.com/8146561/79147818-6b201180-7d79-11ea-9b52-5b306887ddb3.PNG)

I tried Choco and some other commands.

**Comment by peff** [comment]
This repository and issue tracker is only for the git-scm.com website; problems with Git itself should be discussed elsewhere.

Probably the mailing list or issue tracker linked from https://gitforwindows.org/ would be your best bet.
