### ISSUE TITLE
{litdd} instead of double dash/hyphen (--) in docs

### ISSUE THREAD

**Issue by jakseb** [git/git-scm.com#1452]
Some pages in 'Documentation/Reference' contain a sequence `{litdd}` where `--` should appear. For example, the description of `--web` in [git-help](https://git-scm.com/docs/git-help) has:

> If none of these config variables is set, the **git web{litdd}browse** helper script (called by git help) will pick a suitable default. See **git-web{litdd}browse[1]** for more information about this.

**Comment by jnavila** [comment]
That's a difference between the asciidoc+docbook and asciidoctor. I think it shoud be upstreamed.

**Comment by peff** [comment]
I don't think it is. The `{litdd}` attr is an invention of the upstream manpages, and is defined in `asciidoc.conf` or [on the command line](https://github.com/gitster/git/blob/v2.26.1/Documentation/Makefile#L205) for asciidoctor. I think we'd need to do something similar when we format the pages.

As an aside, before figuring that out I also wondered whether it might have to do with our somewhat ancient version of the asciidoctor gem. Perhaps it's time to upgrade.

**Comment by jnavila** [comment]
Oh, that's clearer. And easy to solve.

**Comment by jakseb** [comment]
I tried to fix this on my own a few moments ago and I found that `compat-mode` needs also to be defined, otherwise `{litdd}` inside single quotes will not be expanded.

**Comment by peff** [comment]
@jakseb Interesting, I didn't need to do anything about `compat_mode` and the output looks fine (including the one in single quotes in `git-help`). I think compat-mode should be kicking in automatically due to the way the upstream manpages are formatted (using a 2-line title).

I've opened #1453, which should fix this.

**Comment by jakseb** [comment]
@peff Maybe I just forgot to refresh the page in the browser after rebuilding docs.

**Comment by jnavila** [comment]
Normally, compat mode is enable by default when document title is using old setext-style (i.e., two-line). See https://asciidoctor.org/docs/migration/#compat-mode . This is the case for all manpages.

**Comment by jakseb** [comment]
I noticed there are still at least two pages whose issues could be fixed with `compat-mode`:

- [user-manual][]
    - the first two bullets under the [term `glob` in section 'Git Glossary'][glob-manual]: asterisks are misinterpreted as boldface (compare with the same part in [gitglossary][glob-glossary]),
    - in [section 'A birds-eye view of Git’s source code'][birdseye]: `->` in `&commit->object` misrendered as `→`,
- [api-trace2][], the last paragraph before 'Trace2 Targets': an asterisk issue similar to the above.

[user-manual]: https://git-scm.com/docs/user-manual
[api-trace2]: https://git-scm.com/docs/api-trace2
[glob-manual]: https://git-scm.com/docs/user-manual#Documentation/user-manual.txt-glob
[glob-glossary]: https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-glob
[birdseye]: https://git-scm.com/docs/user-manual#birdview-on-the-source-code

Asciidoc sources of those pages use new-style headers. So maybe it would be a good idea to request `compat-mode` explicitly, like [upstream does][git-compat].

[git-compat]: https://github.com/gitster/git/blob/v2.26.1/Documentation/Makefile#L203

**Comment by jnavila** [comment]
This [commit](https://github.com/git/git/commit/fd5b820d9c1688fde9505effd48a0d98be6a24cb) changed the title styling in the user's manual.

We have to force compat-mode, or correct to new mode (may break with asciidoc).

**Comment by peff** [comment]
Yeah, certainly if there are breakages, we'd be happy to take a patch to force compat mode (and since upstream is doing the same, we shouldn't get any surprises).
