### ISSUE TITLE
community: add mention of `git bugreport`

### ISSUE THREAD

**Issue by phil-blain** [git/git-scm.com#1464]
Git 2.27 adds the `git bugreport` tool. Probably this should be mentioned on the "Community" page, and maybe featured in the "docs" page also.

**Comment by peff** [comment]
Agreed that it is probably worth mentioning (post-2.27 release, obviously). It might be worth discussing wording with @nasamuffin on the list (and possibly getting an overall review of the bug-reporting advice on that page).

**Comment by nasamuffin** [comment]
I think it's a great idea. @phil-blain, were you wanting to work on it? Otherwise I can do a little blurb - I've got a couple more outstanding bugreport topics anyways, so I can still make time for it.

**Comment by peff** [comment]
@nasamuffin Oh good, I wasn't sure if you'd get the ping since you weren't already in the org (or at least the `@`-mention didn't autocomplete you :wink:). As somebody who's been thinking on this topic, I'd welcome any suggestions you have for improving the community page.

**Comment by phil-blain** [comment]
@nasamuffin you can go ahead.

While I have your attention, I noticed that MyFirstContribution, which I find is a really great resource, is not linked or mentioned from anywhere in the Git repo. I think it could be great to maybe mention it in `Documentation/SubmittingPatches` since it's linked to in the README, and probably also `.github/CONTRIBUTING.md` since that's what people are directed to on GitHub when they open a PR.

I added links to it in the website "Community" page and on Gitgitgadget's homepage but I think it deserves more exposure.

**Comment by nasamuffin** [comment]
Sure. I'll see if I can spend a little time this week or next week to add pointers all over :) Thanks for noticing!

**Comment by nasamuffin** [comment]
Should a patch for git/git-scm.com be reviewed on the list? Or should I just send a PR? I'm working on this today.

**Comment by peff** [comment]
> Should a patch for git/git-scm.com be reviewed on the list? Or should I just send a PR? I'm working on this today.

We've typically just used PRs for updates here. But then again, most of the changes aren't so community-oriented. The audience of Git devs here is _way_ smaller than it would be on the list. So I'm happy to review a PR here, but it might be a good opportunity to get wider input by sending a patch to the list.

**Comment by nasamuffin** [comment]
fyi: https://lore.kernel.org/git/20200528231608.59507-1-emilyshaffer@google.com/

**Comment by nasamuffin** [comment]
> @nasamuffin you can go ahead.
> 
> While I have your attention, I noticed that MyFirstContribution, which I find is a really great resource, is not linked or mentioned from anywhere in the Git repo. I think it could be great to maybe mention it in `Documentation/SubmittingPatches` since it's linked to in the README, and probably also `.github/CONTRIBUTING.md` since that's what people are directed to on GitHub when they open a PR.

https://lore.kernel.org/git/20200528234939.145396-1-emilyshaffer@google.com

> Same thing for "MyFirstObjectWalk" (could be linked to at then end of MyFirstContribution maybe ?

I think it's a fine idea; might also want to refer to it somewhere in other object walking docs. I'll save this task for another rainy day, but I won't be offended if you want to add it yourself :)
