### ISSUE TITLE
git svn crash in windows

### ISSUE THREAD

**Issue by mmkulikov** [git/git-scm.com#1469]
In file 'subversion/bindings/swig/perl/libsvn_swig_perl/swigutil_pl.c' line 1666: assertion failed (get_current_pool_cb != NULL)
      0 [main] perl 249 cygwin_exception::open_stackdumpfile: Dumping stack trace to perl.exe.stackdump

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
