### ISSUE TITLE
Lack of content: feature requests for git

### ISSUE THREAD

**Issue by WHK102** [git/git-scm.com#1473]
The website does not have a valid communication channel where to make comments regarding possible improvements to git, for example, the possibility of setting a static repository for git-shell.

**Comment by jnavila** [comment]
There's [this page](https://git-scm.com/community) which describes the communications channels available available for getting involved.

**Comment by WHK102** [comment]
Thanks, but:

- git@vger.kernel.org: Is the bug reports mailing list (not to report)
- https://groups.google.com/forum/?fromgroups#!forum/git-for-windows is for Windows specific threads.
- https://groups.google.com/forum/?fromgroups#!forum/git-users is for general beginners questions.
- https://github.com/git/git-scm.com/issues is for git-csm.com website only.
- git-security@googlegroups.com is for security reports (no feature request).
- irc.freenode.net#git is for the general community, no for send a feature request.
- https://git-scm.com/docs/SubmittingPatches is for send patches, but i want to request a feature, not develop the solution.

As you can see, there is no valid communication channel to send a feature request to the git project maintainers. This communication channel does not exist or is missing on the website?.

**Comment by antdog1982** [comment]
Add requests #1473 for "communication channel

**Comment by peff** [comment]
@WHK102 The vger mailing list is the place for _all_ discussion. That's what I was trying to get at with "questions and comments", but perhaps you can suggest a better wording.

I'm a little hesitant to explicitly say "send your feature requests here", because I don't want to create a false expectation that if people send in a feature request, it's likely to get picked up. It _might_ intrigue somebody on the list enough to work on it, but often not. Requests like "I think this feature is worth implementing, but I don't know how to do it; can somebody help me get started" are (in my subjective experience) more likely to get traction.

**Comment by pedrorijo91** [comment]
I can see why there may be some confusion. We start by saying the mailing list is open to questions/comments, but then we specifically say bug reports, which may give the impression it's just for bug reports (specially if we take into account that non-english speakers may have yet harder times understanding the sentence):

>  Questions or comments for the Git community can be sent to the mailing list by using the email address git@vger.kernel.org. Bug reports for git should be sent to this mailing list. 

Maybe something like the following would be a bit more clear @WHK102 ?

> General questions or comments for the Git community can be sent to the mailing list by using the email address git@vger.kernel.org. 
>
> If you wish to report any possible bug for git, please use this mailing list as well.

Feel free to make any other wording suggestion :)

**Comment by WHK102** [comment]
Thank you very much, it's true, I don't speak English, I use a translator. When I read that it says "Community", I understand that the suggestions can be exposed within a community but not necessarily reach those responsible for a project, or so I understand.

Generally, in most projects, the incident system also includes an option to present improvements, at least in that flow a state of moderation can be obtained directly towards the managers of a project, but in other cases such as git (Apparently) they omit these channels to avoid receiving changes and focus only on reporting problems.

Anyway, I understood that it is not a problem of lack of information on the part of the website but a communication problem on the part of the community that maintains the project.

Thanks for the clarifications.
