### ISSUE TITLE
community: let's feature Git Rev News!

### ISSUE THREAD

**Issue by phil-blain** [git/git-scm.com#1476]
I noticed [Git Rev News](https://git.github.io/rev_news/) is not mentioned on git-scm.com/community, I think it would be nice to mention it there.

@peff @chriscool

**Comment by pedrorijo91** [comment]
totally agree @phil-blain :) 

Do you want to make a PR adding a 'Newsletter' section to https://git-scm.com/community ?

**Comment by chriscool** [comment]
PR sent!
