### ISSUE TITLE
highlighted text has funny vertical centering

### ISSUE THREAD

**Issue by peff** [git/git-scm.com#1480]
I noticed that our `<code>` blocks on the site have funny centering (this is from https://git-scm.com/docs/gitattributes):

![highlight-top](https://user-images.githubusercontent.com/45925/85629612-2e597c00-b640-11ea-8421-ec5f6dd90daf.png)

There's no highlighting _above_ the words at all, but lots below. It makes those blocks look a bit off the baseline from the rest of the text (even though the words themselves are the right spot).

The same is true of the `highlight` class, which you can see at https://git-scm.com/community (look under the "IRC Channel" section). I suspect it's actually true of _all_ the text, but you don't see it in most places because without a change of background, the actual margin boundaries don't matter.

There's probably a simple CSS fix related to margins.

@jasonlong There's a reasonable chance you might know right away what's going on. But I'd welcome input or fixes from anyone. :)

**Comment by pedrorijo91** [comment]
in firefox mac os seems not to happen?

<img width="683" alt="imagem" src="https://user-images.githubusercontent.com/1999050/85634728-fcfaa380-b673-11ea-821b-81df0445a3f7.png">

**Comment by jasonlong** [comment]
@peff I'm not seeing this either in Chrome/Brave or Safari. I'm a Mac – is your screenshot from something on Linux?

**Comment by peff** [comment]
Interesting. I don't see the problem in Chrome on Linux, but I _do_ on Firefox on Linux. I double-checked with `--safe-mode` to make sure it wasn't some local config, but still saw the issue there.

**Comment by rimrul** [comment]
I don't see this happening it on Firefox 77 on Linux either.

>The same is true of the highlight class, which you can see at https://git-scm.com/community (look under the "IRC Channel" section)

Are we using that anywhere else? Because it looks like it doesn't belong IMHO.

**Comment by peff** [comment]
> Are we using that anywhere else? Because it looks like it doesn't belong IMHO.

No, some quick grepping shows it's not really used anywhere else. I wouldn't be opposed to `s/highlight fixed/fixed/` on that page.

**Comment by peff** [comment]
I'm also using Firefox 77 on Linux. I'm not sure what could be different. I removed my whole `.mozilla` directory in case there was something even `--safe-mode` didn't catch, and I still see it. I guess it could be related to some other system settings, but I'm having a hard time thinking of what (this is a 4k display and my `Xft.dpi` is set to 140, but it seems odd that would show up as a box-size or line-height issue).

**Comment by peff** [comment]
Ugh, I finally figured this out. It's a font problem. We specify `Courier, monospace` here. There isn't (usually) a true Courier on Linux. I'd be perfectly happy bumping to my normal monospace choice, but instead it picks `Nimbus Mono PS`, which claims to be an alias for Courier but clearly has some funky baseline issues.

Swapping it out for literally any other typewriter font like `FreeMono`, or even `Courier New` from `msttcorefonts`. I'll have to wrestle with Linux `fontconfig` to make sure I get a better `Courier` (it's hard to just dump Nimbus because it's one of the URW "base 35" fonts for doing postscript).

So sorry for the noise, and thanks to everybody who offered thoughts.
