### ISSUE TITLE
Meu Git bash here não abre

### ISSUE THREAD

**Issue by Mateusprogramador** [git/git-scm.com#1481]
Meu git bash here não esta abrindo e eu acabei de instalar.

**Comment by pedrorijo91** [comment]
Ola @Mateusprogramador . Este repositorio é para problemas especificos encontrados no site gite-scm.com.

Aconselho os seguintes links:

* https://git-scm.com/community para problemas de git no geral
* https://github.com/git-for-windows/git para problemas de git em windows

Aconselho a fornecer mais informacoes: sistema operativo, versao de git, como é que instalou, qual o erro em concreto, e se ha algum log/mensagem de erro
 
ps: é mais facil obter ajuda pedindo em ingles, visto que a maioria das pessoas nao fala portugues aqui.

**Comment by pedrorijo91** [comment]
(for anyone interested in the conversation, it seems his git bash doesn't open. I showed him where he can get help for his issue)
