### ISSUE TITLE
git difftool --dir-diff broken when using links pointing outside of git folder

### ISSUE THREAD

**Issue by joachimlechner** [git/git-scm.com#1492]
Hi,

I am using git 2.17 and 2.22 and see the following issue.

git difftool -d <branch>
fatal: could not open '/tmp/git-difftool.pQZ8DA/left/test2' for writing: No such file or directory

I do not have a newer version available to try.
I could not find anything when searching the issues nor the web.
Sorry for that, if its already solved.
Is this issue fixed already in a newer version?
If so which version would I need?

Here a minimum example:

Many thanks in advance and BR, Joachim

rm -rf git_dir_issue
mkdir git_dir_issue
cd git_dir_issue

mkdir some_folder_outside_git
echo bar > some_folder_outside_git/bar
mkdir some_other_folder_outside_git
echo foo > some_other_folder_outside_git/foo
mkdir another_other_folder_outside_git
echo foo2 > another_other_folder_outside_git/foo2
mkdir another_other_folder_outside_git/test
echo foo3 > another_other_folder_outside_git/test/foo3

mkdir git_repo
cd git_repo
git init
touch test
git add test
git commit -a -m 'test'

git branch test_branch

ln -s ../some_folder_outside_git test2
git add test2
git commit -a -m 'test2'

git checkout test_branch
ln -s ../another_other_folder_outside_git/test test2
git add test2
git commit -a -m 'test2a'

git checkout master
ln -fs ../some_folder_outside_git test2
git commit -a -m 'test2a'

git difftool -d test_branch

=> fatal: could not open '/tmp/git-difftool.pQZ8DA/left/test2' for writing: No such file or directory

**Comment by peff** [comment]
This repository is just for the git-scm.com website, not Git itself. You'll have more luck getting an answer from the mailing list or one of the other venues mentioned in https://git-scm.com/community.

**Comment by joachimlechner** [comment]
Hi Jeff,

Sorry I did read to fast over the description of the git-scm website. My
fault.
I have posted the issue i have on the google group as suggested!

Thanks and BR, Joachim

Am Fr., 31. Juli 2020 um 03:05 Uhr schrieb Jeff King <
notifications@github.com>:
