### ISSUE TITLE
Heads up: ProGit2 build process is not providing .mobi files for now

### ISSUE THREAD

**Issue by HonkingGoose** [git/git-scm.com#1498]
### Which download is failing?

The link to the latest .mobi files at https://git-scm.com/book/en/v2 is gone.

### Problem

The .mobi files are gone upstream, and so the link to the .mobi files is too.

### Context

The ProGit2 project had to disable .mobi builds with https://github.com/progit/progit2/pull/1497 because the `kindlegen` gem that we use to generate the .mobi files whenever Travis CI makes a build cannot be downloaded anymore. See https://github.com/progit/progit2/issues/1496 for more on this.

### Steps to Reproduce 

1. Go to the https://git-scm.com/book/en/v2 once the git-scm site build is refreshed.
1. Click on the .mobi link.
1. It will probably break.

### Other details

Hi git-scm team, I wanted to provide a heads up for you. I hope I filled the correct issue template! :smile:

**Comment by pedrorijo91** [comment]
wow :) thanks a lot for the heads-up @HonkingGoose !

is there any ETA for getting the .mobi files working again? If I understood correctly, amazon stopped serving a binary which kindlegen wrapped?

**Comment by pedrorijo91** [comment]
I think it's just a matter of removing from the UI until things are solved, in these lines https://github.com/git/git-scm.com/blob/8b4de72025e2fa95491d86c7dc2185258d320d91/app/views/books/show.html.erb#L26-L30

**Comment by HonkingGoose** [comment]
I cannot provide any ETA on when the .mobi files will be available again, because I'm not the one that has the ability or knowledge to fix this.

You can follow the `asciidoctor-epub3` issue here: https://github.com/asciidoctor/asciidoctor-epub3/issues/363
and the upstream `kindlegen` issue here: https://github.com/tdtds/kindlegen/issues/42

**Comment by HonkingGoose** [comment]
> I think it's just a matter of removing from the UI until things are solved, in these lines
> 
> https://github.com/git/git-scm.com/blob/8b4de72025e2fa95491d86c7dc2185258d320d91/app/views/books/show.html.erb#L26-L30

Feel free to propose a pull request to delete the .mobi link. I would recommend putting a comment in, so that it's clear why the link was removed, and maybe link to this issue and the upstream ProGit2 issue. 

That way it's documented in your code what happened and why, and people can check if/when the issue is fixed and put the .mobi link back.

**Comment by HonkingGoose** [comment]
I visited the page after the site build refreshed: the .mobi link is gone. The pdf and epub have links to version 2.1.259, which are current as of now.

So maybe this takes no action on your side, and the system will just pick up the .mobi files once they are available again. :smile:

**Comment by jnavila** [comment]
Calibre has a converter to azw, but I fear the quality of the output is not the same as kindlegen.

**Comment by HonkingGoose** [comment]
Yeah I searched for some alternative tool-chain and stumbled into Calibre as well, it does have a command line interface that we maybe could use. That would probably require another Travis CI build chain to be built.

And we would first need to know if the .epub -> Calibre -> Kindle output is any good. So maybe we can get a Kindle user to do the conversion and report back on the results?

**Comment by peff** [comment]
> So maybe this takes no action on your side, and the system will just pick up the .mobi files once they are available again.

Yeah, I _think_ that's what's supposed to (and will) happen. But thank you very much for letting us know about the situation.

I suppose we could also provide an older version of the `.mobi`, if somebody feels strongly enough about that format that they'd prefer out-of-date content to using `.epub` or whatever. But I'd prefer not to get into that unless somebody asks for it.

**Comment by HonkingGoose** [comment]
Yeah, I agree: only provide outdated `.mobi` files if there is actual demand. 

This is also a good way to figure out if those `.mobi` builds are actually valued at all... I've yet to see a issue report here, or on the ProGit2 repo asking about the `.mobi` files.

**Comment by pedrorijo91** [comment]
not sure if it's possible to find out how many accesses to the mobi file there were before this. The url seems to be something like

```
https://github.com/progit/progit2/releases/download/2.*.*/progit.pdf
```

I can try to find out during the weekend perharps

**Comment by HonkingGoose** [comment]
Having some historical data would help with making the judgement call if the `.mobi` files are even worth the support/maintenance cost.

I've seen no comments/issues on the ProGit2 repo, asking about the `.mobi` files. So it could be that those `.mobi` files are not really in high demand.
Maybe people just use the version of the book hosted on the website (`.html`) or download the `.epub` and `.pdf` files for their e-book reader or local workstation.

**Comment by HonkingGoose** [comment]
I've opened a PR upstream at the ProGit2 repository that should re-enable the `.mobi` files. See https://github.com/progit/progit2/pull/1655, once that's merged I'll close this issue.

**Comment by pedrorijo91** [comment]
seems like the PR was already merged right @HonkingGoose ?

**Comment by HonkingGoose** [comment]
Yeah, but it's not working... I'm not sure what I need to do to fix it... 😕

**Comment by HonkingGoose** [comment]
Turns out https://github.com/progit/progit2/pull/1655 was a partial solution, that is not functional...

So I opened https://github.com/progit/progit2/pull/1656 to fix the bad PR, but I don't know how to get the build to work properly... 😞 If you (or anyone else) can help out, that would be great!

**Comment by HonkingGoose** [comment]
ProGit2 is publishing `.mobi` files again! Go to https://github.com/progit/progit2/releases to see the `progit.mobi` files. 😄 

The only thing left to do is to verify that `git-scm` picks up the new files correctly when your Heroku build process runs?

By the way, the `progit/progit2` repository now uses a `main` branch, instead of a `master` branch. This shouldn't cause issues as @peff already did some preparatory work with PR https://github.com/git/git-scm.com/pull/1502.

But you should still verify that things work properly after both those changes. 😉

**Comment by HonkingGoose** [comment]
> Having some historical data would help with making the judgement call if the `.mobi` files are even worth the support/maintenance cost.
> 
> I've seen no comments/issues on the ProGit2 repo, asking about the `.mobi` files. So it could be that those `.mobi` files are not really in high demand.
> Maybe people just use the version of the book hosted on the website (`.html`) or download the `.epub` and `.pdf` files for their e-book reader or local workstation.

The `progit2` repository maintainer has said that they consider providing the `.mobi` files to be very important. So we'll probably continue to provide these files, unless we encounter new issues with the toolchain. 😄

**Comment by HonkingGoose** [comment]
We did just migrate ProGit2 from **Travis CI -> GitHub Actions**. Maybe that's breaking something?

**Comment by peff** [comment]
> So it looks like something changed recently on the release-generation side, and the content-types were lost.

Diffing 2.1.308 and 2.1.309, it looks like the release creation now uses https://github.com/ncipollo/release-action, but doesn't pass `artifactContentType`, so the default is `raw`. It's not clear to me if that property can take a comma-separated list like `artifacts` does.

**Comment by peff** [comment]
> It's not clear to me if that property can take a comma-separated list like artifacts does.

Looks like no. The code seems to [apply a single content-type to every artifact](https://github.com/ncipollo/release-action/blob/a5a057b70732aaff1a5f3e4033950338ef662e7a/lib/Inputs.js#L40-L45). So a fix would probably involve extending that action, and then updating progit2 to make use of the new feature. Yikes.

Even if that happens, it may take a while. I think we should switch to selecting based on the names in the meantime.

**Comment by peff** [comment]
Should be fixed by #1615. Running it locally restores the epub and pdf links, and now generates a mobi link, too. :sweat_smile:

**Comment by peff** [comment]
OK, with #1615 merged, I kicked off a manual book generation job, purged the cloudflare cache, and now things are looking good: the main https://git-scm.com/book page has three links (epub, pdf, and mobi). So I think we're probably good to close this issue now!

**Comment by HonkingGoose** [comment]
Looks good to me on the deployed site as well.

I agree, let's close this issue! 😄

**Comment by muhamadhafizy1991** [comment]
![Screenshot_2021-10-08-05-04-11-82_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/92123873/136462061-b356ae36-4202-4efe-a6a8-f951e55da5b9.jpg)
Block block block all
