### ISSUE TITLE
installer locks up when testing custom editor notepad.exe

### ISSUE THREAD

**Issue by esaulpaugh** [git/git-scm.com#1500]
Git-2.28.0-64-bit.exe a8ef3311ac0c8747ba2f5aef3e475ad42fbc084ada7e6fb5060481a78c1a9cf2

using Windows 10 Pro version 2004 build 19041.450

select `Select other editor as Git's default editor`

specify location:

`C:\Windows\System32\notepad.exe`

click `Test Custom Editor`

**Comment by pedrorijo91** [comment]
Hey @esaulpaugh 

As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
