### ISSUE TITLE
Preventing problems with git-scm for Asciidoctor 2 and version bump to ProGit2 book generation.

### ISSUE THREAD

**Issue by HonkingGoose** [git/git-scm.com#1516]
### Incoming changes upstream ProGit2 English

- Migration from Asciidoctor `1.5.6.2` to Asciidoctor `2.0.10` for the ProGit 2 book generation.
- Potential ProGit 2 book minor version bump from `2.1.x` -> `2.2.x` (this is not yet fully decided yet)

### Questions for git-scm.com

1. The version of Asciidoctor that the book uses will change, is this a breaking change on your end?
1. Would bumping the ProGit 2 minor version number cause problems on your end? I notice you reference `edition 2` in the [book2.rake script](https://github.com/git/git-scm.com/blob/master/lib/tasks/book2.rake). Does that handle minor version changes automatically???
1. Is there something else that I should know about to prevent problems on your end?

### Reference for incoming change

You can see the work-in-progress pull request at https://github.com/progit/progit2/pull/1373 to get a preview of incoming changes.

**Comment by peff** [comment]
Thanks as usual for looping us in early on big changes. The bump to Asciidoctor 2.0.10 shouldn't be a problem; we're already using that version. So it's likely we may end up fixing any bugs if you make changes as part of the migration.

The `edition` field is our own internal value, to differentiate it from the 1st edition entries in our database. I don't think we look at any tags/releases from progit2 at all for the site content, and instead just always pull the latest tip of `HEAD`. So as long as we can continue pulling data from the same repo, I think we won't even notice the difference.

We do pull the ebook/pdf/etc links from the releases, but there we're just asking octokit for the latest release. We don't even look at the name or version number.

**Comment by HonkingGoose** [comment]
So we're good to go, as-is. :smile: 
Thanks for the response! :+1: 

Do you want to keep this issue open until ProGit2 has done the Asciidoctor 2 migration or do you want to close it?

**Comment by peff** [comment]
I'll close it; I don't expect issues, and if we do we can reopen (or make a new issue for the specific symptom).
