### ISSUE TITLE
Add intructions on the macOS dowload page for git-gui

### ISSUE THREAD

**Issue by unbeatable-101** [git/git-scm.com#1525]
Add `$ brew install git-gui` to the page

**Comment by pedrorijo91** [comment]
The idea for the page https://git-scm.com/download/mac is to focus on git itself, but I agree it could be useful to add a note learning on how to install git-gui (maybe even link to https://git-scm.com/docs/git-gui)

would you be interested in contributing @unbeatable-101 ? We can point out the file you would need to update

**Comment by unbeatable-101** [comment]
Yes, I would.

**Comment by pedrorijo91** [comment]
the file to be updated is located at https://github.com/git/git-scm.com/blob/master/app/views/downloads/download_mac.html.erb
