### ISSUE TITLE
Vulnerabilities 

### ISSUE THREAD

**Issue by unbeatable-101** [git/git-scm.com#1529]
![Capture](https://user-images.githubusercontent.com/58151048/98173655-6c558f00-1ec1-11eb-93f2-0d66f384cd6a.PNG)

**Comment by unbeatable-101** [comment]
Anybody can see these by forking it and enabling dependabot

**Comment by peff** [comment]
I don't think any of these are urgent; we don't actually perform any computation on the site based on user input, nor do we store any secrets in the filesystem or database (so information disclosure bugs, etc, aren't an issue). That said, I'd love to see the list cleared up. It looks like it will take some untangling of various dependent versions for the gems.

For the json bits, none of that is even run on the production site. We only have it for running grunt lint checks by developers. There's some dependency untangling that needs to happen around lodash. I spent an hour or three with it a long time ago and gave up in disgust.

So basically: yes, if you'd like to bring some of the dependencies up to date, I'd love to see a PR.

**Comment by HonkingGoose** [comment]
Hi @peff, I noticed you're not running any dependency management bot on this repository. Want me to get you set up with one?

I can make a pull request with a complete official GitHub-native *Dependabot* config that you can merge and enjoy right away without you needing to bother with configuring it. The main drawback of Dependabot is that it's a bit of a dumb bot, it's easy to use and get setup with, but it's not very configurable. The only way to turn down the "firehose" of updates is by limiting the schedule to a weekly or monthly run.

Or I can help you get started with the *Renovate* bot. That bot is more configurable, but the bot requires you to install an (GitHub verified) app into your organizations account.
You could for example have a "dashboard" where you can select what updates you want to get a PR for. You would have a list of all pending updates, and then you can pick and choose from the dashboard. That way you would only get updates when you're ready to deal with them. You can even "auto-merge" minor version bumps automatically so you don't have to deal with those. You can also limit the schedule in way more ways than you can with Dependabot.
I won't pretend to know everything about Renovate, but I can at least get you started, and call in extra help to configure the Renovate bot to your exact liking.

Let me know if you fancy either of those. And if you don't want any of those, let me know as well. :smile: 

References:

[Dependabot configuration options](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates)
[Renovate bot docs](https://docs.renovatebot.com/)
[Renovate bot docs on reducing the spam/noise of update pull requests](https://docs.renovatebot.com/noise-reduction/)

Greetings HonkingGoose

**Comment by peff** [comment]
@HonkingGoose We do have dependabot running, as it powers GitHub's baked-in security alerts. It's possible that adding more specific config could help, but I think the main problem is that somebody has to actually untangle the dependencies that dependabot can't manage to create a PR for.

**Comment by HonkingGoose** [comment]
@peff Did you fix these vulnerabilities with https://github.com/git/git-scm.com/pull/1598#issuecomment-812004486?

**Comment by peff** [comment]
The JSON ones were fixed recently, yes. I didn't dig, but the gem ones should have been fixed by #1548 (or possibly #1597). At any rate, dependabot has no complaints with the current state.

**Comment by peff** [comment]
I'm going to close this, since we're now at a clean slate with respect to dependabot.
