### ISSUE TITLE
Git Scm - Auto Fetch feature request

### ISSUE THREAD

**Issue by moyavuz** [git/git-scm.com#1539]
Git Scm - Auto Fetch feature request

The main purpose of these request is; Sometimes we forget to using fetch command during the development process. Because of this we think that **autofetch** property will be the best solution to solve this issue. 

For example, The help of the **autofetch=true** flag we dont need to use **git fetch** command before any other git command. So fetch command is worked automatically. This method will be increase productivity and development quality. 

If you need detail information please feel free get in touch with me on e-mail also. 

![autofetch](https://user-images.githubusercontent.com/15840603/99965077-627ac980-2da5-11eb-8311-63de75ba48d0.png)

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
