### ISSUE TITLE
Please improve documentation on git difftool/mergetool trustExitCode

### ISSUE THREAD

**Issue by SetTrend** [git/git-scm.com#1543]
_Please pardon me for being ignorant and wrong here, but I don't want to take the utterly annoying process of joining a cumbersome mailing list just to report a documentation flaw. The GitHub issue tracker seems much more appropriate channel to me. Hopefully, someone appropriate will read this issue:_

**The documentation on the `--trust-exit-code` option isn't consistent.**

### [git difftool](https://git-scm.com/docs/git-difftool)

> `--[no-]trust-exit-code`
>
> git-difftool invokes a diff tool individually on each file. Errors reported by the diff tool are ignored by default. Use --trust-exit-code to make git-difftool exit when an invoked diff tool returns a non-zero exit code.

### [git mergetool](https://git-scm.com/docs/git-mergetool)

> If the custom merge tool correctly indicates the success of a merge resolution with its exit code, then the configuration variable `mergetool.<tool>.trustExitCode` can be set to `true`. Otherwise, `git mergetool` will prompt the user to indicate the success of the resolution after the custom tool has exited.

### [StackOverflow](https://stackoverflow.com/questions/2069490/git-diff-with-beyond-compare#answer-3395497)

> About `trustExitCode`: For a custom merge command, specify whether the exit code of the merge command can be used to determine whether the merge was successful. If this is not set to true then the merge target file timestamp is checked and the merge assumed to have been successful if the file has been updated, otherwise the user is prompted to indicate the success of the merge. 
<br/>

Please elaborate in the documentation on what will happen when this option is set to `true`/`false`, resp.

**Comment by pedrorijo91** [comment]
hello @SetTrend ,

unfortunately this repo doesn't control the git documentation, so the best way to report the issue is indeed the mailing list. I don't think you need to join the mailing list as it is open to anyone:

>  Mailing List
>
> General questions or comments for the Git community can be sent to the mailing list by using the email address git@vger.kernel.org.
>
> If you wish to report any possible bug for Git, please use this mailing list as well.
>
>You do not need to subscribe: you will be Cc'd in replies. Please keep the Cc list intact when replying (use "Reply to all"). Greylisting may delay your first post for a few hours. Note also that the list only accepts plain-text email; please disable HTML in your outgoing messages.

**Comment by peff** [comment]
Yeah, you definitely don't need to subscribe to the list. But do watch out for the HTML thing, as the list's spam filter does not allow it.

> The GitHub issue tracker seems much more appropriate channel to me. Hopefully, someone appropriate will read this issue:

Sorry, but it's unlikely. This repo is only watched by people who work on the website. You'll get a much wider audience on the mailing list. You can also try irc if you prefer that (see https://git-scm.com/community).

**Comment by SetTrend** [comment]
@peff, @pedrorijo91:

It's like I feared ... it doesn't work:

_(In the following error report I replaced private data with an asterisk.)_
<br/>

> **vger.kernel.org rejected your message to the following email addresses:**
> 
> `git*vger.kernel.org (git*vger.kernel.org)`
> 
> Your message wasn't delivered because the destination email system rejected your message for security or policy reasons. For example, the email address might only accept messages from certain senders, or it might not accept certain types of messages, like those larger than a specific size.
> 
> Contact the recipient (by phone, for example) and work with them and their email admin to determine what policy or setting blocked your message and what you should do to make sure that future messages from you won't be rejected.
> 
> For more information, see Status code 5.7.1.
> 
> **vger.kernel.org gave this error:**
> ```
> Hello [*.*.*.*],
> for your MAIL FROM address <*****@hotmail.com> policy analysis reported:
> Your address is not liked source for email
> ```
