### ISSUE TITLE
"Guides" section of git-scm.com/docs/git shows wrong 'man' section

### ISSUE THREAD

**Issue by phil-blain** [git/git-scm.com#1546]
Compare:
- https://git-scm.com/docs/git#_guides (website) 
and 
- https://git.github.io/htmldocs/git.html#_guides (vanilla asciidoc version)

I think it's due to this line in the "index" task that hardcodes "1":

https://github.com/git/git-scm.com/blob/2534d29eb616117a07b7e00a86e3a46a95b94441/lib/tasks/index.rake#L195

I missed that in #1497...

**Comment by pedrorijo91** [comment]
cc @peff  and @jnavila  who have looked at #1497 deeper than I did. Any comments?

**Comment by jnavila** [comment]
IIUC, that's the man section that's false here. It should be inferred depending on the category's name. Is that correct?

**Comment by phil-blain** [comment]
Yes exactly. « 1 » is hard coded in the line I mention above.

**Comment by jnavila** [comment]
The site needs a rebuild for that change to appear.

**Comment by phil-blain** [comment]
@jnavila thanks for working on this. But some guides are in section 5 and some are section 7. That’s why the Perl script in git.git now reads the section directly from the Asciidoc source using a regex...

**Comment by jnavila** [comment]
Ooops. Too hasty...
