### ISSUE TITLE
Move from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by HonkingGoose** [git/git-scm.com#1559]
The Travis CI on the `.org` domain is shutting down very soon.
After the shutdown no tests will run on pushes to `master` or when PRs are opened that target `master`.

Travis suggest that you migrate to their offering on the `.com` domain. You get a one-time 1000 minutes of build time. After the free one time credit is used up, you can apply to open source plan where "upon validated request you may receive free OSS credits for your public builds".

Quote from https://www.travis-ci.com/plans

> Free for open source. We love the Open Source Community, and to show how much we love it, upon validated request placed with our Support Team you may receive free OSS credits for your public builds.

I think the easiest thing is to migrate to GitHub Actions, as those are free for public repositories, with no strings attached.

[GitHub docs on migrating from Travis to GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions)

**Comment by pedrorijo91** [comment]
I think it may be easier just to ask for free credits. but if anyone wants to work on the migration for github actions it would be ok as well

cc @peff it seems we need an admin on this:

* https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setup
* https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

**Comment by pedrorijo91** [comment]
This may be a good first issue for someone wanting to contribute. setting up a new CI is not rocket science, specially if you have used that CI before. and we don't do a lot for travis: https://github.com/git/git-scm.com/blob/master/.travis.yml

**Comment by jnavila** [comment]
Plus we really need some reliable test (see #1561)
