### ISSUE TITLE
Paste not working in Git Gui

### ISSUE THREAD

**Issue by milindck** [git/git-scm.com#1560]
### Paste is not working as expected in the commit message

When I type some text in the commit message and then select part of the message and then use paste, the expected behavior is that the selected text must be deleted and in place replace with the pasted text. But the way it is working is that it inserts the message without deleting the selected text.

### Steps to Reproduce 

1) Copy some text to clipboard by selecting some text and then pressing `Ctrl + C`
2) Open GIT GUI by typing **`git gui`** 
3) Type some text into the commit message. e.g. "`This is a message`"
4) Select some text e.g. select "`This is a message`"
5) Paste from the clipboard. e.g. by pressing `Ctrl + V` to paste the clipboard content.

expected behavior is that the selected text is replaced with the pasted text. But it inserts the pasted text instead of deleting the selected text and replacing it with the pasted text.

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

book related issues (i.e. anything with a URL starting with https://git-scm.com/book or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
