### ISSUE TITLE
https://git-scm.com/docs/git-config.html is slow

### ISSUE THREAD

**Issue by jnavila** [git/git-scm.com#1563]
### URL for broken page

Try https://git-scm.com/docs/git-config.html

other webpages seem to work correctly e.g:
https://git-scm.com/docs/git-add.html

**Comment by jnavila** [comment]
It is back on-line. But it takes a lot of time, just as if it was not cached and served by Heroku.

**Comment by peff** [comment]
I was able to reproduce and grab a log from the production site. It indicates we were timing out while building the version-list box, which is something that's given us trouble before:

```
Started GET "/docs/git-config" for 172.69.33.156 at 2021-01-07 23:18:53 +0000
Processing by DocController#man as HTML
  Parameters: {"file"=>"git-config"}
  Rendered doc/man.html.erb within layouts/application (Duration: 15616.8ms | Allocations: 3766151)
  Rendered layout layouts/application.html.erb (Duration: 15618.9ms | Allocations: 3766470)
Completed 500 Internal Server Error in 15686ms (ActiveRecord: 1712.2ms | Allocations: 3768338)
Rack::Timeout::RequestTimeoutException (Request waited 13ms, then ran for longer than 15000ms ):
app/models/doc_version.rb:30:in `diff'
app/models/doc_file.rb:63:in `block in version_changes'
app/models/doc_file.rb:48:in `each'
app/models/doc_file.rb:48:in `each_with_index'
app/models/doc_file.rb:48:in `version_changes'
app/views/doc/_versions.html.erb:11
app/views/doc/man.html.erb:8
app/views/doc/man.html.erb:4
```

I'm not sure what changed:

  - if the code got slower; perhaps the new ruby/rails are slower for some reason

  - if we were just creeping up on the timeout and it crossed the line as we added more versions to process. A while back I limited how far back we'd go to avoid this growing without bound. We might need to do so again.

  - the sql server was just slow due to other load (perhaps not even ours). IIRC one of the problems with building that list is it makes a lot of queries (possibly even `n+1` if there are `n` versions of the manpage)

**Comment by pedrorijo91** [comment]
we have been having a lot of alerts from heroku for response times, but I could not get some free time to look at it yet. maybe the problem is here.

As a quick fix, limiting the number of versions a bit further seems like a good idea, while we can't find some time to improve the queries

**Comment by peff** [comment]
The cutting-off hack was actually not so long ago: less than a year in 63b66f5e773dce4fed6a37d309396b31f952d438. There have only been 4 major releases since then, though there were some maint ones, too.

If we more aggressively avoid intermediate maint releases, like so:

```diff
diff --git a/lib/tasks/index.rake b/lib/tasks/index.rake
index a6954e56..4e8b6db4 100644
--- a/lib/tasks/index.rake
+++ b/lib/tasks/index.rake
@@ -122,8 +122,8 @@ def drop_uninteresting_tags(tags)
         numeric = Version.version_to_num(tag.first[1..-1])
         # drop anything older than v2.0
         next if numeric < 2000000
-        # older than v2.17, take only the highest release
-        if numeric < 2170000 and !ret.empty?
+        # older than v2.30, take only the highest release
+        if numeric < 2300000 and !ret.empty?
```

that does cut us from 70 versions to 31.

**Comment by pedrorijo91** [comment]
I'm ok with trying that solution and see if things improve :)

**Comment by peff** [comment]
>  IIRC one of the problems with building that list is it makes a lot of queries (possibly even n+1 if there are n versions of the manpage)

Sorry, I was wrong here. I just ran it locally and it is only one query, which doesn't take all that long. The slow part is actually processing the data in ruby.

Running it locally on my laptop, it takes ~5s to render the page. If I cut off point releases as in the diff above (and then clean out the old ones and reimport based on the now-smaller list), it still takes ~4s. So better, but not substantially so.

TBH, I'd consider just removing the "diff" part of the version box anyway. I think all of this effort is going to produce the little red/green diffstat image for each:
![diffstat](https://user-images.githubusercontent.com/45925/104003812-f0055380-5170-11eb-9472-6c79f4b72b15.png)

If we instead just showed the list of versions that made any change at all, that should be much cheaper. I think we store a sha1 of the content of each page, so we should be able to just retrieve those and walk the sorted list of versions, comparing hashes (that saves us not only from doing a diff, but also from pulling the manpage content from sql at all; I suspect the problem with `git-config` is that it is touched in a lot of versions _and_ it is a large file).

**Comment by jnavila** [comment]
Otherwise, we could just cache the dots when building the manpages (provided we add the version in ascending order).

**Comment by peff** [comment]
> Otherwise, we could just cache the dots when building the manpages (provided we add the versions in ascending order).

I think we do add things out of order (e.g., we may release v1.2.3 after v1.3.0 has come out). It would probably be fixable by sorting the whole list and re-adjusting the neighbors of any newly-added items. But if we are not going to rip it out entirely, I think the speedup you showed in #1567 should be plenty.
