### ISSUE TITLE
git merge doesn't work correctly

### ISSUE THREAD

**Issue by dengxiao0509** [git/git-scm.com#1568]
Recently, i met a stange problem, which causes wrong merge result.

this is the merge commit info ( we can see that, git thinks only one parent modified the key line I mentioned below, so it doesn't appear in the git show output) :

![image](https://user-images.githubusercontent.com/11377310/104116768-98284180-5356-11eb-865e-99a624bccb64.png)

commit b2a51158ffd7e316c8722e83b0cba1cd8a48b459
Merge: bfa3abde47 de67d8cb40
index 0202cbdaca,d3b4568b9b..a71884d28a

bfa3abde47 is parent 1 (current branch), and de67d8cb40 is another parent 2 (branch to merge), and 

0202cbdaca is the file blob for parent 1 , de67d8cb40 is for parent2.

the base commit is ad0b2c3e4abf6305a9c7c7952e144abef93b021e, and the blob for the file is a0f67f3f01ec238ed9c284c70fdd2c05178d826e, I found it like this:

-----------
$ git cat-file -p ad0b2c3e4abf6305a9c7c7952e144abef93b021e                                        
tree 4cd8f022c06c1e8fa1ba2aedb564cc562bf72670
parent 984f93c60e4c8550ae647d3d2e5e7fbe8cb76179
author ameliexx <ameliexx@xxxx.com> 1610005740 +0800
committer xxxx <xxxx@xxxx.com> 1610007566 +0000

ameliexx: xsplitChunks mr_link xxxx                               

$ git cat-file -p 4cd8f022c06c1e8fa1ba2aedb564cc562bf72670                                        
100644 blob 9482c12fca6c4be75a59ec9ad6666f0dbdf26f7f    .code.yml
100644 blob 3e16e7f1b100b1c19741049a0de54882f2765ba4    .commitlintrc.js
100644 blob fb43e5c2954425c42ce7ecadf85c40fd2c8bdcc8    .editorconfig
100644 blob cd7ea942b6c51bbb92f333c6edc437fe66e6525e    .eslintignore
100644 blob 163da1e9fc7b253bc4a0871d0f96061a73fd9d81    .eslintrc
100644 blob b007b9bfc453009914deac0e09150425e541fee2    .eslintrc_tencent
100644 blob c380eed034882f318fba08c4537ea7a77d163715    .gitignore
100644 blob 45772f0e4f940980af628952a56504bc688efa76    .huskyrc.js
100644 blob d37a523e55f5137628350202708dea053afa674c    .npmrc
100644 blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391    BLADE_ROOT
100644 blob fe54a1adcd227e7b92c7ef711a80e73d0ce212af    OWNERS
100644 blob 9038f9187db8be5b57a7c35f72595bed2871f267    README.md
040000 tree 66e6798db706ae9498c435ee84110ad77454b397    app
100644 blob 425ffb6c1fe99c9db4497b80318dc7a06aaddeec    babel.config.js
040000 tree af8b2966fcf6e7fcab91be296e2432291b79d80b    base
040000 tree 6cc7084efca59a18da6c7187329f434f1008390e    e2e_test
100644 blob d6400721ff57fa61805ed39539ec648ebabffdbd    legit.conf
040000 tree 2bf2a54b8b9659c257e74c2b556580daeb2623f0    lib
100644 blob b4fb3535f9541e86e0d47654caec99dcde27c502    lint-staged.config.js
100644 blob 213aac882b58e27a8a129a7b7c162c6e4f2c7a5b    package-lock.json
100644 blob 567d8221c6764c4b0e6e4999a7fc3f86b7496e08    package.json
040000 tree 0e1e59a8a02b1f1e767831ec35506f80a2a0b23d    rpc
040000 tree 3cbf584cf73d39e92d9fb5bf1240589536584f62    scripts
100644 blob c453e2d37d26cb0fb6ed9a3a1e92b29a71c24e7a    tsconfig.json

$ git cat-file -p 66e6798db706ae9498c435ee84110ad77454b397                                        
040000 tree 13165e2c191ccf1eba9fb1ff28bb069ba6c95522    atlas_v2
040000 tree bd2501849fa9ca4829dac2498e4a6d791624ea7e    domain-home-page
040000 tree d7fa2a5259abbb64bc14c3921e4abbaa87065258    order-page
040000 tree 8e1198693c8d43d22aae25bf4db2ef4eac937446    phoenix
040000 tree 6cdd674720e7b3c306b402a4edd418ba556a5569    user-report-page

$ git cat-file -p d7fa2a5259abbb64bc14c3921e4abbaa87065258                                        
100644 blob ea8235f5b2ec4d916103fad29727fbc394d09e5c    CHANGELOG.md
100644 blob 2a55055f62c41f94ce86159594e98a6791f369b1    OWNERS
040000 tree 9aea105de0056187cb9d14c8dba2f2ce5cbcff3f    __mocks__
100644 blob 235145d5ec32f98e8f216c1d11ae72531f4f56ba    babel.config.js
040000 tree 5487f80b454d1cdaace7ffc7bb0ff6404ad13fef    cfg
040000 tree aa8b9bef7d8f684446287ccb8f57f594371b9941    code-templates
040000 tree 698d0d9c9bafe0fdcdccc47f07ec0e0657cd3dd7    externals
100644 blob 1eebda359147b73b526abfc05250be4ed952f4dc    jest-setup.js
100644 blob 03f516054ddfd89bfa03dae1ac8cefa68c461647    jest.config.diff_coverage.js
100644 blob 7c291ca198832b9841e3a31b53c8ed0328b8a479    jest.config.js
100644 blob 99f7b7b8a3786f56445704aa5ab789814ed9465d    jsconfig.json
100644 blob 735cee63b3e58ebf000218209aadcc6fa7135d05    jsdoc.conf.json
040000 tree 0cb0cf74634b3bc750abc418d5df0a5291580028    jsdocs_template
100644 blob a263daf33c802481bc12688e9aeb190631e44026    package-lock.json
100644 blob 5ab22015c540ea62b976eb7419e536d2d78a9f86    package.json
100644 blob 1e900709226ca41c36178d790d72e91b42e25ab5    readme.md
040000 tree 8fce53d8dc658cded008700163fa1f73fe7e6f1e    scripts
040000 tree 55f4ac170fc27a03f74f4d5ea806d01054304f7c    src
100644 blob 57d508f3dc23244e4a8ecede1c3a0037b6319270    tsconfig.json

$ git cat-file -p 55f4ac170fc27a03f74f4d5ea806d01054304f7c                                        
040000 tree e8ba7e1433b5d40cf34d6efd1f962233ce9fad99    __tests__
040000 tree 587dd4bc98f1539fc3ae4f792faa6aa52bcea969    actions
040000 tree d500f0eb1e3dac83b845029d834cab0bd403ceb8    bgm-instance
040000 tree e7f2caa73f8d929633f1b5676ed30bf7334be686    bgm
040000 tree 2adedbbf139d4395b46c249d45ca970fcfd650a6    biz-components
040000 tree d31d1c51cec5267a41d493635f1483b7a295e2de    collectors
040000 tree d8fdd7037851460cd9e2d240e586ad6fc4d3eb6a    components
040000 tree 1c94169b1d33d2d7cb6aa3d3bc6bec128572247a    components_v2
040000 tree 0d016e2b30c06bce30431f94af077433931c342a    config
040000 tree ca6beb004d4a3942c35640ae72c693ca474032b3    containers
040000 tree 58b17d656820fa841cc187e8b458a2cd2789c53a    featureflag
040000 tree d864455f1b218fdd2d9aa6d6d83fb57b3d73e9f1    hooks
040000 tree c64513bd5a9a37fadf3b20f34bb5e786db1a75a5    mapState
040000 tree 8332c9428a1ea1d30f09a491b10dc9706a7d8f06    models
040000 tree 90ec255f8d379614dbe6e8f65b9e79e782d65036    modules
040000 tree e9928cd62e3c54a16cff5c937a7dbb90cf59015e    pages
040000 tree 29daf2bc2245335ae3eeb70a01a3384db9676804    reducers
040000 tree afbde70672889aeb92bd02eea3979cbf69ad0abd    stores
040000 tree 09c74f95ec654beff2de614812a3274b75ef4e97    targets
040000 tree 78fd983cd68fafa2fd6fd5114ab6ce22cc539cf3    tpl_v2
040000 tree a1229a36b3f21a1d2ebfe2b3ccfc3d2fe0d74495    web-components

$ git cat-file -p e7f2caa73f8d929633f1b5676ed30bf7334be686                                        
100644 blob 090e8b17c4f9fe378a747535fd066f9fb5a2603c    BaseModel.js
100644 blob a264dfb3193e0be74bcffb12104480903df424f8    README.md
040000 tree 6791629e3a0e566932ab17e7ba7f3b08f4f7e767    __tests__
040000 tree e842ed469446d37747e71978b45192d4868f7371    additional-site
040000 tree fe06f2fa118f4e9916210442d8e0bd6a6586c94d    adtargets-edit
040000 tree 914ae99a16f02da16899753216cba042e19765f7    change-items
040000 tree 5c769e0b1ba8a464a96676e1cc5a891099261e4e    cold-start
040000 tree a32af7990c02bad5c03f29354a0e37426331c98d    creative-form
040000 tree a1e64400a56e2d054fb5b28c78ae385037f210bd    demo
040000 tree baa0669b5b528b3a28b552f88bac86f4a381bb35    dynamic-product
040000 tree 70420e09e652910f91a865d4ac4fb63091431160    estimate
100644 blob 7786cc38acd5355dbd858f937b4dcc56c4607a92    helper.js
100644 blob f8478a1bc954d05ee6fa31a9814534cb91af2cc0    index.js
040000 tree c2203d719d6d00403741d5bd59c9ec9b33379c21    landing-page-info
040000 tree e72d5e8c8846fd540500f1d1ad16e003f95ec04a    single-dynamic-product-list
040000 tree 27c3400698ca766fdd1b13a7007fc666efab14df    wechatshop-product

$ git cat-file -p baa0669b5b528b3a28b552f88bac86f4a381bb35                                        
100644 blob 3d1a739e58615a96ab1987658636ff414eaec92a    README.md
040000 tree d61f478ee50897df64525d5e3ce983c74ec657a9    __tests__
100644 blob 51184abc02f61b9058947b2614b789ce81bf258d    adapter.js
100644 blob 1c21af3aeb51198473f5637afe4c19ff97a6f4ae    cgi.js
100644 blob 255b6781bdaa804082773c38df2580718cb65f6c    constants.ts
100644 blob 79c47f0e5a47730c8ab031699a4587d242497bc1    index.d.ts
100644 blob ab19c4d48174f413163d79c103a16ea741ddc9fe    index.js
040000 tree d71d78ec2ca74639f0540dc22fd76d8c4c4bdcd1    service
100644 blob 5f3b56b4bd882f99deca0aa6f5642a564f31fde5    state.ts
040000 tree 330be5720d0a63d1ec4440a3b87b99af85ab0f9e    utils
040000 tree 498f1047e751c3d13ad16e71c5ca0bc9a0d9ee3f    view

$ git cat-file -p d71d78ec2ca74639f0540dc22fd76d8c4c4bdcd1                                        
100644 blob c20b19fbf243bf60bbdfc3605b7f735c6447ec3d    index.d.ts
100644 blob d7761fddb953a4621456919ae4cd5d7825db4b24    index.js
100644 blob a0f67f3f01ec238ed9c284c70fdd2c05178d826e    privateServices.tsx
100644 blob 5adbeec358206fffa2d72c96dd699499d15eefed    publicServices.ts

$ git cat-file -p a0f67f3f01ec238ed9c284c70fdd2c05178d826e                                        

.....

  ensureCatalogListInfo: (forceUpdate = false) => (dispatch$, getState$, instance) => {
    return new Promise((resolve, reject) => {
      const state = getState$();
      const {
        status: originStatus,
        data: moduleData,
      } = state;
      // 按需加载
      if (originStatus?.show || canUseNewProductOrder()) {
        dispatch$(instance.privateServices.getDynamicListInfo(forceUpdate)).then((data: any) => {
          // getDynamicListInfo里可能会改变status，需要重新获取
          const upToDateState = getState$();
          const {
            status,
          } = upToDateState;
          instance.setting.setDynamicProductInfo(data);
          const envData = instance.setting.getEnvData();
          const {
            productType,
            campaignInfo = {},
            isProductAutoDetect,
            pageInfo,
          } = envData;
          const productOptions = genProductOptions(data, {
            productType,
            campaignInfo,
            isEdit: pageInfo?.isEdit,
            dpaFormat: moduleData.dynamic_ad_product_form,
          } as EnvData);
          const updateQuery = {
            productOptions: {
              $set: productOptions,
            },
          };
              
          if (canUseNewProductOrder()) {
            const newStatusState = update(status, updateQuery);
            dispatch$(instance.actions.setStatus(newStatusState));
            let _isProductAutoDetect = !!isProductAutoDetect;
                    
            const cache = getIsProductAutoDetectCache();
            if (cache) {
              instance.setting.onSetIsProductAutoDetect(true);
              _isProductAutoDetect = true;
          
/***************************
** this is the key line which is not merged correctly **
             **} else if (typeof isProductAutoDetect === 'undefined') {**

*****************************/
              if (productOptions && productOptions.length > 0) {
                // 默认选中“选择已有商品”
                _isProductAutoDetect = false;
              } else {
                if (canUseProductAutoDetect()) {
                  // 无商品，默认选中自动识别
                  _isProductAutoDetect = true;
                } else {
                  // 如果不在自动识别白名单，就置为“不选择”
                  if (!pageInfo?.isEdit) {
                    // 如果商品库为空，选择“不使用”商品
                    instance.setting.setNotUseProduct();
                    // 修改为常规广告
                    dispatch$(instance.services.onProductFormChange(null, true));
                  }
                }
              }
              instance.setting.onSetIsProductAutoDetect(_isProductAutoDetect);
            }
            const {
              dynamic_product_id: dynamicProductId,
              dynamic_ad_product_form: dynamicAdProductForm,
            } = moduleData;
            const isSDPA = isSingleDynamicProductForm(dynamicAdProductForm);
            if (isSDPA) {
              // 选中了选择已有商品且无商品库选中
              if (!dynamicProductId && typeof dynamicProductId !== 'number' && productOptions && productOptions.length > 0) {
                if (!_isProductAutoDetect) {
                  // 默认选中第一个商品库
                  dispatch$(instance.services.onDynamicProductIdChange(productOptions[0].value, true));
                }
              } else {
                if (canUseProductAutoDetect()) {
                  // 初始化商品库行业字段信息
                  dispatch$(instance.privateServices
                    .initCatalogIndustryConfig(productOptions, dynamicProductId));
                }
              }
            }
          } else {
            const newStatusState = update(status, updateQuery);
            dispatch$(instance.actions.setStatus(newStatusState));
          }
          resolve(true);
        }, (errorMsg: string) => {
          dispatch$(instance.privateServices.updateErrorByKey('productListMap', errorMsg));
          reject(errorMsg);
        });
      } else {
        resolve(true);
      }
    });
  },

......

-----------

(1) diff parent1 && base
![image](https://user-images.githubusercontent.com/11377310/104116859-53e97100-5357-11eb-986f-55618a95f349.png)

(2) diff parent2 && base
![image](https://user-images.githubusercontent.com/11377310/104116875-68c60480-5357-11eb-871f-e31729ed361b.png)
![image](https://user-images.githubusercontent.com/11377310/104116878-6c598b80-5357-11eb-9edd-e25c14f77785.png)

(3) diff parent 1 && merge result
![image](https://user-images.githubusercontent.com/11377310/104116899-a75bbf00-5357-11eb-88e3-7abaecea6624.png)

(4) diff parent2 & result - no diff for the key line

The pb is, we can see both parents modified the key line (parents 2 only adds some whitespaces), but when merging, git traited the line change only be changed by one parent (like git show above shows), so no conflicts shown about the line. And the result is that git used parent 2 as the result which is also strange , why not use that of parent 1 ?

**Comment by pedrorijo91** [comment]
hey @dengxiao0509 .

Unfortunately, as you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
