### ISSUE TITLE
Broken links in video/quick-wins

### ISSUE THREAD

**Issue by dlwlb** [git/git-scm.com#1577]
Numerous links are broken in the video graphics of Git Basics Episode 4, Quick Wins with Git (https://git-scm.com/video/quick-wins). See #957 for links in text.
* progit.org/book/ch*-*.html links (4) report 502 Bad Gateway
* http://help.github.com/send-pull-requests link at 2:25 redirects to docs.github.com then says page doesn't exist.
* http://whygitisbetterthanx.com link at 4:00 error ERR_CONNECTION_RESET

**Comment by dlwlb** [comment]
In case it helps to find replacements, here are the full links in context.
* Content, not files: http://progit.org/book/ch6-2.html 
* Opt in, not opt-out: http://progit.org/book/ch2-2.html 
* Open, not locked: http://progit.org/book/ch5-2.html 
* Distributed, not centralized: http://progit.org/book/ch5-1.html 
* Conversations, not cutoffs: http://help.github.com/send-pull-requests 
* Anywhere, not just online: http://whygitisbetterthanx.com/#everything-is-local

**Comment by pedrorijo91** [comment]
thank you for reporting this @dlwlb . Unfortunately we don't have control over the video content in order to update it.

I wonder if videos are not too much outdated, or if visitors find them interesting...

**Comment by dlwlb** [comment]
I am new to git and found them helpful, and would have wanted to read more from the links, especially to understand what was meant by the "Conversations" win.

**Comment by dlwlb** [comment]
If the video's links aren't fixed, a workaround might be to provide a comments area beneath where corrected links could be posted by community members.

**Comment by pedrorijo91** [comment]
I think the best solution may be to contact through the original video source (vimeo comments maybe?). For instance: https://vimeo.com/41027679

**Comment by rimrul** [comment]
The Author does seem to still work at github, so maybe we can convince them.

@matthewmccullough do you still have the old files for this video series and/or would you be interested in creating an updated version?

**Comment by rimrul** [comment]
> * progit.org/book/ch*-*.html links (4) report 502 Bad Gateway

Those should still roughly correlate with the corresponding chapters of the second edition of the book (chapter 6 became chapter 7)

https://git-scm.com/book/en/v2
> * http://help.github.com/send-pull-requests link at 2:25 redirects to docs.github.com then says page doesn't exist.

I think the closest modern option is 

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

> * Anywhere, not just online: http://whygitisbetterthanx.com/#everything-is-local 


The source for that page is still on github:

https://github.com/schacon/whygitisbetter/blob/master/index.html#L177

**Comment by pedrorijo91** [comment]
closing as it's a bit out of our control
