### ISSUE TITLE
Change reference to "filter-branch" in the topic Git-Branching-Rebasing?

### ISSUE THREAD

**Issue by SRM256** [git/git-scm.com#1583]
At the end of this page:
    https://git-scm.com/book/en/v2/Git-Branching-Rebasing
there is discussion of using rebase and filter-branch. When I looked up [the help for filter-branch command](https://git-scm.com/docs/git-filter-branch), the first thing I saw was a big warning saying that this command is not recommended for use and I should use something else (specifically [the git-filter-repo tool](https://github.com/newren/git-filter-repo/)). 

I wonder if the Git-Branching-Rebasing page should be rewritten to remove the reference to filter-branch and instead refer to the correct tools directly. (I am still very new to git and so I'm not proposing specific changes.)

**Comment by pedrorijo91** [comment]
hey @SRM256 and thanks for reaching out!

this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). That page, in particular, is from the  [progit/progit2 book](https://github.com/progit/progit2/issues), so i'd suggest to raise the issue there, but I think your suggestion may be very useful indeed
