### ISSUE TITLE
Git Merge: Cannot merge with conflicts without committing

### ISSUE THREAD

**Issue by SetTrend** [git/git-scm.com#1586]
I cannot submit to the mailing list. The mailing host refuses to accept my e-mail address:

> ```
> vger.kernel.org gave this error:
> Hello [40.92.*.*], for your MAIL FROM address <******@hotmail.com> policy > analysis reported:
> Your address is not liked source for email 
> ```

So, I don't have no choice than to post my feature request here:

<hr/>

In the process of merging two branches with merge conflicts, it's not possible to prevent a commit in order to inspect the result first. If I enter `git merge --continue --no-commit`, I get an error message.

After performing a comprehensive merge with merge conflicts, it should be possible to inspect the result first before committing. I know, I can eventually update the commit using `git commit --amend --no-edit --reset-author`, but I don't think that's a reasonable path to follow.

**Comment by peff** [comment]
> So, I don't have no choice than to post my feature request here:

Just because one venue does not work does not mean that another venue is actually going to be a good one. Almost nobody will see your message here.

That said:

> After performing a comprehensive merge with merge conflicts, it should be possible to inspect the result first before committing.

I don't know what you mean by "inspect", but after updating the conflicted files with `git add <file>` or `git add -u`, you can see the diff of what is about to be committed with `git diff --cached`.

**Comment by SetTrend** [comment]
> Just because one venue does not work does not mean that another venue is actually going to be a good one. Almost nobody will see your message here.

I agree. It's stupid, I know. I just took a chance here. It's the only related channel I could think of. The only suggested channel is blocked. No way to change that. If there'd been a better approach I certainly would have used that.

> I don't know what you mean by "inspect"

I mean: Inspect in a developer IDE, like Visual Studio Code.

This sequence currently doesn't work:

```ps
> git merge B --no-commit
   conflicts in ....
> git mergetool
> git merge --continue --no-commit
   successfully merged
> code .
> git commit -m "done"
```

The 3<sup>rd</sup> step won't execute.

**Comment by peff** [comment]
> If there'd been a better approach I certainly would have used that.

There's a git-users list hosted separately which might be less picky about your domain. There's also irc. See https://git-scm.com/community for links.

> This sequence currently doesn't work

I still don't understand what you're trying to accomplish. How does one continue a merge except by making a commit? What is it in the state before running that command that you want to change? Is it just that you have some entries marked as unmerged in the index, and you want stage the resolutions? I'd use `git add -u` for that.

**Comment by SetTrend** [comment]
Thank you for pointing me, @peff.

> I still don't understand what you're trying to accomplish

Well, the reason for the `--no-commit` option is obvious: Merge code bases into the working directory but don't commit the result, so manual amendmends to the code will be possible before finally commiting in a separate step.

The same process should simply be true for merge operations that had been interrupted by a merge conflict.

**Comment by peff** [comment]
I understand why you'd want `--no-commit` in the first command. But what do you expect `merge --continue --no-commit` to do, if it is not creating a commit?

**Comment by SetTrend** [comment]
Hmm ... Now I'm in doubt ... Isn't the following workflow sequence true:

![Workflow without conflict](https://user-images.githubusercontent.com/9283914/109796894-0253b900-7c19-11eb-9601-9a97cfe97d87.png)

_supposed behaviour:_
![Workflow with conflict](https://user-images.githubusercontent.com/9283914/109796900-054ea980-7c19-11eb-8819-a101dca31b99.png)

**Comment by peff** [comment]
You eventually have to `merge --continue` to make the final commit (or just run `git commit`; they are synonyms, see 367ff694281ce569edd8f6e444fc770f92f5d215). But before then, you are just collecting changes in the working tree (and in the index, if you ran `git add` or if the changes applied without conflict) that will go into that commit. After you've run `git mergetool`, your working tree should contain the resolutions, and you can use normal tools to look at them. Git-aware tools like vscode might look at the index, too, so you probably want to mark the resolved paths using `git add`.

**Comment by SetTrend** [comment]
I was able to reproduce this. Thank you for enlightening me.
