### ISSUE TITLE
Please enable fullscreen in vimeo videos

### ISSUE THREAD

**Issue by teo1978** [git/git-scm.com#1587]
The videos at https://git-scm.com/videos

e.g. https://git-scm.com/video/quick-wins

lack a fullscreen button. I see the iframes do have the `allowfullscreen` attribute. The issue seems to be in the videos hosted at vimeo. I think you need to edit the embed options on Vimeo's side and enable fullscreen.

https://vimeo.zendesk.com/hc/en-us/articles/115015759768-Fullscreen-button-missing-from-the-player#:~:text=Make%20sure%20the%20fullscreen%20button,these%20values%20are%20being%20retained.

**Comment by pedrorijo91** [comment]
hey @teo1978 

we do not have control over those videos, and we do not have contact with the owners in most cases.

as a workaround, firefox seems to allow to display the video in another window (which can be maximized): see the button at the right side of the video

<img width="676" alt="imagem" src="https://user-images.githubusercontent.com/1999050/109396218-75fb7a80-7928-11eb-8940-1b7d86ab633e.png">
