### ISSUE TITLE
unable to access

### ISSUE THREAD

**Issue by mofengfs** [git/git-scm.com#1588]
![image](https://user-images.githubusercontent.com/16655229/109421844-fcd95180-7a13-11eb-9606-eb8ad7667509.png)
![image](https://user-images.githubusercontent.com/16655229/109422056-ea134c80-7a14-11eb-8cef-7e5ad8fbb625.png)

Git has been working well, why is it not working these days?
This happened to both my company’s computer and my home computer. I guess it is a problem with the git server.

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)

**Comment by pedrorijo91** [comment]
furthermore, I'm able to clone the repo (mac os). So the problem can be on your network configuration, or in the git configuration
