### ISSUE TITLE
Is the auto-refresh from ProGit2 content working properly?

### ISSUE THREAD

**Issue by HonkingGoose** [git/git-scm.com#1589]
Changes from upstream ProGit2 are still not visible on the live pages on `git-scm.com`.

Steps to reproduce:

1. Upstream PR fixes bad Markdown link (merged 3 days ago): https://github.com/progit/progit2/pull/1603
2. Go to https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project
3. Scroll to very bottom of page.
4. See bad Markdown style link still present:
```markdown
For help on configuring your system and email, more tips and tricks, and a sandbox to send a trial patch via email, go to [git-send-email.io](https://git-send-email.io/).
```

Can you guys take a look at your logs to see if your local ProGit2 book content build is failing or something?

The ProGit2 project recently also updated their Rakefile to build the book: https://github.com/progit/progit2/blob/master/Rakefile
Maybe the change in the Rakefile is causing issues on your end?

Also the new link uses a caret `^` to open the link in a new browser window, is that supported on your end?

Quote from [Asciidoctor writers guide, links and images](https://asciidoctor.org/docs/asciidoc-writers-guide/#links-and-images):

> Since `_blank` is the most common window name, we’ve introduced shorthand for it. Just end the link text with a caret (`^`):

```
Let's view the raw HTML of the link:view-source:asciidoctor.org[Asciidoctor homepage^].
```

I hope this is enough info to help you get started with debugging! 😄

**Comment by jnavila** [comment]
The bug was not squashed on Heroku. So the script is choking for some reason.

**Comment by jnavila** [comment]
So the refresh is not working properly. Updates to gems of asciidoctor and rails make the update script crash.

**Comment by peff** [comment]
I re-ran the nightly build job after merging #1590, and the broken link is now fixed on the heroku site (the main `git-scm.com` site is still cached, but will catch up soon).

Thanks for calling attention to this, @HonkingGoose (and thanks @jnavila for the fix!). It's clear we need better feedback when the scheduled jobs fail.

**Comment by jnavila** [comment]
> It's clear we need better feedback when the scheduled jobs fail.

That's a recurring issue. Maybe we could at least check that the script works in CI.

**Comment by HonkingGoose** [comment]
Thank you @jnavila and @peff for fixing the problem! 🎉 🚀
