### ISSUE TITLE
Revert Command Variations

### ISSUE THREAD

**Issue by tabhresh** [git/git-scm.com#1592]
This can be a Concern / Bug / Issue

One quick query from a similar example with two different OS different response by git: 

Windows 10 Machine

1. Create 1st file(new.txt) and commit it – M1
2. Create 2nd file(abhi.txt) and commit it – M2 
3. Create 3rd file(temp.txt) and commit it – M3 
4. One liner log shows 3 commits with 3 files created
5. Run – git revert 0cef110 – the commit id of M2 
6. File abhi.txt is removed from the repo 
7. Now Run – git revert 85398fc – the commit id of M3 
8. Now all 3 files are back in the repo - new.txt, abhi.txt, temp.txt 
9. The status is clean and clear of the repo.

 
Ubuntu Machine 

1. Create 1st file(new.txt) and commit it – M1 
2. Create 2nd file(abhi.txt) and commit it – M2 
3. Create 3rd file(temp.txt) and commit it – M3 
4. One liner log shows 3 commits with 3 files created 
5. Run – git revert 0cef110 – the commit id of M2 
6. File abhi.txt is removed from the repo 
7. Now Run – git revert 85398fc – the commit id of M3 
8. Now only one file is present in the repo new.txt 
9. The status is clean and clear of the repo .

Which one is resulting correct and what is correct according to your understanding.
My execution steps are added in the attached file.

[Steps1.docx](https://github.com/git/git-scm.com/files/6132742/Steps1.docx)

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/issues/new/choose), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).


Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)

**Comment by pedrorijo91** [comment]
furthermore, the linux version seems the correct behaviour, so it may be some problem with [git for windows](https://github.com/git-for-windows/git)
