### ISSUE TITLE
The setup files are corrupted. Please obtain a new copy of the program.

### ISSUE THREAD

**Issue by StefanSigfried** [git/git-scm.com#1599]
Trying to download git I get:
First windows defender says the file is not to be trusted. Trying to install anyway gives this error:
The setup files are corrupted. Please obtain a new copy of the program.

Latest version.
### Problem

Downloading git I get:
First windows defender says the file is not to be trusted. Trying to install anyway gives this error:
"The setup files are corrupted. Please obtain a new copy of the program."

### Operating system and browser
Windows 64, tried different browsers. And tried several times.

### Steps to reproduce
Try to download the latest windows version of git

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/issues/new/choose), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
