### ISSUE TITLE
Mailing list doesn't work

### ISSUE THREAD

**Issue by abelardolg** [git/git-scm.com#1613]
Please,

Make sure your mailing list works. If it fails, make sure your give us an additional way so that we can send our suggestions.

![image](https://user-images.githubusercontent.com/22522883/122032935-610bff80-cdd0-11eb-94c8-b4253bcc450f.png)

**Comment by pedrorijo91** [comment]
hey @abelardolg , looking at the error message returned, it seems like you are sending a message containing HTML, which is not accepted (as stated in https://git-scm.com/community `Note also that the list only accepts plain-text email; please disable HTML in your outgoing messages.`)

if you are using gmail for instance, see https://smallbusiness.chron.com/turn-off-html-gmail-composer-40114.html on how to disable HTML in messages
