### ISSUE TITLE
About options aren't working on disabling Javascript.

### ISSUE THREAD

**Issue by adsingh14** [git/git-scm.com#1645]
### URL for broken page
https://git-scm.com/about/

### Operating system and browser

OS: **Windows 10** (64-bit)

Browsers:
- Google Chrome - **v95.0.4638.54** (Official Build) (64-bit)
- Mozilla Firefox - **v93.0** (64-bit)
- Microsoft Edge - **v95.0.1020.30** (Official build) (64-bit)

### Steps to reproduce

1. Visit https://git-scm.com
2. Disable Javascript [^1] [^2]
3. Click About OR visit https://git-scm.com/about/
4. Click any sub-option under 'About'.
5. It'll open clicked link but won't render any category except first one.

### Other details

It's working as expected on Firefox Nightly Browser **v95.0a1** (2021-10-27) (64-bit)

---
[^1]: Chromium : Visit site preferences to disable Javascript for selected website
[^2]: Firefox: Open DevTools and click on gear icon to disable Javascript

**Comment by pedrorijo91** [comment]
wondering if making the website usable with JS disabled is a goal or if we want to accept this limitation? same for #1646

thoughts @peff @jnavila ?

**Comment by peff** [comment]
In an ideal world, everything works without javascript or at least degrades gracefully. That said, the About page has been this way for probably a decade. While it may bug some privacy nuts (like me) who have javascript disabled by default, it's probably not the worst thing we do there (I think being behind Cloudflare means people using TOR nodes, etc, will occasionally get annoying DDoS challenges).

So if somebody wants to work on it, great. But I don't think it's a high priority. And if nobody is working on it, I think it would be OK to close.
