### ISSUE TITLE
Dead links for courses

### ISSUE THREAD

**Issue by 4nn1l2** [git/git-scm.com#1649]
### URL for broken page

https://git-scm.com/doc/ext

Courses
Git: Mastering Version Control
https://www.packtpub.com/application-development/git-mastering-version-control

Git: Version Control Made Easy
https://www.packtpub.com/product/git-version-control-made-easy/9781787287136

### Problem

There are three courses in the external links, two of which redirect to rotten links

### Operating system and browser

Debian, Chrome

### Steps to reproduce

Go to https://git-scm.com/doc/ext
Scroll down to the bottom of the page
Click on the links of the Courses section

**Comment by peff** [comment]
Thanks for bringing this up. We can drop them, or if they've just moved URLs, we can update them. @jnareb do you have an updated link for the course you're involved in?
