### ISSUE TITLE
New responsive menu does not work on some older mobile browsers

### ISSUE THREAD

**Issue by phil-blain** [git/git-scm.com#1650]
### URL for broken page

For example https://git-scm.com/docs/git-config
### Problem

- On my phone, tapping the sidebar menu does not work (nothing happens)
- On my computer, the space for the menu appears, but the menu is at the top of the page so I have to scroll up to see anything (see screenshots below).

### Operating system and browser

mobile: iOS 12.1 / Google Chrome 70.0.3538.75 and Safari
computer: macOS 10.11 / Google Chrome 96.0.4664.55

### Steps to reproduce

Mobile:
1. Navigate to https://git-scm.com/docs/git-config on mobile
2. Click the side bar menu
3. Nothing happens

Desktop:
1. Navigate to https://git-scm.com/docs/git-config and shrink browser width until the sidebar menu appears
2. Click the side bar menu
3. Notice the apparently empty div, scroll to top and see the menu.

### Other details
Click the menu mid-page:
![Capture d’écran 2021-11-25 à 14 03 25](https://user-images.githubusercontent.com/44212482/143491464-3509fd38-294b-4b24-a1c3-74899ed192ca.png)
Scroll to top:

![Capture d’écran 2021-11-25 à 14 03 44](https://user-images.githubusercontent.com/44212482/143491462-780be3f6-95de-4e3f-b80a-98bb2e3d4d07.png)

**Comment by adsingh14** [comment]
I'm aware of that. Those links on top is a temporary change.

**Comment by adsingh14** [comment]
Well, it looks like you're using an outdated web browser. Current Apple Store offers Chrome version 96.0.4664.53.


> Other details

That's a temporary change. I'm am aware of that.

**Comment by peff** [comment]
> On my computer, the space for the menu appears, but the menu is at the top of the page so I have to scroll up to see anything

I think this should be fixed by #1651 (which is merged, but it will be a few hours before caches are fully turned over).

> On my phone, tapping the sidebar menu does not work (nothing happens)

I couldn't reproduce this. Is it still an issue for you after #1651?

**Comment by phil-blain** [comment]
> > On my computer, the space for the menu appears, but the menu is at the top of the page so I have to scroll up to see anything
> 
> I think this should be fixed by #1651 (which is merged, but it will be a few hours before caches are fully turned over).

Yes, this works correctly now.

> 
> > On my phone, tapping the sidebar menu does not work (nothing happens)
> 
> I couldn't reproduce this. Is it still an issue for you after #1651?

Yes, it's still an issue. I tried also on Safari and Chrome on iOS 13, same behaviour. I can't use install the latest version of Chrome as it requires iOS 14...

**Comment by Morganov** [comment]
Unfortunately, the side menu doesn't work on the actual versions of the mobile browsers iOS.
The issue is reproducible on the following browsers:

- Safari (iOS 15.5)
- Firefox 102.1 (12709)
- Chrome 103.0.5060.63

**Comment by adsingh14** [comment]
@Morganov Hey ! Thanks for the update. I don't have any Apple device but will add some lines. 
@peff Any suggestion on this? Is there any collaborative platform to solve this issue practically or I add some lines ?

**Comment by pedrorijo91** [comment]
closed by #1714
