### ISSUE TITLE
Please add mentioning of winget installation method on https://git-scm.com/downloads

### ISSUE THREAD

**Issue by lnlp** [git/git-scm.com#1652]
### Problem

_I did not find any other suitable place on GitHub to post this so forgive me if this is not the correct place._
_(I have no intention for subscribing to a mailing list for providing this feedback)._

Since recently the Microsoft [**winget** cli for Windows Package Mager](https://docs.microsoft.com/en-us/windows/package-manager/winget/) is available.

https://git-scm.com/downloads and https://git-scm.com/downloads/win do not provide information about the possibility to install Git for Windows via **winget**.

Git for Windows can be installed with the following winget command:

```text
    winget install git
```

Please add this information to https://git-scm.com/downloads and https://git-scm.com/downloads/win

### Operating system and browser

Windows 10, Microsoft Edge (Chromium)

### Steps to reproduce

Not relevant.

### Other details

Git for Windows can be installed with the following winget command:

```text
    winget install git
```

Git for Windows can be upgraded with the following winget command:

```text
    winget upgrade git
```

The winget-cli repository can be found here: https://github.com/microsoft/winget-cli

**Comment by pedrorijo91** [comment]
thanks for letting us know of this new package manager @lnlp ! would you be interested in contributing by adding this detail yourself?

**Comment by pedrorijo91** [comment]
it should be around this file https://github.com/git/git-scm.com/blob/main/app/views/downloads/download_windows.html.erb

**Comment by lnlp** [comment]
> would you be interested in contributing by adding this detail yourself?

No thanks. I have no experience with Ruby and its tooling so this will take too much of my time.

**Comment by adsingh14** [comment]
You'll see it on the website till next week. I'm working on it.

**Comment by adsingh14** [comment]
> it should be around this file https://github.com/git/git-scm.com/blob/main/app/views/downloads/download_windows.html.erb

Just this file? I could add a few lines.

**Comment by pedrorijo91** [comment]
yes @adsingh14  :) thanks for looking into this

**Comment by adsingh14** [comment]
Do you think adding an official link will look better though it's multistep process like installing WSL on Windows?

**Comment by lnlp** [comment]
Not sure if the question was for me, but the question is not all clear.

**Comment by pedrorijo91** [comment]
sorry @adsingh14 , didn't fully get your question

**Comment by adsingh14** [comment]
Shall I add just a single link on windows download page?

**Comment by adsingh14** [comment]
> Not sure if the question was for me, but the question is not all clear.
> sorry @adsingh14 , didn't fully get your question

@pedrorijo91 I didn't get the proper flow how to install it ?
