### ISSUE TITLE
three dots are replaced by … (unique character) in commands

### ISSUE THREAD

**Issue by Arthur-Milchior** [git/git-scm.com#1700]
### URL for broken page

https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-Theem82308203emthree-dotSymmetricDifferenceNotation

### Problem

In short code sample imported from git documentation, `'...'` are transformed into a single character three dots instead of the actual three separate dots that should be used for the three-dot symmetric difference notation.

As far as I can tell, it's not a bug with original documentation https://github.com/git/git/blob/master/Documentation/revisions.txt#L286 which never use this symbol (it is also an issue in some translations however) but with the way the documentation is compiled to this website.

### Operating system and browser

Latest ubuntu and chrome

### Steps to reproduce

open the browser and look at the command example, not three characters are replaced by a single one

### Other details

I suppose the problem is in one of the tool you use to compile documentation into html. So this issue will probably simply be forwarded to another project. But I was not able to find which tool is doing the compilation in this particular case

**Comment by peff** [comment]
Fix sent upstream: https://lore.kernel.org/git/YrOmsA04FZae89be@coredump.intra.peff.net/

**Comment by peff** [comment]
I'm going to close the issue, as I think there's nothing to be done in this repo. When the fix makes it into the next Git version, we'll pick it up on the site. Thanks for reporting!

**Comment by Arthur-Milchior** [comment]
Thanks for taking it into account. Congrats for finding how to solve it, I admit I did take a quick look and decided not to try to understand how to install and test the whole pipeline.
