### ISSUE TITLE
git-scm.com doesnot redirect to https: when manually surfed http: on edge

### ISSUE THREAD

**Issue by mandip1213** [git/git-scm.com#1705]
### URL for broken page
http://git-scm.com

### Problem
 Although git-scm uses https but it doesnot redirects to https://git-scm.com when manually entering http://git-scm.com

### Operating system and browser
OS: windows 10 
browser: 
Microsoft Edge | 103.0.1264.49

### Steps to reproduce
Enter `http://git-scm.com` in the url bar and hit enter.

**Comment by peff** [comment]
I turned on the Cloudflare option (for both git-scm.com and git-scm.org). Let's see if anybody screams.

**Comment by peff** [comment]
> I turned on the Cloudflare option (for both git-scm.com and git-scm.org). Let's see if anybody screams.

Well, nobody seems to have complained after almost 2 weeks, so let's go with it! I think we can consider this closed.
