### ISSUE TITLE
Brand icons information update.

Facebook (now Meta) icon needs to be updated with permission.

### ISSUE THREAD

**Issue by adsingh14** [git/git-scm.com#1707]
### Problem

I reached to Meta brand page where they asked for permission to use their new logo.
 Please open this [link](https://www.facebook.com/brand/resources/meta/company-brand/) and scroll to 'How to submit a brand permissions request'. 

### Operating system and browser

Windows 10
Firefox browser

### Steps to reproduce

- Open home page
- Scroll to bottom, 'Companies & Projects Using Git' and check old facebook logo 

### Other details

I'll update the logo after your team get permission or vice versa.

In future, this list will be filled with new brands and some brands logo will change eventually (like Facebook). I request your team to make this issue as a placeholder for brand image/link relevant updates. Whenever a new author wants to change something,  just comment under this along with a brief summary.

**Comment by pedrorijo91** [comment]
how should we proceed in this case @peff ? not sure if we can do it, or needs to be the Git / Software Freedom Conservancy doing the req?

**Comment by peff** [comment]
TBH, I'm not sure they would grant permission, as it implies endorsement and we have no real relationship with them. I also thought that they mainly used a hacked-up version of Mercurial!

I suspect anybody could ask permission on behalf of this site, but it probably would be stronger coming from the Conservancy PLC. I'm not on it anymore, but @ttaylorr is (though note he's going to be offline for a few weeks, so don't expect a response immediately).

All that said, I think most of these logos are supposed to involve permission, which we never got. E.g., see https://github.com/git/git-scm.com/issues/595#issuecomment-225279342. Also in that thread is the notion that we should drop the logos entirely (and that was going to be part of the site redesign that never quite finished). So I'd probably rather just drop them than go to any significant work to update them or seek permissions.
