### ISSUE TITLE
git-subtree documentation is missing?

### ISSUE THREAD

**Issue by mwisnicki** [git/git-scm.com#1709]
No sign of git-subtree[1] on this page: https://git-scm.com/docs/git#_git_commands

**Comment by peff** [comment]
I think this is working as designed. `git-subtree` is not an official git command, but rather carried in the `contrib/` section of git.git. So it is upstream Git's documentation that chooses not to include it in the regular command list.

We _could_ build the `subtree` manpage ourselves and put it on the site, but I think I'd rather follow upstream Git's lead here no deciding what to include. (There's a whole separate discussion one could have about whether `subtree` ought to become a core Git command, but I suspect it's a big rabbit hole and don't have any opinions or knowledge myself).
