### ISSUE TITLE
time to update ruby?

### ISSUE THREAD

**Issue by peff** [git/git-scm.com#1710]
I noticed today that ruby-2.7.3 doesn't build on debian unstable anymore, because the openssl dependency has moved on. Looks like ruby-3.1.2 is the latest stable release. A trivial replacement of the versions in `Gemfile` and `.ruby-version` _seems_ to work OK, but it probably needs somebody to poke around at the result and make sure everything works as expected.

**Comment by ttaylorr** [comment]
I think that we use few-enough exotic Ruby features that this upgrade poses fairly little risk. We could do a conservative roll-out and look at errors on the new build, but I doubt that anybody is looking at those errors closely enough that such an approach would catch any errors.

I think that a safe-enough approach would be something on the order of running the site locally, with an updated `Gemfile` and `.ruby-version` file to reflect the new version. Assuming that nothing seems obviously broken at this stage after exercising a few basic functions of the site, I think it'd be OK to push this out.

Folks can open issues over time if they run into issues, but Ruby releases are high quality enough that I'm not expecting any notable bugs here.

**Comment by peff** [comment]
> I think that we use few-enough exotic Ruby features that this upgrade poses fairly little risk.

You'd think. And yet here are 115 patches that say otherwise: #1736. To be fair, a lot of that is because I split out the results of `rubocop --autocorrect` into individual warnings (which I think makes it easier to understand what's going on, and certainly to bisect if need be). But there were definitely some changes needed to make everything run.
