### ISSUE TITLE
online book and 2nd edition do not match

### ISSUE THREAD

**Issue by jonhp** [git/git-scm.com#1734]
Although the online book says that it is the 2nd edition, it isn't. It is, I guess, "second edition plus". While this might be obvious to those working on the book, it is not to the new comer. Best I can tell, there have been a lot of changes since the printed "second edition", at least the one I have. I am just suggesting that some text or warning be added to the initial web page linked below that makes us aware that the online book has changed since the hard-copy second edition was published. 
Thanks for considering this suggestion.

 https://git-scm.com/book

**Comment by peff** [comment]
Yeah, I'd agree that text could be updated. There are indeed a lot of changes: https://github.com/progit/progit2/compare/2.0.0...main (though I'm not 100% sure that the 2.0.0 tag represents what went to press).
