### ISSUE TITLE
git config doc doesn't render includes properly

### ISSUE THREAD

**Issue by chriscool** [git/git-scm.com#1739]
### URL for broken page

https://git-scm.com/docs/git-config#_variables

### Problem

Instead of rendering the content of the included files (which describe configuration variables), only the filenames are displayed:

![image](https://user-images.githubusercontent.com/208954/194496282-a87210dc-4fa1-49e3-8280-008bcfaaee6e.png)

### Operating system and browser

Linux with Firefox or Chrome.

### Steps to reproduce

Just go to:

https://git-scm.com/docs/git-config#_variables

and see that only filenames are displayed, instead of config variable description.

**Comment by chriscool** [comment]
Note that `git help -m config` and `git help -w config` properly show the doc (in man and html format respectively). So I don't think that the problem comes from Git.

**Comment by derrickstolee** [comment]
I was just coming here to say this! Thanks for reporting it, @chriscool.
