### ISSUE TITLE
Logos are not shown in /downloads/logos

### ISSUE THREAD

**Issue by nnsee** [git/git-scm.com#1741]
### URL for broken page

https://git-scm.com/downloads/logos

### Problem

Logos are not shown - code for rendering them is shown instead.

### Operating system and browser

Linux / Firefox 105.0.3

### Steps to reproduce

Open the page.

**Comment by pedrorijo91** [comment]
could it be due to https://github.com/git/git-scm.com/pull/1736 @peff ?

**Comment by pedrorijo91** [comment]
we also had https://github.com/git/git-scm.com/pull/1731 recently, but IIRC everything was fine after deployment
