### ISSUE TITLE
Revert commit e74a1ec that remove CodeReview

### ISSUE THREAD

**Issue by FabriceSalvaire** [git/git-scm.com#1746]
I am asking to revert commit e74a1ec

I rewrote the installation doc, and it should be easily installable on Linux, where Python and a C compiler is nearly available by default.

However, I need help on Windows and OSX to write an installation procedure or make an installer.

https://github.com/FabriceSalvaire/CodeReview

**Comment by pedrorijo91** [comment]
hey @FabriceSalvaire . feel free to submit a PR adding the GUI client to the list :)

There are some instructions here: https://github.com/git/git-scm.com#adding-new-gui
if you still need some help let us know so that we can help you on that

**Comment by pedrorijo91** [comment]
are you interested in doing it @FabriceSalvaire ?
