### ISSUE TITLE
500 Internal server error when visiting link for Pro Git v1 book

### ISSUE THREAD

**Issue by HonkingGoose** [git/git-scm.com#1782]
### URL for broken page

https://git-scm.com/book/en/v1

### Problem

The page linked above leads to a 500 Internal Server Error.

### Operating system and browser

macOS 13, Firefox 113.0.1

### Steps to reproduce

1. Go to https://git-scm.com/book/en/v1
2. End up at Internal server error page

### Other details

The Pro Git book is on version 2 now. We should probably redirect to the landing page for the v2 book.

Related issue (filed in the wrong place):

- https://github.com/progit/progit2/issues/1836

**Comment by pedrorijo91** [comment]
hey @HonkingGoose @derberg,

can you share where did you find links to book v1?

either way, it seems reasonable to redirect to some page. probably we removed the routing  because v1 is really old AFAIK (i see v2 was released around 2014)

**Comment by HonkingGoose** [comment]
According to the first issue there are links pointing to the v1 version of the book in the GitHub Docs. I will open a PR in the GitHub Docs repo to fix the links.

**Comment by HonkingGoose** [comment]
I tried making the changes to the GitHub Docs myself, but I'm not allowed to touch the files with the bad links in it. So I'm opening an issue with GitHub Docs, so one of their maintainers can fix it. 😄

**Comment by HonkingGoose** [comment]
> either way, it seems reasonable to redirect to some page. probably we removed the routing because v1 is really old AFAIK (i see v2 was released around 2014)

I'll let you guys decide. Possible fixes:

1. Do nothing, let downstream projects update their own links to broken pages
2. Redirect `v1` to `v2` in-place: only change `v1` to `v2` in the link
3. Redirect `v1` links to a generic "homepage" for the `v2` version of the book

**Comment by dscho** [comment]
For the record: after #1804 was merged, the link no longer 500s but 404s instead.

**Comment by LemmingAvalanche** [comment]
Related: I found this link which doesn’t say anything about the edition:

https://git-scm.com/book/en/Git-Tools-Rewriting-History

404.

But this works:

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

The second edition.

Maybe the first link could try to redirect to `/v2`?

**Comment by dscho** [comment]
@LemmingAvalanche good idea! We should automate this by patching in aliases [here](https://github.com/git/git-scm.com/blob/58628f3694e1f6accbe5f8b9746c4c18a24a2fbb/script/book.rb#L135) (both `v1.html` and `v1/index.html`), and [here](https://github.com/git/git-scm.com/blob/58628f3694e1f6accbe5f8b9746c4c18a24a2fbb/script/book.rb#L297) (being careful to special-case `%3F`, i.e. the question mark, also for the v1 redirect).

@LemmingAvalanche want to give it a try?

**Comment by LemmingAvalanche** [comment]
@dscho Sure thing, I can look at this this evening.

I’ll reply later if it turns out that it needs someone more experienced.

**Comment by dscho** [comment]
@LemmingAvalanche thank you for clarifying (in a separate, private communication) that you were thinking of redirecting:

https://git-scm.com/book/en/Git-Tools-Rewriting-History

To:

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

I indeed misunderstood, or maybe it was a Freudian mistake, as the information necessary to reliably map the sections of v1 to v2 is simply not available in the current version of `git-scm.com`.

But maybe you can add that mapping, say, as `/data/book-v1.yml`, probably (semi-automatically) generated from a clone of https://github.com/progit/progit/, and then use that information in `script/*book*.rb` to add the respective aliases?

**Comment by LemmingAvalanche** [comment]
@dscho Thank you for doing that research. I agree that it’s best to not do anything here.

All I’ve done on this subject is to search Stackoverflow for v1 links and update them when there is a v2 mapping. That’s what we can do at this stage (all these years later).

**Comment by HonkingGoose** [comment]
How about creating a landing page for incoming "progit v1 link users"? Like this:

1. Bob clicks on outdated link to v1 book. Server redirects all v1 links to the new v1 to v2 page.
3. The page explains that Bob used an old link.
4. The page shows a prominent link or button, that links to the table of contents for the v2 book on `git.scm`.
5. Bob clicks on the v2 link, and reads the table of contents to find a similar chapter.

This way you avoid doing any manual mapping from v1 to v2. And you give users a simple way to recover from the outdated link.

**Comment by dscho** [comment]
> How about creating a landing page for incoming "progit v1 link users"?

@HonkingGoose that would require hosting a server so that arbitrary `/book/v1/` routes could be redirected. But since #1804 was merged, git-scm.com is a _static_ site. No wildcard routes available there.

There is some _sort_ of an option to do wildcard routes: https://git-scm.com/book/en/Git-Basics-Getting-a-Git-Repository#Cloning-an-Existing-Repository serves the 404.html page. Javascript could be added to that page to detect v1 book links and reroute, but that would not work for browsers (or crawlers) that have (nor want) Javascript support.

What we _could_ do is to scrape the v1 links from the Internet Archive and then present them as aliases for something like this new "ProGit v1 landing page". But that would already be 90% of the work to redirect them (modulo anchor) to the v2 pages. So I think that if we already do the work to identify all of the v1 links, we might just as well go the whole nine yards and save us the work of creating a new page.

**Comment by dscho** [comment]
> What we _could_ do is to scrape the v1 links from the Internet Archive and then present them as aliases for something like this new "ProGit v1 landing page". But that would already be 90% of the work to redirect them (modulo anchor) to the v2 pages.

And that wasn't too much work on top of what I already poured into this here ticket: https://github.com/git/git-scm.com/pull/1915.

**Comment by dscho** [comment]
@LemmingAvalanche @HonkingGoose could you please review that PR?
