### ISSUE TITLE
git commit struck in terminal 

### ISSUE THREAD

**Issue by bala-auvaria** [git/git-scm.com#1797]
### Problem
git commit struck in terminal and unable to commit staged files 

### Operating system and browser
Mac M1 (Apple Silicon) 

### Steps to reproduce
Previously it was working fine suddenly getting this issue - updated my Mac OS to Ventura 13.5.1 (22G90) 

### Other details
<img width="676" alt="Screenshot 2023-08-26 at 00 45 27" src="https://github.com/git/git-scm.com/assets/104763693/4fbb0492-3004-48b6-8953-da71ab2910a8">
<img width="676" alt="Screenshot 2023-08-26 at 00 45 37" src="https://github.com/git/git-scm.com/assets/104763693/e25e01db-1c04-45c9-a3ce-7452f2067be2">

**Comment by pedrorijo91** [comment]
As you can see in the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md), this repository issue tracker should only be used to report problems found on the git-scm website (https://git-scm.com/). 

Git specific issues should be raised with the community (https://git-scm.com/community).
