### ISSUE TITLE
Windows Downloads on https://git-scm.com not working

### ISSUE THREAD

**Issue by MITCHYUGAN** [git/git-scm.com#1810]
### Which download is failing?

Windows Download 

### Problem

When I try to download a Windows version of Git using this URL: https://git-scm.com/download/win
It loads for a bit, then I get this in the browser:

![image](https://github.com/git/git-scm.com/assets/108536470/8d196bca-483e-4062-80a0-e2d13ae3ad04)

I've tried downloading in Incognito mode on Chrome and also used Microsoft Edge, but the issue still persists.
Pls help me out. 

### Operating system and browser

Windows and Chrome

### Steps to reproduce

1. Opened Chrome Browser and Navigated to https://git-scm.com/download/win
2. Click on "Click here to download"
3. Git the Issue on the Browser

**Comment by ttaylorr** [comment]
This looks like a momentary blip, since I was able to download the 64bit installer of Git for Windows. If the problem persists for you, however, I'd encourage you to contract `<support@github.com>`, since git-scm.com does not control GitHub's user content distribution service.
