### ISSUE TITLE
Version 2.42.1 announced for Windows on https://git-scm.com/ but is not available

### ISSUE THREAD

**Issue by dbornand** [git/git-scm.com#1812]
### URL for broken page

[https://git-scm.com/](https://git-scm.com/) and [https://git-scm.com/download/win](https://git-scm.com/download/win)

### Problem

The version 2.42.1 is announced as the latest stable release for Windows on [https://git-scm.com/](https://git-scm.com/), but is not available on the download page [https://git-scm.com/download/win](https://git-scm.com/download/win).  The download link targets the 2.42.0 version.

### Operating system and browser

Windows + Chrome

### Steps to reproduce

1. Go to [https://git-scm.com/](https://git-scm.com/)
2. Click on _Download for Window_
3. Click on _Click here to download_

The 2.42.0 version is downloaded (released on 2023-08-30.), although the version 2.42.1 (2023-11-02) is announced on the homepage

### Other details

- The release notes link on  [https://git-scm.com/](https://git-scm.com/) targets the 2.42.1 version [https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.42.1.txt](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.42.1.txt)
- On  [https://git-scm.com/download/win](https://git-scm.com/download/win), 2.42.1 seem to be the target version for winget. I didn't try to install it and don't know which version will actually be installed.
- There is no 2.42.1 version on [https://github.com/git-for-windows/git/releases](https://github.com/git-for-windows/git/releases)

**Comment by pedrorijo91** [comment]
hey @dbornand , unfortunately the build for windows has some delay. looking at https://github.com/git-for-windows/git/releases, seems 2.42.1 has not yet been released
