### ISSUE TITLE
Ligatures in monospace fonts hurt legibility of config keys

### ISSUE THREAD

**Issue by rybak** [git/git-scm.com#1817]
The choice of the font in `app/assets/stylesheets/variables.scss` for the rule:

```scss
$fixed-width-font-family: Courier, monospace;
```

can make it harder to read some of the text in the documentation. This is especially applicable to the names of the configuration keys and to mentions of the shell commands, which people would usually edit in a text editor or in a shell with a monospace font. Fonts used by `<code>` tags are also affected.

### URL for broken page

Example: https://git-scm.com/docs/git-config

### Problem

Ligatures in the fonts for the `Courier` in CSS make it harder to read parts of the website.

### Operating system and browser

Operating System: KDE neon 5.27 (≈ Kubuntu 22.04)  
Browser: Firefox 119.0

### Steps to reproduce

1. Look at mentions of `reflog` in monospace font on page <https://git-scm.com/docs/git-config#Documentation/git-config.txt-gcreflogExpireUnreachable>
   ![screenshot of mention of gc.reflogExpireUnreachable in Git documentation](https://github.com/git/git-scm.com/assets/624072/ea96fee1-f58b-4b31-8df1-9d6bb7b697ce "before fix")

### Other details

- Adding CSS code:
   ```css
   font-variant-ligatures: none;
   ```
   fixes the instances highlighted on the screenshot above:
   ![screenshot of mention of gc.reflogExpireUnreachable in Git documentation](https://github.com/git/git-scm.com/assets/624072/52ba915d-d017-4534-9c35-1d57f385d216 "after fix")
- Other examples:
  - [mention of `color.diff.new`](https://git-scm.com/docs/git-config#Documentation/git-config.txt---get-colorltnamegtltdefaultgt)
  - [mention of `git config`](https://git-scm.com/docs/git-config#Documentation/git-config.txt---typelttypegt)
    ![screenshots of mentions of color.diff.new and git config in Git documentation](https://github.com/git/git-scm.com/assets/624072/34412c30-6ea8-4b2b-8b51-57d5db2a5f12)
   These styled via `<code>`.
- [MDN documentation for `font-variant-ligatures`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures)
-  In my setup, these CSS rules for Courier actually end up using [Nimbus Mono PS](https://en.wikipedia.org/wiki/Nimbus_Mono_L). This is caused by [config file `/etc/fonts/conf.avail/30-metric-aliases.conf`](https://superuser.com/a/1095575/133421), quote:
   ```xml
        <alias binding="same">
          <family>Nimbus Mono PS</family>
          <default>
          <family>Courier</family>
          </default>
        </alias>
   ```
   See also [Arch Linux wiki article about it](https://wiki.archlinux.org/title/Metric-compatible_fonts).

**Comment by sparr** [comment]
https://github.com/ArtifexSoftware/urw-base35-fonts/issues/31

`font-variant-ligatures: none;` seems like a good fix, until various monospace fonts stop shipping this sort of ligature
