### ISSUE TITLE
The git-users (e)mailing list seems spam-drowned: can’t access

### ISSUE THREAD

**Issue by LemmingAvalanche** [git/git-scm.com#1828]
https://git-scm.com/community

> There is also [Git user mailing list](https://groups.google.com/forum/?fromgroups#!forum/git-users) on Google Groups which is a nice place for beginners to ask about anything.

I am not allowed to access it. Just as well because this is apparently what it looks like: https://www.mail-archive.com/git-users@googlegroups.com/

The last thread (except [“I’m leaving](https://www.mail-archive.com/git-users@googlegroups.com/msg13739.html)) seems to have been 2023-12-29 https://www.mail-archive.com/git-users@googlegroups.com/msg13689.html

### How this relates to git-scm

I don’t know if there is any relation between this mailing list and git-scm. But maybe the Community page needs an update.

**Comment by dscho** [comment]
> How this relates to git-scm

Well, it does not. I would suggest that the Git mailing list would be a better place for this report (even if I suspect that not many people there will be helpful regarding this here issue, unfortunately), see https://git-scm.com/community for details. Still, I could not find out who's the owner of git-users but would expect them to be on the Git mailing list and see that message.

**Comment by LemmingAvalanche** [comment]
Redirecting https://lore.kernel.org/git/339f17e1-c6a0-4859-aa5b-481dd6e0e91b@app.fastmail.com/T/#u

**Comment by LemmingAvalanche** [comment]
Reopening since I forgot about the mention of this list _here_ which should be altered.
