### ISSUE TITLE
Error 500 when visiting the greek git book

### ISSUE THREAD

**Issue by infl00p** [git/git-scm.com#1831]
### URL for broken page
https://git-scm.com/book/gr/v2/

### Problem

I get a server error 500 when visiting the Greek Git book. I follow the link from
https://git-scm.com/book/en/v2 and press Ελληνικά (Greek language)

**Comment by infl00p** [comment]
Are there any updates on this issue?
As a workaround I can download the book from the translator's fork https://github.com/progit2-gr/progit2

**Comment by pedrorijo91** [comment]
any clue @jnavila ?

**Comment by dscho** [comment]
Another (temporary) work-around would be to go to https://git.github.io/git-scm.com/book/gr/v2.html, i.e. using the current state of the [transition to a Hugo website](https://github.com/git/git-scm.com/pull/1804).

**Comment by rimrul** [comment]
> Another (temporary) work-around would be to go to https://git.github.io/git-scm.com/book/gr/v2.html, i.e. using the current state of the [transition to a Hugo website](https://github.com/git/git-scm.com/pull/1804).

For some reason that now also produces the internal server error page.

**Comment by dscho** [comment]
> > Another (temporary) work-around would be to go to https://git.github.io/git-scm.com/book/gr/v2.html, i.e. using the current state of the [transition to a Hugo website](https://github.com/git/git-scm.com/pull/1804).
> 
> For some reason that now also produces the internal server error page.

The reason is that we started the work on transitioning to Hugo last Friday, i.e. finishing #1804, and therefore the `git.github.io/` site wants to live in the top-level directory (and automatically redirects there, on the git-scm.com domain for good measure).

**Comment by dscho** [comment]
This is now fixed by switching to the Hugo/Pagefind-based site in https://github.com/git/git-scm.com/pull/1804.
