### ISSUE TITLE
Compiled installer releases versus WinGet releases

### ISSUE THREAD

**Issue by JessePeden** [git/git-scm.com#1859]
### Which download is failing?

No downloads are "failing" but there is an availability discrepancy.  Pre-compiled downloads for 2.46.0 are available on the https://git-scm.com site but winget still only has 2.45.2 as its newest release.

### Problem

WinGet only has 2.45.2 available as the newest release of Git, so users that are only able to install via this method (i.e., for security reasons, they may be unable to download compiled installers), installing via WinGet would be their only option.  With 2.45.2 being the newest release available there, this could mean they remain subjected to bugs that are fixed in 2.46.0.

PS C:\Users\redacted-username> winget search git.git
Name Id      Version Source
----------------------------
Git  Git.Git 2.45.2  winget

### Operating system and browser

Windows 11 Enterprise

### Steps to reproduce

1. winget search git.git

**Comment by rimrul** [comment]
WinGet isn't done creating their package yet for 2.46.0, but they've started. https://github.com/microsoft/winget-pkgs/pull/165183

**Comment by JessePeden** [comment]
> WinGet isn't done creating their package yet for 2.46.0, but they've started. https://github.com/microsoft/winget-pkgs/pull/165183

That explains why it's not listed there yet, but the process seems broken for it to take this long after being available nearly instantly via other methods.

Maybe something should be added to the https://git-scm.com downloads page that automatically checks the status of the WinGet listings for each release to show potential users that it isn't or is available at this time, a link such as you shared so they can see the progress, and to tell them to maybe hold of.

**Comment by JessePeden** [comment]
Am I reading the chain of entries correct on the link you previously provided, that 2.46.0 wasn't available via WinGet until 8/5/2024 (2 days ago)?  It took from 7/29/2024 to 8/5/2024 (8 days) for WinGet's repo to have the updated release?  Something seems wrong with the process if that's accurate.
