### ISSUE TITLE
Problem using zoom in the page

### ISSUE THREAD

**Issue by Fede5432** [git/git-scm.com#1916]
When I have the 150% zoom in the page and I open up this hidden list which contains "about", "documentation", etc. When I select one of them I can't get in

![image](https://github.com/user-attachments/assets/f765eb9f-0907-4bb2-b604-5118901cb1ee)

**Comment by dscho** [comment]
@Fede5432 thank you for reporting this issue! I have opened #1917 to fix this, and deployed it to https://dscho.github.io/git-scm.com/. Could you please verify that it works for you there?
