### ISSUE TITLE
Clean up stale branches

### ISSUE THREAD

**Issue by dscho** [git/git-scm.com#1923]
When I go to https://github.com/git/git-scm.com/branches/stale, I see the following stale branches:

![Image](https://github.com/user-attachments/assets/e38b9f66-28a3-417e-b7cb-c0b63ea97c42)

@pedrorijo91 do you need `v2` or `revert-1806-anna_skoulikari_add_book`, still?

@peff, do you need `css-fix`, still?

@jnavila, do you need `book_svg_images`, still?

`v2` seems to have 117 unmerged commits, the three other branches seem to have one unmerged commit each.

**Comment by peff** [comment]
Nope, I'll delete mine.

**Comment by dscho** [comment]
> Nope, I'll delete mine.

Thank you, @peff!

**Comment by jnavila** [comment]
Done

**Comment by dscho** [comment]
> Done

Thank you @jnavila!

@pedrorijo91 what about your two branches?

**Comment by pedrorijo91** [comment]
feel free to delete 🙏 thank you

**Comment by dscho** [comment]
> feel free to delete 🙏 thank you

Done!

![Image](https://github.com/user-attachments/assets/b14bc313-df4f-4f28-88ea-0d862d559eae)
