### ISSUE TITLE
Diagram error

### ISSUE THREAD

**Issue by qwertzguy** [git/git-scm.com#207]
Hello,

On the page http://git-scm.com/2010/03/02/undoing-merges.html, I noticed there is twice commit C8 in the schemas which makes it confusing. One of them should be C9 which is missing.

I don't know if I'm right in reporting this because the page dates from 2010/03/02, but I didn't find the same page in the current documentation.

Regards,
Gaspard van Koningsveld

**Comment by pedrorijo91** [comment]
I would say the problem was solved through https://github.com/git/git-scm.com/commit/a52537d95be7d6d993f3001c6846c408722debdc on https://github.com/git/git-scm.com/pull/893 @peff

**Comment by pedrorijo91** [comment]
also, https://github.com/git/git-scm.com/issues/215 seems a duplicated from this one

**Comment by qwertzguy** [comment]
Yea, looks fixed to me.
