### ISSUE TITLE
Duplicate commits in diagram

### ISSUE THREAD

**Issue by jogwen** [git/git-scm.com#215]
First two commit tree diagrams at http://git-scm.com/2010/03/02/undoing-merges.html have two commits called C8 and none called C9. Unfortunately part of the description is to "rewind master back to C8" so although it should be clear that it's the C8 on master the text is on about, it may well confuse new users.

**Comment by pedrorijo91** [comment]
duplicated from https://github.com/git/git-scm.com/issues/207 

@peff close?
