### ISSUE TITLE
Literal IPv6 addresses with custom port doesn't work in git-remote

### ISSUE THREAD

**Issue by baryluk** [git/git-scm.com#239]
Hi,

I found a minor problem when using literal IPv6 addresses with git. Apparently it is imposable to use custom port with literal IPv6 addresses, I would expect `ssh://user@[x:y:z:y:z:x]:port/path/path`
should work, but it doesn't.

Because  `ssh://user@hostname:port/path/path`  works.

Steps to reproduce (assuming ssh server on local machine on port 22):

```
$ (mkdir /tmp/p2 && cd /tmp/p2 && git --bare init .)
$ mkdir /tmp/p1 && cd /tmp/p1 && git init .
$ touch a ; git add a; git commit -a -m "example"
[master (root-commit) e74245e] example
 0 files changed
 create mode 100644 a
$ git remote add origin "ssh://[::1]::22/tmp/p2"
// or $  git remote add origin "ssh://[::1]/tmp/p2" # also doesn't work
$ git push
ssh: Could not resolve hostname [::1]:22: Name or service not known
fatal: The remote end hung up unexpectedly
$
```

It looks that git passes everything between ssh:// and / to ssh, but openssh doesn't understand this syntax.

```
$ ssh "[::1]"
ssh: Could not resolve hostname [::1]: Name or service not known
$ ssh "[::1]:22"
ssh: Could not resolve hostname [::1]:22: Name or service not known
```

`ssh` have -p parameter for passing port.

```
$ ssh "::1"
// or $ ssh -p 22 "::1" # also works
You have new mail in folder /home/you/Maildir/.
Linux xxx 3.8.0...
Last login: Fri Jan 18 01:00:00 2013 from xyz
$$ exit
Connection to ::1 closed.
$
```

Removing square brackets make it work.

```
$ git remote set-url origin "ssh://::1/tmp/p2"
$ git push origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 206 bytes, done.
Total 3 (delta 0), reused 0 (delta 0)
To ssh://::1/tmp/p2
 * [new branch]      master -> master
$ git push origin master
Everything up-to-date
$
```

but then I cannot pass custom port.

I am not sure if it is bug in git or rather ssh, but it would be useful to have this functionality. I have many machines around a world, with random ports for ssh (various reasons, including running custom unprivileged ssh servers  from normal user account), and use few of them for git backup purposes. I know I can easily setup DNS and then custom port will work (localhost:22 works with openssh apparently), but it I would consider lack of port support in literal IPv6 addresses a bug.

Thanks.

**Comment by dabaer** [comment]
>only related issue to my problem on google
>provides no follow up issue
