### ISSUE TITLE
image text (reset command) should contain --soft string

### ISSUE THREAD

**Issue by kamchy** [git/git-scm.com#257]
http://git-scm.com/images/reset/squash-r2.png 

this image illustrates state of report and trees after. reset --soft which does not update index, so the command on the image  shoud reflect that

**Comment by sxlijin** [comment]
Is this still a relevant issue? If not, I'd move to close it.

**Comment by peff** [comment]
I think it is still relevant. AFAICT, the diagram itself is correct; it just doesn't say `--soft` in the image text.

**Comment by sxlijin** [comment]
The main reason I ask is because it seems like the image is from Pro Git v1, not v2.

**Comment by peff** [comment]
I think it's from https://git-scm.com/blog/2011/07/11/reset.html, though it may have originated elsewhere. And that _is_ original content for the site (although I wonder if most of the blog posts should now go away, as I'd think they are mostly superseded by updates in progit2).

**Comment by kamchy** [comment]
ProGit v.2 has fixed the image text ([correct image|https://git-scm.com/book/en/v2/images/reset-squash-r2.png] is visible in "7.7 Git Tools - Reset Demystified" chapter). If ProGit v1. is supposed to stay online, I think the image should be changed into something like this:
![squash-r2-soft](https://cloud.githubusercontent.com/assets/230475/23224459/cb800328-f92e-11e6-9006-5e71ca6b5dd1.png). 

Original image was probably downscaled or rasterized from vector image - is the original one available somewhere? We could then just fix it... What do you think?

**Comment by peff** [comment]
All I know about are the raster images in the repo. If it came from the progit book originally, though, you might find better sources in https://github.com/progit/progit or https://github.com/progit/progit2.

I'm not actually that worried about progit-v1 content. It's largely been superseded, and I think you'd mostly see it in translations which haven't moved to v2 yet. I dunno. If you have a PR that adjusts the image without sacrifcing the image quality, I'd merge it.

**Comment by pedrorijo91** [comment]
closing as the image does not exist anymore in the repo. Deleted during #1138
