### ISSUE TITLE
Front page shows "Latest stable release = 1.8.2" but downloads only 1.8.1.3

### ISSUE THREAD

**Issue by paulschreiber** [git/git-scm.com#268]
The git-scm.com front page shows "Latest stable release = 1.8.2" but when you click download (on a Mac), you get 1.8.1.3 from https://git-osx-installer.googlecode.com/files/git-1.8.1.3-intel-universal-snow-leopard.dmg.

**Comment by peff** [comment]
I think the OS X installer is doing better at staying up to date these days (though I do notice it's still offering 2.10.1).

IMHO, though, if we're not keeping the builds up to date, we're better off fixing _that_ problem than trying to hack around it with more descriptive links.

**Comment by peff** [comment]
> IMHO, though, if we're not keeping the builds up to date, we're better off fixing that problem than trying to hack around it with more descriptive links.

That said, it's probably a quicker fix to do something like #186 in the meantime. If somebody wants to verify that that PR still applies, and looks good in all cases (sounds like there were some formatting issues?), I'd be willing to merge it.
