### ISSUE TITLE
git-log page formatting problem

### ISSUE THREAD

**Issue by kebno** [git/git-scm.com#292]
In the [git-log page](http://git-scm.com/docs/git-log.html), the text within the section "History Simplification" becomes an orange code listing which continues until halfway into the section "Diff Formatting."

**Comment by bk2204** [comment]
This has been fixed for some time. Asciidoctor is stricter about block delimiters: they have to be ±1, not ±2.  I submitted a patch to Git which fixes those issues, and the website has been automatically updated.

**Comment by maxlazio** [comment]
Looks like this has been resolved so I will close this issue. Let us know if that is not the case :)
