### ISSUE TITLE
Automatic Downloads

### ISSUE THREAD

**Issue by masonsbro** [git/git-scm.com#373]
I Googled "git for windows", and the first result was http://git-scm.com/download/win. I clicked through and the download immediately started. I think it is inappropriate for the top Google result to result in an automatic download - perhaps the direct download page should not appear in Google search results, or perhaps the page should not automatically start the download when it is reached via Google (checking referrer URL maybe).

I apologize if I am just being picky and if this is not considered a real issue. But when I was looking for a URL to send a friend, I was instead greeted with an executable.

Thanks!

**Comment by pedrorijo91** [comment]
another issue that should be considered on #1179 @jasonlong

**Comment by mloyd** [comment]
I think @masonsbro provided a very reasonable suggestion (inspect referring URL).  A correct one, in my opinion.  It is inappropriate for this page, or any other, to automatically download an executable when accessed from a Google search result, clicking on a link from an email, or even by clicking [https://git-scm.com/download/win](https://git-scm.com/download/win) in a Github issue comment.  Not to mention basic usability issues for non-windows users.

Would all it take to fix this is for someone to generate a pull request?  I would be happy to if that's the way forward.

**Comment by pedrorijo91** [comment]
Thanks for your availability @mloyd . 

I would say that a PR would solve this issue. As stated in the issue/comments, if we can reliably look at the referrer to disable the auto-download, then I would be all for it

**Comment by mloyd** [comment]
Created pull request #1418

**Comment by pedrorijo91** [comment]
closed by #1418
