### ISSUE TITLE
Inconsistent OS listings on Downloads page

### ISSUE THREAD

**Issue by emaste** [git/git-scm.com#377]
On http://git-scm.com/downloads I see:

Mac OS X    Windows
Linux   Solaris

Linux and Solaris both link to http://git-scm.com/download/linux, which has instructions for 4 Linux distributions, 2 BSDs, and Solaris.

Objective OS market share data is hard to find, especially for other than Mac/Windows/Linux, but some sources put FreeBSD as about 5x that of Solaris.

FreeBSD should likely be added there, or perhaps just have an "other" link?

**Comment by pedrorijo91** [comment]
FreeBSD already has instructions on this page, added through https://github.com/git/git-scm.com/commit/8ff988c5792f4ca92c1ac2ba96555843276dd884 

should be closed @peff ?

**Comment by peff** [comment]
The `/download` page has a link for Linux and for Solaris, but not other Unixes.  Even though the Linux and Solaris links go to the same page, which does have instructions for FreeBSD and others.

So we _could_ add more links there, but I think it might make more sense to go the opposite direction, and give the Linux link more generic and inclusive text. PRs welcome.

**Comment by sxlijin** [comment]
Barring further substantive discussion, I think it's safe to close this issue.

**Comment by emaste** [comment]
https://git-scm.com/downloads still lists:

Mac OS X 	Windows
Linux 	Solaris

so from my perspective the issue still exists.

How about changing "Linux" and "Solaris" to a single "Linux/UNIX"?

**Comment by peff** [comment]
@emaste Exactly, I think that is the right direction. Want to open a PR?

**Comment by pedrorijo91** [comment]
closing as it seems fixed from #1033
