### ISSUE TITLE
Add licence information in `GUI Clients` page. 

### ISSUE THREAD

**Issue by jaseemabid** [git/git-scm.com#381]
`Price: Free` is not adequate enough, we need to add the licence information for each GUI client. 

I am willing to send a PR

**Comment by sxlijin** [comment]
Can you elaborate on this and why you think adding license information matters?

Alternatively, if you don't think of this as an issue anymore, I'd move to close it.

**Comment by peff** [comment]
I think license information would be fine to add, but until there's a PR, there's not much to discuss.

**Comment by pedrorijo91** [comment]
closed by #1040
