### ISSUE TITLE
Windows download says 1.9.2, points to download page with 1.9.0

### ISSUE THREAD

**Issue by mloskot** [git/git-scm.com#392]
Similarly to #384, the download page for Windows says:

![08d6e0d0-c6dc-11e3-9a8d-2c858d45ca2b](https://cloud.githubusercontent.com/assets/80741/2742861/d9dacbf0-c70a-11e3-8df0-f30d39a40e0d.png)

but points to 

![23c98d98-c6dc-11e3-8957-8845fe9efe25](https://cloud.githubusercontent.com/assets/80741/2742867/eb5c14a6-c70a-11e3-90fe-ee2322b46020.png)

**Comment by wolf99** [comment]
Same again for git 2.2.2 on git-scm.com actually downloading Git for Windows 1.9.5.
This had me guessing for a few minutes as git --version gives 1.9.5, but I was totes sure teh website said 2.2.2 when I hit that big ol' download button!

**Comment by kleinfreund** [comment]
I have to say, that is really not the best user experience here.

**Comment by pedrorijo91** [comment]
seems very related (and the same underlying cause) from https://github.com/git/git-scm.com/issues/268. Maybe this (and other existing issues #715) should be closed over #268 or another, more generic issue @peff

**Comment by peff** [comment]
There was a lot of confusion for a while, as Git for Windows was not being updated for a period, and then it changed names, etc. I _think_ everything should be accurate now going forward (and certainly the page today looks right). So I'll close, but feel free to reopen (or open a new issue) if it crops up again.
