### ISSUE TITLE
Vote and Answer counts in "Related StackOverflow Questions" sidebar out-dated

### ISSUE THREAD

**Issue by orzechow** [git/git-scm.com#398]
The vote and answer counts of the _Related StackOverflow Questions_ (sidebar in docs pages) are out-dated.

So for example the [Undoing a git rebase](http://stackoverflow.com/questions/134882/undoing-a-git-rebase) question linked [here](http://git-scm.com/docs/git-diff) shows 
`160 votes / 7 Answers`
but in fact has 690 votes and 7 answers today.

Instead of being hardcoded [here](https://github.com/git/git-scm.com/blob/242783421bc7c98f6d0300404ea243a92784161c/app/views/shared/_related.html.erb#L8) you should use the [StackExchange API](https://api.stackexchange.com/docs/questions-by-ids#order=desc&sort=activity&ids=134882&filter=default&site=stackoverflow&run=true) to get the current vote and answer counts (or at least update them regularly with a cronjob).

This of course is not a real issue, rather a feature request.

**Comment by peff** [comment]
I think this sidebar is gone entirely since b6a61b9dc9523041ccc8ab9ecd1d73e9454132a1.
