### ISSUE TITLE
/community should direct website and book bug reports to GitHub

### ISSUE THREAD

**Issue by bk2204** [git/git-scm.com#413]
We frequently get reports of website-related bugs or issues on the Git mailing list, and have to redirect them to GitHub to file an issue report. Would it be possible to mention that issues related to the website and book should be filed at GitHub and not sent to the mailing list?

**Comment by sxlijin** [comment]
This no longer seems to be an issue\* and should be closed.

\* The git-scm.com website mentions it in the footnote in passing, which isn't particularly prominent. Also, I think the website was a lot less mature when this was originally opened and I haven't seen anything about the website on the mailing list in the past few weeks.

**Comment by peff** [comment]
I think it gets its own paragraph under "Bug reporting" now. IMHO the volume on the list these days is fine (and there will always be some misdirection). Much worse is the _opposite_ direction, Git problems in this issue tracker. Hopefully the recent issue template will address that.
