### ISSUE TITLE
some links produce Internal server errors

### ISSUE THREAD

**Issue by hginzel** [git/git-scm.com#439]
Hello,

I have detect that the link "Poznámky k překladu" (http://git-scm.com/book/cs/Pozn%C3%A1mky-k-p%C5%99ekladu) or the link "Zpětná synchronizace s originálem" (http://git-scm.com/book/cs/Pozn%C3%A1mky-k-p%C5%99ekladu-Zp%C4%9Btn%C3%A1-synchronizace-s-origin%C3%A1lem) on the page http://git-scm.com/book/cs/ produce Internal server error.
Also the "next" link on the page http://git-scm.com/book/cs/Pozn%C3%A1mky-k-p%C5%99ekladu-Prvn%C3%AD-kompletn%C3%AD-p%C5%99eklad-z-Edice-CZNIC produces Internal server error.

Best regards
HG

**Comment by ginzel** [comment]
@bry4n Thank you. It seems there is another problem, the links (urls) are not liniked (clickable) (e.g. in in http://git-scm.com/book/cs/v1/Pozn%C3%A1mky-k-p%C5%99ekladu).
