### ISSUE TITLE
Include tortoisegit in the gui section

### ISSUE THREAD

**Issue by simonzack** [git/git-scm.com#448]
[TortoiseGit](http://code.google.com/p/tortoisegit/) is one of the most popular git guis on windows. I think it will help promote git if it were included in the gui section.

**Comment by rdp** [comment]
I had a similar thought just now...why is it not on the list of GUI's, its pretty nice.

**Comment by sxlijin** [comment]
@peff thoughts?

**Comment by peff** [comment]
I generally merge any PR adding new items to the GUI list. So to answer your question, it is not there because nobody opened a PR to add it.

**Comment by csware** [comment]
I think this can be closed now.

**Comment by maxlazio** [comment]
Thanks @csware.
