### ISSUE TITLE
book.git-scm.com uses '%2F' instead of '/' in a redirect link

### ISSUE THREAD

**Issue by dennisschagt** [git/git-scm.com#454]
When following an old link (http://book.git-scm.com/5_submodules.html) I got redirected to 'http://git-scm.com/book/en%2FGit-Tools-Submodules'. I don't know if this is the only case or if this happens with every HTTP 301 redirect from book.git-scm.com. Is this redirection build into the code from this repository, or should I submit this issue somewhere else?

**Comment by sxlijin** [comment]
This no longer seems to be an issue (redirects resolve to Pro Git v2 correctly now) and should be closed.

**Comment by dennisschagt** [comment]
Yup, redirecting works fine now.
