### ISSUE TITLE
git-log page broken

### ISSUE THREAD

**Issue by JLuc** [git/git-scm.com#456]
http://git-scm.com/docs/git-log page is broken at half-page.
A code quotation is open and never closed. Half end of page is quoted as code.

Text goes :
E.g, format:"The author of %h was %an, %ar%nThe title was >>%s<<%n" would show something like this:

The author of fe6e0ee was Junio C Hamano, 23 hours ago
## The title was >>t4119: test autocomputing -p<n> for traditional diff input.<<

+
The placeholders are:
- '%H': commit hash
- '%h': abbreviated commit hash...

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
