### ISSUE TITLE
gitremote-helpers rendering error (resp. AsciiDoc issue)

### ISSUE THREAD

**Issue by fingolfin** [git/git-scm.com#460]
On http://git-scm.com/docs/gitremote-helpers near the end, one can see this:

```
option progress \{true|false\}
```

It really should look more like this:

```
option progress {true|false}
```

For some strange reason, a few options are rendered even worse, e.g.:

```
option cloning \{'true|false\}
```

Note that on http://git-scm.com/docs/gitremote-helpers/1.8.4 and older versions, everything is still shown correctly. Same for https://www.kernel.org/pub/software/scm/git/docs/git-remote-helpers.html

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.

**Comment by fingolfin** [comment]
It still is an issue for plder versions of the page, like https://git-scm.com/docs/gitremote-helpers/2.4.0

Of course this would be resolved by a saner architecture of the site that does not rely on manually recreating everything each time a bug in asciidoctor gets fixed...

**Comment by jnavila** [comment]
Hum, hum, as a matter of fact, the errors *is* in the manual page. Quotes are missing.

https://github.com/git/git/blob/master/Documentation/gitremote-helpers.txt#L455

is different from the preceding line.

**Comment by peff** [comment]
Yeah, this is broken in the normal manpage builds via asciidoc, too.  I've sent a [fix upstream](http://public-inbox.org/git/20170213203835.vssj64tcvuq35dny@sigill.intra.peff.net/).  It's trivial enough that it will hopefully make it into v2.12.
