### ISSUE TITLE
Broken link to "Sharing Notes"

### ISSUE THREAD

**Issue by dserodio** [git/git-scm.com#463]
In [A3.5 Git Commands - Sharing and Updating Projects: git push](http://git-scm.com/book/en/v2/Git-Commands-Sharing-and-Updating-Projects#git-push), 5th paragraph, it says "In [???](http://git-scm.com/book/en/v2/ch00/_sharing_notes) we…" and the ??? link is broken

**Comment by sxlijin** [comment]
This no longer seems to be an issue (the linked anchor resolves correctly now) and should be closed.

**Comment by dserodio** [comment]
Sorry, somehow I completely missed this 2-years old notification. The broken link I reported—which you can see in [this Internet Archive snapshot](https://web.archive.org/web/20141029153907/http://git-scm.com/book/en/v2/Git-Commands-Sharing-and-Updating-Projects) is indeed fixed, it was removed in progit/progit2@e2af0d7b17b4900774596685323e21642646d0e2. However, all the documentation about `git notes` is gone. 🙁 

According to grep there is now absolutely nothing about `git notes` in the book except for a trivial mention in [8.2 Customizing Git - Git Attributes](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes)

**Comment by sxlijin** [comment]
There is always [the man page](https://git-scm.com/docs/git-notes); if you think it's worth adding back to the book in more substantial detail though, I'm sure the folks over at progit/progit2 would be happy to talk about it (:
