### ISSUE TITLE
Missing checkout-index from the reference

### ISSUE THREAD

**Issue by lethalman** [git/git-scm.com#466]
In http://git-scm.com/docs the reference is missing `git checkout-index`. It's a very important command of the plumbing. Without it you aren't able to modify the working directory according to the contents of a snapshot (i.e. doing `read-tree` + `checkout-index`).

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If this issue is still relevant and you still want to discuss it, you should reach out to the [community](https://git-scm.com/community).

**Comment by peff** [comment]
Yeah, I don't think it is any less important than `read-tree`. Patches welcome.

**Comment by pedrorijo91** [comment]
it shouldn't be hard to add. I **think** it's this file: https://github.com/git/git-scm.com/blob/1ed2af1811d1b3816b6a017892afff940f84b5dd/app/views/shared/ref/_plumbing.html.erb

**Comment by jnavila** [comment]
They are already generated anyway. On question though: shouldn't a dedicated page be created to list all the available plumbing commands?

**Comment by pedrorijo91** [comment]
the OP is complaining that `checkout-index` should be list under https://git-scm.com/docs in the `Plumbing Commands` section, and from what I can see, this is still not solved.

About your question, I agree it could be interesting yes. The only reference I remember seeing to plumbing commands was in the book

**Comment by peff** [comment]
Yeah, I think an update to `_plumbing.html.erb` is all that is needed.

There's a bigger question of whether we should perhaps be auto-generating these lists, but I think the manual generation lets us group them better.
