### ISSUE TITLE
Getting the TFS author list uses commands incorrectly

### ISSUE THREAD

**Issue by lanekelly** [git/git-scm.com#467]
http://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git#TFS

Shell code presented on the page:
`PS> cat AUTHORS_TMP | cut -b 11 - 20 | tail -n + 3 | uniq | sort > AUTHORS`

Should be:
`PS> cat AUTHORS_TMP | cut -b 11-20 | tail -n +3 | sort | uniq > AUTHORS`

Changes: 
- No spaces between numbers with `cut`
- No space between `+` and `3` with `tail`
- `uniq` and `sort` switched to the correct order

**Comment by sxlijin** [comment]
This no longer seems to be an issue (the described changes are seen at the linked page) and should be closed.
