### ISSUE TITLE
Error in Merge Documentation

### ISSUE THREAD

**Issue by flyingL123** [git/git-scm.com#471]
I believe there is a typo in the branching and merging documentation located here:  http://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

In the diagram labeled "A merge commit", shouldn't the commit that "Master" points to be labeled "C6", not "C5"?

**Comment by doingweb** [comment]
Looks like the content isn't up-to-date with the upstream https://github.com/progit/progit2. This has already been [fixed over there](https://github.com/progit/progit2/commit/3491527b33251fcacd8d2964bf7fb5e0f1cfe455), but hasn't made it to the site yet. See #515.

**Comment by pedrorijo91** [comment]
seems a similar problem to #472

**Comment by sxlijin** [comment]
Closed by #952 @peff
