### ISSUE TITLE
Possible Typo?

### ISSUE THREAD

**Issue by daveomcd** [git/git-scm.com#472]
Didn't see a contact form or anything on the following website: http://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

I believe there is a typo at the bottom of this article; however, I'm probably wrong.  It seems the "Divergent history" graph references 'c2b9e' to the Testing branch, and '87ab2' to the master branch.  The console output below it however states the reverse.

**Comment by dennisschagt** [comment]
It looks like this is fixed in the [progit2 repository](https://github.com/progit/progit2) by changing the image to match the console output, in commit https://github.com/progit/progit2/commit/87254184fd3642148c284df68c59ae20751ca44a

**Comment by pedrorijo91** [comment]
what is it needed to have the image updated on the website also @peff ? I though the images were reused from the book repository

**Comment by peff** [comment]
I'm not sure why we don't have the updated images (if we failed to import them, or if they're in the repo but need something special done with the asset code to be served on the site). Some discussion in https://github.com/git/git-scm.com/issues/515#issuecomment-279069880, but I haven't had a chance to dig deeper.

**Comment by jnavila** [comment]
It was fixed last november. We haven't pulled since then.

**Comment by peff** [comment]
I don't think that's it. The versions I pulled in #775 have several fixes. E.g., see https://github.com/git/git-scm.com/pull/775/files#diff-812dfc5fbd8656872fbf64fe9ffd8c57 for this case.

But the ones you added in https://github.com/git/git-scm.com/commit/4d71b81a565ad2f30a0aa5fc232d47c470330f65 don't have the fixes. So I think we actually _were_ fixed for a while, but regressed recently.

The ones from #775 were mined out of the Atlas-generated zipfile (and as a result, you can see in the diff linked above that the resolution isn't quite as good). So I think we need to re-import, but do it directly into your new image hierarchy.

**Comment by peff** [comment]
Fixed by #952.
