### ISSUE TITLE
Bad link in "docs/git-config"

### ISSUE THREAD

**Issue by larsbrinkhoff** [git/git-scm.com#476]
About in the middle of the page at http://git-scm.com/docs/git-config, there is a bad link called `diff-config.txt`.  Looks like another instance of #425?

**Comment by Dmole** [comment]
more here:
http://git-scm.com/docs/git-merge
mergetools-merge.txt
etc

**Comment by jcrben** [comment]
Bump. I noticed that http://git-scm.com/docs/git-config was missing some information at https://www.kernel.org/pub/software/scm/git/docs/git-config.html and I think this probably explains it.

**Comment by sxlijin** [comment]
Hey, is still an issue for anyone? If not I'd move to close.

**Comment by larsbrinkhoff** [comment]
Made a quick check - seems ok.
