### ISSUE TITLE
Wrong commit number in image "Divergent history" of page "3.1 Git Branching - Branches in a Nutshell"

### ISSUE THREAD

**Issue by rogerl-prisma** [git/git-scm.com#477]
"testing" branch points to c2b9e and "master" to 87ab2. It should be the opposite.

The URL of the page is:
http://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

**Comment by YueLinHo** [comment]
Please close this issue as dulicate #472.
