### ISSUE TITLE
git svn clone error on svn 1.8 created respository

### ISSUE THREAD

**Issue by saschwarz** [git/git-scm.com#478]
I'm following the steps in:
http://git-scm.com/book/en/v2/Git-and-Other-Systems-Git-as-a-Client

to move an svn repository to git. My local svn versions are:
$ svn --version
svn, version 1.8.10 (r1615264)
   compiled Aug 25 2014, 10:52:18 on x86_64-apple-darwin12.5.0

When I clone the repository I get an error reading the local file system format:
$ git svn clone file:///tmp/test-svn -s
Initialized empty Git repository in /private/tmp/test-svn/.git/
Couldn't open a repository: Unable to connect to a repository at URL 'file:///tmp/test-svn': Unable to open an ra_local session to URL: Unable to open repository 'file:///tmp/test-svn': Expected FS format between '1' and '4'; found format '6' at /usr/local/Cellar/git/2.1.0/lib/perl5/site_perl/Git/SVN.pm line 310

According to this svn release note FS format 6 was introduced in svn 1.8:
http://subversion.apache.org/docs/release-notes/1.8.html#revprop-packing

Could it be the git 2.1 Perl script isn't yet compatible with this svn release?

**Comment by kelvinau** [comment]
@saschwarz I am having the same problem. I am using git 2.14.1 and svn 1.8.8. May I know how you have solved this issue?

**Comment by saschwarz** [comment]
I should have posted the answer: https://stackoverflow.com/a/27325713/457935
