### ISSUE TITLE
request pull should be more helpful when failing

### ISSUE THREAD

**Issue by rustyrussell** [git/git-scm.com#488]
When invoked without any revid:

warn: No match for commit b0a65b0cccd477b2fd8b7adad0ac39433df54829 found at korg
warn: Are you sure you pushed 'HEAD' there?

This broke my scripts, but worse, that commit _is_ on the remote repository, and stating it explicitly on the commandline works.  Of course, it's better to use the tag, but this message is deeply misleading.

**Comment by Sicaine** [comment]
This is probably you wanna talk to the guys of git. This issue tracker is for git-scm.com. You can find there mailing list at git@vger.kernel.org.

@maxlazio easy close :)
