### ISSUE TITLE
Connecting to the site over TLS presents a mismatched certificate

### ISSUE THREAD

**Issue by csuhta** [git/git-scm.com#489]
The site serves the `*.herokuapp.com` certificate if you try to visit it at https://git-scm.com

![screen shot 2014-12-18 at 7 49 50 pm](https://cloud.githubusercontent.com/assets/769083/5498585/260cff44-86ef-11e4-97d8-efcc1cd380c4.png)

**Comment by julianladisch** [comment]
https://git-scm.herokuapp.com/ works, though.

**Comment by peff** [comment]
This came up again on the [git list](http://article.gmane.org/gmane.comp.version-control.git/267273).

According to [this documentation](https://devcenter.heroku.com/articles/ssl-endpoint), to get this right we have to provision an SSL endpoint at Heroku. Which makes sense, but does appear to cost $20/month.

/cc @schacon

**Comment by schacon** [comment]
Ah. This was confusing me for a bit until I realized that I never figured anyone would use git-scm.com over https since there is no state or login data stored. I suppose if you directly type it in it's broken, I just never considered that. I can either redirect https traffic or buy a cert. I'll buy a cert and see if that works at all.

**Comment by peff** [comment]
I'm in the habit of just typing `https://` by default these days. Also, extensions like HTTPS Everywhere will auto-redirect. So yeah, this is probably biting a minority of users, but it would be nice in the "everything should be encrypted just because" kind of way.

**Comment by schacon** [comment]
I also can't just add the endpoint, I need to provision a cert. This may take a bit of time.

**Comment by schacon** [comment]
Sweet, looks like this works now.

**Comment by peff** [comment]
:boom: Looks good from here, too. Thanks @schacon.

**Comment by csuhta** [comment]
Hooray! Thank you! 🎉
