### ISSUE TITLE
Homepage: Alert banner about the urgency of the upgrade?

### ISSUE THREAD

**Issue by tasinet** [git/git-scm.com#490]
I was expecting the git-scm.com homepage to convey some sort of urgency about this upgrade  - maybe something to the effect of a flashing red alert/banner, explaining the situation? Am I not seeing it because I'm on a Linux, or ...?

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.

If I'm mistaken, please correct me, because I have no context for this whatsoever.
