### ISSUE TITLE
Git Mac Installer page not updating

### ISSUE THREAD

**Issue by timcharper** [git/git-scm.com#491]
It is stuck in the past, saying the last build was published 6 months ago. Is there something I can do to help get this resolved?

http://git-scm.com/download/mac

https://sourceforge.net/projects/git-osx-installer/files/

**Comment by mindsocket** [comment]
People new to git are downloading a vulnerable client via this page. It looks like a version bump is needed in the db. Who can do that?

**Comment by timcharper** [comment]
no they aren't. I pulled the vulnerable package version. It prompts them to download a later.

Version bump would be helpful.

**Comment by mindsocket** [comment]
I see, and stand corrected in that respect.

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
