### ISSUE TITLE
dependencies for installing documentation

### ISSUE THREAD

**Issue by flip111** [git/git-scm.com#493]
http://git-scm.com/book/en/v2/Getting-Started-Installing-Git#Installing-from-Source

this section does not mention you need `asciicode` -> `xmlto` -> `getopt`

**Comment by sxlijin** [comment]
Is this still an issue? If not, I'd move to close.

**Comment by peff** [comment]
Not sure if this is an issue still or not, but it's book content; the fix would need to go into the [progit2 repo](https://github.com/progit/progit2).

**Comment by flip111** [comment]
Unless the dependencies are dropped i guess it's still an issue. Would you guys like it if i open up an issue in progit2 repo instead?

**Comment by peff** [comment]
@flip111 Yes, exactly. Thanks!
