### ISSUE TITLE
http://git-scm.com/docs/git-branch -v documentation issue

### ISSUE THREAD

**Issue by vikramvi** [git/git-scm.com#494]
Hi,

Please refer to section under  -v
"..When in list mode, show sha1 and commit..."

please correct this sentence

Thanks & Regards,
Vikram

**Comment by carlosmn** [comment]
The documentation is kept in git's source tree. This project is about the code for the website. See http://git-scm.com/community for how to get in contact with the developers of the git tool.

**Comment by pedrorijo91** [comment]
not sure about the reported problem. was there any problem on the documentation and the OP ( @vikramvi  ) is suggesting to replace it by `"..When in list mode, show sha1 and commit..."` ? If so, that's what is being shown currently, so I would say it is fixed. If not, can you please clarify the problem @vikramvi ?

nevertheless, as already pointed out by @carlosmn , the issue should be reported to the community as it is not an issue directed to this repo.

close @peff ?
