### ISSUE TITLE
Update source code link to point to git-for-windows project rather than msysgit

### ISSUE THREAD

**Issue by aholmes** [git/git-scm.com#496]
The download page states

> The current source code release is version 2.2.1. If you want the newer version, you can build it from the [source code](https://github.com/msysgit/git/).

The msysgit project is no longer maintained as stated in their readme

> Please note that the Git for Windows project will soon switch to [another development environment](https://github.com/git-for-windows/) and that the upcoming Git for Windows 2.\* will be maintained [here](https://github.com/git-for-windows/git).

The link should now point to https://github.com/git-for-windows/git.

**Comment by sxlijin** [comment]
This no longer seems to be an issue (the download pages don't seem to suggest building from source anymore) and should be closed.
