### ISSUE TITLE
wrong command in git aliases

### ISSUE THREAD

**Issue by magicly** [git/git-scm.com#498]
at the bottom of http://git-scm.com/book/en/v2/Git-Basics-Git-Aliases page, this command:
```
$ git config --global alias.visual "!gitk"
```
is wrong, should be
```
$ git config --global alias.visual '!gitk'
```

**Comment by peff** [comment]
It depends on your shell, but yeah, I think using single-quotes is a better plan to avoid `!`-expansion in bash. However, all of the book content comes from the https://github.com/progit/progit2 repository, so I think the change would have to be made there (and then as a bonus, it will go into the next version of the book).

I'm closing this, as the issue should be tracked in that repository.
