### ISSUE TITLE
[Feature request] Syntax highlighting in code snippets / examples.

### ISSUE THREAD

**Issue by absorber** [git/git-scm.com#500]
Right now the code snippets (for instance in [example sections](http://i.imgur.com/wHL6JnB.png)) are all red, which is confusing for a lot of new people. So why not just use something like [gist embedding](https://github.com/blairvanderhoof/gist-embed)?

Should I make a pull request which utilizes pretty colors? :)

**Comment by sxlijin** [comment]
None of those snippets are particularly heavily colorized even in normal terminal output - did you have something specific in mind?

If not, or if you don't feel strongly about this, I'd move to close this.

**Comment by peff** [comment]
The section in the linked screenshot comes from the Git manpages. So before we could do any content-specific colorization, we'd need annotation of what content is in the examples. I know this is easy with markdown, but I'm not sure how it would work with asciidoc. Either way, though, the change needs to happen in Git's manpages, and then we can look at formatting it in a pretty way on the site.
