### ISSUE TITLE
accept crypto currency (bitcoin) donations

### ISSUE THREAD

**Issue by borisplotkin** [git/git-scm.com#501]
as title states

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If this issue is still relevant and you still want to discuss it, you should reach out to the [community](https://git-scm.com/community).

**Comment by peff** [comment]
I think this isse is actually up to the Software Freedom Conservancy, as they handle all of the donations to the project. The complete list of options can be found at https://sfconservancy.org/donate/ (and you can donate there and earmark for the Git project). It's possible that the git-scm.com donate page needs some updating to make the options more obvious.
