### ISSUE TITLE
Figure description missing in images' captions

### ISSUE THREAD

**Issue by rajbdilip** [git/git-scm.com#502]
![2015-01-26_015439](https://cloud.githubusercontent.com/assets/5624277/5893133/8fc71f82-a4fe-11e4-865e-068018019c63.png)

In many sections, text references figures like shown in this snapshot but figure numbering is missin in captions of images. Clicking in the figure reference loads the imgae in a new tab.

As you go with the flow, its obvious that which figure the text is trying to reference but sometimes its not.

**Comment by jnavila** [comment]
This is an issue with progit2 book. Please open the issue, or even better fix the text and send a pull-request to progit/progit2.

**Comment by jnavila** [comment]
In fact, this has already been fixed in the source. If you are reading the PDF or ebook version, please download the latest version.

**Comment by rajbdilip** [comment]
@jnavila This is the issue with the site as well. Is it fixed too?

**Comment by jnavila** [comment]
@schacon How come the web page are not updated with the latest source of the book?

**Comment by jnavila** [comment]
Fixed.

**Comment by pedrorijo91** [comment]
@maxlazio @peff this can be closed
