### ISSUE TITLE
Broken link 'Figure 7-1' in Git Tools - Revision Selection

### ISSUE THREAD

**Issue by dregad** [git/git-scm.com#506]
Hello,

I noticed that in the [Commit Ranges section](http://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Commit-Ranges) there are 2 links (in _Double dot_ and _Triple dot_) labeled `Figure 7-1` pointing to http://git-scm.com/book/en/v2/ch00/double_dot which displays an HTTP 500 error.

HTH.

**Comment by pedrorijo91** [comment]
it seems to be fixed. no HTTP 500 shown @peff

**Comment by peff** [comment]
Yes, the broken figure links were all fixed by @jnavila last year (I think in #762).
