### ISSUE TITLE
Feature request: Automatically push .gitignore files

### ISSUE THREAD

**Issue by DaveJarvis** [git/git-scm.com#507]
# Replicate
1. Create a new repository (`git init`).
2. Create some log files that should not be added to the repository (e.g., `touch filename.log`).
3. Create a `.gitignore` file (`echo filename.log >> .gitignore`).
4. Commit changes (`git commit -a -m`).
5. Push changes to repository (`git push origin master`).
# Expected Results

The `.gitignore` is automatically added to the list of files to be added to the repository.
# Actual Results

The file must be added manually using `git add .gitignore`.
# Additional Details

For backwards compatibility, this could be a command line option (`--auto-add-gitignore`).

**Comment by YueLinHo** [comment]
In your step 3, the option **-a** of git commit:
Tell the command to automatically stage files that have been modified and deleted, 
but **new files you have not told Git about are not affected**.
see [here](http://git-scm.com/docs/git-commit)

So, git add is needed. :)

And it may be irrelevant that post such kind of issue here.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If this issue is still relevant and you still want to discuss it, you should reach out to the [community](https://git-scm.com/community).
