### ISSUE TITLE
More broken links: section 5.2 Distributed Git - Contributing to a Project

### ISSUE THREAD

**Issue by zbeekman** [git/git-scm.com#508]
On [this page](http://git-scm.com/book/ch5-2.html) There are a number of broken links that give 404 errors: [“Interactive Staging”](http://git-scm.com/book/ch07/_interactive_staging) [“Rewriting History”](http://git-scm.com/book/ch07/_rewriting_history) [“Commit Ranges”](http://git-scm.com/book/ch07/_commit_ranges) [“The Refspec”](http://git-scm.com/book/ch10/_refspec) [“Chapter 6”](http://git-scm.com/book/ch06/_github) [Figure 5-18](http://git-scm.com/book/ch00/psp_b) It seems like this is a common problem throughout the online version of the book.

**Comment by zbeekman** [comment]
ping @schacon

**Comment by jnavila** [comment]
The URL has changed: please read the page at https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project where the crossrefs work.

**Comment by zbeekman** [comment]
Thanks @jnavila
