### ISSUE TITLE
Git Tools - Submodules - example repo does not exist

### ISSUE THREAD

**Issue by abdullah2** [git/git-scm.com#509]
In describing Submodules (http://git-scm.com/book/en/v2/Git-Tools-Submodules), DbConnector repo was used. However, on attached link (https://github.com/chaconinc/DbConnector), which is used for explanation and examples, mentioned repo does not exist.

**Comment by honor6-channe** [comment]
honor6-channe

**Comment by sxlijin** [comment]
Hey, so this is actually about the Pro Git book - I think you want to reopen this issue over at [that repository](https://github.com/progit/progit2).
