### ISSUE TITLE
Document likely error

### ISSUE THREAD

**Issue by dper** [git/git-scm.com#511]
I spent several hours trying something like the following in an `.htaccess` file.  It's very similar to the example on http://git-scm.com/docs/git-http-backend showing how to have anonymous read access but authenticated write access.  Here's the relevant part of the `.htaccess` file.

```
# Get a password for write requests.
RewriteCond %{QUERY_STRING} service=git-receive-pack [OR]
RewriteCond %{REQUEST_URI} ^/git/.*/git-receive-pack$
RewriteRule ^ - [env=WRITE]

Order Deny,Allow
Deny from env=WRITE
```

This code doesn't work because the `Deny from` part is evaluated before the `RewriteRule` part.  The `Deny from` is evaluated first, and at that time `env` is not yet set, so it never denies anyone, so you never are asked to authenticate, so you can never push to the repository.  That is consistent with Apache documentation, but it's very easy to not realize this and spend several hours of effort only to later learn the setup is no good.  Apparently `mod_authz_core` is loaded before `mod_rewrite`.  Anyhow, the above code looks sensible, after all, and it's _very_ similar to the example shown in the documentation.  That's worth noting somehow.

Anyhow, it might be nice to document that this doesn't work.  Alternately, if someone has some way of doing this kind of thing in an `htaccess` file, that would be a great addition.

At least on Apache 2.2 on Dreamhost, the above setup does not work.  This also suggests the example in the documentation would fail, but since I don't have access to `httpd.conf` on that machine, I can't test it.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If this issue is still relevant and you still want to discuss it, you should reach out to the [community](https://git-scm.com/community).
