### ISSUE TITLE
Add "autoconf" to tools needed to build from source

### ISSUE THREAD

**Issue by JJ** [git/git-scm.com#519]
That is, here http://git-scm.com/book/en/v2/Getting-Started-Installing-Git

Make

    apt-get install libcurl4-gnutls-dev libexpat1-dev gettext  libz-dev libssl-dev

this

     apt-get install libcurl4-gnutls-dev libexpat1-dev gettext  libz-dev libssl-dev autoconf

You need to add asciidoc too if you want to build docs.

**Comment by jnavila** [comment]
This is an issue with the book. Please fill an issue (or better a pull request) in project progit/progit2.

**Comment by JJ** [comment]
OK, thanks.
