### ISSUE TITLE
Empty duplicate `branch` entries in config

### ISSUE THREAD

**Issue by chillum** [git/git-scm.com#520]
I have Git 2.3.3 and a Git repo. I have to migrate to another server for push and pull. I do:

`git remote remove origin; git remote add origin new_repo; git push; git branch --set-upstream-to=origin/master`

Now I get in my `.git/config`:

```
[core]
...
[branch "master"]
[remote "origin"]
    url = new_repo
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
    remote = origin
    merge = refs/heads/master
```

The case is the first line `[branch "master"]` is left from the old upstream. It's empty (when I remove the old origin, its' contents are removed), but it's still in the config file and that's not necessary.

My suggestion that Git should either:
1. When removing an entry from the config file it should remove the config section, if it's empty
2. When appending to a config file, it should search for a matching section, it should append to it, not leaving it blank and writing a duplicate one.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If this issue is still relevant and you still want to discuss it, you should reach out to the [community](https://git-scm.com/community).
