### ISSUE TITLE
surplus backlashes in rev-list

### ISSUE THREAD

**Issue by hginzel** [git/git-scm.com#521]
Please remove surplus backslashes in Synopsis in [git rev-list](http://git-scm.com/docs/git-rev-list).

**Comment by peff** [comment]
This is an asciidoc/asciidoctor compatibility problem, and is being fixed in the [upstream manpage](http://article.gmane.org/gmane.comp.version-control.git/268932).

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
