### ISSUE TITLE
Swapped Checksums in Image

### ISSUE THREAD

**Issue by jakehemmerle** [git/git-scm.com#524]
master/public/book/en/v2/book/03-git-branching/images/advance-master.png

In the image, the checksums of the latest commits for 'master' and 'testing' are swapped.

**Comment by jnavila** [comment]
This has been fixed in the book 6 months ago. Sadly, the fixes don't seem to be visible on the site.

**Comment by jakehemmerle** [comment]
It happens. Thanks for acknowledging!

**Comment by maxlazio** [comment]
Duplicate of #472, closing this one.
