### ISSUE TITLE
Please suggest using Homebrew for OS X install since OS X installer is no longer being maintained

### ISSUE THREAD

**Issue by garysweaver** [git/git-scm.com#529]
See: https://github.com/timcharper/git_osx_installer/issues/41

**Comment by timcharper** [comment]
They are still being updated, just got a little behind.

**Comment by garysweaver** [comment]
@timcharper totally understand, but I think it might be a good idea for git-scm.com to display both well-used means of staying up-to-date with Git. There have been times in the past when Homebrew wasn't up-to-date and for the past few months git_os_installer was out-of-date, so unless git_os_installer is going to be continually tracking the latest version of Git, I think there should be other options.

**Comment by timcharper** [comment]
If there is an urgent reason for upgrade (such as a import security vulnerability), I am quick to update. Giving additional options may introduce more confusion for the users. I'd argue that most people looking for a quick way to install git aren't as concerned if they are installing a version a couple months old. I'll try and keep it more up to date in the future (maybe set a reminder to build and deploy weekly).

**Comment by garysweaver** [comment]
@timcharper I had been using the git_osx_installer version provided by git-scm.com for a while and suggesting it to others, but unless it is tracked to the latest, I couldn't continue to recommend that.

I understand at times an earlier version could be more stable- but if that were the case, I'd expect that to be noted in the page.

The confusing part to me is that git-scm on the front page says "Latest source Release..." as if it tracks the latest, but it sounds like that is not the goal of the git_osx_installer project, and that is fine, but I think in that case, git-scm.com should be much more careful about how it labels things.

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
