### ISSUE TITLE
OS X version 10.10 shows a *-snow-leopard download when it should be *-mavericks

### ISSUE THREAD

**Issue by wking** [git/git-scm.com#532]
Over at Software Carpentry we're having a hard time getting novice users to download the appropriate Git installer for their OS X version (see swcarpentry/workshop-template#196 and swcarpentry/workshop-template#204).  I'm not familiar with the JavaScript browser detection used by this page, but it would be nice if we could detect the OS X version behind a given browser, and point them at the appropriate downloader, automating the selection detailed under [“Which version should I download?” in the git-osx-installer](http://sourceforge.net/projects/git-osx-installer/files/) page.

**Comment by sxlijin** [comment]
Is still a relevant issue? The downloads are hosted on git-scm.com now, so I'm not sure how applicable this still is.

**Comment by wking** [comment]
> The downloads are hosted on git-scm.com now…

Really?  It looks like you're still linking to SourceForge for git-osx-installer:

```
$ curl -s https://git-scm.com/download/mac | grep sourceforge
<p>You are downloading version <strong>2.10.1</strong> of Git for the <strong>Mac</strong> platform. This is the most recent <a href='https://sourceforge.net/projects/git-osx-installer/'>maintained build</a> for this platform. It was released <strong>4 months ago</strong>, on 2016-10-14.</p>
<p><strong>If your download hasn't started, <a href="http://sourceforge.net/projects/git-osx-installer/files/git-2.10.1-intel-universal-mavericks.dmg/download?use_mirror=autoselect">click here to download manually</a>.</strong></p>
<iframe frameborder='0' height='1' src='http://sourceforge.net/projects/git-osx-installer/files/git-2.10.1-intel-universal-mavericks.dmg/download?use_mirror=autoselect' width='1'></iframe>
```

So I think this is still relevant.  I expect you need to either:

* Distinguish between assorted OS X versions [here][1] like you currently do between different Windows versions [here][2], or
* Require users to explicitly pick, sort of like you do for Linux [here][3].

Which way you go probably depends on how reliably you can detect the OS X version from the user agent (like [you do for Windows][4]), and I have no idea on that score ;).

[1]: https://github.com/git/git-scm.com/blob/0d229fc86fa3730a3a2cba1a08f0b65d5fc84c37/app/controllers/downloads_controller.rb#L32
[2]: https://github.com/git/git-scm.com/blob/0d229fc86fa3730a3a2cba1a08f0b65d5fc84c37/app/controllers/downloads_controller.rb#L40-L52
[3]: https://github.com/git/git-scm.com/blob/0d229fc86fa3730a3a2cba1a08f0b65d5fc84c37/app/views/downloads/download_linux.html.erb#L8-L40
[4]: https://github.com/git/git-scm.com/blob/0d229fc86fa3730a3a2cba1a08f0b65d5fc84c37/app/controllers/downloads_controller.rb#L46

**Comment by sxlijin** [comment]
Whoops, that's my bad - I must've looked at the wrong link when I double-checked the page. @peff thoughts?

**Comment by peff** [comment]
Yes, we definitely still link to the osxinstaller project. It looks like that really only has mavericks releases for recent versions. TBH, I do not have any idea how the osxinstaller works, what versions of OS X are common, how good browser detection support is, or what's normal for people on those platforms.

So what I'd really like is a PR from somebody familiar with those things.

**Comment by wking** [comment]
On Wed, Feb 08, 2017 at 09:58:29AM -0800, Jeff King wrote:
> TBH, I do not have any idea how the osxinstaller works, what
> versions of OS X are common, how good browser detection support is,
> or what's normal for people on those platforms.

Me neither.  Looking at the last week's download counts on [1], there
are many more git-*-mavericks downloads (16,515) than
git-*-snow-leopard downloads (142), but I'm not sure how many of those
are unique users (vs. repeat users or mirrors or whatever).

> So what I'd really like is a PR from somebody familiar with those
> things.

To cover this case in the absence of someone familiar with OS X, I
think we should err on the side of safety and make the user explicitly
choose which version to use.  Someone who is familiar with OS X can
say “I'm tired of choosing this by hand, why can't we decide based on
$THING”, and we can update then.  I'm happy to work up an
explicitly-choose PR if that approach sounds appealing.

[1]: https://sourceforge.net/projects/git-osx-installer/files/

**Comment by peff** [comment]
@wking Sure, that sounds like a reasonable path forward.

**Comment by jasonlong** [comment]
As I triage the open issues for the current design work, is this one still relevant?

**Comment by peff** [comment]
I'm not sure. It looks like the only build these days is the Mavericks one (which works on releases after that). So there's really no choice to be made by the user at this point (and anything pre-Mavericks has been at least two years since the last security release from Apple, so I'm not sure it's even worth worrying about).

But I'm not a Mac user, so my impressions of what's common may be off.

**Comment by pedrorijo91** [comment]
The last not mavericks version was released 3 years ago https://sourceforge.net/p/git-osx-installer/activity/?page=0&limit=100#5530108b271846501f3a00ad

I'm fine with closing this issue. But we probably want to design the new version in such a way the user can easily fetch the correct version if our browser detection fails, no @jasonlong ?

**Comment by jasonlong** [comment]
Let's keep this open for now as something to keep in mind when we get to the downloads page.

**Comment by pedrorijo91** [comment]
closing this as the mac installer is unique for all recent versions for 3 years now.
