### ISSUE TITLE
When will the latest release available for windows platform?

### ISSUE THREAD

**Issue by duytrung** [git/git-scm.com#537]
Hi,

It's really amazing that git release version 2.0, 2.1, 2.2, 2.3, 2.4...What does it mean for Windows version? It's still 1.9.5. I'm not a professional programmer, however I found that git is a part of my study of programming. Windows is still the most popular development platform. Why do they not provide the compiled binary for Git, 2.4 at the moment for everyone to use?

**Comment by JHGitty** [comment]
It is confusing that on the first page on http://git-scm.com there is "Latest source Release: 2.4.1" and the download button under it for Windows will give you Version 1.9.5-previewXYZ.

**Comment by ubershmekel** [comment]
Linking to https://github.com/git-for-windows/git/releases would help a lot.

> The current source code release is version 2.4.1. If you want the newer version, you can build it from the source code.

For a windows developer that translates to "a binary does not exist on the internet and you shouldn't go looking for one".

**Comment by dscho** [comment]
It is really amazing that so few people search far enough to see that I am *really* busy to get Git for Windows 2.x ready, and you guys don't lift a finger, really, to help me there.

In any case, I think this can be closed in favor of PR, which should however only be merged once I publish Git for Windows other than as a preview for Git for Windows developers who are willing to help.

**Comment by nalla** [comment]
See https://github.com/git/git-scm.com/pull/535

**Comment by JHGitty** [comment]
> For a windows developer that translates to "a binary does not exist on the internet and you shouldn't go looking for one".

This is really really bad and should be explained to everybody who like to download Git for Windows.

**Comment by dscho** [comment]
Why don't you gentlepeople just head over to the project, pick up a few of the remaining issues, help resolve them, and then we can finally release a Git for Windows built from a current Git version? This would really help much more than distracting the maintainer with discussions like this one.

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
