### ISSUE TITLE
Private code encryption

### ISSUE THREAD

**Issue by Odonno** [git/git-scm.com#538]
Hi,

I am thinking about a really useful feature : private code encryption.

It comes from a painful system where you gitignore your private code file to not let anyone see your passwords, for example. With encryption, it helps us to not gitignore our code.

It remains one problem, if you encrypt your code in your local git and you push that code, the code is now unreadable for anyone and so yourself if you pull again... And other problem, everyone can decrypt code if they know how it is encrypted (like watching git source file).

But, to solve this, I imagined a new online software solution (based on GitHub) that automatically save/retrieve your private code when push/pull occurs (and checking you're owner/admin of the code/repository).

And now is the workflow :
1. Commit your code
2. Push your code (start the push)
   - Check for private code
   - If private code, encrypt it by calling the new software solution
   - Mark code encrypted in the way that git can recall the decryption on pull (your own code is still unchanged, stay uncrypted, it is only the in-memory part that is updated)
   - So push the entire code to the centralized git

And the second part :
1. Pull the code from the centralized git
2. Check for private code
   - If private code, check if you are owner/admin of this repository
   - If so, call the new software solution to decrypt the code
3. And you are ready to code now without losing time to encrypt/decrypt yourself everytime

**Comment by jnavila** [comment]
This is not the place to talk about git development. There is a mailing list at git@vger.kernel.org for this purpose.
