### ISSUE TITLE
Getting started page image url issue

### ISSUE THREAD

**Issue by vigneshwaran-ms** [git/git-scm.com#539]
In the online version of the git scm book(v2) the getting started page having a image which is pointing to an image which acutally does not exist(checked the github source of this app) which is renamed due to  this ( #217)  issue.
![issue_git-scm com_book_en_v2_getting-started-about-version-control](https://cloud.githubusercontent.com/assets/6781197/7440200/c3a4a86e-f0c2-11e4-8044-ed7be52df75b.png)

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
