### ISSUE TITLE
gitcore-tutorial formatting issue

### ISSUE THREAD

**Issue by mcint** [git/git-scm.com#544]
Just after the first appearance of `git diff-files -p` there is an unclosed code block which affects the format of 5 screen-heights, about half of the page, at https://git-scm.herokuapp.com/docs/gitcore-tutorial for version 2.4.0.

**Comment by jnavila** [comment]
The documentation coming from the git project is correctly processed by asciidoc 8.6.9 on my system, but the formatter (gem asciidoctor 0.1.4 !) seems to fail on git-scm.com.

**Comment by jnavila** [comment]
The code fences are not matched. Fix proposed to git project.

**Comment by sxlijin** [comment]
Is this still an open issue?

**Comment by pedrorijo91** [comment]
Updated url: https://git-scm.com/docs/gitcore-tutorial

I could not replicate the problem using iPhone6 and testing using several emulated devices on chrome inspector.

Closing the issue unless someone can provide a reproducible test case ( @mcint  if you can confirm if this is happening it would be great)

**Comment by peff** [comment]
Yeah, this was fixed long ago by @jnavila in git/git@975e382d13ba9ce98cd58820283464b6aaefbad1.
