### ISSUE TITLE
Typo in image (chapter 3.2)

### ISSUE THREAD

**Issue by vladimirkroupa** [git/git-scm.com#546]
I believe the commit pointed at by the master branch should have label C6, not C5.
https://git-scm.com/book/en/v2/book/03-git-branching/images/basic-merging-2.png

**Comment by jnavila** [comment]
This was an issue in the book (progit/progit2), but it was fixed few months ago. Now, the issue is that the site does not update from the the content of the book. You can check the PDF or ebook files ; these one are correctly updated and all the fixups are applied.

**Comment by prasopes** [comment]
Didn't realize that. Thanks for letting me know.

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
