### ISSUE TITLE
Mixed content error

### ISSUE THREAD

**Issue by dhimmel** [git/git-scm.com#547]
Got a [mixed content error](https://developer.mozilla.org/en-US/docs/Security/MixedContent/How_to_fix_website_with_mixed_content) in chrome when visiting:
https://git-scm.com/video/what-is-version-control

Had to allow non-https content to see video. Can links be changed to [protocol-relative URLs](https://en.wikipedia.org/wiki/Uniform_resource_locator#Protocol-relative_URLs)?

**Comment by 719Ben** [comment]
Fixed with https://github.com/git/git-scm.com/pull/548

**Comment by imalsogreg** [comment]
I see the change has gotten into the repository, but the git-scm website link still points to the http, rather than https vimeo link.

**Comment by bocahnakal** [comment]
Stop send me email.thanks
Pada tanggal 10 Jan 2016 09:07, "Greg Hale" <notifications@github.com>
menulis:

**Comment by dhimmel** [comment]
@bocahnakal, you need to update your GitHub email subscriptions. There is an unsubscribe button on the right. You may want to unfollow the project.

**Comment by sxlijin** [comment]
9 This no longer seems to be an issue and should be closed.
 10
