### ISSUE TITLE
Pro Git book picture error

### ISSUE THREAD

**Issue by warriorkitty** [git/git-scm.com#549]
Hi all,

I don't know if I'm at the right place but I'm reading the book Pro Git book online and the chapter:

Centralized Version Control Systems (https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control#Centralized-Version-Control-Systems) doesn't show the picture "Centralized version control diagram".

**Comment by randomecho** [comment]
Second edition of the book looks like it's handled at https://github.com/progit/progit2/

**Comment by warriorkitty** [comment]
Thank you, I'll open this issue there.
