### ISSUE TITLE
Mac OS X Beta: Changes to git-credentials-osxkeychain

### ISSUE THREAD

**Issue by leesavide** [git/git-scm.com#563]
Evidently, `osxkeychain` is no longer a valid command in the Mac OS X beta. The new command that replaces it is [`security`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/security.1.html). I don't think it changes any particular part of git internals, but the documentation on git-scm.com (and everywhere else it's mentioned) is going to need to change, lest there be a 100+ issues of "git credentials on mac os x doesn't work". :)

**Comment by MoOx** [comment]
This will even make more sense now that OS X is renamed macOS starting (mac)OS( X) 10.12.

**Comment by sxlijin** [comment]
Hey, so this is actually about the Pro Git book - I think you want to reopen this issue over at [that repository](https://github.com/progit/progit2).
