### ISSUE TITLE
Missing option for processing Mercurial tags in fast-export in section 9.2 Migrating to Git

### ISSUE THREAD

**Issue by hawkman69** [git/git-scm.com#565]
In section 9.2 Git and Other Systems - Migrating to Git, subsection Mercurial it states:

"That’s pretty much all there is to it. All of the Mercurial tags have been converted to Git tags, and Mercurial branches and bookmarks have been converted to Git branches."

But this is not correct with given example of how to use hg-fast-export.sh in respect to tags.  To get hg-fast-export.sh to also process tags one must use the --hgtags option.

So this:
/tmp/fast-export/hg-fast-export.sh -r /tmp/hg-repo -A /tmp/authors

Should be this:
/tmp/fast-export/hg-fast-export.sh -r /tmp/hg-repo -A /tmp/authors --hgtags

I just converted all the Mercurial repos for my team to Git and have tested the --hgtags option is needed and works.

**Comment by sxlijin** [comment]
Hey, so this is actually about the Pro Git book - I think you want to reopen this issue over at [that repository](https://github.com/progit/progit2).
