### ISSUE TITLE
Book display is broken

### ISSUE THREAD

**Issue by ben** [git/git-scm.com#567]
Here's what I see on [the site](http://git-scm.com/book/en/v2) right now:

![image](https://cloud.githubusercontent.com/assets/39902/9159194/cc6e09b8-3ed8-11e5-9693-eb5b66b1b38f.png)

@schacon, any idea what's going on?

**Comment by schacon** [comment]
Oh no. I'll look into it, thanks!

**Comment by schacon** [comment]
Atlas changed the way they produce the HTML product quite dramatically for some reason. Working on a fix now.

**Comment by schacon** [comment]
This is now fixed temporarily, I'll work on a PR to get it merged permanently. Images are broken, but I'm working on that now.

**Comment by schacon** [comment]
I messed up the images somehow, I'm not sure what changed. I'm going to have to fix them tomorrow I think.

**Comment by schacon** [comment]
OK, this also appears to be related to Atlas updating their toolchain this weekend. They've pushed out a fix that appears to have fixed the images, I'll verify in a few minutes.

**Comment by schacon** [comment]
sweet, images are fixed now too

**Comment by bry4n** [comment]
:+1:
