### ISSUE TITLE
Image link broken

### ISSUE THREAD

**Issue by e-ruiz** [git/git-scm.com#568]
On this page https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository
the image: _Figure 2-1. The lifecycle of the status of your files_ (https://git-scm.com/book/en/v2/images/lifecycle.png) is broken.

**Comment by e-ruiz** [comment]
Some other cases:
Page https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell
- commit-and-tree.png --> https://git-scm.com/book/en/v2/images/commit-and-tree.png
- commits-and-parents.png --> https://git-scm.com/book/en/v2/images/commits-and-parents.png
- branch-and-history.png --> sorry, I am lazy =P
- two-branches.png
- head-to-master.png
- head-to-testing.png
- advance-testing.png
- checkout-master.png
- advance-master.png

Actually, there are many links broken in this page, not only images:
- first link: Charpter 1 --> https://git-scm.com/book/en/v2/1-introduction/_getting_started
- Figure 3-9 https://git-scm.com/book/en/v2/ch00/divergent_history returns **500 error**

**Comment by schacon** [comment]
All the images were broken for a few hours due to a breaking change in the Atlas toolchain. It has been fixed now.
