### ISSUE TITLE
git install instruction are incomplete

### ISSUE THREAD

**Issue by kaustavha** [git/git-scm.com#570]
The page
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
is missing some pre-reqs for redhat linux at least. 
I also had to install these guys:

``` sh
yum install gcc gcc-c++ autoconf automake perl-devel perl-CPAN
```

**Comment by sxlijin** [comment]
Is this still an issue? I'm not familiar enough with the RHEL/CentOS/Fedora ecosystems to track down what the `git-all` source installs.

This is also actually about the Pro Git book, so even if this is still an issue, it should be reopened over at [that repository](https://github.com/progit/progit2).
