### ISSUE TITLE
some images missing && code block parse incorrectly

### ISSUE THREAD

**Issue by branchzero** [git/git-scm.com#573]
on http://git-scm.com/book/en/v2/Embedding-Git-in-your-Applications-Libgit2,
all the images can't access.
&&
I also find that in all code blocks ,
`(1)`, `(2)` and similar tags are parsed incorrectly.
`<`, `>` has been converted into `&lt;`, `&gt;` , but display wrong.

**Comment by networm** [comment]
I have found the image display wrong at http://git-scm.com/book/zh/v2/%E5%B0%86-Git-%E5%B5%8C%E5%85%A5%E4%BD%A0%E7%9A%84%E5%BA%94%E7%94%A8-Libgit2
Here is the image url: http://git-scm.com/book/en/v2/book/B-embedding-git/callouts/1.png
I open 'zh' version, so I replace 'en' to 'zh' in url: http://git-scm.com/book/en/v2/book/B-embedding-git/callouts/1.png
still 404.
I think 'book' in the url is useless. So I remove it and open http://git-scm.com/book/zh/v2/B-embedding-git/callouts/1.png and http://git-scm.com/book/en/v2/B-embedding-git/callouts/1.png
still 404.

**Comment by networm** [comment]
I also found at http://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository

the quote mark ' ' and "" was encoded in [source, console] section. It seems that Oreilly Atlas build error html version or git-scm.com ruby has change the character to escape.

here is single quote
$ echo &apos;My Project&apos; &gt; README

here is double quote
$ git commit -m &quot;Story 182: Fix benchmarks for speed&quot;

**Comment by branchzero** [comment]
I found at http://git-scm.com/book/zh/v2/Git-%E5%91%BD%E4%BB%A4-%E8%8E%B7%E5%8F%96%E4%B8%8E%E5%88%9B%E5%BB%BA%E9%A1%B9%E7%9B%AE
the link which point to other sections seems to be wrong.

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
