### ISSUE TITLE
Internal linking between chapters of progit2 is broken on git-scm.com only

### ISSUE THREAD

**Issue by crd** [git/git-scm.com#575]
For example, see this page from the first chapter, [history.asc](https://github.com/progit/progit2/blob/master/book/01-introduction/sections/history.asc) (here is the [rendered version](http://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git) at git-scm.com). The asciidoc file contains the appropriate link <<_git_branching>> and [1-git-branching.asc](https://github.com/progit/progit2/blob/master/book/03-git-branching/1-git-branching.asc) has the correct corresponding anchor: [[_git_branching]] but the book as deployed on git-scm.com doesn't correctly build links between chapters.

I initially opened an Issue against the progit2 repository (https://github.com/progit/progit2/issues/369) but as @ben points out links are built correctly in the pdf version and this seems to be an issue with how git-scm.com is deployed.

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
