### ISSUE TITLE
Broken link on "Basic Branching and Merging"

### ISSUE THREAD

**Issue by uri2x** [git/git-scm.com#585]
The link inside https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging that is supposed to lead to https://git-scm.com/book/en/v2/Git-Tools-Stashing-and-Cleaning is actually leading to 404 at https://git-scm.com/book/en/v2/1-git-tools/_git_stashing

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.

**Comment by maxlazio** [comment]
Thanks for reporting!
