### ISSUE TITLE
Superscript broken in book CSS

### ISSUE THREAD

**Issue by ben** [git/git-scm.com#586]
As reported over at https://github.com/progit/progit2/issues/409, the book's CSS has a reset applied to `sup` tags, but they're never restyled to their correct positions again.

**Comment by sxlijin** [comment]
Is still an issue? I glanced at [the linked page](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#Short-SHA-1) but I'm not entirely sure what to look for; I'm pretty sure that browsers still apply default styles to those tags though.

**Comment by peff** [comment]
The superscripts like 2<sup>80</sup> look fine on the page now. Closing.
