### ISSUE TITLE
Broken link to Git Basics

### ISSUE THREAD

**Issue by botanize** [git/git-scm.com#588]
On page: https://www.git-scm.com/book/en/v2/Getting-Started-Git-Basics
The Git Basics link is: https://www.git-scm.com/book/en/v2/1-git-basics/_git_basics_chapter

The correct link should be:
https://www.git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository

**Comment by f1remind** [comment]
The problem continues throughout the book. I think the variables dont get replaced properly.

**Comment by pmlparticipant** [comment]
I would like to second this issue.

**Comment by moehabib** [comment]
Indeed, it seems there's an extra`/1-git-branching/_` added to all links

**Comment by ben** [comment]
@schacon, I think this was your doing. Any idea what's going on?

**Comment by myshov** [comment]
@ben I want to contribute. But I have a question. Is it possible to fix this bug without access to book on atlas platform?

**Comment by ben** [comment]
I think this is an issue with this very repository, but I'm not sure where the thing is that takes fresh builds from Atlas and ships them to git-scm.com. Take a look, see if you can figure it out.

**Comment by anitadiamond** [comment]
The problem still seems to be occurring. On [http://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes](url) the link to Git Branching [https://git-scm.com/book/en/v2/1-git-branching/_git_branching](url) is broken. It seems that the only working version of this topic is on v1 of the book at [https://git-scm.com/book/en/v1/Git-Branching](url)

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.
