### ISSUE TITLE
Underscores in code blocks are not visible in Chrome on Windows

### ISSUE THREAD

**Issue by jhominal** [git/git-scm.com#596]
When I look at [https://git-scm.com/book/en/v2/Git-on-the-Server-Smart-HTTP](https://git-scm.com/book/en/v2/Git-on-the-Server-Smart-HTTP), one can see the following block:

```
SetEnv GIT_PROJECT_ROOT /opt/git
SetEnv GIT_HTTP_EXPORT_ALL
ScriptAlias /git/ /usr/lib/git-core/git-http-backend/
```

However, when I see it on screen, the underscores are not visible:
![image](https://cloud.githubusercontent.com/assets/96824/10015775/abd3fab6-6122-11e5-8dd7-7b749132241f.png)

However, the underscores are in the text.

This display issue occurs for me on Chrome 45 (on Windows), but not in Firefox or Internet Explorer.

**Comment by sxlijin** [comment]
This no longer seems to be an issue and should be closed.

**Comment by jhominal** [comment]
You are right. Closing.
