### ISSUE TITLE
Comma in tag name, can't delete.

### ISSUE THREAD

**Issue by Seanmcn** [git/git-scm.com#599]
So created a tag v0.9,6 instead of v0.9.6 
I was able to delete it locally, but trying to delete it from the remote has a problem:

`git push origin :refs/tags/v.0.9,6` 

I get the following:

remote: warning: Allowing deletion of corrupt ref.
remote: **\*  Unknown type of update to refs/tags/v0.9,6 ()
remote: **\* - no notification generated

And it doesn't delete from remote, is there a work-around for this?

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If this issue is still relevant and you still want to discuss it, you should reach out to the [community](https://git-scm.com/community).
