### ISSUE TITLE
Possible misspelling in Chapter 3

### ISSUE THREAD

**Issue by hugoender** [git/git-scm.com#601]
First page of **Chapter 3** under the _Branches in a Nutshell_ section 5th paragraph:

"When you create the commit by running git commit, Git checksums each subdirectory (in this case, just the root project directory) and stores those **_tree**_ objects in the Git repository." 

Not sure if you really meant "tree" or "three".

**Comment by YueLinHo** [comment]
Please report it to [progit2](https://github.com/progit/progit2/issues).

**Comment by YueLinHo** [comment]
Report it to correct place, please close it. :smiley:

**Comment by sxlijin** [comment]
This issue has been re-opened in the appropriate repository and should be closed.
