### ISSUE TITLE
Reset Demystifed 404

### ISSUE THREAD

**Issue by varunagrawal** [git/git-scm.com#602]
The link to [Reset Demystified](http://git-scm.com/book/en/v2/Git-Tools-Reset-Demystified) on [this page](http://git-scm.com/book/en/v2/Git-Basics-Undoing-Things) is pointing to http://git-scm.com/book/en/v2/1-git-tools/_git_reset which gives a 404 error.

I wanted to fix this, but it seems that it needs to be done one a DB level to which I don't have access. :disappointed:

**Comment by twify93** [comment]
I see this problem too. In the Book there are a lot of links not working, maybe the old style urls are left the same after some change?
For example a "Stashing and Cleaning" url is :"https://git-scm.com/book/en/v2/1-git-tools/_git_stashing" and gives 404 error

**Comment by sxlijin** [comment]
This issue seems to be resolved.
