### ISSUE TITLE
asciidoc formatting broken on https://git-scm.com/docs/user-manual.html

### ISSUE THREAD

**Issue by moy** [git/git-scm.com#605]
Hi,

Starting from the middle of the page (more precisely, from the sentence "The index is a binary file (generally kept in `.git/index`) containing a [...]"), the asciidoc is formatted as verbatim code (the source code is displayed, without formatting).

One of the consequences is that it breaks links to the glossary like https://git-scm.com/docs/user-manual.html#def_head which appear in the text but do not have corresponding anchor.

Reported by Xue Fuqiao:
http://thread.gmane.org/gmane.comp.version-control.git/279557

I do not get this mis-formatting when I run "make user-manual.html" in my Git source tree so it seems to be an issue with git-scm.com, not with the source file.

**Comment by moy** [comment]
As John Keeping pointed out on-list, the bug is indeed commit from the source code, and is fixed in https://github.com/git/git/commit/be510e0105eaed87dca76fd71f13e22952640599 (Documentation: fix section header mark-up, 2015-09-25), which isn't released yet.

**Comment by sxlijin** [comment]
This issue seems to be resolved, if I'm not mistaken - please correct me if I am.

**Comment by moy** [comment]
Yes, it is fixed.
