### ISSUE TITLE
Can not reset some files with just lineending differences

### ISSUE THREAD

**Issue by r105m** [git/git-scm.com#611]
Hi, our teem working under Windows platform on our project. And when i checkout to one of branches and do not any changes - git status tells me something like that:

On branch [branch-name]
 ...
        modified:   folder/folder/sql-script.sql

When i open that files on my diff tool, i see, that files did not have changes and lineendings is changed.

In our teem we worked in "dos" line endings and utf8 encoding.

git checkout folder/folder/sql-script.sql didn't work
git reset --hard didn't work

**Comment by Less97** [comment]
Same problems. It happens very often for us.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

This sounds mostly like someone (or many people) didn't check the man pages, which tell you how to use `core.eol`, `core.autocrlf`, and `core.safecrlf`.

**Comment by Less97** [comment]
I tried to change both core.eol and core.autocrlf. I agree thought that probably there was a bug with git-scm. Since I updated to the latest version never happened. Thank you very much for your kind reply.
