### ISSUE TITLE
might want to add a TL;DR to after 'git branch testing' 'git checkout testing'

### ISSUE THREAD

**Issue by ckot** [git/git-scm.com#612]
I totally should have known better, as I've used git for a while, but had been using svn for a different project for a few weeks.  I simply went to the 'Git-Branching-Branches-in-a-Nutshell' page to verify I remembered the create branch syntax, saw that I remembered it properly, created the branch, checked it out and made changes.

Unfortunately, I checkout my 'master' branch, forgetting that without a commit being done on my new branch, 'master' and my new branch are pointing at the same revision, and the changes got merged into 'master'.

This was totally stupid on my part, but I thought that, just so others don't experience this, you might want to add a 'tl;dr' right after the 'git checkout testing' bit that this will happen unless they do either a commit or stash on their new branch prior to switching back.  

Still can't believe I did this. :(

**Comment by pedrorijo91** [comment]
not sure on how to proceed with this @peff ...

**Comment by peff** [comment]
This is a suggestion for book content, so I think if anything is to be done, it would have to be via an issue or PR in https://github.com/progit/progit2 (the suggestion overall seems reasonable to me, though).
