### ISSUE TITLE
Git for windows makes merge conflict markers with the wrong line ending

### ISSUE THREAD

**Issue by DeadMG** [git/git-scm.com#613]
When using Git for Windows, if you get a merge conflict, the merge marker is produced with the wrong line ending. It's a Unix line ending, which produces some noisier diffs.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.

**Comment by pedrorijo91** [comment]
@maxlazio @peff this should be closed as not repo related

the issue should be posted to https://github.com/git-for-windows/git probably
