### ISSUE TITLE
Can someone push the changes in this repository to the website? 

### ISSUE THREAD

**Issue by i-give-up** [git/git-scm.com#614]
I saw that the ["GUI Clients" page](https://git-scm.com/downloads/guis) still lists Github for Mac and Github for Windows even though they have been superseded by Github Desktop.

So I came to this repository to see if I can do something about it. But I found out that [the change fixing this has already been committed back in Sept. 9](https://github.com/git/git-scm.com/commit/4741f990403baea9fed65e8105323ee933f02ad0).

Seeing that this (and probably many other commits) has yet to be reflected on the git-scm website, can someone please update it? Thanks.

**Comment by sxlijin** [comment]
This seems to be resolved.
