### ISSUE TITLE
core.ignorecase should be false by default

### ISSUE THREAD

**Issue by InderKumarRathore** [git/git-scm.com#615]
Was working on android project and suddenly renamed 'FaceBookLogin.java`to`FacebookLogin.java`, since the ignorecase is true by default and this change doesn't get reflected in the git status command and this file was not renamed on my peer's system. It cause an compile time error since java public class name must match with the file name.

Using Mac OSX

**Comment by carlosmn** [comment]
This is the bug tracker for the website. The Git project handles issues over the [mailing list](http://git-scm.com/community).

But regarding `core.ignorecase`. This does not have a default but reflects a fact of the filesystem on which your working directory is stored.

**Comment by pedrorijo91** [comment]
@peff not repo related. close?
