### ISSUE TITLE
Centralized Workflow image missing

### ISSUE THREAD

**Issue by robertobasile84** [git/git-scm.com#616]
In chapter **5.1 Distributed Git - Distributed Workflows**, the image that represents the Centralized Workflow is missing.
Probably the [link](http://git-scm.com/book/en/v2/book/05-distributed-git/images/centralized_workflow.png) is wrong

**Comment by Manuzor** [comment]
I can confirm this, the image is still missing for me as well.

**Comment by vsevolodp** [comment]
Seems like duplicate #540

**Comment by YueLinHo** [comment]
I think it's fixed by PR #652 and can be closed.

**Comment by pedrorijo91** [comment]
@peff or @maxlazio this should be closed
