### ISSUE TITLE
Where can I find checksums?

### ISSUE THREAD

**Issue by zachborboa** [git/git-scm.com#620]
I'm unable to find checksum hashes (md5, sha1, sha256, ...) for the different versions of Git on git-scm.com.

For Ubuntu, I can find checksums from the releases page.
![image](https://cloud.githubusercontent.com/assets/1083146/11216198/c7fa1704-8cfe-11e5-9fce-60eff346b6c7.png)

Thanks

**Comment by sxlijin** [comment]
To be honest I'm not sure if this information is actually published.

I know G4W does so on [their releases page](https://github.com/git-for-windows/git/releases) but I'm not sure about Git itself... @peff?

**Comment by peff** [comment]
The source packages are signed by the maintainer's GPG key. See the `.sign` files at https://www.kernel.org/pub/software/scm/git/. There is also a signed [sha256 file](https://www.kernel.org/pub/software/scm/git/sha256sums.asc).

For binary packagers, we're just linking to third-parties, who may have different practices.

**Comment by zachborboa** [comment]
The sha256 file is perfect. Thanks
https://www.kernel.org/pub/software/scm/git/sha256sums.asc
