### ISSUE TITLE
Personal Note When Creating Branch

### ISSUE THREAD

**Issue by joshcrawmer4** [git/git-scm.com#621]
Whenever I create a new branch off of master I find myself making a personal note on my desktop on what that branch is used for. It looks something like this: Iss1 -> branch off of master. Issue when creating new users. Email not getting assigned to user table.

Is this a feature we could add in. For example, when creating a new branch $ git branch iss2 --note=branch off of master. Issue when logging in to website. Probably related to user table Sha1 hash

**Comment by smith-kyle** [comment]
This repo (`git/git-scm.com)` is primarily for documenting git. If you'd like to make a feature request for git it would probably be better suited in `git/git`.

But what your describing sounds more like an integration between an item tracker and git. You could look into some project management software like [Jira](https://www.atlassian.com/software/jira)

**Comment by joshcrawmer4** [comment]
Cool. Thanks for the response. 
Josh C 


    On Friday, November 20, 2015 12:09 PM, Kyle Smith <notifications@github.com> wrote:
 

 This repo (git/git-scm.com) is primarily for documenting git. If you'd like to make a feature request for git it would probably be better suited in git/git.But what your describing sounds more like an integration between an item tracker and git. You could look into some project management software like Jira—
