### ISSUE TITLE
Bad links in "git book"

### ISSUE THREAD

**Issue by twify93** [git/git-scm.com#623]
Hello guys, so I saw there are a lot of bad links, maybe old style routing in the Git Book for example:
[Getting a Git Repository](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository#Cloning-an-Existing-Repository) see the link

> Getting Git on a Server

Is there way to get access and fix those links in the Book, because I'm currently learning git from beginning and I can go threw it.

**Comment by smemsh** [comment]
Indeed, all the links in the online book appear to be broken.  Not just links from external sites.  Links within the book itself, to itself.  For example, every link on the page:

http://git-scm.com/book/en/v2/Git-Commands-Branching-and-Merging

(besides next/prev) is broken.

The book needs to be regenerated.

**Comment by pedrorijo91** [comment]
seems solved. probably from #762 as refered in #506  by @peff

**Comment by twify93** [comment]
Yeah well the issues is reported 1 year and something back, so probably it is fixed already.

**Comment by smemsh** [comment]
agreed seems to work for me now, all the links which previously didn't.  probably issue can be closed...
