### ISSUE TITLE
Update Qt's link in the homepage

### ISSUE THREAD

**Issue by thiagomacieira** [git/git-scm.com#627]
As you may know, Gitorious shut down, so qt.gitorious.org no longer works. The official repositories are now at http://code.qt.io/. There's a mirror in GitHub, but it's read-only.

Thanks
Thiago Macieira - QtCore maintainer

**Comment by Ikke** [comment]
Already fixed in 06d91fb96c

**Comment by thiagomacieira** [comment]
Thanks
