### ISSUE TITLE
Page has broken link

### ISSUE THREAD

**Issue by ghost** [git/git-scm.com#628]
This page here:
https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository
has a broken link to git internals here:
https://git-scm.com/book/en/v2/1-git-internals/_git_internals

**Comment by UweKrause** [comment]
To be more precisely, it has 3 broken links,
1 time git internals
2 times Getting Git on a server

**Comment by sxlijin** [comment]
This issue seems to be resolved.
