### ISSUE TITLE
Is a "file" an abstract thing that can have multiple different versions, in different states?

### ISSUE THREAD

**Issue by clymbon** [git/git-scm.com#631]
The text in the second paragraph of Section 2.2. states: "Tracked files are files that were in the last snapshot; they can be unmodified, modified, or staged."   This is confusing and a little misleading, because it implies that a file is in only one of these states: unmodified, modified, or staged.  But if I modify a file, then stage it, then modify it again in my working directory, is that file "modified" or is it "staged" or is it both?  I think the answer is that it is both modified AND staged.  And there's also an unmodified version of it in the repository HEAD.  Or perhaps these are considered different files?  

I don't know how to fix it, but in general, the text doesn't make it clear whether a "file" is an abstract thing that has a specific filename, and that can have multiple different instantiations, or versions (an unmodified version in the repository, a staged version, and a working version).  Or is each of these considered a different "file"?  (This may seem obvious to a reader who already understands git, but for a new user it would help to be very clear about terminology and concepts like this.)

**Comment by stonerfish** [comment]
A new file or a modified file become staged when you use "git add filename".   Then the file is considered staged for commit.  If you modify the file again, then there is the staged version, and also the new modified version as shown by git status .
$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

    new file:   README
    modified:   CONTRIBUTING.md

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   CONTRIBUTING.md
as is explained later in section 2.2
http://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository
Also note if you try "git add filename" on a file that is not modified notice it does not become staged.

**Comment by clymbon** [comment]
Got it, yes.  But my comment was about how best to introduce the reader to the concepts, rather than the content.  When the reader gets to that point in section 2.2, they are likely to be confused.  (At least I was.)  

As it's written, the text seems to imply that a given file is in one of 3 states: "Tracked files ... can be unmodified, modified, or staged."    But that's not the case.  A given tracked file may have many, many versions.  The file itself doesn't have a state (modified, etc.).  Rather, it is a specific version of a file that has a state (unmodified, modified, deleted) with respect to some other version.  The paragraph in question is discussing the state of versions in the working directory with respect to versions in the repository (I think).

The suggestion I was trying to make was for the authors to try to be really clear and precise when the terms "file" and "version" are used.

Maybe the terms need definition up front.  And then perhaps it's OK to slip into shorthand, referring to a file when in fact we really should be referring to a specific version of the file.

Or maybe I have the concepts wrong myself...

**Comment by sxlijin** [comment]
Hey, so this is actually about the Pro Git book - I think you want to reopen this issue over at [that repository](https://github.com/progit/progit2).

**Comment by clymbon** [comment]
I no longer have an active interest.  Feel free to delete or close this issue.
