### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by spookiecookie** [git/git-scm.com#633]
On https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows is img included. Img links to https://git-scm.com/book/en/v2/book/05-distributed-git/images/centralized_workflow.png which doesn't exist. Should link to https://git-scm.com/book/en/v2/book/05-distributed-git/images/centralized.png.

**Comment by YueLinHo** [comment]
I think it's fixed by PR #652 and can be closed.

**Comment by maxlazio** [comment]
Indeed, it looks fixed. I'll close this issue but feel free to open a new one if you find more links that need fixing. :)
