### ISSUE TITLE
single user causes conflicts without branching&merging

### ISSUE THREAD

**Issue by adrian-herscu** [git/git-scm.com#635]
I am working with a remote git repository, I am the only one who commits into that repository, and only into the master -- that is, no branching, no merging.

Most of the time it works fine.

But sometimes, when I am trying to commit and push, I am getting some weird "fast forward rejected" message. Then, I am trying to synchronize by running git pull, I am getting my local copy into conflicted state :(

Last time it corrupted one of my binary files.

Any idea how that can happen that one user gets into conflicted state?

**Comment by smith-kyle** [comment]
This isn't really the spot for asking git related questions. The issues section of this repo is for reporting issues with [git-scm.com](https://git-scm.com/). I'd suggest looking [here](https://help.github.com/articles/dealing-with-non-fast-forward-errors/) to answer your fast forward question. Also in most cases you should be ignoring binaries in your `.gitignore`

**Comment by pedrorijo91** [comment]
not repo related @peff
