### ISSUE TITLE
Text contains &lt; instead of <

### ISSUE THREAD

**Issue by spookiecookie** [git/git-scm.com#637]
At link https://git-scm.com/book/en/v2/Embedding-Git-in-your-Applications-JGit there's text 
&lt;dependency&gt;
    &lt;groupId&gt;org.eclipse.jgit&lt;/groupId&gt;
    &lt;artifactId&gt;org.eclipse.jgit&lt;/artifactId&gt;
    &lt;version&gt;3.5.0.201409260305-r&lt;/version&gt;
&lt;/dependency&gt;

It should contain no &lt; or &gt;

**Comment by spookiecookie** [comment]
Also the code contains extra spaces, they seem unnecessary 

CredentialsProvider cp = new UsernamePasswordCredentialsProvider("username", "p4ssw0rd");
Collection&lt;Ref&gt; remoteRefs = git.lsRemote()
    .setCredentialsProvider(cp)
    .setRemote("origin")
    .setTags(true)
    .setHeads(false)
    .call();
for (Ref ref : remoteRefs) {
    System.out.println(ref.getName() + " -&gt; " + ref.getObjectId().name());
}

**Comment by spookiecookie** [comment]
The code looks like this in browser
![image](https://cloud.githubusercontent.com/assets/5195215/11896345/5c2e0b90-a58e-11e5-8011-aef065756e08.png)

**Comment by breyed** [comment]
The encoding problem occurs in console snippets as well. For example on [Undoing Things](https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things), there are instances like this:

```
Changes to be committed:
  (use "git reset HEAD &lt;file&gt;..." to unstage)
```

that should be like this:

```
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)
```

**Comment by sxlijin** [comment]
This issue seems to be resolved.
