### ISSUE TITLE
Merge-conflict markers are rendered incorrectly in Pro Git Chapter 3, Section 2.

### ISSUE THREAD

**Issue by deisner** [git/git-scm.com#640]
The merge-conflict markers in [3.2 Git Branching - Basic Branching and Merging](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) are rendered as html entities, e.g. `&lt;` rather than `<`. I pulled the latest version of progit2 and built the html with Asciidoctor. That looked OK.

I was planning to find the bug and issue a pull request, but the latest master builds an older version of http://git-scm.com/, with the first edition of the Pro Git book.

**Comment by radar** [comment]
:+1: this is still an issue. I saw this today.

**Comment by sxlijin** [comment]
This issue seems to be resolved; I don't see any issues of the sort on the linked page.

**Comment by deisner** [comment]
Yes, it's fixed now. Looking at the Wayback Machine, it was fixed sometime after 2016-04-14 and before 2016-05-23.
