### ISSUE TITLE
Instead of < and > &lt; and &gt; are shown

### ISSUE THREAD

**Issue by anshbansal** [git/git-scm.com#645]
On the getting started page the html encoded values are shown instead of < & >

http://git-scm.com/book/en/v2/Getting-Started-Getting-Help

**Comment by anshbansal** [comment]
The same is the case on this page http://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository

**Comment by randomecho** [comment]
Related: #618 #626 #606 #637

**Comment by MysticOdin** [comment]
Same on https://git-scm.com/book/en/v2/Git-Basics-Tagging#Sharing-Tags

even though in the book (link below) it is displayed correctly

https://github.com/progit/progit/blob/master/en/02-git-basics/01-chapter2.markdown

I think markdown conversion of code styled markdown is converting `<` and `>` to their HTML escaped version when it doesn't have to

**Comment by jasonkeene** [comment]
Same on: https://git-scm.com/book/en/v2/Git-Internals-Git-Objects

Double escaping < and >

**Comment by Peter-Liang** [comment]
Since the issue still exist, my workaround is to format every page with my script.
`
$('pre').each((i,e)=>{ 
    e.innerText = e.innerText.replace(/&lt;/g,'<').replace(/&gt;/g,'>');
});
`

**Comment by peff** [comment]
There are a ton of duplicates here, which I'm closing to keep the discussion in one place. I'm pointing them all at #753, so I'm going to do the same here. There's some nice discussion, though, so I've put a pointer back from that issue to here.
