### ISSUE TITLE
Figure 3-17, is master pointing at wrong commit?

### ISSUE THREAD

**Issue by weegreenblobbie** [git/git-scm.com#649]
In Figure 3-17, shouldn't master be pointing at C6?

**Comment by randomecho** [comment]
Correct, and it seems like the issue was [fixed in the source](https://github.com/progit/progit2/pull/192) but it's not currently reflected over here.

Related: #515 #471 #546

**Comment by sxlijin** [comment]
Is this still an issue, or can this be closed?

**Comment by sxlijin** [comment]
Closed by #952 @peff
