### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by bartim** [git/git-scm.com#657]
Hi,

Chapter **1.1 Getting Started - About Version Control** tries to display a file under https://git-scm.com/book/en/v2/book/01-introduction/images/centralized.png, which is missing. ![screen shot 2016-01-18 at 14 28 17](https://cloud.githubusercontent.com/assets/9659253/12392488/bc0ed124-bdef-11e5-9d3b-422c82b4cb4e.png)

**Comment by IgorKoltunov** [comment]
Noticed this as well. Thanks for filing.

**Comment by pedrorijo91** [comment]
seems to be solved already. visible at https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control

close @peff ?

**Comment by maxlazio** [comment]
Page looks good now, closing :)
