### ISSUE TITLE
"Search entire site ..." for "<any word>" returns "Sorry, no search matches"

### ISSUE THREAD

**Issue by JohnWulff** [git/git-scm.com#659]
When attempting a Search in the "Search entire site ..." window of <http://git-scm.com/book/en/v2> the search for \<any word\>, it returns "Sorry, no search matches". eg. for "branch" the full text is: 
Search results for branch
Sorry, no search matches

This is obviously not correct.

I noticed this today, 20th January 2016. I believe it was OK up to a few days ago. I also noticed, that previously as you entered words into the search field a list of headings containing that word would be listed below the search box. That does not happen now. The only text now shown is "Show all results" for any word entered.

The Pro Git book is great, but with the Search facility broken it is not nearly as useful.
PS: This happens both on Firefox in OpenSuse 13.1 Linux and Safari on an iPad.

**Comment by deisner** [comment]
Same here. Another example: there are no results when you search for "git".

**Comment by JohnWulff** [comment]
It is now 2 weeks since the Search facility in the Online Pro Git book is broken. I am glad someone else has noticed. Since I am new to Git I make do with the Reference page to find things, but the Search facility was so much easier.

**Comment by enderandpeter** [comment]
This is ridonkulous. Searching this site was one of its best features. Alright... I'll try to deploy this site and see what I can find out...

**Comment by JohnWulff** [comment]
At last - search was indeed one of its best features. It has been such a pain going backwards and forwards via Reference on the front page. I am reasonably comfortable with GIT now, but it was hard having this happen just as I was starting with GIT.
If there is anything I can help with - testing - let me know.

**Comment by dragon788** [comment]
Search is still busted, and its killing me that I have to use Google to search the site I'm already on instead of the site search. Its almost as bad as having to search Microsoft's site with Google because their Bing site search engine is so horrible.

**Comment by dragon788** [comment]
Discovered this by using the Chrome Developer Tools, this may not be the fatal error, but it certainly doesn't seem good. I'm wondering if the site simply needs a rebuild since the one developer had pulled a bunch of node.js stuff from their repositories and broke half the internet, maybe they need to update their package list or framework?

```
session.min-a819047….js:formatted:389Uncaught TypeError: Cannot set property 'version' of null
c.package_obj @ session.min-a819047….js:formatted:389
t.google.t.source.e.gloader_ready @ session.min-a819047….js:formatted:321
(anonymous function) @ jsapi?callback=gloader_ready:45
```

**Comment by JohnWulff** [comment]
Good to see you are addressing this problem dragon 788.

I tried to contact  'schacon' directly on Feb 2 with a comment on Fix Builds #569, but I have had no response. I pointed out that the Search failure occurred close to Jan 23 2016 and when the the Banner  "Git is a member project of Software Freedom Conservancy ..." appeared. I cannot be sure of this, but this observation may be of help. That Banner is no longer there and the Search still does not work. 

My guess is that whatever code was introduced with this banner did the damage. There were no changes on GitHub and no _build_ for introducing the Banner reported anywhere, as fas as I can see, but there must have been a _build_.

I presume 'schacon' is the maintainer of the Git Book. Can any of you reach him to do a re-build as suggested by dragon788.

**Comment by JohnWulff** [comment]
Found where the Banner was introduced by 'peff' on Dec 22, 2015
'schacon' merged commit b0566c8 into master on Dec 24, 2015

Looks innocuous enough, but I am no expert on this - just trying to follow the time-line when things went wrong.

**Comment by peff** [comment]
Search should be working again.

I don't know why, but for some reason the `gitscm` index on the ElasticSearch cluster didn't exist, and ElasticSearch just returned 404 for all requests to the site (both for queries, and for trying to index new data). I was able to re-create the index using the `search_clear` rake job, followed by re-populating it with `search_index` and `search_index_book` (all via `heroku run rake`; it uses Bonsai's ElasticSearch cluster on the backend, and you need the correct credentials to get to it).

This is literally the first time I've ever looked at any of the search stuff on the site (or any use of elasticsearch, bonsai, or tire at all), so I mostly just prodded things until it worked. I have no idea what caused the original problem or whether it will happen again.

**Comment by JohnWulff** [comment]
Phew - thanks a million - it is good to have the search back.

**Comment by JohnWulff** [comment]
One last request. Since the search facility has been inoperative for 5 months, many users will not expect it to be working again. It would be very easy for you to change the text in the Search box at the top of the site for a couple of months from

     Search entire site...

to

     Search site (fixed)..

which is exactly the same length. I think that will help many users. The file involved is app/views/shared/_header.html.erb

[diff_header.html.erb.txt](https://github.com/git/git-scm.com/files/243540/diff_header.html.erb.txt)
