### ISSUE TITLE
git branch case insensitive inconsistency

### ISSUE THREAD

**Issue by mharthoorn** [git/git-scm.com#660]
**git checkout** is case insensitive (in windows), but the git branch command does a case sensitive match.
The result is that the active branch is not highlighted in the list from **git branch**.

**Comment by mharthoorn** [comment]
Occurs when checking out an existing branch in a different casing than it was originally written

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
