### ISSUE TITLE
Bug report e-mail address does not work

### ISSUE THREAD

**Issue by Download** [git/git-scm.com#662]
[This page](https://git-scm.com/community) tells us we can report Git issues to git@vger.kernel.org 
It says that 

> Bug reports for git should be sent to this mailing list.
> 
> You do not need to subscribe: you will be Cc'd in replies.

But when I try to send a mail to that address, it bounces:

> Undeliverable: .gitignore file does not work when saved as UTF-8 + BOM
> 
> postmaster@mail.hotmail.com
> Reply|
> To:
> git@vger.kernel.org; Fri 1/22/2016 10:11 PM
> To send this message again, click here.
> This is an automatically generated Delivery Status Notification.
> 
> Delivery to the following recipients failed.
> 
> ```
>    git@vger.kernel.org
> ```

So.... without further ado, here is the issue I am trying to report:

.gitignore file does not work when saved as UTF-8 + BOM #663

**Comment by jnavila** [comment]
This mailing list's address is correct and it works...

**Comment by Download** [comment]
I believe the address is correct, but it seems the spam filters may be set a bit too strict. I only sent two mails to this address (trying to report a bug) and they both bounced.

Are there other ways to report this bug that do not involve me changing my e-mail provider or bugging :) you with it?

**Comment by jnavila** [comment]
If you'd like, I can forward your mail to the list.

**Comment by pedrorijo91** [comment]
not related with this git website, and it seems to have been addressed by @jnavila 

close @peff ?

**Comment by peff** [comment]
Yes, I don't think this is the right forum (for interactive help with mailing list issues, the IRC channel is probably a better venue). There's also some advice on the [vger site](http://vger.kernel.org/majordomo-info.html). The thing that often trips people up is the HTML prohibition (which we also warn about on https://git-scm.com/community). The bounce snippets above don't have enough detail to know whether that's the case.
