### ISSUE TITLE
.gitignore file does not work when saved as UTF-8 + BOM

### ISSUE THREAD

**Issue by Download** [git/git-scm.com#663]
Removing the BOM makes it work.
This is very unfortunate as it prevents us from writing out the BOM for `.gitignore` files, effectively making applications _guess_ the encoding i.s.o. being able to _detect_ it.
The Unicode spec mandates conforming applications to accept the BOM.
If Git does not support Unicode this issue can be closed (but that would be another issue :)

**Comment by jnavila** [comment]
At its core, Git uses UTF-8 to encode pathnames. `.gitignore` makes heavy use of path names and so is expected in UTF-8. There's no further need to add a BOM, as the Unicode guidelines describes.

**Comment by Download** [comment]
Strange to close this. The Unicode spec *requires* all software that supports Unicode to correctly deal with the BOM. I spent time discovering this issue, then reporting it (which wasn't so easy because of the other issue) and then you just close it?

**Comment by jnavila** [comment]
Even if I still don't bite the usefulness of a BOM when UTF-8 exhibits no byte-order problem, you have perfectly the right to raise this issue. Anyway, I have searched for the issue in the mailing-list history and it seems to have been already fixed. 

http://thread.gmane.org/gmane.comp.version-control.git/267288/focus=267399

Have you tried with the latest version?

**Comment by Download** [comment]
Ah I didn't even know how to search that list! Thank you for digging this up, let me look into it.

**Comment by sxlijin** [comment]
@Download is it safe to mark this issue as resolved?

**Comment by Download** [comment]
@sxlijin I just tried it and it seems to be working fine now:

```sh
C:\ws\test>git --version
git version 2.7.4.windows.1

C:\ws\test>git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   .gitignore

no changes added to commit (use "git add" and/or "git commit -a")
```

It is (correctly) showing .gitignore as modified and not any of the files in the ignore list. 
So I guess it's fixed! Yay!
