### ISSUE TITLE
git 2.7 ignores global core.excludesfile

### ISSUE THREAD

**Issue by padhia** [git/git-scm.com#664]
After upgrading to git 2.7 from git 2.6.5, all patterns that were ignored at the global level, started showing up as "Untracked files". If I switch back to git 2.6.5, the problem goes away. I am wondering if this is bug or something changed in git 2.7.

- Thanks

**Comment by jnavila** [comment]
This project is only dedicated to the git-scm.com website. Please send your issues concerning git itself to git@vger.kernel.org.

**Comment by peff** [comment]
Closing as off-topic.
