### ISSUE TITLE
information about internals of index file missing?

### ISSUE THREAD

**Issue by huttarl** [git/git-scm.com#665]
The beginning of chapter 10 (http://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain) promises to explain how the index file works:

> The objects directory stores all the content for your database, the refs directory stores pointers into commit objects in that data (branches), the HEAD file points to the branch you currently have checked out, and the index file is where Git stores your staging area information. You’ll now look at each of these sections in detail to see how Git operates.

But I looked in vain for any information about the index file, or staging area information, in any of the following sections of chapter 10. Am I just blind, or is it missing? (Search returned no results... it seems to be broken.)

**Comment by JohnWulff** [comment]
I also read the whole of Chapter 10 again and found no reference to the structure of the index file, which would be very useful! Also I am surprised that the __Search facility for the Git Book is still broken__. I reported this in #659, 5 weeks ago on Jan 20 and apart from one person who also noticed, nothing is being done about it. If somebody can give me some hints I am prepared to help fix this.

**Comment by pedrorijo91** [comment]
I believe this issue should be addressed on the book repository at https://github.com/progit/progit2

@peff
