### ISSUE TITLE
Crash on Windows 10 - Build 14251

### ISSUE THREAD

**Issue by CorruptComputer** [git/git-scm.com#666]
Upon updating to from build 11102 to 14251 I can no longer use Git due to a crash, this can be easily reproduced by doing any Git command using the Command Prompt or TortoiseGit. I don't know if this helps but here is the crash log:

````
Faulting application name: git.exe, version: 2.7.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14251.1000, time stamp: 0x56a54488
Exception code: 0xc0000005
Fault offset: 0x00000000000a6eeb
Faulting process id: 0x1d58
Faulting application start time: 0x01d15a11664d2a5f
Faulting application path: C:\Users\NGupt\AppData\Local\Programs\Git\mingw64\bin\git.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: c22514e2-0917-4dab-a109-b0a5a8405fa1
Faulting package full name: 
Faulting package-relative application ID: 
````

**Comment by CorruptComputer** [comment]
I think I might have the wrong repository for this, but I cannot seem to find the correct one.

**Comment by CorruptComputer** [comment]
I have reported this to Microsoft as well in case it is just a botched update to Windows.

![image](https://cloud.githubusercontent.com/assets/5573038/12659644/811251fc-c5d5-11e5-9d36-a21c20330098.png)

**Comment by gyretech** [comment]
Same here!

**Comment by jnavila** [comment]
Send your issue to the "git for windows" 

https://git-for-windows.github.io/

specify the version of git, your environment.
