### ISSUE TITLE
Windows downloads need to be signed with SHA-2

### ISSUE THREAD

**Issue by jprichey** [git/git-scm.com#667]
As a result of Microsoft Security Advisory 3123479 (https://technet.microsoft.com/library/security/3123479) and the associated software update.  Windows download signature validation will report "The signature of this program is corrupt or invalid".  This is because the above update will no longer accept certificates and signatures that use SHA-1 hashing algorithm.  This is really a development defect, but appears as a web site defect, so please route as appropriate.

**Comment by randomecho** [comment]
Previously #655 which is also of git-for-windows/git/issues/592

**Comment by dscho** [comment]
Could someone with the power please close this as a duplicate? Thanks.

**Comment by dscho** [comment]
This was never a bug in git-scm.com and therefore this ticket should have been closed long ago, referring to git-for-windows/git#592 instead. Sadly, this never happened.

Maybe at least now somebody with the power can close this ticket? Git 2.7.0(2) is dual-signed and therefore addresses this.

**Comment by dscho** [comment]
@jprichey can you please, please, please close this?

**Comment by pedrorijo91** [comment]
@peff it seems it should be closed
