### ISSUE TITLE
Switch Caps Lock button issue on the input windows

### ISSUE THREAD

**Issue by o0oke** [git/git-scm.com#671]
When I try to press the 'Caps Lock' of the keyboard, and then try to input the uppercase string, 

but after I switched to capital and finished input, I try to press the 'Caps Lock' button again, seems the input still keep capital letter for input, 

Only when I move my cursor to the other input area and press the 'Caps Lock' button again, then when I try to input in the Git console, then the issue will be fixed.

I am using the newest mintty 2.0.3(x86_64-pc-msys) and installed the Google Pinyin for input, Windows 7 64bit system.

**Comment by randomecho** [comment]
This is more an issue that should be directed to [Super User](http://superuser.com/questions/tagged/git) or another help site, as opposed to this current repo which deals with the website for the Git project

**Comment by o0oke** [comment]
thanks for guiding.

**Comment by pedrorijo91** [comment]
close @peff ?
