### ISSUE TITLE
1.3 Getting Started - Git Basics - Figure 1.6

### ISSUE THREAD

**Issue by Gruximillian** [git/git-scm.com#673]
In the section 1.3 Getting Started - Git Basics, the figure 1.6 has an arrow that
says "Stage Fixes". I'm not sure if that is intentional or it should say "Stage Files".
Although there can be actual fixes to the files to be staged, I think that 
saying "Stage Files" would be more general.

**Comment by sxlijin** [comment]
Hey, so this is actually about the Pro Git book - I think you want to reopen this issue over at [that repository](https://github.com/progit/progit2).

In any case, that seems intentional to me, although admittedly in context "Stage Files" would probably make more sense.

**Comment by Gruximillian** [comment]
Oh, sorry, I haven't realized that the book has it's own repository. Thanks for pointing that out. I'll check if there is an issue related to this case and if not I'll post this there.

**Comment by sxlijin** [comment]
@peff seems safe to close this issue now.
