### ISSUE TITLE
Unable to recover my local repository

### ISSUE THREAD

**Issue by jayaexpress** [git/git-scm.com#674]
```
                        When I was working in my computer with Local git machine being running, All of the sudden my computer shut down. It was abrupt shutdown. Later on when I restarted the computer and tried to run my local development machine, I see a message that says “Not a git repository”.
```

I am not able to checkout any of my local branches. Looks like I might have lost all my local work/branches. Can you please advise if I can recover from the loss.

**Comment by randomecho** [comment]
This is a question more suited for [Super User](http://superuser.com/questions/tagged/git) but would require more details and probably more investigation on what is left or what the state of the (hidden) directories are.

This repo only deals with the website about Git and unfortunately not any issues you may experience with your instance.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
