### ISSUE TITLE
Documentation of plain `git` is not linked on reference landing page

### ISSUE THREAD

**Issue by rybak** [git/git-scm.com#675]
There is no link to https://git-scm.com/docs/git on the reference landing page https://git-scm.com/docs

**Comment by rybak** [comment]
Also, not all topics are linked in the "Topics" popup. For example, https://git-scm.com/docs/gitrevisions is not linked there.

**Comment by rybak** [comment]
Actually, all guides aren't linked in the reference:

```
$ git help -g
The common Git guides are:

   attributes   Defining attributes per path
   everyday     Everyday Git With 20 Commands Or So
   glossary     A Git glossary
   ignore       Specifies intentionally untracked files to ignore
   modules      Defining submodule properties
   revisions    Specifying revisions and ranges for Git
   tutorial     A tutorial introduction to Git (for version 1.5.1 or newer)
   workflows    An overview of recommended workflows with Git
```

**Comment by peff** [comment]
I agree it would be a good thing to link these from https://git-scm.com/docs.

It looks like everything is defined manually `shared/ref/*.html.erb`, and not pulled from the upstream documentation automatically. I guess we'd need a new category for "guides", and then to fill it in with the appropriate guide links.

Want to try your hand at a patch?

**Comment by rybak** [comment]
On Sep 7, 2016 8:57 AM, "Jeff King" <notifications@github.com> wrote:
>
> I agree it would be a good thing to link these from
https://git-scm.com/docs.
>
> It looks like everything is defined manually shared/ref/*.html.erb, and
not pulled from the upstream documentation automatically. I guess we'd need
a new category for "guides", and then to fill it in with the appropriate
guide links.
>
> Want to try your hand at a patch?

I can try to do it on the weekend. I've never actually looked at the source
code.

**Comment by rybak** [comment]
I'm not sure in which column to put "Guides"

Topic dropdown:
![image](https://cloud.githubusercontent.com/assets/624072/18418516/b36023ae-7850-11e6-856a-2061a5a75124.png)

Reference landing page (with "Debugging" moved to the end of the first column):
![image](https://cloud.githubusercontent.com/assets/624072/18418517/c545b994-7850-11e6-8a05-0daf3e2b4823.png)

Plus, new category needs a new icon.

**Comment by pedrorijo91** [comment]
already merged, can be closed @peff
