### ISSUE TITLE
Add support to pkcs12/p12 certificate file format

### ISSUE THREAD

**Issue by kelson42** [git/git-scm.com#679]
Certificates are often delivered from certification authorities in the PKCS12 (*.p12) file format. This format bundles private-key+public-cert in one file and allows to set a pass-phrase. It would be helpful to have git working directly with it because:
- users would not have to extract cert & key from the p12 (ie. using openssl on the command line)
- this would also allow users to protect their private key with a pass-phrase (without having to write a wrapper script doing the p12 extraction at each push).

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
