### ISSUE TITLE
Git Internals link is broken on Git Basics. Getting-a-Git-Repository page

### ISSUE THREAD

**Issue by dmitryTsarevich** [git/git-scm.com#683]
https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository

Link [Git Internals](https://git-scm.com/book/en/v2/1-git-internals/_git_internals) is broken.

**Comment by sxlijin** [comment]
The link on the page no longer seems to be broken, so I think this issue is safe to close.
