### ISSUE TITLE
Download link on website takes 30 minutes to download on good connection.

### ISSUE THREAD

**Issue by pointcache** [git/git-scm.com#684]

**Comment by pointcache** [comment]
can you just upload them to google drive or something

**Comment by randomecho** [comment]
Where in the world are you located? Tested from US and it took about 20 seconds on a 30MB down connection.

**Comment by sxlijin** [comment]
@pointcache if this is still an issue, please comment; otherwise, this issue should be closed.

**Comment by pointcache** [comment]
#NEVER_CLOSE_ISSUES
