### ISSUE TITLE
[REQ] Use color.branch settings in git status -b

### ISSUE THREAD

**Issue by axbender** [git/git-scm.com#692]
Right now the color of the branch types in **git status -b** can not be configured as there are no corresponding settings in **color.status**.

Changing the color settings in **color.branch** to values different from the defaults will have **git status -b** display branches in colors different from the ones configured for display in e.g. **git branch** which results in an inhomogeneous behavior.

I'd consider it helpful to use the colors configured in **color.branch** for display in **git status -b** (or even in any place where branch names are used).

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

**Comment by peff** [comment]
Yep, what @sxlijin said. If anyone is interested in a patch, I think it just needs to teach [`parse_status_slot()`](https://github.com/gitster/git/blob/6ec89f72d55e6d68bc583df597c35ed94a9731fd/builtin/commit.c#L1250-L1267) about the `LOCAL_BRANCH` and `REMOTE_BRANCH` slots.
