### ISSUE TITLE
problems with transfer.fsckobjects=true

### ISSUE THREAD

**Issue by shining** [git/git-scm.com#693]
This is a forward of the following problem: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=743227

```
$ git -c transfer.fsckobjects=true clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware
  Cloning into 'linux-firmware'...
  remote: Counting objects: 2518, done.
  remote: Compressing objects: 100% (1168/1168), done.
  remote: Total 2518 (delta 1313), reused 2518 (delta 1313)
  error: object 087fbb748f50af6eac2248a445d25d666cc92c78:contains zero-padded file modes
  fatal: Error in object
  fatal: index-pack failed
```

But:

```
  $ git clone https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware
[...]
  $ git fsck
  Checking object directories: 100% (256/256), done.
  warning in tree ff42cbe9e62d5d3e383ca621028bd6554597d5f0: contains zero-padded file modes
  warning in tree a1b6cee91e8ec2d6234662bae82e7311ddebcae4: contains zero-padded file modes
[...]
```

It is normal that git clone fails with an error, when git fsck only shows a warning ?

According to Mike Hommey (message 15), the problem is not critical, and not possible to fix without rewriting the project's git history and sha1.
The same problem exists with https://github.com/jasmine/jasmine.git repository.

And I failed to find in the documentation if transfer.fsckobjects could be disabled per repository, can you confirm it's not possible for now ?

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
