### ISSUE TITLE
Include Android and iOS clients in gui section

### ISSUE THREAD

**Issue by palmin** [git/git-scm.com#694]
There are some capable clients for mobile platforms:
- [Pocket Git](http://pocketgit.com) for Android
- [Git2Go](http://git2go.com) for iOS
- [Working Copy](http://WorkingCopyApp.com) for iOS (made by me)

Could these be included in the gui section?
I would be happy to provide a pull request.

**Comment by pedrorijo91** [comment]
I think there's no problem in adding a iOS and Android section to https://git-scm.com/downloads/guis, no @peff ?

**Comment by peff** [comment]
I think that would be fine, as long as their platforms are marked appropriately (and since #951, we'd probably need matching filter buttons, too).

**Comment by Gangezilla** [comment]
Hey guys, looking at implementing this. Trying to find good clients for both iOS and Android and have got these ones for Android: https://www.slant.co/topics/5207/~github-clients-for-android and these ones for iOS: https://www.slant.co/topics/1429/~github-clients-for-ios. Haven't used any of them, but googling 'best iOS/Android git client led me to them. Do they seem like good ones to add? Thanks guys!

**Comment by peff** [comment]
I think I'd rather have people who are users or developers of particular clients add them (or least have tried them out). This isn't exactly a curated list, but I'd like there to at least be a minimum bar of knowing that the tool is supported and works.

So if we even start with 1 or 2 entries, then that may entice people to add their favorite clients (and gives the framework for how to add more).

**Comment by Gangezilla** [comment]
Fair enough. Well, I've got an iPhone, I can try and find 1 or 2 that seem decent, and well supported and add those ones. Does that sound okay?

**Comment by palmin** [comment]
I made this issue originally and sort of regretted it. It felt wrong to add my own app to such a list even if someone else had to approve the pull request. A little like making your own wikipedia bio. 

If you have any questions or need some kind of materials or specific work done for this, I can help, but I would prefer to not help decide which apps go on the list.

**Comment by peff** [comment]
@Gangezilla Yes, that sounds great.

**Comment by peff** [comment]
@palmin Actually, developers requesting their apps be added is how most of the gui list has been built. I don't mind devs promoting their own apps. I just want to see that _somebody_ thinks it's useful enough to promote. Finding a mention on a random list may or may not be a good filter; I've seen a lot of vaporware and abandoned projects, and that's what I'm really trying to protect against.

**Comment by palmin** [comment]
OK. But Working Copy and Git2Go have both been supported for a number of years and my app is sometimes featured in the US and Canadian App Store.

**Comment by pedrorijo91** [comment]
I would say the 3 clients from the original comment could be a nice start. As someone who developed a client, I would assume he tried a few similar apps before/during developing its own :)

**Comment by pedrorijo91** [comment]
started looking at this here: https://github.com/pedrorijo91/git-scm.com/tree/feature/mobileGUI

@palmin If you want to have a look at the new GUI mobile clients, you can see at https://github.com/pedrorijo91/git-scm.com/blob/feature/mobileGUI/resources/guis.yml#L185-L208

> Note: I still need to scrap the images

**Comment by palmin** [comment]
@pedrorijo91 Looks good, but I would really like the Working Copy link to be https://

Should I provide some images?

If so, should the dimensions be 588x332 pixels just like it seems to be in the GUI section?

**Comment by pedrorijo91** [comment]
I know there's a PR where the images are approached (or maybe the PR is about other images? not sure, and did not check yet). I wanted to see it to know if we have any restrictions/recommendations (I should probably document somewhere else after I find out) 

about the https:
I simply clicked on the link you provided and copied, but of course I will change to https :) (maybe you should have a redirect to https on your side also)

**Comment by pedrorijo91** [comment]
@palmin I started by choosing these images: https://github.com/git/git-scm.com/compare/master...pedrorijo91:feature/mobileGUI

let me know if you have any other recommendation

**Comment by palmin** [comment]
If you could use the attached image for Working Copy, I would be super happy.
The one you picked is getting a little old.

![working-copy-image](https://user-images.githubusercontent.com/1230554/32663772-681ae39c-c62f-11e7-9114-bf7b1dbad450.png)

**Comment by pedrorijo91** [comment]
sure ;) will update the image when I get back to this (probably tonight or this weekend)
