### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ShashankaNataraj** [git/git-scm.com#695]
This page:
https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

has a broken link for the "Getting Started" link in the second Paragraph.

May I make a PR for this?

**Comment by YueLinHo** [comment]
I'd like to see how to fix it. :smile:

**Comment by ftwbzhao** [comment]
#630

**Comment by maxlazio** [comment]
Fixed with #630, thanks for reporting :)
