### ISSUE TITLE
&lt; and &gt; ?

### ISSUE THREAD

**Issue by ShashankaNataraj** [git/git-scm.com#696]
https://git-scm.com/book/en/v2/Getting-Started-Getting-Help

has 

> $ git help &lt ;verb&gt ;
$ git &lt ;verb&gt ; --help
$ man git-&lt ;verb&gt ;

**Comment by unratito** [comment]
This seems to happen all along the online book:

https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History

But it's correct in the PDF version, so I guess the problem is not on the source, but on the HTML generation.

**Comment by peff** [comment]
Closing as a duplicate of #753 (even though this is older, there are more details and links there). Thanks.
