### ISSUE TITLE
git svn --ignore-paths regex

### ISSUE THREAD

**Issue by Camts** [git/git-scm.com#698]
Example taken from help does not work: --ignore-paths="^doc"

> git --version
git version 2.7.0.windows.1

**Comment by Camts** [comment]
Sorry, it works, but documentation is not clear:
The path tested by regex is not the local path of added file, but on the path from the SVN URL, example:

git svn init svn://svn.foo.com/bar/ --trunk=trunk/project

regex is not tested on doc/bar.txt (local added file), but on what is after svn://svn.foo.com/bar/, so on  trunk/project/doc/bar.txt

So, to exclude doc directory, ignore path is "^trunk/project/doc"

**Comment by jan-pesta** [comment]
Thats not nice as you wold like to have same ignore also for branches and tags, and those name are groving, so you would need to extend ignore path for every branch/tag also

**Comment by pedrorijo91** [comment]
hey @jan-pesta. Unfortunately this repository is just for the git-scm website. If you want to propose the problem to the git developers just check the mailing list contact at https://git-scm.com/community.

Don't forget to properly state the problem, and feel free to provide some suggestions
