### ISSUE TITLE
The docs for mention a GIT URLS section which doesn't exist.

### ISSUE THREAD

**Issue by shawninder** [git/git-scm.com#699]
In the docs for [git-fetch](https://git-scm.com/docs/git-fetch), in the `OPTIONS` section, under `<repository>`, you'll notice "(see the section GIT URLS below)". Such a section doesn't exist (and the link doesn't work).

To jump immediately to the problem, see [my annotation](http://genius.it/8760997/git-scm.com/docs/git-fetch)

Perhaps this section has been moved? Perhaps removed?

**Comment by jnavila** [comment]
This is a bug with the automatic edition of the man pages of git. The man pages are complete but for some reason, the compilation script for the website does not handle correctly the nested Asciidoc includes.

In the mean time, you can just type "man git fetch" to get the full and correct man page.

**Comment by jnavila** [comment]
The bug is located here:

https://github.com/git/git-scm.com/blob/master/lib/tasks/local_index.rake#L64

Only one level of includes... But git-fetch and git-pull both require two levels. Feel free to submit a PR if you feel comfortable with ruby.
