### ISSUE TITLE
How about perma links for each section?

### ISSUE THREAD

**Issue by ShashankaNataraj** [git/git-scm.com#703]
I find myself wanting to quote a section to one of my colleagues. I then have to say scroll down... no scroll down further.

**Comment by pedrorijo91** [comment]
I assume this still happens @ShashankaNataraj ? As far as I've noticed, there are some links, but a lot more anchors could exist. Also, the sections and sub-sections I've seen already contain a html id, so you can manually add the anchor to the url as a temporary solution

**Comment by peff** [comment]
If you mean man-page sections, that was added in #888. Check out also #849 which adds anchors to the option lists, too.
