### ISSUE TITLE
No image for Figure 1-2 in online book Pro Git

### ISSUE THREAD

**Issue by ankerok-dingdong** [git/git-scm.com#704]
Hello.

On the page https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control should appear image for figure 1-2 but it's missing. The link to image is https://git-scm.com/book/en/v2/book/01-introduction/images/centralized.png. The image presents in downloadable version of the book.

Thanks.

![progitmissingimage](https://cloud.githubusercontent.com/assets/17823068/13737919/a71ca4f2-e9c9-11e5-93e8-21a9974c7444.jpg)

**Comment by YueLinHo** [comment]
It shows now.

**Comment by pedrorijo91** [comment]
duplicated from #661 

already solved @peff

**Comment by jnavila** [comment]
@pedrorijo91 @maxlazio also has admin rights on the repo.

**Comment by pedrorijo91** [comment]
I understood that yesterday as I saw maxlazio closing some issues. Didn't want to spam all admins for each issue. Is there any preference on the mentioned user? should I mention all?

**Comment by jnavila** [comment]
I don't know! But it seems right now that peff is already on the spot. Just ask him if it bothers him to receive the notifications now.

**Comment by peff** [comment]
The repository is on my watch-list, so I get the notifications either way.
