### ISSUE TITLE
Very confusing explanations

### ISSUE THREAD

**Issue by ShashankaNataraj** [git/git-scm.com#708]
> Snapshots, Not Differences

![Image Alt](https://git-scm.com/book/en/v2/book/01-introduction/images/deltas.png)

How are these snapshots? The diagram clearly shows delta1, delta2, etc. The reader instantly associates deltas with differences, not with snapshots.

It is becoming increasingly difficult to give this link to anyone and expect them to learn how git works!

**Comment by jnavila** [comment]
Have you even tried to read what's written? That figure depicts the way most previous VCS system think the history of a project, that is as differences. If you want to see the way Git thinks the history, you just have to read a little further.
