### ISSUE TITLE
git svn authorization failed on 2.7.3 for git svn branch

### ISSUE THREAD

**Issue by albfan** [git/git-scm.com#709]
After upgrade, authorization fail arises on git svn branch. git svn fetch or git svn commit works correctly

<pre>
albfan@ubuntu:~/projects/project1$ git svn branch newbranch -m "develop #453" 
Copying svn://url:port/somepath/trunk at r31190 to svn://url:port/somepath/branches/newbranch...
falló la autorización: No se pudo obtener el usuario o la clave at /usr/lib/git-core/git-svn line 1196
</pre>

But the same with svn works

<pre>
albfan@ubuntu:~/projects/project1$ svn cp svn://url:port/somepath/trunk svn://url:port/somepath/branches/newbranch -m "develop #453"
</pre>

This are the versions for git and svn (this machine is little old)
<pre>
albfan@ubuntu:~/projects/project1$ svn --version
svn, versión 1.6.17 (r1128011)
</pre>

<pre>
albfan@ubuntu:~/projects/project1$ git --version
git version 2.7.3
</pre>

**Comment by jnavila** [comment]
Please post your issue at the git development mailing list git@vger.kernel.org and describe more precisely your setup.

This project is dedicated to the git-scm.com website.
