### ISSUE TITLE
Binary (text-file) file fails to auto-merge

### ISSUE THREAD

**Issue by desandy** [git/git-scm.com#710]
We are attempting to merge an xml file with an extension of .plan, using UCS-2 LE BOM encoding, approximate size 802kb into our master branch.

We have a .gitattributes file located in the repository root directory, contents:
# Custom for XMPie
*.plan     diff

When we work on this file, we follow this procedure:
1) Create a new branch off the master. (e.g. change_1971)
2) Pull down from master - just to be safe.
3) Ensure we have switch our working directory to new branch.
4) Complete our changes in our working directory.
5) Commit our changes.
6) Push our changes to the remote branch with the same name (e.g. change_1971).
7) Create a pull request.

This is where the issue begins.  Often, not always, when we create the pull request, Git states that it cannot auto-merge the .plan file because it is binary.  Obviously, when this happens, Git doesn't know it's a text file and therefore cannot determine changes, etc.  It makes perfect sense except for our .gitattributes file and the fact that it is an intermittent problem.  Sometimes it does work.

We have a fail-safe, so far anyway, work-around.  We create a new branch off the master, re-do our changes to the .plan file, commit, push and the pull request will auto-merge.  

The work we perform on this file is only done by a proprietary software package called XMPie.  The encoding MUST stay as UCS-2, and it is very error prone to attempt to edit the file with a text editor.
Only the above package is used to make changes to this .plan file.

Due to the file's encoding Git

What would cause this issue?  Are we doing something wrong?
What can we try?

**Comment by desandy** [comment]
Additional information:

We use Sourcetree for Git management.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by desandy** [comment]
Thank you.  I have sent it to the mailing list.
