### ISSUE TITLE
Git version on download page for OSX is not updated

### ISSUE THREAD

**Issue by MiguelDebruyne** [git/git-scm.com#715]
https://git-scm.com/download/mac
Still downloads 2.6.4, not 2.7.4 which  is the current release. Even though it states that it will download the 2.7.4 version

When I click on 'maintained build' it redirects me to:
https://sourceforge.net/projects/git-osx-installer/
Where the latest version is 2.7.1

It also states the following
_The current source code release is version 2.7.4. If you want the newer version, you can build it from the source code._

Which links me to: https://github.com/git/git/ that in turn links me to https://github.com/git/git/blob/master/INSTALL where I'm left clueless what to do. I don't get the installation instructions

**Comment by majnu-campact** [comment]
+1 
2.7.4 contains an important security fix. Due to that I can't do my own build, since our admin has disallowed us to use git with remote repos until we install 2.7.4. So I'm desparately waiting for the download! ;)

**Comment by peff** [comment]
I'm going to close this as I think it's a subset of #268 (and the root of the issue is that the OS X packages are a totally independent project, which often lag the source releases by quite a bit).
