### ISSUE TITLE
git clone always fail

### ISSUE THREAD

**Issue by YuleiXiao** [git/git-scm.com#717]
only clone fail,but git pull/push is ok

error message:
git clone https://github.com/chzyer/readline 
Cloning into '/mnt/hdd1/work/src/github.com/chzyer/readline'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
package github.com/chzyer/readline: exit status 128
exit status 1

**Comment by d0f** [comment]
Clone failed
RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received. The remote end hung up unexpectedly early EOF index-pack failed

**Comment by hiyali** [comment]
same problem on ubuntu 16 / git 2.7.4

**Comment by qeesung** [comment]
+1 on ubuntu14 64bit / git 2.9.2

**Comment by peff** [comment]
This is the issue tracker for the git-scm.com website, not git itself. You're more likely to get answers by asking on the mailing list.

That being said, I don't think this is a Git issue at all, but rather a problem with GnuTLS. See https://bugs.launchpad.net/ubuntu/+source/gnutls26/+bug/1111882 for example.

**Comment by mwshubham** [comment]
Check https://stackoverflow.com/a/6849424/2437655 for `git` and `curl` related problems


try 
`git config --global http.postBuffer 1048576000`

**Comment by qeesung** [comment]
I solved the problem by recompile the GIT with openssl.

More detail can be find [here](https://gist.github.com/pescobar/6ae5634f92d75d23c36a)

**Comment by dotaheor** [comment]
`git config --global http.postBuffer 1048576000` doesn't work.

**Comment by qeesung** [comment]
@dotaheor Are you cloned through a proxy? and what is your OS ?

**Comment by dotaheor** [comment]
debian sid 64.
I rebuilt git using this script: https://gist.github.com/pescobar/6ae5634f92d75d23c36a
now it is ok.

I forget if a proxy is on for former fails.

**Comment by Sody666** [comment]
failed on latest macos.
compile git client again is unacceptable.

**Comment by sxlijin** [comment]
I'm not sure why people keep commenting on this issue, but because people are I'm going to lock this.

People, please remember that this repository is for the Git *website*, not Git itself (please post to the mailing list, git@vger.kernel.org, or check the manual pages or StackOverflow if you're having issues with Git).
