### ISSUE TITLE
The  --name-only option for git log does not play nicely with --graph

### ISSUE THREAD

**Issue by davidedelvento** [git/git-scm.com#719]
`git log --graph  --name-only` works fine, but the name is not properly indented as it is for `git log --graph  --name-status`

I tested this in git v1.9.1

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

**Comment by davidedelvento** [comment]
Ok, thanks for letting me know
