### ISSUE TITLE
Broken link to "git branching" on "working with remotes"

### ISSUE THREAD

**Issue by felisadae** [git/git-scm.com#720]
On this page: https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes

In the section called "Fetching and Pulling from Your Remotes" and also in the section "Adding Remote Repositories", the link named 'Git branching' (which links to https://git-scm.com/book/en/v2/1-git-branching/_git_branching) leads to a 404.

See screenshot: 
![screen shot 2016-03-28 at 11 06 17 am](https://cloud.githubusercontent.com/assets/6626597/14082418/68863822-f4d5-11e5-8577-4ad4c4dd822a.png)

**Comment by unratito** [comment]
The same happens with the link in https://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git. I guess that all these broken links are related to a generation problem.

**Comment by unratito** [comment]
It seems that a lot of people have already noticed it: #633.

**Comment by pedrorijo91** [comment]
seems already fixed @peff

**Comment by peff** [comment]
Yes, all the internal links should all have been fixed by #762.
