### ISSUE TITLE
No support for graphemes in regexps

### ISSUE THREAD

**Issue by jcayzac** [git/git-scm.com#722]
Git doesn't support `\X` (grapheme) in regexps passed to e.g. `git diff word-diff-regex='…'` (tested on `2.7.4` installed on OS X with `brew install git --with-pcre --with-blk-sha1 --with-brewed-openssl --with-brewed-svn --with-persistent-https`).

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by jcayzac** [comment]
Dooh. Thanks for the heads up!
