### ISSUE TITLE
VIM not working on Windows since Git 2.8.0 for Windows

### ISSUE THREAD

**Issue by kwaxi** [git/git-scm.com#725]
The VIM shipped with Git for Windows 2.8.0 doesn't work any more.

When starting it from the Windows Command Prompt or from Git Bash, either directly or via git commit it seems that vim is launched but startup doesn't complete.

**Comment by yoava333** [comment]
I'm having the same problem. 
Windows 10 x64

**Comment by kwaxi** [comment]
I regonized it on Windows 10 Pro x64 and Windows 7 Enterprise x64

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program.  Please see https://git-for-windows.github.io/  for reporting bugs.

**Comment by kwaxi** [comment]
The Problem is tracked there as https://github.com/git-for-windows/git/issues/711
