### ISSUE TITLE
git msys2 problems

### ISSUE THREAD

**Issue by GFdevelop** [git/git-scm.com#727]
I have this error after i have run the configuration command:
`$ git commit -m "test"`

`*** Please tell me who you are.`

`Run`

`git config --global user.email "you@example.com"`
`git config --global user.name "Your Name"`

`to set your account's default identity.`
`Omit --global to set the identity only in this repository.`

`fatal: unable to auto-detect email address (got 'Gabriele@Gabriele-PC.(none)')`

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org
