### ISSUE TITLE
Broken link to Advanced Merging from the Basic Merging page

### ISSUE THREAD

**Issue by pshelton-skype** [git/git-scm.com#728]
The link inside https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging that is supposed to lead to https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging is actually leading to a 404 at https://git-scm.com/book/en/v2/1-git-tools/_advanced_merging.

**Comment by ftwbzhao** [comment]
@pshelton-skype #630

**Comment by pshelton-skype** [comment]
Resolved.
