### ISSUE TITLE
Can `git grep` have `--Author` option?

### ISSUE THREAD

**Issue by redguardtoo** [git/git-scm.com#731]
This is a feature request.

From time to time, I want to re-use MY code. So `git grep` with `--Author` options is really useful.  My current git version is `2.6.3`, looks it doesn't have this option.

**Comment by paulschreiber** [comment]
@redguardtoo This repository is for the git-scm.com website, not git itself.

From https://git-scm.com/community:

> Questions or comments for the Git community can be sent to the mailing list by using the email address git@vger.kernel.org. Bug reports for git should be sent to this mailing list.

**Comment by redguardtoo** [comment]
sorry
