### ISSUE TITLE
wrong html escaping in Git-Branching-Basic-Branching-and-Merging page

### ISSUE THREAD

**Issue by pomarc** [git/git-scm.com#732]
in the two examples on merging conflict the <<<<<<< signs are rendered as &amp;lt;&amp;lt;&amp;lt;&amp;lt;&amp;lt;&amp;lt;&amp;lt;

**Comment by mlefleur** [comment]
This is also happening for the greater than characters, with any `>` being displayed as `&gt;`.

(Here's a link to see exactly where this is occurring.)[https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#Basic-Merge-Conflicts]

n.b. This occurs anywhere these characters are used, not just on this page. For example in the (advanced merging chapter with merge conflicts)[https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging#Merge-Conflicts].

**Comment by jnavila** [comment]
This is fixed now. You can close the issue.
