### ISSUE TITLE
Git Gui Edit Options Error

### ISSUE THREAD

**Issue by jfaquinojr** [git/git-scm.com#734]
Happens everytime. New install.

window name "!paving" already exists in parent

[git-windows-error-log.txt](https://github.com/git/git-scm.com/files/208965/git-windows-error-log.txt)

![image](https://cloud.githubusercontent.com/assets/8035580/14362127/2ac01c7a-fccc-11e5-8f16-8f589c094a9b.png)

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.

**Comment by jfaquinojr** [comment]
ok. closing this
