### ISSUE TITLE
git clone fails with error: Failed to connect to ... port 443: Network is unreachable

### ISSUE THREAD

**Issue by askb** [git/git-scm.com#735]
This issue occurs intermittently with `git clone` on some of the repositories.

```
git clone https://git.openstack.org/openstack-dev/sandbox.git
Cloning into 'sandbox'...
fatal: unable to access 'https://git.openstack.org/openstack-dev/sandbox.git/': Failed to connect to git.openstack.org port 443: Network is unreachable

$ git --version
git version 1.9.1

$ uname -a
Linux xxxxxxx 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

strace logs: `strace -o ~/git.strace -s 5000 -f -e trace=network git clone <repo.git>`
[git.strace.zip](https://github.com/git/git-scm.com/files/209677/git.strace.zip)

workaround was to disabling IPv6:
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
sysctl -w net.ipv6.conf.lo.disable_ipv6=1

cat /proc/sys/net/ipv6/conf/all/disable_ipv6
1
```
If required I can also provide a packet capture, if required.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by askb** [comment]
Sorry for confusion, let me close this now!
