### ISSUE TITLE
HTML encoding issues on "1.7 Getting Started - Getting Help"

### ISSUE THREAD

**Issue by ecnepsnai** [git/git-scm.com#736]
On page [1.7 Getting Started - Getting Help](https://git-scm.com/book/en/v2/Getting-Started-Getting-Help) the command examples have encoded HTML characters instead of their decoded values.

Chrome 49 Windows 10.

![capture](https://cloud.githubusercontent.com/assets/1607109/14408344/8ec71004-fea5-11e5-92b8-178f431a6195.PNG)

**Comment by madhugb** [comment]
It seems v2 of the book has encoding issue. It is repeated in many other pages as well.

**Comment by Sicaine** [comment]
This looks fixed to me. When i open the page, there is no issue anymore. @peff

**Comment by peff** [comment]
Yeah, I didn't dig up this issue, but I think this was reported (and fixed) elsewhere.
