### ISSUE TITLE
Missing second paragraph of each chapter of Pro Git v2

### ISSUE THREAD

**Issue by YueLinHo** [git/git-scm.com#738]
![missing paragraph](https://cloud.githubusercontent.com/assets/5831804/14415280/d19dcf64-ffcf-11e5-90a6-80fdc3b5af04.png)

([progit2 issue #582](https://github.com/progit/progit2/issues/582))

Not only chpater 3, but also chapter 4, 5, 6, 7, 9, 10 have the same problem. All content from second paragraph disappear from web page.

**Comment by peff** [comment]
Fixed by #756.
