### ISSUE TITLE
git clean -d removes things that are in my .gitignore

### ISSUE THREAD

**Issue by jonasmorwing-nuance** [git/git-scm.com#745]
When running "git clean -d" I would expect it to remove all the folders that are listed as untracked when I do "git status" and nothing else. But it actually removes a lot more.
This comes from the fact that I have listed in my .gitignore file:
subdir/*
or explicitly listed all files in the subdir like:
subdir/a
subdir/b
Then nothing from subdir is shown when I do git status, but when I do git clean -d it will still remove subdir and all its contents
If I list in .gitignore
subdir 
alone, then it is not removed, but that is not always the best solution, since perhaps I want to be more explicit with what should be git-ignored. For example if someone adds something new to subdir that they want to track in git, then it would be better if I had explicitly described the earlier items in subdir that were to be ignored.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by jonasmorwing-nuance** [comment]
Thanks. Sorry my mistake.
I tried reporting to that email address, but the email bounced. Do you know any other place where I can report the issue?

**Comment by sxlijin** [comment]
Hey, if this issue is still a problem, and you still can't email the list, it might be because the mailing list only accepts plaintext emails.
