### ISSUE TITLE
Book : choose a language brings us back to the summary

### ISSUE THREAD

**Issue by mathieubrd** [git/git-scm.com#747]
In the book section, when we are in a chapter and we click on a language to translate, we are   brought to the summary. We have to find our section again.

Thank you :+1:

**Comment by jnavila** [comment]
This one is hard... But you are welcome to propose a PR ! :hurtrealbad:

**Comment by To1ne** [comment]
This one also might have become a bit easier now we're on Hugo.

**Comment by dscho** [comment]
> This one also might have become a bit easier now we're on Hugo.

Indeed, it has become a bit easier: https://github.com/git/git-scm.com/pull/1878 😁

**Comment by dscho** [comment]
Fixed via #1878
