### ISSUE TITLE
Git for windows setup can not remember "Enable Credential Manager" settings

### ISSUE THREAD

**Issue by marjune163** [git/git-scm.com#748]
on Git for windows installation, when reinstall or upgrade, you can see settings made by previous installation are reserved, except one option: "Enable Credential Manager". Once I unchecked it, next time I started installation again, it still keep checked.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.
