### ISSUE TITLE
Git difftool ridiculously slow in Cygwin/MinGW

### ISSUE THREAD

**Issue by nowox** [git/git-scm.com#751]
I noticed that `git difftool` is very slow. An delay of about 1..2 seconds appears between each diff invocation. 

To benchmark it I have written a custom `difftool` command: 

```
#!/bin/sh
echo $0 $1 $2
```

And configured Git to use this tool in my `~/.gitconfig`

```
[diff]
    tool = mydiff
[difftool "mydiff"]
    prompt = false
    cmd = "~/mydiff \"$LOCAL\" \"$REMOTE\""
```

I tested it on the Git sources:

```
$ git clone https://github.com/git/git.git
$ cd git
$ git rev-parse HEAD
1bc8feaa7cc752fe3b902ccf83ae9332e40921db
$ git diff head~10 --stat --name-only | wc -l
23
```

When I time a `git difftool` with `259b5e6d33`, the result is ridiculously slow: 

```
$ time git difftool 259b5
mydiff /dev/null Documentation/RelNotes/2.6.3.txt
...
mydiff /tmp/mY2T6l_upload-pack.c upload-pack.c

real    0m10.381s
user    0m1.997s
sys     0m6.667s
```

By trying a simpler script it goes much faster:

```
$ time git diff --name-only --stat 259b5 | xargs -n1 -I{} sh -c 'git show 259b5:{} > {}.tmp && ~/mydiff {} {}.tmp'
mydiff Documentation/RelNotes/2.6.3.txt Documentation/RelNotes/2.6.3.txt.tmp
mydiff upload-pack.c upload-pack.c.tmp

real    0m1.149s
user    0m0.472s
sys     0m0.821s
```

What did I miss?

Here the results I got

```
| Cygwin | Debian | Ubuntu | Method   |
| ------ | ------ | ------ | -------- |
| 10.381 |  2.620 | 0.580  | difftool |
|  1.149 |  0.567 | 0.210  | custom   |
```

For the `Cygwin` results, I measured 2.8s spent in `git-difftool` and 7.5s spent in `git-difftool--helper`. The latter is 98 lines long. I don't understand why it is that slow. 

This issue is the copy of my SO question (http://stackoverflow.com/questions/34028497/git-difftool-ridiculously-slow-in-cygwin-mingw)

**Comment by peff** [comment]
@nowox This repository is just for the git-scm.com site itself; you might get a better response from the Git for Windows issue tracker at https://github.com/git-for-windows/git/issues.
