### ISSUE TITLE
Broken link on ch3.2

### ISSUE THREAD

**Issue by oldanderw** [git/git-scm.com#752]
the link for  Stashing and Cleaning is broken on the web page: https://git-scm.com/book/ch3-2.html. here is the right link: https://git-scm.com/book/en/v2/Git-Tools-Stashing-and-Cleaning

I could not find the web page on the git repo so but I know someone will know where it is

**Comment by jnavila** [comment]
This is fixed. :tada:

**Comment by pedrorijo91** [comment]
if it was fixed, it is broken again. it is pointing to https://git-scm.com/book/ch00/_git_stashing

**Comment by jnavila** [comment]
For starters, the first URL shouldn't resolve or should be a redirect to the actual one.

**Comment by peff** [comment]
I think this is identical to the issue in #786.

**Comment by peff** [comment]
Closing in favor of #786, which has more discussion.
