### ISSUE TITLE
Broken chapter links

### ISSUE THREAD

**Issue by voxspox** [git/git-scm.com#754]
In chapter 3.4, text at the bottom of the page:
We will go into more detail about the various possible workflows for your Git project in `Distributed Git` ...
Link points to `https://git-scm.com/book/en/v2/1-distributed-git/_distributed_git` which is a 404.
Maybe it should point to `https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows`

It seems there are even more chapter links broken, p.ex. in 5.2 link to "Interactive Staging" and "Rewriting History".

**Comment by douglasnaphas** [comment]
The link to the Distributed Git chapter is also broken at https://git-scm.com/book/ch2-3.html.

**Comment by jnavila** [comment]
In fact, most of the links are broken in the book. We are aware of this.

**Comment by ftwbzhao** [comment]
@jnavila #630

**Comment by jnavila** [comment]
Done! :tada:

**Comment by pedrorijo91** [comment]
@maxlazio @peff this can be closed
