### ISSUE TITLE
Git checkout command not working in git HOOKs

### ISSUE THREAD

**Issue by AS044149** [git/git-scm.com#757]
I have small hook which need file to do merge on OBIEE repositories from Different branch . 

On version 2.6.2 I was able to do checkout from my Groovy script but not able to do so in new one .

Can you please look into this .

Thanks
Anand
[pre-commit - wc_4_May_2016_v2.txt](https://github.com/git/git-scm.com/files/249650/pre-commit.-.wc_4_May_2016_v2.txt)

**Comment by peff** [comment]
This repository is just for development and issues regarding the git-scm.com website itself. General git questions should go to one of the forums mentioned in https://git-scm.com/community.
