### ISSUE TITLE
Invalid handling of hash_parent with pathinfo

### ISSUE THREAD

**Issue by richardbraun** [git/git-scm.com#758]
Whith pathinfo enabled, href() produces invalid URLs to parent commitdiffs in the form "http:/somedomain/somerepo.git/commitdiff/abc123somehash456def?hp=fed654theparenthash321cba".

**Comment by richardbraun** [comment]
Assuming the link was indeed meant to show the parent commitdiff, here is a patch that fixes the issue.
[0001-gitweb-fix-link-to-parent-diff-with-pathinfo.patch.zip](https://github.com/git/git-scm.com/files/250565/0001-gitweb-fix-link-to-parent-diff-with-pathinfo.patch.zip)

**Comment by peff** [comment]
@richardbraun This repository is just for development and issues of the git-scm.com website, not git itself. The usual channel for submitting changes to git is to send them to the mailing list; details are at https://git-scm.com/community. You can also make a pull request on the git/git repository and use [SubmitGit](https://submitgit.herokuapp.com/) to send it to the list.

**Comment by richardbraun** [comment]
Woops, my bad. Thanks for the quick reply.
