### ISSUE TITLE
Broken link to figures from Section 5.1

### ISSUE THREAD

**Issue by douglasnaphas** [git/git-scm.com#761]
The links to Figures 5-2 and 5-3 at https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows are broken.

**Comment by paul-bjorkstrand** [comment]
I have found that many links across the book-site are broken. Another example: "The Perils of Rebasing" on https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging#Undoing-Merges

**Comment by jnavila** [comment]
This should be fixed now.

**Comment by maxlazio** [comment]
Since this is resolved, I'll go ahead and close this issue.
