### ISSUE TITLE
table xrefs are broken

### ISSUE THREAD

**Issue by peff** [git/git-scm.com#765]
E.g., in https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History, the link to table 2-2 yields a 500.

In the original ebook html this is just a link to `#log_options`, which I would think would work unmodified. But we munge it in the `genbook2` task. I'm not sure why.

I don't think this is caused by  #762, but it is a related area. /cc @jnavila

**Comment by jnavila** [comment]
#762 did not fix everything. The first level chapters are broken into individual pages for each section; we can not be sure that the local refs won't be broken across pages. So the simplest is to add the table xrefs to the xref resolver, just as it was done for figures.

**Comment by peff** [comment]
Ah, right, I forgot that the single-page HTML from the ebook was split. So the case I found would be fine to leave as-is, but in the general case, we do need to handle these.
