### ISSUE TITLE
The Simplified Chinese PDF ebook is garbled

### ISSUE THREAD

**Issue by ngxiaoyi** [git/git-scm.com#768]
Hi there,

Not sure whether raise up the issue here or not.  Just found that the online ebook - [ProGit2-zh.936](https://progit2.s3.amazonaws.com/zh/2015-12-02-9d8a9/progit-zh.936.pdf) (listed here: https://git-scm.com/book/zh/v2) was garbled.

**Comment by Sicaine** [comment]
FYI: The book release here https://github.com/progit/progit2-zh/releases is not scrambled.

**Comment by peff** [comment]
The PDFs we currently link to are the latest Atlas builds, and we can't fix them at all. Atlas has been down for a year now, and the "new" way is to build straight from the progit2 repository. We're building the HTML for the site, but not the other forms (PDF, etc).

If all of the translations push PDFs to their releases pages, we could probably link to those. I don't know if they all do so consistently, though. /cc @jnavila

**Comment by jnavila** [comment]
I don't know how the rewrite of the site for Jekyll will run for the books.  see  #942 

Meanwhile the links to the ebook versions are stored in db. The script to update the site could also  update the links. I will try to come up with something.

**Comment by pedrorijo91** [comment]
is this problem still happening? How can we check if it's scrambled without understanding chinese? Did anyone see something really easy to spot?

**Comment by jnavila** [comment]
I guess not.The asciidoctor toolchain works.

**Comment by ngxiaoyi** [comment]
Yes. Problem fixed.
