### ISSUE TITLE
[GIT - Linux] git diff working inconsistently (not showing changed in working tree)

### ISSUE THREAD

**Issue by dragGH102** [git/git-scm.com#772]
Git **version: 2.1.4**

Most times **git diff** works like a charm.

However sometimes it doesn't. I tried all the following:
- git diff
- git diff --staged
- git --no-pager diff
- git add . << Nothing is added (and therefore not committed)

none of them show **anything**.
- git status << Shows: working directly clean, no files added (I usually git add. and commit at the same time)

Note: **files were tracked and not .gitignored** for sure.

**A possible cause**: 
Now, I am not sure whether this could be the reason, but I had a connection reset (no push/pull operation was in progress) during which I tried to **git diff** which showed nothing (should it should something even offline?). After that it stop working even adding new files or modifying existing ones.

**HOW I SOLVED**:
- git rm -rf .git/
- git init
- git remote add <url>
- git add . && git commit -m "..." && git push -f   // << Force here (now sure whether it'd be really necessary)

After this (on Bitbucket) I can see that **exactly the files** that I modified result in the **forced commit**.

**Comment by Sicaine** [comment]
This project is for git-scm.com and not git the tool. There is a mailinglist git@vger.kernel.org you can try.

@peff should be closed
