### ISSUE TITLE
Conflict, while applying stash for file that was never created on current branch

### ISSUE THREAD

**Issue by ghuser** [git/git-scm.com#773]
When applying a stash on master, I get a conflict for file2. But file2 was never created on master.

    $> git --version
    git version 2.8.3
    $> ls
    $> git init
    Initialized empty Git repository in /home/me/test1/.git/

    $> touch file1
    $> git add file1
    $> git commit -m "committing file1"
    [master (root-commit) 7c29335] committing file1
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 file1

    $> git checkout -b br1
    Switched to a new branch 'br1'

    $> touch file2
    $> git add file2
    $> git commit -m "committing file2"
    [br1 b565401] committing file2
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 file2

    $> echo "updated.." >> file2
    $> git add file2 
    $> git stash
    Saved working directory and index state WIP on br1: b565401 committing file2
    HEAD is now at b565401 committing file2

    $> git checkout master
    Switched to branch 'master'

    $> git stash pop
    CONFLICT (modify/delete): file2 deleted in Updated upstream and modified in Stashed changes. Version Stashed changes of file2 left in tree.

    $> git status
    On branch master
    Unmerged paths:
      (use "git reset HEAD <file>..." to unstage)
      (use "git add/rm <file>..." as appropriate to mark resolution)

            deleted by us:   file2

    no changes added to commit (use "git add" and/or "git commit -a")

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org
