### ISSUE TITLE
Explanation about .gitignore in online book could be improved

### ISSUE THREAD

**Issue by samuraijane** [git/git-scm.com#774]
On page https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository, at the list that begins with "The rules for the patterns you can put in the .gitignore file"...

Replace "Blank lines or lines starting with # are ignored" with two list items as follows:

   • Blank lines are skipped.
   • Lines starting with # are for comments

Because this section specifically discusses files and folders that the .gitignore file ignores, some novice users might be confused that a blank line or a line that starts with # are "ignored."

**Comment by sxlijin** [comment]
Hey, so this is actually about the Pro Git book - I think you want to open
this issue over at [that repository](https://github.com/progit/progit2).
