### ISSUE TITLE
OS filtering should allow selecting other operating systems than current

### ISSUE THREAD

**Issue by vid** [git/git-scm.com#777]
I'm on Linux but want to find a client for a friend using Windows. I can't filter by "another" OS on https://git-scm.com/download/gui/linux. It would be better to have the filter a select option, with the user's OS selected by default.

**Comment by vid** [comment]
n/m, I got the selector wrong (I thought it was saying the current view was only showing for Linux)

**Comment by sxlijin** [comment]
Do you mean something like [this](https://git-scm.com/downloads/guis)?

**Comment by peff** [comment]
I think the point is that @vid would like to click "filter by Windows" even when running Linux. Which seems like a reasonable thing to want.

**Comment by jvusich** [comment]
I've proposed a solution for this issue in PR https://github.com/git/git-scm.com/pull/951 _(Allow filtering by any platform, not just current OS)_
