### ISSUE TITLE
final git bisect step leads to: "fatal: you want to use way too much memory"

### ISSUE THREAD

**Issue by octoploid** [git/git-scm.com#783]
```

markus@x4 gcc % git --version
git version 2.9.0
...
markus@x4 gcc % git bisect good

Bisecting: 0 revisions left to test after this (roughly 1 step)
[a64301f7ac47b9d8f4f816c5e935cda4c92716b7] 2016-05-26  Jerry DeLisle  <jvdelisle@gcc.gnu.org>
markus@x4 gcc % git bisect good

f216419e5c4c41df70dbe00a6ea1faea46484dc8 is the first bad commit
commit f216419e5c4c41df70dbe00a6ea1faea46484dc8
fatal: you want to use way too much memory
markus@x4 gcc %  

```

**Comment by octoploid** [comment]
Version 2.8.4 is fine. So this is a regression...

**Comment by peff** [comment]
This repository is just for the git-scm.com website, not git itself. You'll probably get better responses by posting to the [mailing list](https://git-scm.com/community).

That being said, if it is a regression, bisecting it (using a working version, naturally :wink:) would be a good start.

That message comes from hitting integer overflow when allocating a `strbuf`. So it's likely to involve reading uninitialized memory, or some signed integer being cast to unsigned and appearing to be very large. It may depend on the exact contents of your repository. Sharing the repo and the sequence of good/bad (e.g., from `git bisect log`) can help others reproduce the issue.

**Comment by octoploid** [comment]
OK. Thanks. Will do.
