### ISSUE TITLE
Incorrect version downloaded for OSX binary

### ISSUE THREAD

**Issue by fwielstra** [git/git-scm.com#785]
On the git-scm frontpage, the new 2.9 release is proudly advertised. Clicking the download link (https://git-scm.com/download/mac for me) however says it's going to download 2.8.1.

This issue may be related to https://github.com/git/git-scm.com/pull/741, I believe that had to do with reading the sourceforge RSS feed url.

edit: Actually no it's not; there is not yet a release of the osx installer for 2.9. Seems there's just a discrepancy in between what version is displayed for Mac on the front page vs what version of the installer is actually available.

**Comment by peff** [comment]
Yes, the version on the frontpage is always the latest version pulled from the maintainer's repository. But as you noticed, the OS X binary releases tend to lag a bit (they are done by a third party).

**Comment by pedrorijo91** [comment]
seems the same problem from #268 ?

**Comment by peff** [comment]
Yes, I'll close this in favor of #268 which has a lot more discussion of the possible solutions.
