### ISSUE TITLE
Broken Link to Basic Merging on 3.6 Git Branching - Rebasing

### ISSUE THREAD

**Issue by spottedmahn** [git/git-scm.com#786]
https://git-scm.com/book/ch3-6.html

If you go back to an earlier example from **Basic Merging**, you can see that you diverged your work and made commits on two different branches.

**Comment by jnavila** [comment]
Hi,

This is not the first time somebody pointed to this kind of issue. The point is that the page you are referering is a ghost page. The real page url is at https://git-scm.com/book/en/v2/Git-Branching-Rebasing where the cross reference links are correctly resolved. 

As I haven't found any way to reach this url from the git-scm site itself, my question is: where did you get this link?

**Comment by spottedmahn** [comment]
Hi Jnavila - I'm not sure at the moment.  Maybe google.  If I come across it again I'll be sure to tell you how I got there.

Regards,
Mike D.

**Comment by pedrorijo91** [comment]
still broken. what's the best way to fix this kind of issues with broken links @peff ? it is manually, or since it is from the book, there's another process?

**Comment by peff** [comment]
Any content or link fixes needs to be done automatically as part of the `remote_genbook2` process in `lib/tasks/book2.rake`.

That said, as @jnavila pointed out, this does work fine from the "right" URL. The problem with the `ch3-6` URL is that it is not in the same path as the rest of the book, so relative links will be broken. I have a feeling that the right solution is for the `ch3-6` URL to issue a redirect, not to quietly serve the subtly-broken page.

**Comment by peff** [comment]
This should be fixed now by @jnavila's #968.
