### ISSUE TITLE
Enable URL linking to elements in git-config page

### ISSUE THREAD

**Issue by jbrowngithubuser** [git/git-scm.com#787]
In https://git-scm.com/docs/git-config can you enable linking to sections/individual elements?

e.g. I could have a url link to "DESCRIPTION" (such as https://git-scm.com/docs/git-config#DESCRIPTION) or "http.proxyAuthMethod".

This would save a lot of time as I could send URLs to other developers which take them to the exact command reference I want them to read.

The source for the docs is at:
https://github.com/git/git/blob/master/Documentation/git-config.txt
https://github.com/git/git/blob/master/Documentation/config.txt

**Comment by jnavila** [comment]
There are already anchors for these section titles:

 https://git-scm.com/docs/git-config#_description

**Comment by jbrowngithubuser** [comment]
Interesting... when I view the page in Firefox I don't get any mouseover links that show these URLs, so I've no way of knowing they're there?

**Comment by jnavila** [comment]
The anchors are not appearing by default, unless some javascript code shows them. Maybe try to view the page in developper mode ?

**Comment by jbrowngithubuser** [comment]
So as the page is currently setup a piece of JavaScript should run, which then shows the anchors on mouseover for headings etc?

To test I browsed to https://git-scm.com/docs/git-config

Firefox 47 OSX:

```
TypeError: a is null
i.package_obj()
 session.min-84e4d7864bab5f4f7b2eafd9c1ebc0ca.js:9
h.gapi_location/</a.gloader_ready()
 session.min-84e4d7864bab5f4f7b2eafd9c1ebc0ca.js:9
<anonymous>
 jsapi:45
 session.min-84e4d7864bab5f4f7b2eafd9c1ebc0ca.js
```

Safari:
```
[Error] TypeError: null is not an object (evaluating 'a.version=d')
	package_obj (session.min-84e4d7864bab5f4f7b2eafd9c1ebc0ca.js:9:7555)
	gloader_ready (session.min-84e4d7864bab5f4f7b2eafd9c1ebc0ca.js:9:5871)
	global code (jsapi:45)
```

I've no idea if this is related or a different bug?

**Comment by jnavila** [comment]
I meant: right now, there is no javascript or css code to show the anchors on the git-scm.com site. So, it is up to you find them. I don't understand where your errors are coming from.

However I don't know enough of CSS or javascript to enable the visibility of anchors.

**Comment by gnbl** [comment]
This is a general documentation improvement, as I would like to link to options as well, but only sections have IDs: https://git-scm.com/docs/git-clone#_options

Whatever converts the txt files in https://github.com/git/git/blob/master/Documentation/ should create anchors for any line ending in "::" (double colons).

**Comment by peff** [comment]
That "whatever" is [asciidoctor](https://github.com/asciidoctor/asciidoctor), so I suspect the best approach to this would be to ask if they would consider implementing list-anchors as a feature.

**Comment by gnbl** [comment]
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#lists
Or change the lists in the documentation to something that already gets anchored.

**Comment by peff** [comment]
I'm not sure what I'm supposed to be looking at in your link. Is there a feature to put anchors in lists already? If so, I'm not seeing it.

Changing the source text might be an option, if you can find something that looks good in both asciidoc (which upstream git uses) and asciidoctor (which git-scm.com uses). Your best there would be to bring it up with the [upstream Git project](https://git-scm.com/community).

**Comment by gnbl** [comment]
Just a reference to the asciidoc syntax for lists, which is what the options use.
I won't be able to contribute.

**Comment by phil-blain** [comment]
I think this was done in #888 and can be closed.

**Comment by peff** [comment]
@phil-blain Yep, thanks!
