### ISSUE TITLE
why git svn fetch try to handle mergeinfo changes when no-follow-parent is enabled?

### ISSUE THREAD

**Issue by proff** [git/git-scm.com#788]
git try to follow parents regardless of this option value.
If branch created without this option then git will follow parent succesfully
If branch created with this option then git try to follow and fail with "cannot find common ancestor" error
If branch does not exists (ignored) then git try to follow and fail with "couldn't find revmap" error. It is very long operation

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org
