### ISSUE TITLE
Error during compilation.

### ISSUE THREAD

**Issue by sirlucjan** [git/git-scm.com#789]
Hello

I got this error during compilaton:

 ```
CC convert.o
convert.c: In function 'convert_to_git_filter_from_file':
convert.c:996:2: error: too few arguments to function 'crlf_to_git'
  crlf_to_git(path, dst->buf, dst->len, dst, ca.crlf_action, checksafe);
  ^~~~~~~~~~~
convert.c:240:12: note: declared here
 static int crlf_to_git(const char *path, const char *src, size_t len,
            ^~~~~~~~~~~
make: *** [Makefile:1950: convert.o] Error 1
make: *** Waiting for unfinished jobs....
```
Version - commit 217f6d0 - branch **pu** (and older). Commit 6c81e93 was latest working version. 

Regards.

**Comment by peff** [comment]
Hi @sirlucjan. This repository is just for issues about the git-scm.com website, not git itself. You'll get more luck posting to the [mailing list](https://git-scm.com/community).

It's also not uncommon for compilation or tests to break on `pu` if there is a bad interaction between topics. The maintainer is generally aware of such breakage and will kick back a comment to the topic authors as appropriate.
