### ISSUE TITLE
atom won't open after command line prompt

### ISSUE THREAD

**Issue by ddrake44** [git/git-scm.com#790]
I am new to this so please bare with me. 

When I attempt to open a file in atom from git bash, instead of the file opening in atom, a windows shell engages and expects a prompt.  I have tried uninstalling/reinstalling both git bash and atom, but the problem still occurs. 
Atom will still open in windows prompt, but not git bash.  Below is a link to the same issue I believe I am having, but I don't understand much of it.  Could I get some help please?

https://github.com/atom/atom/issues/11817

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
