### ISSUE TITLE
git checkout --merge overwrites untracked files

### ISSUE THREAD

**Issue by xlq** [git/git-scm.com#792]
`git checkout --merge` will overwrite untracked files with files from the destination branch.

Expected behaviour: should this be recorded as an add/add conflict? In any case, it shouldn't lose data.

Steps to reproduce:

    $ git init
    $ echo hello > test
    $ git add test && git commit -m initial
    $ git checkout -b topic
    $ echo hello > foo
    $ git add foo && git commit -m topic
    $ git checkout master # now "foo" is on branch "topic" but not in working directory
    $ echo this is lost > foo
    $ git checkout --merge topic # the untracked "foo" containing "this is lost" is now overwritten by "hello" from branch "topic"

**Comment by xlq** [comment]
`git-checkout` writes a tree before switching branches, which of course doesn't include untracked files. Once it has finished the merge it checks out the index, overwriting previously untracked files. It would behave correctly if it added any untracked files that exist in the target branch to the index before writing the tree, but at that point it hasn't even looked at the target branch.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by xlq** [comment]
Oh, my mistake.
