### ISSUE TITLE
Input box git gui interface can not enter Chinese under MAC environment

### ISSUE THREAD

**Issue by cumtkangyi** [git/git-scm.com#795]
git gui界面的输入框无法输入中文

Input box git gui interface can not enter Chinese under MAC environment。

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by pedrorijo91** [comment]
@maxlazio @peff i think this can be closed

**Comment by phonet** [comment]
@yajw 请问最后解决了么？怎么解决的
