### ISSUE TITLE
git clone in windows gives unknow host

### ISSUE THREAD

**Issue by balak80** [git/git-scm.com#796]
Git clone in windows command prompt give error "Couldn't resolve host"

The bad part is out of 30 times 1 or 2 times able to clone properly.. 
[Log.txt](https://github.com/git/git-scm.com/files/348212/Log.txt)

Please help to resolve the issue ..Thanks in advance. 

Regards,
Bala

**Comment by KubaKaszycki** [comment]
Please verify your internet connection. My fix for this problem is to take router with me and go outdoor.

**Comment by balak80** [comment]
Its a bitbucket server instance with in same data center. Telnet are verified and its fine as per network connectivity

**Comment by KubaKaszycki** [comment]
Are you using git built over MinGW or Cygwin or native Windows API?

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org
