### ISSUE TITLE
'git status' gives wrong output when accessed by other users 

### ISSUE THREAD

**Issue by sandeep048** [git/git-scm.com#799]
For instance etckeeper is installed as sudo -> /etc/.git directory is created and owned by root.
Other users cannot access/modify this directory.
Should `git status` not explicitly say that message in the output.
Incorrect message: `fatal: Not a git repository (or any of the parent directories)`.

```
sandeep@Audility:/etc⟫ git status
fatal: Not a git repository (or any of the parent directories): .git
sandeep@Audility:/etc⟫ ls .git
ls: cannot open directory '.git': Permission denied
root@Audility:/etc# git status .
On branch master
nothing to commit, working directory clean
```

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the `etckeeper` program. Please report your issue to the issue tracker of the project.
