### ISSUE TITLE
continuous index.lock issues

### ISSUE THREAD

**Issue by alexyoodoo** [git/git-scm.com#800]
I apologise in advance if this is duplicated - I can't believe no ones put this query up. I did search but to no avail.
We are fairly new to using Git and this issue is making us ask whether it was a good idea to change to it.
We are running on Git 1.9.1
Essentially when doing a git diff git status git checkout or git commit  before doing a git pull orign master, we all find that the index gets corrupted. and the golden rule is do a rm -f  index.lock and carry on.

though I find that deeply unsatisfactory.   Why does it keep on happening?
A.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by alexyoodoo** [comment]
Solved it. Turns out Aptana was the issue not Git.
