### ISSUE TITLE
lists of external links should be more "fair"

### ISSUE THREAD

**Issue by peff** [git/git-scm.com#804]
We have a few pages that are sets of links to external resources, some of which are commercial in nature (e.g., gui clients, or books about git). The Git Project doesn't endorse any of these in particular; the lists try to err on the side of inclusion, and we do not want to promote one production over another.

However, the order is static, which presumably gives preference to some items over others (e.g., those at the top). Should we try to make these more fair?

I can think of a few ideas:
- randomize the list order via javascript; this is mildly annoying if you visit the page again and try to find an item based on your recollection of its position
- order by popularity / number of users. This is nice because it puts the things people are most likely to want near the top. It also rewards incumbent products versus new ones. But more importantly, I'm not sure where we would get accurate user counts for most of them.
- order alphabetically by name; this is impartial, but is game-able. I'm not sure anybody cares enough to game our list, though.

We may also want to have _some_ editorializing in the order. E.g., to put free-software guis in one list, and then non-free ones in another. I think that's a preference the project should be OK with expressing.

I don't have any particular plans to work on this. I just happened to be merging a PR for the gui page
and noticed this. Thoughts (and patches) are welcome.

**Comment by ShashankaNataraj** [comment]
@peff alphabetically ordering the list and splitting the list into commercial and free software I think is a good idea.

Id be willing to make a PR for this if this is OK to go with.

**Comment by peff** [comment]
@ShashankaNataraj Sure. Splitting by license, and then alphabetizing seems like a step in the right direction. You'll have to dig up license information on each project, though, as we don't currently carry it.

**Comment by smith-kyle** [comment]
A random order would be the most fair but popularity would probably be the most useful to users. Here are a couple ideas for measuring popularity:
  -  Randomize the order for some amount of time while tracking the number of clicks on each link. After enough clicks have been collected sort by the click count. The idea being that we'd arrive at an order that closely matched the popularity / number of users.
  - Use the Google Trends interest percentage. Either the average or the current percentage. Any PR that changes the order could include a link to the google trend comparison. Ex: [GitHub Desktop vs Tower](https://trends.google.com/trends/explore?q=github%20desktop,git%20tower)

What do you think, @peff?

**Comment by peff** [comment]
Popularity does suffer from one problem: it rewards incumbents by making them easier to find, and new items don't get the chance to "break in" to the top of the list. I'm sure people have come up with clever systems for this sort of thing that balance popularity versus exposing new things (in fact, this seems like a slight variant on a classic machine learning problem).  But I'm not sure that we want to get all that fancy.

Regarding implementation, I'd prefer something that doesn't require storing anything server-side like a click count (hitting Google trends every few months and storing the results in the repo would be fine).

**Comment by peff** [comment]
@smith-kyle I think #975 turned out nicely. Do you want to try doing the same thing for the book list? It might be harder to get Trend numbers there.

**Comment by smith-kyle** [comment]
Sure! The numbers on Google Trends seem good enough to sort with.

**Comment by sxlijin** [comment]
An idea that I just had: perhaps we could add a Travis build matrix that checks this? (A bare minimum: fetch Google Trends numbers for each entry, and sort according to said numbers, probably some combination of `cut`, `sort`, `curl`.)

Looking at the [code backing these link lists](https://github.com/git/git-scm.com/blob/master/app/views/downloads/guis/index.html.haml), I'm not so sure how a comparison might be done.

**Comment by peff** [comment]
If you can come up with an automated script that generates the list (from whatever sane-looking input you want, or even just the list broken out into its own renderable file), I think that would be sufficient. It would just need somebody to run it every 6-12 months. If we want to tie that into Travis as a reminder that's fine, but the tricky step is the script, I would think.

**Comment by sxlijin** [comment]
Took a look at some of the links and I might take a stab at it at some point. Whenever you load a Trends page you can find this GET request:

```
https://trends.google.com/trends/api/widgetdata/multiline?hl=en-US&tz=300&req=%7B%22time%22:%222016-03-15+2017-03-15%22,%22resolution%22:%22WEEK%22,%22locale%22:%22en-US%22,%22comparisonItem%22:%5B%7B%22geo%22:%7B%7D,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22gitg%22%7D%5D%7D%7D,%7B%22geo%22:%7B%7D,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22git+extensions%22%7D%5D%7D%7D,%7B%22geo%22:%7B%7D,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22git+tower%22%7D%5D%7D%7D,%7B%22geo%22:%7B%7D,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22smartgit%22%7D%5D%7D%7D,%7B%22geo%22:%7B%7D,%22complexKeywordsRestriction%22:%7B%22keyword%22:%5B%7B%22type%22:%22BROAD%22,%22value%22:%22gitx%22%7D%5D%7D%7D%5D,%22requestOptions%22:%7B%22property%22:%22%22,%22backend%22:%22IZG%22,%22category%22:0%7D%7D&token=APP6_UEAAAAAWMsCtZXLnN3AhdCCL1E6tv0IhkAfKfGk&tz=300
```

which is really just a `GET https://trends.google.com/trends/api/widgetdata/multiline` with these params:

```
{  
  "hl":"en-US",
  "tz":300,
  "req":{  
    "time":"2016-03-15 2017-03-15",
    "resolution":"WEEK",
    "locale":"en-US",
    "comparisonItem":[  
      {  
        "geo":{  

        },
        "complexKeywordsRestriction":{  
          "keyword":[  
            {  
              "type":"BROAD",
              "value":"gitg"
            }
          ]
        }
      },
      ...
    ],
    "requestOptions":{  
      "property":"",
      "backend":"IZG",
      "category":0
    }
  },
  "token":"APP6_UEAAAAAWMsCtZXLnN3AhdCCL1E6tv0IhkAfKfGk",
  "tz":300
}
```

that returns this:

```
{  
  "default":{  
    "timelineData":[
    ... ,
    {  
        "time":"1489276800",
        "formattedTime":"Mar 12 - Mar 18 2017",
        "formattedAxisTime":"Mar 12, 2017",
        "value":[  
          10,
          50,
          24,
          63,
          7
        ],
        "formattedValue":[  
          "10",
          "50",
          "24",
          "63",
          "7"
        ],
        "isPartial":true
      }
   ],
    "averages":[  
      9,
      62,
      29,
      81,
      10
    ]
  }
}
```

Those `value` fields in the response (`response["default"]["timelineData"][-1]["value"]`) are really the key: they're the normalized search frequencies of the respective term.

I also came across [this article](http://techslides.com/hacking-the-google-trends-api) while looking.

@smith-kyle how did you get around the search term normalization issue?

**Comment by smith-kyle** [comment]
Do you mean how did I decide what search term to use for each app?

**Comment by sxlijin** [comment]
Specifically how you compared the Trends results for the various search terms, since each individual Trends page normalizes the plot to the biggest datapoint.

**Comment by smith-kyle** [comment]
I see what you mean. Since each page has a max of 5 terms and the trend score is only relative to the other terms in the search, you're wondering how I compared terms across groups of searches. First I sorted them through trial and error then justified the separation of groups by comparing the lowest ranked term in a group to the highest ranked term in the group below it. The searches are at the bottom of this PR description: https://github.com/git/git-scm.com/pull/975#issue-211235704

Not sure how helpful that is since the first step is "sort them". Maybe you could find the most popular term in the entire list then compare all other terms to the most popular term.

**Comment by pedrorijo91** [comment]
should the list of OS under https://git-scm.com/download/linux be sorted? We can use https://distrowatch.com/dwres.php?resource=popularity

**Comment by peff** [comment]
@pedrorijo91 I agree with your follow-up comment that distro order isn't really important for fairness. But I'd say it may also be worth sorting by distro popularity, just so more people find what they're looking for early in the list. So I certainly don't mind if somebody wants to do that sort.

**Comment by pedrorijo91** [comment]
Is there any other list we should try to order?

I saw this one (https://git-scm.com/documentation/external-links), but I think there's no 'section'  long enough to be interest to sort

**Comment by peff** [comment]
Yeah, I think the external-links list is fine. I think we did sort the books, but in theory they could get the same automation that the GUI clients did.

**Comment by pedrorijo91** [comment]
closing this then. Feel free to reopen if you think it's important to sort any other section. Personally, I think GUI have a lot more changes, are more searched, and have many more items than any of the other sections.
