### ISSUE TITLE
git push -n and git pull -n are not symmetric

### ISSUE THREAD

**Issue by ramses0** [git/git-scm.com#805]
recommend deprecating `git push -n` (messaging) and instruct users to use `git push --dry-run` instead.

`git push --dry-run` and `git pull --dry-run` should both be non-destructive operations because currently `git push -n` and `git pull -n` do not honor those expectations.

**Comment by peff** [comment]
Is there some particular spot you think should be updated to reflect this?

If it's in the manpages, those are pulled straight from the upstream git project (and any patches should go there). If it's in the Pro Git book, that is also pulled directly from https://github.com/progit/progit2, and content patches should go there.

**Comment by ramses0** [comment]
Sorry, this was the wrong place to file the issue.  Closing!
