### ISSUE TITLE
git-svn dies all the time

### ISSUE THREAD

**Issue by abique** [git/git-scm.com#807]
Hi,

git-svn is super unreliable and dies all the time on large commit.

We did update boost libraries (from 1.30 to 1.61) and the commit is so large that git-svn just dies : 
error: git-svn died of signal 11

this is what coredumpctl gdb tells me:

`           PID: 19450 (git-svn)
           UID: 1000 (abique)
           GID: 1000 (abique)
        Signal: 11 (SEGV)
     Timestamp: Sat 2016-07-16 17:54:40 CEST (49s ago)
  Command Line: /usr/bin/perl /usr/lib/git-core/git-svn rebase -v
    Executable: /usr/bin/perl
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (abique)
       Boot ID: 5f8da03191eb452cb5e622c69f094bbe
    Machine ID: 3b4ef4a7c78d422d9e40773d0fdcb820
      Hostname: altamira
      Coredump: /var/lib/systemd/coredump/core.git-svn.1000.5f8da03191eb452cb5e622c69f094bbe.19450.1468684480000000000000.lz4
       Message: Process 19450 (git-svn) of user 1000 dumped core.

```
            Stack trace of thread 19450:
            #0  0x00007f638733a5dc _wrap_svn_txdelta_apply (_Delta.so)
            #1  0x00007f638af57da0 Perl_pp_entersub (libperl.so)
            #2  0x00007f638af502c6 Perl_runops_standard (libperl.so)
            #3  0x00007f638af8e33f S_docatch (libperl.so)
            #4  0x00007f638af502c6 Perl_runops_standard (libperl.so)
            #5  0x00007f638aed03cb Perl_call_sv (libperl.so)
            #6  0x00007f6388d528f8 svn_swig_pl_callback_thunk (libsvn_swig_perl-1.so.0)
            #7  0x00007f6388d52fe5 n/a (libsvn_swig_perl-1.so.0)
            #8  0x00007f63859ba1b9 n/a (libsvn_ra_svn-1.so.0)
            #9  0x00007f63859ba4d4 svn_ra_svn_drive_editor2 (libsvn_ra_svn-1.so.0)
            #10 0x00007f63859b43ec n/a (libsvn_ra_svn-1.so.0)
            #11 0x00007f63870e170d svn_ra_reporter2_invoke_finish_report (_Ra.so)
            #12 0x00007f638af57da0 Perl_pp_entersub (libperl.so)
            #13 0x00007f638af502c6 Perl_runops_standard (libperl.so)
            #14 0x00007f638aed82a5 perl_run (libperl.so)
            #15 0x0000000000400e29 main (perl)
            #16 0x00007f638aafd741 __libc_start_main (libc.so.6)
            #17 0x0000000000400e69 _start (perl)
```

GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/perl...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 19450]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/bin/perl /usr/lib/git-core/git-svn rebase -v'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _wrap_svn_txdelta_apply (my_perl=<optimized out>, cv=<optimized out>) at svn_delta.c:3850

3850    svn_delta.c: No such file or directory.
(gdb) 
`

I am using archlinux (up to date). git version 2.9.0. But I believe that the bug has been there for ever.

Good luck.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by abique** [comment]
Oh sorry how could I miss that.

**Comment by Sicaine** [comment]
@peff should be closed. Is there a specific reason to keep such issues open? I have seen a few of them.
