### ISSUE TITLE
git push http[s] uses wrong username

### ISSUE THREAD

**Issue by hohwille** [git/git-scm.com#810]
If you have multiple accounts for the same host (say github.com) there seems to be no way to tell git which user to use when pushing a repository.
Some time ago I was able to workaround this limitation by using different credential helpers and switching in `.gitconfig` but with the recent version of git client this does not work anymore.
So I end up in a situation where I want to push but this fails because git automatically chooses the (wrong) account (username and password) and the server then rejects the push due to missing permissions. I can not find any way to tell git to ask me for a username or to specify another.
I commented out credential helper from `~/.gitconfig`. Also I read on the web about a config `credential.username` but also this seems to have no effect. Also I tried this:
https://git-scm.com/docs/git-credential-cache
```
>git credential-cache exit
git: 'credential-cache' is not a git command. See 'git --help'.
```
Very interesting. New feature added it patch version or documentation bug?

Seems I either have to switch to SSH or I need a separate machine (VM) for each account what seems absurd.
I would be more than pleased to get any better workaround or solution for this. Thanks in advance.
BTW: I am working on windows with `git version 2.9.0.windows.1`. I will update to 2.9.2 but do not expect anything from that...
Also I am quite happy that the times are over where I had to enter login and password for each push but if git automagically chooses the wrong user and there is not even a fallback to enter the login manually if authorization failed this is kinda bad.

**Comment by hohwille** [comment]
In case it helps for enlightenment:
```
git config --list --system
credential.helper=manager
```

Where does that come from on a windows machine?
According to here:
https://www.onwebsecurity.com/windows/git-on-windows-location-of-global-configuration-file
It should be in my programs in `Git\etc\gitconfig` but this `Git\etc\` folder does not contain such file (only fstab, hosts, inputrc, etc.).
Seems that there are several small odds with git and its docs especially when it comes to windows...

**Comment by hohwille** [comment]
Getting closes:
```
>git config  --system --unset credential.helper
error: could not lock config file C:\Program Files\Git\mingw64/etc/gitconfig: Permission denied
error: could not lock config file C:\Program Files\Git\mingw64/etc/gitconfig: Invalid argument
```
This file is present...
I commented this out as admin...
...pused...
and voilla git uses the correct username and ask for password.
Push successful.

I hope you will consider this as some kind of feedback to improve git or at least its documentation.

**Comment by peff** [comment]
This tracker is for reporting issues with the git-scm.com website, not git itself (or its documentation).  Details for reporting problems with git are at https://git-scm.com/community.

That being said, the way to specify a specific username to git is by putting it in the url (e.g., `https://youruser@github.com/...`, or by setting it up in the credential config (e.g., `credential.*.username`). It sounds like in this instance your problem was a non-standard credential helper which did not respect a username set by an earlier config (i.e., setting `credential.username` should have passed to the helper "I want the credential for this username", but the helper may have ignored that). So I'm not sure if there's actually anything in git to fix. Specific suggestions for documentation improvements are welcome.

**Comment by hohwille** [comment]
For the record (no need to respond):
Adding `<username>@` as prefix to the hostname of the URL in `.git/config` (remote origin url) does not help when using `git-credential-winstore` that seems to ignore that config. Seems like I have to file a bug there.

However, when using credential helper `store` using this username tweak, I get asked for the password every time what makes the credential helper kind of useless. So it seems I have to report a bug via the mailing list...

**Comment by hohwille** [comment]
Nice error on push with credential helper `store` (see below). After that `.git-credentials.lock` remains and prevents the helper from any further processing.
```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
A
s
s
e
r
t
i
o
n

f
a
i
l
e
d
!




P
r
o
g
r
a
m
:

C
:
\
P
r
o
g
r
a
m

F
i
l
e
s
\
G
i
t
\
m
i
n
g
w
6
4
\
l
i
b
e
x
e
c
\
g
i
t
-
c
o
r
e
\
g
i
t
-
c
r
e
d
e
n
t
i
a
l
-
s
t
o
r
e
.
e
x
e


F
i
l
e
:

e
x
e
c
_
c
m
d
.
c
,

L
i
n
e

2
3




E
x
p
r
e
s
s
i
o
n
:

a
r
g
v
0
_
p
a
t
h
```

**Comment by peff** [comment]
The `credential-store` bug is [known and fixed](http://public-inbox.org/git/7210bce6-093b-9fdf-9a9b-94059ad0d4e3%40ucar.edu/T/#u), but not yet in any released version of git.

**Comment by hohwille** [comment]
Thanks for the feedback. There is also a fork of winstore that solves the login problem:
http://stackoverflow.com/questions/24290289/git-credential-winstore-exe-for-two-github-logins
