### ISSUE TITLE
git force push should check for remote changes before pushing

### ISSUE THREAD

**Issue by teeohhem** [git/git-scm.com#813]
In effort to avoid lost commits, the force push command should check for remote changes in the branch and prompt to continue. Perhaps a -f (force) flag can be added to forgo this check.

**Comment by To1ne** [comment]
@teeohhem Option `--force-with-lease` exists for this purpose.

Although I agree, the `-f` option is dangerous. So I have some suggestions to fix this:
- bind `-f` to `--force-with-lease` and `-F` to `--force`
- add an config option (e.g. `push.defaultForceStrategy`) which can be set to `withLease` or `hard` or something like that.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
