### ISSUE TITLE
Website search is broken again

### ISSUE THREAD

**Issue by deisner** [git/git-scm.com#822]
Searching for anything returns 'Sorry, no search matches'

E.g. https://www.git-scm.com/search/results?search=git produces:

![image](https://cloud.githubusercontent.com/assets/742277/17489483/355f308e-5d6c-11e6-8461-e1aaa311c5f4.png)

**Comment by peff** [comment]
Hrm. This was broken in the same way as it was [a few months ago](https://github.com/git/git-scm.com/issues/659#issuecomment-215936132) (a broken ElasticSearch database). I fixed it again by manually running the clear/index jobs. But I still have no idea what puts it into the broken state.
