### ISSUE TITLE
Typo on hooks documentation page (french website)

### ISSUE THREAD

**Issue by sidewinder94** [git/git-scm.com#823]
In the "Autres crochets côté client" paragraph

The exact URL of the page is : https://git-scm.com/book/fr/v1/Personnalisation-de-Git-Crochets-Git

The `post-checkout` hook is written `post-chechout`

As far as I can tell, this error is not present on the English version.

**Comment by jnavila** [comment]
It's already fixed in https://github.com/progit/progit2-fr/blob/master/book/08-customizing-git/sections/hooks.asc but not updated on the website.

**Comment by sidewinder94** [comment]
Ok, nice, closing then :)
