### ISSUE TITLE
git svn --version requires working copy

### ISSUE THREAD

**Issue by nijel** [git/git-scm.com#824]
Running ```git svn --version``` requires working copy, what is quite ugly to require working copy just to figure out if git svn is installed and what version.

```
$ git svn --version
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Unable to find .git directory
 at /usr/lib/git-core/git-svn line 347.
```

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by nijel** [comment]
Sorry, didn't read the website properly, just followed the first "issue tracker" link in the "Bug Reporting" section...
