### ISSUE TITLE
Fatal: UriFormatException encountered when URL includes a port number

### ISSUE THREAD

**Issue by donpellegrino** [git/git-scm.com#828]
"Fatal: UriFormatException encountered." is reported when cloning from a URL having a port specified.

Issue is documented on Stack Exchange: 
http://superuser.com/questions/1114193/when-cloning-on-with-git-bash-on-windows-getting-fatal-uriformatexception-enco

**Comment by nategreco** [comment]
Seems like it's still an open point:
http://superuser.com/questions/1124302/github-push-clone-and-fetch-functions-in-produce-taskcanceledexception-and

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

Since this seems to specifically be relevant to G4W you should look at git-for-windows/git.

**Comment by donpellegrino** [comment]
Sorry, I posted this issue to the wrong Git repository.
