### ISSUE TITLE
Wrong commit number in images for "Undoing Merges" blog post

### ISSUE THREAD

**Issue by slopes321** [git/git-scm.com#830]
Several (all?) of the images on this page have more than one C8 commit shown. For the top image, for instance, it seems that the C8 entry at the top of the image (third commit from the left at the top) should be C9.

The images in question are embedded on this page:
git-scm.com/app/views/blog/posts/2010-03-02-undoing-merges.markdown

**Comment by peff** [comment]
Yeah, I agree that it should be C9 (which I think would involve updating the text to mention C9 as well).

Unfortunately we don't have any source available for those diagrams beyond the PNGs. So we need a volunteer to either hand-edit the PNG, or to generate new diagrams. Or, I suppose, to make a note of the error in the text.

**Comment by radistao** [comment]
https://github.com/git/git-scm.com/pull/893

**Comment by peff** [comment]
Fixed by #893.
