### ISSUE TITLE
RFE: a git rev code for 'beginning of time'

### ISSUE THREAD

**Issue by fche** [git/git-scm.com#831]
It would sometimes be helpful to refer to the beginning of time of the repository - before the first commit - as a revision code.  This way, git diff BEGINNING_OF_TIME..$rev would work, to show the changes of even a first commit $rev.

**Comment by peff** [comment]
You can already do this by comparing against the empty tree. It doesn't have a convenient name, but you can get it by asking `hash-object`:

```
$ git hash-object -t tree /dev/null
4b825dc642cb6eb9a060e54bf8d69288fbee4904
```

If you are doing an actual traversal and asking for diffs against parents, most commands should understand the `--root` option to show any zero-parent commit as a diff against the empty tree (in fact, I think we flipped `log.showRoot` to default to true at some point, so you shouldn't even need `--root`).

**Comment by fche** [comment]
Thanks, Jeff.  Any chance of getting a user-friendly alias of that `git mktree </dev/null` code?

**Comment by peff** [comment]
It's been discussed off and on over the years on the mailing list, but I think the consensus is that it just doesn't come up enough to merit a special case.

**Comment by fche** [comment]
ok then
