### ISSUE TITLE
Cannot set `git config --global` settings in chrooted environment, because of `.gitconfig.lock` permissions

### ISSUE THREAD

**Issue by arnisjuraga** [git/git-scm.com#835]
The scenario is not so common, but I have searched and noticed few users having similar issue.

If user Home directory is, e.g.:
`/home/users/developer`
and this directory is owned by `root:root`, and only sub-directories are user-writable, then calling 

`git config --global user.name "User Name"`

will generate an error:

`error: could not lock config file /home/users/developer/.gitconfig: Permission denied`

Of course, I can create that file with root, set permissions to `developer`, however - the command anyway will not be executed successfully, because `git` needs to create a `~/.gitconfig.lock` file, which is not possible because `~` directory is not writable by the user.

Is it possible to search for sub-folder by default, writable by user, e.g. `~/.git` ?

**Comment by peff** [comment]
This is the issue tracker for the git-scm.com website, not git itself. You might try asking on one of the [mailing lists](https://git-scm.com/community).

But do note that in addition to looking at `$HOME` (which you could set to something else), Git will also look in `$XDG_CONFIG_HOME/git/config`, which defaults to `$HOME/.config/git/config`. More details are in `git help config`.

**Comment by arnisjuraga** [comment]
Long time no see!

The real problem in this case is that `git config` requires permissions to create/delete file:
`~/.gitconfig.lock`

This file is created and deleted by `git` uppon configuration changes.
If there is _Problem_  with permission settings as in  chrooted env sometimes, `shell` could not be allowed to create and delete files directly in `$HOME` directory.

Even though @peff is right - git is looking into `$HOME/.config/git/config` but the `.gitconfig.lock` file still requires permission to be created in and only `$HOME`.

https://stackoverflow.com/a/39256605/1720476
