### ISSUE TITLE
can't not find "Git\mingw64\share\git\git-for-windows.ico"

### ISSUE THREAD

**Issue by ehlxr** [git/git-scm.com#837]
Git for Windows v2.10.0

can't not find "Git\mingw64\share\git\git-for-windows.ico"

**Comment by jsichak** [comment]
Can confirm, this icon file seem to missing.

"Windows cannot find the file %SystemDrive%\Program Files\Git\mingw64\share\git\git-for-windows.ico"

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.
