### ISSUE TITLE
Error in git diff, really!

### ISSUE THREAD

**Issue by psprint** [git/git-scm.com#840]
Change of single line causes diff to think whole block of text changed, see:

https://asciinema.org/a/e1o6qjrq316f4azjii2wm290i

I saved state of the repository to following commit:

https://github.com/psprint/zconvey/commit/24efceb0c9a99bf351c3b535f67c9738e370d60b

You can check it out, cp zconvey.plugin.zsh /tmp; reset --hard HEAD^1; cp /tmp/zconvey.plugin.zsh . – and you will be at the same point as the video shows.

**PS.** The diff is apparently correct, it's just not minimal, but I'll leave the submission, maybe the diff algorithm can be improved

**Comment by ProoM** [comment]
I'd like to add to this. Git diff really behaves weird recently, today I got this conflict:
![gitdiffbug](https://cloud.githubusercontent.com/assets/5425078/18548842/9089c28a-7b53-11e6-8615-fa20082f0beb.png)

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

**Comment by Sicaine** [comment]
@psprint & @ernestasromeika they added and changed the 'diff heuristic'  two or three times last year. compaction-heuristic in 2.9 and indent-heuristic came end of november. But as @jnavila  said, this is the wrong place.

@peff this can probably be closed.
