### ISSUE TITLE
Cannot sign commit.

### ISSUE THREAD

**Issue by gluons** [git/git-scm.com#843]
I'm using **git-scm** on Windows 10 Pro 64-Bits (Version 1607).

I've just uninstalled **git-scm** 2.8.0 and installed current latest 2.10.0.
I can't use `-S` to sign commit after install 2.10.0.

It always show error.
```
error: gpg failed to sign the data
fatal: failed to write commit object
```

I have no problem with 2.8.0. I use it everyday.
My `user.signingkey` still exists as global config.

I try to uninstall old **gpg4win** and install latest but still not work.
Try to generate **new** key and assign to `user.signingkey` but not work.
😕

Now, I've no idea. Please help me.

Thank you.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.

**Comment by gluons** [comment]
@jnavila Sorry. I know but i didn't see issue tracker in [git/git](https://github.com/git/git).
I have no idea where I can ask for help.
Do you know issue for [git/git](https://github.com/git/git)? Please tell me.

**Comment by peff** [comment]
Try one of the options at https://git-scm.com/community.

**Comment by gluons** [comment]
OK. I found older Windows installer at [git-for-windows/git](https://github.com/git-for-windows/git).
I just know that all Windows installers are on this repo. (Normally, I always get it from **git-scm**.)

I back to [2.9.0](https://github.com/git-for-windows/git/releases/tag/v2.9.0.windows.1). It work fine. It's ok now.

Thank you for your informations. 🙂
