### ISSUE TITLE
Announce Git User's Survey 2016 on git-scm.com

### ISSUE THREAD

**Issue by jnareb** [git/git-scm.com#845]
Could you please add an announcement about **[Git User's Survey 2016](https://survs.com/survey/0janvqmmyg)**
somewhere visible on Git Homepage (http://git-scm.com)? Perhaps
something like in the #844 pull request _(it is only a proposal)_.

Announcing the survey on Git Homepage would allow to get to
wide and diverse set of Git users. In past surveys it was the most
used channel.

Thanks in advance.

P.S. The Git User's Survey 2016 ends on 20 October 2016.

**Comment by peff** [comment]
I just opened #846, which builds on your proposal. I'll merge and deploy it soon, since I gather you don't have a rails environment to see what it looks like anyway. But comments welcome, and we can do fixups on top.
