### ISSUE TITLE
keychain access does not work under macOS Sierra

### ISSUE THREAD

**Issue by nvollmar** [git/git-scm.com#850]
It seems there were some changes at the keychain in macOS Sierra, after upgrading git seems not to be able to find the client certificate required to connect to our server.

> fatal: unable to access 'https://xxx:8443/git/proj.git/': SSL: Can't find the certificate "John Doe" and its private key in the Keychain.

**Comment by peff** [comment]
This repository is for the git-scm.com website, not git itself; you may have better luck reporting the problem on the [mailing list](https://git-scm.com/community).

That being said, the message in question is from libcurl, not git itself, so this is just as likely to be a curl problem.
