### ISSUE TITLE
broken link on gitcvs-migration page

### ISSUE THREAD

**Issue by danpritts** [git/git-scm.com#851]
On this page:
https://git-scm.com/docs/gitcvs-migration

I find the following:

First, install version 2.1 or higher of cvsps from http://www.cobite.com/cvsps/ and make sure it is in your path. Then cd to a checked out CVS working directory of the project you are interested in and run git-cvsimport[1]:

the cobite.com link is a 404.  I presume, but am not sure, it's now this:  https://github.com/andreyvit/cvsps

thanks

**Comment by peff** [comment]
Thanks. This documentation actually comes from the upstream git project, but I've sent [a patch](http://public-inbox.org/git/20160922072607.jptzsuew3l7q6wmu@sigill.intra.peff.net/T/#u) there to fix it.

**Comment by danpritts** [comment]
I kind of wondered about that, but the link at the bottom of the page led here.  

This open sourced site is hosted on GitHub.
Patches, suggestions and comments are welcome

thanks!
