### ISSUE TITLE
[Book] Error in path of notepad++

### ISSUE THREAD

**Issue by castor-troy** [git/git-scm.com#854]
I am not sure if this has been addressed already. I searched for it, but couldn't find any.

In the pdf version of the book, for the path of notepad++ on page 41, there is an error for the path. The values should be swapped between x86 and x64.

**Comment by pedrorijo91** [comment]
it seems a book issue and it's still happening. If so, it should be reported on it's repo at https://github.com/progit/progit2/issues

**Comment by peff** [comment]
Yes, the fix needs to go into the progit2 repo.
