### ISSUE TITLE
[GIT-GUI] unicode problem in commit input box

### ISSUE THREAD

**Issue by nhymxu** [git/git-scm.com#857]
I have problem with unicode character when write unicode text.

![Screenshot](https://cloud.githubusercontent.com/assets/535617/18967825/ebb6ff34-86b0-11e6-957a-390a4a1d0bad.jpg)

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
