### ISSUE TITLE
broken post-via-gmane link

### ISSUE THREAD

**Issue by strk** [git/git-scm.com#859]
The "post via gmane" link on https://git-scm.com/community points to an unexistent server 'post.gmane.org':   http://post.gmane.org/post.php?group=gmane.comp.version-control.git

**Comment by peff** [comment]
Related to https://github.com/git/git-scm.com/pull/827. I think nntp-posting still works after the gmane outage and ownership transfer a few months ago, but it looks like web-posting is dead (the "Posting" link in the navbar of `gmane.org` is no longer an actual link).

I think we need to figure out the best set of instructions at #827 and get that merged. It looks like there probably _isn't_ a way to post via the web anymore.

**Comment by pedrorijo91** [comment]
this seems not to be applicable since #827 was merged. closing
