### ISSUE TITLE
Label download version 10.0.1 but give me version 10.0.0

### ISSUE THREAD

**Issue by donhuvy** [git/git-scm.com#862]
Let's see homepage at https://git-scm.com/
It has these content:
```
Latest source Release
2.10.1
Release Notes (2016-10-03)
Downloads for Mac
```
Then press image to download, the website give me version 2.10.0 . Why?
It happen on my macOS Sierra 10.12.0 , also on Windows 10 Pro x64. I live in Hanoi, Vietnam. Is there wrong with mirror server routing?

Even I choose mirror server manually, I still can't download 2.10.1, it gives me Git client version 2.10.0

**Comment by peff** [comment]
No, it's not a mirror problem.

The latest source release is 2.10.1. The binary packaging for macOS is done by a third party, and lags the source releases. When they release a 2.10.1 package, the site will auto-update the link within a few hours.

In the meantime, you can update to 2.10.1 by building from source, or by using Homebrew.

**Comment by donhuvy** [comment]
So confusing for user, the guy requests **v2.0.1**, then the website *git-scm.com* give him **v2.0.0**. 

Then 1 month later he will comeback, he request **v2.0.2** then it's the time return **v2.0.1** still incorrectly. 

Thank Jeff for the information!
