### ISSUE TITLE
Git User's survey 2016 is terrible long, please cut-down its length

### ISSUE THREAD

**Issue by donhuvy** [git/git-scm.com#863]
Dear administrator, I don't see any contact on the homepage of Git, then I report a issue, indeed, there are include defects.

https://survs.com/survey/0janvqmmyg

I hope:
1. Make Git User's survey 2016 has rational length (cut down the length, revise the questions).
1. Have a close button to close message at the top if user don't want see it. (It is user experience, user interface subject)
2. Have an email contact or a contact form to contact with administrator.

**Comment by peff** [comment]
Regarding (1), the survey is designed by @jnareb. I think it is fixed for this year, but he may want to take your feedback into account for next year.

I'm not opposed to having a "close" button for the survey banner at the top of the site, though I'm not sure how it would persist between pages.  Patches welcome.

**Comment by donhuvy** [comment]
Thank Jeff for the information!

**Comment by ShashankaNataraj** [comment]
@peff Could the preference persist in a cookie on the browser perhaps?

**Comment by peff** [comment]
> Could the preference persist in a cookie on the browser perhaps?

Maybe. I think it's important that there be no server-side logic (so it doesn't block any CDN caching or possible static-site-generator plans), but if we can inspect the cookie via client-side javascript and turn off banners, that would be nice.

**Comment by ShashankaNataraj** [comment]
@peff Inspecting the cookie and turning off banners is definitely possible. I have some free time this upcoming weekend. Would be willing to make a PR for this.

**Comment by pedrorijo91** [comment]
@peff I would say this is not git-scm related and could be closed (perhaps forwarding to other channels)?

**Comment by peff** [comment]
Yeah, the survey is done elsewhere (and @jnareb was already pinged above). There is a question for the site about how the banners should work; I moved that into its own issue (#1028).
