### ISSUE TITLE
Git clone always empty when using custom http server

### ISSUE THREAD

**Issue by LuisHsu** [git/git-scm.com#865]
I've made a simple http server to serve git repository

I checked the bare repository, the thing was definitely in the tree.

![_020](https://cloud.githubusercontent.com/assets/7553694/19211205/950803ee-8d69-11e6-89ee-1e4de62b69f2.png)

But it always show this:

![_021](https://cloud.githubusercontent.com/assets/7553694/19211229/fc4dd9f2-8d69-11e6-80e2-3f8a752d1965.png)

I used Wireshark to track the request

![wireshark follow tcp stream tcp stream eq 0 wireshark_pcapng_lo_20161008145750_dxuaiy_022](https://cloud.githubusercontent.com/assets/7553694/19211239/2a0c871c-8d6a-11e6-9fc4-96a46b24254b.png)

It seems like the client didn't make the POST request after getting the info/refs response.
I don't know whether it's a bug, or I just do something wrong.

**Comment by peff** [comment]
This is the issue tracker for the git-scm.com website, not git itself. You'll probably get better answers on the mailing list (https://git-scm.com/community).

It's probably worth comparing the output of `GIT_TRACE_PACKET=1` against your server versus a stock git one. Just looking at your protocol dump, I think there's an extra flush packet before the ref advertisement begins (which doesn't seem to actually be mentioned in the protocol documentation!).
