### ISSUE TITLE
Is it a typo that you used "sports" instead of "supports" in the 7th step of Win32 Git installation wizard ? 

### ISSUE THREAD

**Issue by bj-syan** [git/git-scm.com#867]
Please refer to the attached screenshot for more. :)
I installed the latest x64 version, which is "Git-2.10.1-64-bit.exe". 
![win32_git](https://cloud.githubusercontent.com/assets/16507963/19222238/9f5b3fe2-8e08-11e6-9122-c298864b2f11.PNG)

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.

**Comment by bj-syan** [comment]
@jnavila Thank you ! :)

**Comment by anatolyborodin** [comment]
@bj-syan , I'm not a native English speaker, but it seems like https://en.wiktionary.org/wiki/sport#Verb 

> 3. (transitive) To display; to have as a notable feature.
> Jen's sporting a new pair of shoes;  he was sporting a new wound from the combat‎

**Comment by y7i** [comment]
@anatolyborodin 👍 Thank you for the link. I'm also not a native English speaker. I think it makes sense, and helps a lot.
