### ISSUE TITLE
Add 'git bzr'

### ISSUE THREAD

**Issue by iHateInventNames** [git/git-scm.com#868]
This https://github.com/kfish/git-bzr can be used to work on 'git bzr' feature.

**Comment by sxlijin** [comment]
Is there an actual issue or feature request here? If so, please expand on it.

**Comment by maxlazio** [comment]
Heya, 

thanks for raising an issue! Since this issue tracker is dedicated to git-scm.com website you might have more success with your issue if you raise your question in one of community channels listed at https://git-scm.com/community .
