### ISSUE TITLE
interactive rebase should highlight commit better

### ISSUE THREAD

**Issue by jpritikin** [git/git-scm.com#870]
As of GIT 2.8.1, if you do an interactive rebase and get some conflict in the stack of patches then the commit with the conflict is buried in 4-5 lines of output. It is visually difficult to immediately pick out which commit did not apply cleanly. I suggest highlighting the 1 line commit summary in red or green or some color to help it stand out from all the other output.

I decided to create this issue after I realized that I probably skipped a commit during an interactive rebase instead of resolving the conflict. I knew I had to skip some commit so I assumed that I just need to skip without reading the commit summary carefully. Now it is 7-15 days after I did the erroneous rebase. Sadly, it's probably not worth the archaeology effort to recover the work that I lost.

**Comment by jpritikin** [comment]
On the other hand, GIT makes archaeology really easy. I ended up finding the lost code. Yay.

**Comment by peff** [comment]
Glad you found your code. :)

This issue tracker is just for the git-scm.com website itself; if you want to propose coloring rebase output, try one of the venues mentioned at https://git-scm.com/community.

**Comment by jpritikin** [comment]
Gotcha.
