### ISSUE TITLE
Add --exclude-existing option to ls-remote

### ISSUE THREAD

**Issue by SineSwiper** [git/git-scm.com#871]
The git-show-ref command has a --exclude-existing option to take a list of references and remove them from the final list.  This allows you to run a command like this:

```
git ls-remote --tags origin | git show-ref --tags --exclude-existing
```

This shows all of the tags that exist on the remote that aren't in the local repo.  However, there is no equivalent for git-ls-remote.  It would be nice to be able to do this:

```
git show-ref --tags | git ls-remote --tags origin --exclude-existing
```

That would show all of the tags that exist on the local repo that aren't on the remote.  This is handy for figuring out which tags might need to be pruned from the local repo.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
