### ISSUE TITLE
Save branch name for each commit

### ISSUE THREAD

**Issue by ghost** [git/git-scm.com#877]
To get the original branch name of a commit, I need to create a hook to add the current branch name in the commit message.

When GIT will do this natively?

[prepare-commit-msg.txt](https://github.com/git/git-scm.com/files/550689/prepare-commit-msg.txt)

**Comment by lverns** [comment]
This issue tracker is dedicated to the [git-scm.com](https://git-scm.com) website.

The question you have asked is related to the git program. Please see https://git-scm.com/community for information on how to ask questions regarding git.

**Comment by jnavila** [comment]
As you remarked it, Git already supports this feature through the prepare-commit-message hook.
