### ISSUE TITLE
Users should be able to configure Git to not send them into a vim editor.

### ISSUE THREAD

**Issue by jrood** [git/git-scm.com#879]
When users pull commits, and a new commit needs to be created for a merge, Git's current way of determining a commit message is to send the user into a vim window so that they can write a message. There are 2 reasons why this might not be the ideal way to prompt for a commit message.
1. Many users are used to writing concise one-line commit messages and would not expect to save a commit message in a multi-line file. Some users will wonder why they are in a text editor or which file they are editing. Other may not, in fact, realize at all that a text editor is what they are in.
2. Many users are not familiar with vim, and do not understand how to modify, save, and exit. It is not very considerate to require a user to learn vim in order to finish a commit that they are in the middle of.

The existing behavior should be optional, and there should be two new options:
1. Use a simple inline prompt for a commit message (in the same way git might prompt for a username).
2. Automatically assign names for commits in the form of "Merged x into y".

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The proposition you have raised is related to the git program. Please, send your issue to the git mailing list git@vger.kernel.org

**Comment by jrood** [comment]
My apologies.

**Comment by diogocp** [comment]
You can configure Git to use any editor you want. [RTFM](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#Your-Editor).

**Comment by maxlazio** [comment]
I will close this issue since it is not strictly related to the git-scm.com website. Hopefully you've found some help at one of the channels listed on https://git-scm.com/community :)
