### ISSUE TITLE
git push error

### ISSUE THREAD

**Issue by gsramesh** [git/git-scm.com#884]
Hi Team,
We are using git for more than 2 years, but suddenly I got a below issue

error: RPC failed; curl 56 SSL read: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac, errno 0
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

I'm pushing a 50 MB file 
I'm using HTTPS repo, windows 8 machine

please assist me,

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org
