### ISSUE TITLE
Prevent access to gitweb root path

### ISSUE THREAD

**Issue by 4LeXFiDin** [git/git-scm.com#885]
Hello,

I need to prevent the users to browse the gitweb root path. For example, I have declared in my /etc/gitweb.conf :
$projectroot = "/var/lib/forge/gitroot";

I have several projects in this folder and I don't want that any user can have browse the root folder of all projects (actually, I have a frontend where each projects is declared, it works with bugzilla etc...)

How can I do that please ?

**Comment by 4LeXFiDin** [comment]
For example :
https://mysqserver.mydomain.com/gitweb --> NO
https://mysqserver.mydomain.com/gitweb/?p=my-module-test;a=summary --> YES

**Comment by 4LeXFiDin** [comment]
nobody ?

**Comment by jnavila** [comment]
This issue tracker is dedicated to issues with the git-scm.com website.

For help, please try some community channels: https://git-scm.com/community

**Comment by 4LeXFiDin** [comment]
Ah ok thanks.
