### ISSUE TITLE
git-remote ignoring --add on set-url subcommand

### ISSUE THREAD

**Issue by rhatto** [git/git-scm.com#886]
Test case:

    mkdir test
    cd test
    git init
    git remote add origin git.example.org:test
    git remote set-url --add --push origin test.example.org:test
    git remote -v

Expected output:

    origin	git.example.org:test (fetch)
    origin	git.example.org:test (push)
    origin	test.example.org:test (push)

Actual output:

    origin	git.example.org:test (fetch)
    origin	test.example.org:test (push)

You can get the expected output by doing this additional step:

    git remote set-url --add --push origin git.example.org:test

Tested on Git versions 2.1.4 and 2.10.2.

**Comment by peff** [comment]
This is the issue tracker for the git-scm.com website, not git itself. You'll probably have more luck on the [mailing list](https://git-scm.com/community).

That said, I think the output you are seeing is expected. There is no configured `push` url after adding the remote initially, so there is nothing to add to. It is just that when there is none configured, pushes by default go to the fetch URL. The output of `git remote -v` does not make this clear, though.

**Comment by maxlazio** [comment]
Since there was no update I'll assume that you had more luck at one of the places in https://git-scm.com/community :)
