### ISSUE TITLE
Git Bash crashes when trying to open the Options dialog.

### ISSUE THREAD

**Issue by MAdrianMattocks** [git/git-scm.com#887]
Steps to rep:

1. Launch Git Bash
1. Right click the icon in the top left of the windows.
1. Click "Options..."
Git bash crashes.

OS: Windows 10 Enterprise (fully patched as of 9Nov)
Git version: git version 2.10.2.windows.1
Install type: Git was installed so that it can only be accessed through git bash (my Path is unchanged).

Restarting my machine does not help.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the Windows port of the git program. Please see https://git-for-windows.github.io/ for reporting bugs.

**Comment by MAdrianMattocks** [comment]
Cool.  Thanks.
