### ISSUE TITLE
subtree merging fails

### ISSUE THREAD

**Issue by stavros-liaskos** [git/git-scm.com#896]
Following the instructions here:
https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging
will lead to an error.

In particular, if the subtree is merged and then updated, this command that is supposed to update the local subtree fails with a `fatal: refusing to merge unrelated histories` error.
```
$ git merge --squash -s subtree --no-commit rack_branch
```

A workaround could be using the `--allow-unrelated-histories` option
```
$ git merge --squash --allow-unrelated-histories -s subtree --no-commit rack_branch
```
But this completely destroys my project by pushing the subtree contents into a completely irrelevant directory in my project (no in the subtree).

Any ideas??

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).

**Comment by peff** [comment]
Yeah, `--allow-unrelated-histories` didn't exist when v1 of the book was published. If the issue persists in v2, I'd suggest opening an issue on the progit/progit2 repo. For general discussion of squash strategies, try the community link that @sxlijin pointed to.
