### ISSUE TITLE
Git merge overwrites rather than giving conflicts

### ISSUE THREAD

**Issue by chetanzade** [git/git-scm.com#901]
I'm trying to merge two repositories. But whenever I merge, it should give conflict in sample.txt file rather that overwriting the same. Steps followed are in the image below:

![git issues 1](https://cloud.githubusercontent.com/assets/23714974/20589081/078c4006-b240-11e6-8d28-1104851d000b.JPG)

Git version is : 2.7.4
Is the process right? if yes, the why don't I get conflicts?

any ideas?

**Comment by pranitbauva1997** [comment]
@chetanzade This repo is not for git problems but for anything related to the website git-scm.com. If you have any doubts please post on the mailing list (git@vger.kernel.org) or the google group (git-users@googlegroups.com). So I think this issue can be closed here.
