### ISSUE TITLE
Release Version number different

### ISSUE THREAD

**Issue by vbjay** [git/git-scm.com#902]
Have noticed the past few releases have not updated the download.  

![image](https://cloud.githubusercontent.com/assets/3629489/20759021/a50b2592-b6e9-11e6-8f87-56970e524224.png)

![image](https://cloud.githubusercontent.com/assets/3629489/20759049/be78e5b4-b6e9-11e6-9136-362aaf6e2c0b.png)

Please make sure they stay the same when a release is made.

**Comment by peff** [comment]
The Git for Windows releases generally lag the source releases of the main project anywhere from a few hours to a few days. At the time you opened this issue, 2.11.0 was the latest source release, and 2.10.2 was the latest GfW release. The site polls the GfW release page once an hour to update; now that GfW 2.11 is out, the download link should be updated.
