### ISSUE TITLE
git-svn rebase

### ISSUE THREAD

**Issue by darkdragon-001** [git/git-scm.com#904]
There seems to be something missing in this section since it refers to itself by its name multiple times:

> This accepts all options that git svn fetch and **git rebase** accept. However, --fetch-all only fetches from the current [svn-remote], and not all [svn-remote] definitions.
> 
> Like **git rebase**; this requires that the working tree be clean and have no uncommitted changes.

**Comment by peff** [comment]
I'm not sure what you mean; the `git svn rebase` relies on `git rebase` to do some of its work, and passes the options along to it. The text looks correct to me.

At any rate, that text is in the `git-svn` manpage, which is pulled verbatim from the upstream Git project (this issue tracker is just for the git-scm.com website itself). If you want to discuss it further, you'll probably get more interest from the [mailing list](https://git-scm.com/community).
