### ISSUE TITLE
git-p4 requires python2.exe?

### ISSUE THREAD

**Issue by karimmac** [git/git-scm.com#905]
Hi,
I noticed that git-p4 in the Windows git downloads differs from:
https://github.com/git-for-windows/git/blob/master/git-p4.py

with the first line:
#!/usr/bin/python2

This fails if you use the official Python for Windows distro. A workaround is to use ActiveState's Python or create your own python2.exe alias, but I wondered if there's a good reason for this change?
It's inconvenient and the error messages didn't save me any time in figuring out why git-p4 wasn't working.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
