### ISSUE TITLE
git archive should have an option to also put submodule content into archive

### ISSUE THREAD

**Issue by taladar** [git/git-scm.com#906]
It would be useful if there was an option

```
git archive --recurse-submodules
```

to package the entire content of a git repository commit, without leaving the submodule directories as empty directories in the archive as it does now.

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
