### ISSUE TITLE
Cant clone any repository

### ISSUE THREAD

**Issue by WinKarbik** [git/git-scm.com#908]
remote: Counting objects: 36162, done.
remote: Compressing objects: 100% (854/854), done.
error: RPC failed; curl 56 GnuTLS recv error (-24): Decryption has failed.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Have this trouble only on server, any idea to fix it?

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org
