### ISSUE TITLE
Feature request: read git config from parent directory

### ISSUE THREAD

**Issue by dod38fr** [git/git-scm.com#911]
Hello

I use the same machine for work and open-source contribution. In both cases, I deal with a lot of repositories. Depending on whether I commit for work or open-source activities, I must use a different mail address. I used to setup work address for each work repo, but this is no longer practical.

Since I use different directories for work and open-source, would it be possible for git to read config also from parent directory ? I.e. setup git to read config from `./.git/config` then `../.gitconfig`, `../../gitconfig` until global `~/.gitconfig`.

All the best

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

If you need help with using git, you can ask the [community](https://git-scm.com/community)

**Comment by dod38fr** [comment]
Oops, sorry. I've forwarded my request to git mailing.

Thanks for taking the time to point me in the right direction.

All the best
