### ISSUE TITLE
window git pull fetch not accepting --all options and pulling from wrong branch.

### ISSUE THREAD

**Issue by aroeber-kovarus** [git/git-scm.com#912]
Trying to pull the latest branches from a remote repository, get error:
> fatal: fetch --all does not take a repository argument

`caroeber@myLaptop MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git --version
git version 2.11.0.windows.1

caroeber@myLaptop MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git pull --all -v --ff-only origin
fatal: fetch --all does not take a repository argument

ccaroeber@myLaptop MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git pull --all -v --ff-only origin --all
fatal: fetch --all does not take a repository argument

caroeber@myLaptop MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git pull -v --ff-only origin --all
fatal: fetch --all does not take a repository argument

caroeber@myLaptop MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git pull origin --all
fatal: fetch --all does not take a repository argument

caroeber@myLaptop MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git pull --force origin --all
fatal: fetch --all does not take a repository argument

caroeber@myLaptop MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git pull --force --all origin
fatal: fetch --all does not take a repository argument

caroeber@myLaptop MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git pull --all origin
fatal: fetch --all does not take a repository argument`

**Comment by aroeber-kovarus** [comment]
Pull wit no remote only gets the current branch not all.
`aroeber@BCM4000L62S7L32 MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git pull --all
Fetching origin
remote: Microsoft (R) Visual Studio (R) Team Services
remote: Found 21 objects to send. (6 ms)
Unpacking objects: 100% (21/21), done.
From https://mygitremoterepo.internal/DevOps/My_Code_Repo.git
   6067337..b6325ff  devops     -> origin/devops
Updating 6067337..b6325ff
Fast-forward
 Somefile                               | 17 +++++------------
 lowerdir/applications/appointments.json |  6 ++++++
 lowerdir/initial.rb                        |  8 +-------
 3 files changed, 12 insertions(+), 19 deletions(-)
 create mode 100644 lowerdir/applications/appointments.json`

**Comment by aroeber-kovarus** [comment]
Pulls to specific branches not staying on the branch this example is switch to production and pull is from devops. NOT good crossing branches like this. 

> aroeber@BCM4000L62S7L32 MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (devops)
$ git checkout production
Switched to branch 'production'
Your branch is behind 'origin/production' by 11 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

aroeber@MyLaptom MINGW64 ~/Documents/Git.Folders/Puppet_Control_Repo (production)
$ git pull --all
Fetching origin
remote: Microsoft (R) Visual Studio (R) Team Services
remote: Found 4 objects to send. (5 ms)
Unpacking objects: 100% (4/4), done.
From  https://mygitremoterepo.internal/DevOps/My_Code_Repo.git
   b6325ff..c114cd8  devops     -> origin/devops
Updating 2a99050..67352bc
Fast-forward
 Somefile        | 15 ++++++++++-----
 lowerdir/initial.rb |  4 ++++
 2 files changed, 14 insertions(+), 5 deletions(-)

**Comment by sxlijin** [comment]
Hey, this is the issue tracker for the git-scm.com website, not Git itself. If you still want to discuss this issue, you should reach out to the [community](https://git-scm.com/community).
