### ISSUE TITLE
FR: git-repack should have --progress

### ISSUE THREAD

**Issue by jaredgrubb** [git/git-scm.com#913]
I am trying to run git-repack from a buildbot where git does not detect a terminal. I'd like to force repack to still show its progress. 

git-repack currently has the '-q' option, which it says it forwards to git-pack-objects. It would be nice if git-repack could also forward the '--progress' option.

**Comment by peff** [comment]
This is the issue tracker for the git-scm.com website; development for Git itself happens on the [https://git-scm.com/community](mailing list).

I do agree that `git repack --progress` is a good idea, though.

**Comment by jaredgrubb** [comment]
Ah, sorry for the noise!
