### ISSUE TITLE
Git blame can support author more stats ?

### ISSUE THREAD

**Issue by vongosling** [git/git-scm.com#916]
Hello, guys. I have requirement for git blame. As many apache projects removed author information from source code, but we want to count some author contribution for some file. Nowadays, I have to use the following shell to do it.

    git blame --line-porcelain README.md | grep  "^author " | sort | uniq -c | sort -nr

May be, it is a common thing for those people have the same  question as me. Can support it , or, am I missing something for usage :-)

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think it can enhance the git program, please, send your issue to the git mailing list git@vger.kernel.org

If you need help with using git, you can ask the [community](https://git-scm.com/community)

**Comment by vongosling** [comment]
thanks @jnavila
