### ISSUE TITLE
500 Internal Server Error on slightly strange book URL

### ISSUE THREAD

**Issue by strugee** [git/git-scm.com#922]
[This page][1] links to http://book.git-scm.com/4_git_treeishes.html, which redirects to https://git-scm.com/book/en%2FGit-Tools-Revision-Selection. The latter page returns HTTP 500.

It seems to me that there are two problems here: the weird redirect that doesn't seem to be quite right, and the 500 response.

 [1]: http://gitready.com/intermediate/2009/02/27/get-a-file-from-a-specific-revision.html

**Comment by peff** [comment]
Thanks! Both problems should be fixed by #930.
