### ISSUE TITLE
Suggestion: Mention git-gui at Linux GUIs page

### ISSUE THREAD

**Issue by RhinoDevel** [git/git-scm.com#923]
git-gui is mentioned at [Interfaces, frontends, and tools](https://git.wiki.kernel.org/index.php/InterfacesFrontendsAndTools),
but why not mentioning it at [Linux GUIs page](https://git-scm.com/download/gui/linux), too (as it is a great tool that is even distributed with Git)?

**Comment by peff** [comment]
I think the GUIs page just grew as "stuff not included in Git". I agree it makes sense to mention it there (as well as gitk, perhaps). Want to make a pull request?

**Comment by RhinoDevel** [comment]
It seems as if someone was faster than me (or both of us had problems with our eyes..): https://git-scm.com/downloads/guis ;-) Thanks!

**Comment by peff** [comment]
Heh. I think "eyes". I had to look through the page twice before I noticed. I am fine with the text as it is, but would also be OK with a more prominent mention of those tools if anybody wants to do a PR.
