### ISSUE TITLE
Incorrect book rendering

### ISSUE THREAD

**Issue by ben** [git/git-scm.com#925]
Got a report of incorrect monospacing over in the [book repo](https://github.com/progit/progit2/issues/709), apparently it looks like this:

![](https://cloud.githubusercontent.com/assets/20299/22089369/87b2d7f6-dd9f-11e6-8c93-b3d1d91f3b71.png)

Is there an Asciidoctor flag that needs to be included or left out? Those backticks should render as curly quotes, not monospace.

**Comment by drifkin** [comment]
It looks like there's a similar issue in "3.5 Git Branching - Remote Branches":

![image](https://cloud.githubusercontent.com/assets/175530/22140501/ad41f134-dea1-11e6-8d77-c946cf8e13ee.png)
