### ISSUE TITLE
VPTA

### ISSUE THREAD

**Issue by jasonjafarian** [git/git-scm.com#936]
Does git have VPTA (Voluntary Product Accessibility Template)?

Thanks,

Jason

**Comment by peff** [comment]
I don't know that anybody has done one for Git specifically. There isn't really a vendor in the traditional sense. However, GitHub has a VPAT for its various offerings at https://government.github.com/accessibility/, which mentions the command-line Git client itself (as people obviously use it to interact with GitHub).

**Comment by jasonjafarian** [comment]
Jeff,

Thank you for the quick response and information. That helped a lot.

Thanks,
Jason

**Comment by maxlazio** [comment]
Hi Jason, I'll go ahead and close this issue since you've received the answer to your question :)
