### ISSUE TITLE
fatal error when diffing changed symlinks

### ISSUE THREAD

**Issue by cricri** [git/git-scm.com#937]
with the commands below, you will get :

> fatal: bad object 0000000000000000000000000000000000000000
> show 0000000000000000000000000000000000000000: command returned error: 128
> 

I am using version 2.5.5 fedora 23

```
cd /tmp
mkdir a
cd a
git init
touch b
ln -s b c
git add .
git commit -m 'first'
touch d
rm c
ln -s d c
git difftool --dir-diff
```

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program. If you think there is a bug in the git program, please, send your issue to the git mailing list git@vger.kernel.org

If you need help with using git, you can ask the [community](https://git-scm.com/community)

**Comment by cricri** [comment]
Thanks Jean-Noël,
sorry for the error
