### ISSUE TITLE
check-ignore: wrong conclusion

### ISSUE THREAD

**Issue by albrin** [git/git-scm.com#946]
Why does the output get these directories (/temporary/import/xml/.gitkeep and /temporary/log/.gitkeep)? I exclude them in .gitignore.

I want to add this empty directories (/temporary/import/xml/ and /temporary/log/) in my git repository .

```bash
$ find -type f -or -type d | git check-ignore --stdin -v
.gitignore:4:/sitemap*.xml      ./sitemap-2.xml
.gitignore:4:/sitemap*.xml      ./sitemap.xml
.gitignore:4:/sitemap*.xml      ./sitemap-1.xml
.gitignore:1:/temporary/        ./temporary
.gitignore:1:/temporary/        ./temporary/import
.gitignore:1:/temporary/        ./temporary/import/xml
.gitignore:1:/temporary/        ./temporary/import/xml/tomsk.xml
.gitignore:1:/temporary/        ./temporary/import/xml/.gitkeep
.gitignore:1:/temporary/        ./temporary/catalog
.gitignore:1:/temporary/        ./temporary/catalog/temp.xml
.gitignore:1:/temporary/        ./temporary/log
.gitignore:1:/temporary/        ./temporary/log/mail.log
.gitignore:1:/temporary/        ./temporary/log/main.log
.gitignore:1:/temporary/        ./temporary/log/.gitkeep
.gitignore:1:/temporary/        ./temporary/log/translate.log
.gitignore:1:/temporary/        ./temporary/cache
```
My .gitignore
```bash
/temporary/
!/temporary/log/.gitkeep
!/temporary/import/xml/.gitkeep
/sitemap*.xml
```

**Comment by sxlijin** [comment]
This issue tracker is about **specifically** the [git-scm.com](https://git-scm.com) website and is **not** an issue about
     - Git (or its man pages), which should be raised with the [community](https://git-scm.com/community),
     - Git for Windows, which should be raised at [git-for-windows/git](https://git-scm.com/community), or
     - the contents of the Pro Git book, which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).

Please re-raise your issue in the appropriate forum.
