### ISSUE TITLE
Community Page Additions

### ISSUE THREAD

**Issue by schacon** [git/git-scm.com#95]
Add a couple of things:
- how to subscribe to the mailing list
- msysgit and osx installer links and information 
- libgit2 link and info

**Comment by sxlijin** [comment]
I think it's safe to say that these have been resolved :)

* [how to subscribe to the mailing list](https://git-scm.com/community)
* [msysgit and osx installer links and information](https://git-scm.com/downloads)
* [libgit2 link and info](https://git-scm.com/book/en/v2/Appendix-B%3A-Embedding-Git-in-your-Applications-Libgit2)

Marking this to be closed.
