### ISSUE TITLE
Update setup instructions on how to get book data

### ISSUE THREAD

**Issue by pedrorijo91** [git/git-scm.com#956]
On the Readme file at https://github.com/git/git-scm.com#setup there's a reference to a rake task that would fetch data from the book repository. But the repository mentioned is from the [1st edition](https://github.com/progit/progit) and not the [2nd edition](https://github.com/progit/progit2).

On the [rakefile](https://github.com/git/git-scm.com/blob/master/Rakefile) I don't find any reference to the task (but I'm not familiar with Rakefile, so it may be defined somewhere else).

* If the task no longer exist, we should update the docs on how to generate data from the book
* If the task exists, we need to check if it works for the 2nd edition
   * If it does, just update the repo link
   * else we need to update the task to work correctly and update the repo link

**Comment by jnavila** [comment]
The task is located in `/lib/tasks/book2.rake`

```console
$  rake remote_genbook2
```
 after setting up the environment variables for GitHub remote services authentication.

**Comment by pedrorijo91** [comment]
Solved by #982
