### ISSUE TITLE
Eliminate all issues with broken links

### ISSUE THREAD

**Issue by ShashankaNataraj** [git/git-scm.com#957]
How about writing an e2e test suite which can be run by devs which programmatically click all the links on the site and log all broken links? Would it bring down all the issues with broken links on this repo seeing that eliminating broken links would then be a one time process?

**Comment by Sicaine** [comment]
Probably but someone has to do it and to maintain it.

It might be easier to just track 404 errors. But for that, someone needs access to logs (anonymisised)

**Comment by jnavila** [comment]
When developing the new publishing script for progit2 books, I used linkchecker to assert that all the internal links are indeed pointing to an existing anchor.

**Comment by ShashankaNataraj** [comment]
@Sicaine Tracking 404 errors is a reactive way of dealing with the errors IMHO. I'd be willing to contribute to the e2e tests if we decide to go that way. I see this project already uses grunt. How hard could it be to just crawl the links and log 404s.

@jnavila does it have grunt integration? I found this: https://github.com/ChrisWren/grunt-link-checker

**Comment by pedrorijo91** [comment]
seems useful: https://github.com/endymion/link-checker

**Comment by pedrorijo91** [comment]
many dead links can be found using http://www.brokenlinkcheck.com/broken-links.php#status

**Comment by Lawrence4code** [comment]
I'd like to work on this, please.

**Comment by pedrorijo91** [comment]
hey @Lawrence4code :) thank you for your interest!

As you can see through the comments, we never investigated a solution for this problem. Do you already have any ideas on how to solve this? If not, we can try to brainstorm some possible implementation

**Comment by dscho** [comment]
The site now uses [lychee](https://lychee.cli.rs/) in its PR builds. This only checks the _internal_ links, though, to avoid network problems causing issues to be opened. Nevertheless, it would probably make for a fine Hacktoberfest project to run it manually _including external links_, and then to fix those.

One could start right off the bat with removing the Packtpub links, as per #1864.

**Comment by dscho** [comment]
Let's just close this, there has not been enough activity to merit keeping this ticket open.

If anybody wants to pick this up, it could be done by first copy/editing `ci.yml` to add a weekly GitHub workflow that runs lychee in _non_-`--offline` mode, to identify the currently broken _external_ links.
