### ISSUE TITLE
trademark page is hard to find

### ISSUE THREAD

**Issue by peff** [git/git-scm.com#959]
The trademark policy at https://git-scm.com/trademark is a little hard to find just navigating site links. You have to get to https://git-scm.com/about/free-and-open-source. That _is_ linked from the splash page, but in a reasonably subtle way. A more likely way is to hit the https://git-scm.com/about page. But then you have to realize that the circles are navigation elements (or click through all the way to the sixth page!).

We could probably improve this in two ways:

  1. The other sections of the site expand their subsections in the navbar, but "About" doesn't. It probably should.

  2. It's not immediately obvious that "Free and Open Source" is the right way to find out about the trademark. Perhaps the trademark should get its own mention on the navbar.

Patches welcome for either or both of those.  I'd be open to other suggestions, too.

**Comment by chotuaashiq** [comment]
@peff @pedrorijo91 Can you guide me how to solve the issue.

**Comment by pedrorijo91** [comment]
Hey @chotuaashiq !

Thanks a lot for your enthusiasm in contributing :)

So, using the suggestions by @peff I would say :

1. you should start by adding the capability of expanding the 'About' section on the navbar. This seems to be defined at `app/views/shared/_sidebar.html.erb`

2. extracting the trademark page for it's own sub section on the nav bar should be about adding a new entry to the previous step

3. You should think if we should add a new 'circle' menu item with the trademark page at the (https://git-scm.com/about/free-and-open-source) 

These are just a few general hints (I wanted to give you some space to explore), but if you need any more details we can help you :)

**Comment by pedrorijo91** [comment]
@chotuaashiq how's that going? Do you need any more guidance? let us know if you need anything :)

**Comment by chotuaashiq** [comment]
@pedrorijo91 Still I am unable to figure out how to do this. Can you help?

**Comment by pedrorijo91** [comment]
sure. just tell me a bit what have you tried, and what problems/doubts are you facing?

1.

 you should try to setup the application locally as described under https://github.com/git/git-scm.com#setup. Have you done this step?

2. 

you should have a look at the file https://github.com/git/git-scm.com/blob/master/app/views/shared/_sidebar.html.erb. 

If you look at https://git-scm.com/doc and https://git-scm.com/about, you'll see  the doc section expands, and the about no, right?

looking at the https://github.com/git/git-scm.com/blob/master/app/views/shared/_sidebar.html.erb you can see the `/doc` section has nested elements inside, while the `/about` section doesn't. So you probably need to add nested elements to the `about` section also

**Comment by sxlijin** [comment]
Mildly more concerning: why doesn't the trademark page show up when you search for "trademark"?

https://git-scm.com/search/results?search=trademark

**Comment by sxlijin** [comment]
I'm not sure we want an explicit section on the About page for this.

On the home page, the About page is described with the following tagline: "The advantages of Git compared to other source control systems."

Glancing at some other OSS projects:

* Django [sticks their trademark link in the fine print in the footer](https://www.djangoproject.com/start/overview/),
* Mercurial doesn't seem to do anything except [link the GPL v2 license in the footer](https://www.mercurial-scm.org/),
* React literally doesn't even have a trademark usage page (there's a mention in the TOS on their forums site) - I'm not sure how conscious a decision that was for them, but given the legal controversy they went through I can't imagine someone never asked the question,
* Node [also sticks their trademark link in the footer fine print](https://nodejs.org/en/), and
* Mozilla [links to the CC license in their footer](https://www.mozilla.org/en-US/).

From this alone I'm inclined to suggest simply either leaving it as is or adding a link in the footer.

**Comment by pedrorijo91** [comment]
@sxlijin I understand your point. We could follow a similar approach of having the trademark linked on the footer. I can live with both solutions. But the solution on #1092 doesn't seem bad to me also. Besides that, after so much work, I think it would be a nice reward the author (a 1st time contributor), to see his changes going live.

**Comment by pedrorijo91** [comment]
thinking about closing this issue since #1092 is already merged. If someone wants to revisit this, and possibly go for the solution of having the trademark in the footer, we can reopen it

**Comment by peff** [comment]
> why doesn't the trademark page show up when you search for "trademark"?

Because we only index the book and manpages, not the static content. That's probably fixable by adding a new rule to `lib/tasks/search.rake`, but we'd have to figure out the right incantation to feed the data to the indexer.

**Comment by pedrorijo91** [comment]
maybe it's worth to create an issue to investigate indexing static content (trademark and other relevant pages)  @peff  ?

**Comment by peff** [comment]
@pedrorijo91 Sure. I'm not planning to work on it myself, but somebody might want to pick it up. Opened https://github.com/git/git-scm.com/issues/1109.
