### ISSUE TITLE
Support Git-Scm with french translation

### ISSUE THREAD

**Issue by AmauryVanEspen** [git/git-scm.com#961]
Hi,

I would like to support Git-Scm with french translation.
Would you be kind to let me know if you are interested in,
then, if you would be kind to setup an language files system.

best

Amaury

**Comment by jnavila** [comment]
Bonjour Amaury,

Je m'occupe de la traduction de git et de progit en français. Pour l'instant, malheureusement, git-scm.com n'est pas prévu pour supporter la localisation dans d'autres langues.

Maintenant, la question est : qu'est-ce qui t'intéresserait de traduire en français sur le site git-scm.com ?

**Comment by AmauryVanEspen** [comment]
Bonjour Jean-Noel,

je vex bien que l'on fasse un point sur l'étendu et le périmètre à couvrir
ainsi que la récurrence des actions,
oui sur le principe, je suis intéressé,
aussi, je souhaiterai savoir quel outil est employé.
je crois que Git, formidale outil, encore trop peu connu du grand public,
aurait tout intérêt à être plus accessible pour les non-initiés, et donc
d'être à minima dans leur langue =)
D'autant que les GUI semblent légion =)
Bien à toi
Amaury





2017-02-18 18:23 GMT+01:00 Jean-Noël Avila <notifications@github.com>:

**Comment by jnavila** [comment]
Alors, de tête, ce que je vois à couvrir : 

 * Les outils graphiques associés à git, tels que gitk et git-gui. Je ne les suis pas en direct. Ils sont rattachés à git, mais pas gérés ensemble, ce qui s'avère assez lourd à intégrer.
 * les pages de manuel (qui font partie du projet git), alors je pense qu'il faudra s'adresser au projet git directement, même si le travail de traduction proprement dit peut prendre place dans un dépôt sur github. Il faudra tout de même suivre le formalisme du projet git pour soumettre les modifications. C'est un très gros morceau.
 * Le contenu original du site git-scm. Comme je l'ai dit, ce n'est pas prévu pour être traduit. J'avoue de plus ne pas voir grand intérêt car certains contenus resteront en anglais : films, infographies, etc.

À quoi pensais-tu plus précisément ?

**Comment by AmauryVanEspen** [comment]
Bonjour Jean-Noel,

cela couvre déjà une bonne partie de ma question,
pourrais tu m'éclairer sur les Gui et le processus ? (pourquoi lourd à
intégrer ?)
Ok pour le manuel, je n'estime pas vraiment le volume, mais petit à petit
on avancera
pour le contenu de git-scm, étrangement je crois qu'il serait nécessaire de
les traduire

peux tu m'indiquer le périmètre que tu couvres actuellement et si vous
utilisez une interface ? (transifex ? weblate ou tout autre outil ?)
A défaut, s'il est envisageable de mettre en place une "organisation" et
une "équipe" sur ces outils pour démarrer la traduction

Merci


2017-02-18 18:34 GMT+01:00 Jean-Noël Avila <notifications@github.com>:

**Comment by jnavila** [comment]
## dans la catégorie existant

Actuellement, je n'utilise aucun outil en ligne de traduction. Pour le livre Progit, un fork du projet anglais et la traduction en lieu et place simplement. C'est simple pour permettre la soumission de corrections par d'autres lecteurs, car c'est de l'asciidoc et ne nécessite pas d'outil spécial. Ça rend le suivi de mises à jour du livre d'origine plus compliqué. Pour git lui-même, l'infrastructure d'internationalisation est gettext et je modifie le fichier po/fr.po avec un éditeur de fichier po (dans mon cas, Emacs mais je ne suis pas sectaire).

## Dans la catégorie à faire

Les deux GUIs livrés d'origine avec git sont : 

 * `gitk` : un outil pour visiter et gérer un dépôt git. Bien que l'intégration se fasse dans le dépôt de git, le dépôt principal sur lequel les modifications sont proposées est git://ozlabs.org/~paulus/gitk, même si les patchs doivent être envoyés sur la liste de diffusion de git...
 * `git-gui` : un outil qui remplace en partie le ligne de commande pour valider des commits. Même combat : intégré au sein du projet git mais géré sur git://repo.or.cz/git-gui . Il est déjà traduit en français, mais les traductions ne correspondent pas au glossaire que j'utilise pour git et le livre progit.

Les pages de manuel n'ont aucune traduction à ce jour. Il n'y a donc aucune structure pour gérer plusieurs langues. Ce sont des 562 fichiers asciidoc (86814 lignes) qui subissent une transformation vers TEXI (le format des pages de manuel), PDF ou HTML. En plus de la traduction, il faudrait ajouter la modification de la compilation pour gérer plusieurs langues.

Tout ce qui précède est géré au sein du projet Git. Cela signifie qu'il faut en passer par la gestion de projet par messages de patch sur la liste de diffusion. On peut tout à fait gérer les traductions à l'extérieur du projet (pourquoi pas weblate), mais l'intégration en amont se fera forcément via ce canal (que je maîtrise déjà).

## Le cas du site web

Je m'interroge sur ce que tu conçois comme faisant partie du site web git-scm.com, et qui aurait besoin d'une traduction. Veux-tu parler du fond du site (menu, textes statiques), des entrées de Blog ou d'autre chose ? Si par exemple, ce sont les pages de manuel, la traduction devra en premier lieu se faire directement dans le projet git, avant une modification du moteur du site pour intégrer les différentes traductions du manuel.

**Comment by AmauryVanEspen** [comment]
Bonjour Jean Noel,

Gestion externe : (transifex)
voici ce que j'ai pu trouver sur transifex :
https://www.transifex.com/git-extensions/
mais il y a d'autres dépôts sur transifex :
https://www.transifex.com/explore/projects/?search=git
j'attend un retour des mainteneurs.

A faire :
pourrais tu me donner les liens pour regarder ce que je peux faire, (sur le
Gui notamment)
je ne connais pas gettext,
le lien vers gitk est en 404
je ne comprend pas par où commencer pour git-gui (par exemple où trouver
ton glossaire, que faire pour comparer ?)

Compte transifex ? ou installation de weblate ?
ok pour gérer "à l'exterieur", et ne pas m'impliquer sur la liste de
diffusion que tu maitrises =)

Siteweb :
pour le siteweb, (pas les articles de blogs) mais en effet, déjà le site,
menu, texte et statique (éventuellement les schémas et graph)

Bien à toi

Amaury



2017-02-19 17:47 GMT+01:00 Jean-Noël Avila <notifications@github.com>:

**Comment by jnavila** [comment]
As-tu reçu mon mail ?

**Comment by pedrorijo91** [comment]
@jnavila i think that if this discussion was in english it could help other contributors who would have similar intentions in the future. Or at least a short summary at the end?

**Comment by AmauryVanEspen** [comment]
Bonsoir Jean Noel,
j'ai reçu ton email,
oui il est possible de continuer en anglais,
je dois m'absenter quelques jours,
on peut démarer un dépot commun et commencer par où il te semblera bon =)
j'aimerais faire une première séance avec toi, pour m'approprier et le
glossaire et les points clés (structures, langage etc ...)
A te lire

Amaury

**Comment by jnavila** [comment]
@pedrorijo91 OK, we switched off line for easier conversation on broader subject. But we can continue online in English for Git. The discussion was about what would be useful/necessary to translate in the git project in general to help people who do not speak english. My short list is:

 * better translation support for gui tools : git-gui and gitk
 * translation of the git-scm.com website 
 * translation of manual pages, which could benefit to git-scm also

The last two part would need a change in the architecture of the website. I don't know much of the capabilities of Ruby on Rails, and if the site is supposed to migrate to static pages, how this can be dealt with for easy access for visitors, easy maintenance of the site, easy way for contributors to translations. Another point would how to keep the interaction with the git mailing-list simple and whether there would be a dedicated centralization of translations that would be a single point of interaction with the git development teams, just like for localization of git itself.

Then there was the question of how to set this up. Simple repo, use online tools such as transifex or weblate, translate in place or use translation tools.

Of course, the solution can be different depending on the artefact, it can even be different according to languages.

**Comment by jnavila** [comment]
Things are going on: I started with the man pages which are part of the git project. The setup of a translation framework and a first request for comment on the git mailing-list.

**Comment by sxlijin** [comment]
[Discussion thread here.](http://public-inbox.org/git/xmqq1su2ujsf.fsf@gitster.mtv.corp.google.com/T/#t)

**Comment by sxlijin** [comment]
Just noticed #365 - you might find that to be of interest.

**Comment by AmauryVanEspen** [comment]
Hello Jean-Noel,

Happy to read you about this subject,
would you be kind to let me know how to support and contribute ?

Best

Amaury

**Comment by jnavila** [comment]
For the moment, there's some discussions as to how this can be integrated. So, it's difficult to provide a definite way to contribute. 

I'll keep you informed, hopefully soon.

**Comment by pedrorijo91** [comment]
It seems the french version is already available at https://git-scm.com/book/fr/v2. Can you confirm (and close this issue if true) this is true? @jnavila

**Comment by jnavila** [comment]
The issue was dealing with the translation of the other parts of the website: the git manpages and the website itself. I tried to start something on that but didn't do much in the end.

**Comment by jnavila** [comment]
Hi all,

I'm trying to revive the project with a different setup. You can find the translation project going on here:

https://github.com/jnavila/git-manpages-l10n

It is base on po files, which you can edit with poedit. Otherwise, you can translate in a web browser at

https://hosted.weblate.org/projects/git-manpages/translations/

With this setup, the translation is opened to other languages too!

**Comment by dscho** [comment]
Let's just close this, there has been quite a lot of work on the translated manual pages as well as on the ProGit book. Even if the _full_ extent of the original request has not been addressed (apart from the manual pages and the book, no pages are translated into languages other than English), it would seem too big of a project, seeing as there has been no movement on this in almost 6 years.
