### ISSUE TITLE
Can a few screenshots or direction for completing an interactive rebase be added?

### ISSUE THREAD

**Issue by StingyJack** [git/git-scm.com#962]
- [x ] This issue is about **specifically** the [git-scm.com](https://git-scm.com) website and is **not** an issue about
     - [ ] Git (or its man pages), which should be raised with the [community](https://git-scm.com/community),
     - [ ] Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git), or
     - [ ] the contents of the Pro Git book, which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).

The section for [interactive mode](https://git-scm.com/docs/git-rebase#_interactive_mode) omits the last part where a commit message needs to be entered. I get a screen that says here are the  commit messages and lists the files, but no obvious place or direction as to where (or how) the new commit message should or can be entered.  

I think a bit of instructive text or a screenshot would really help git noobs (me) avoid panic or frustration when trying to work with an unfamiliar tool.

**Comment by jnavila** [comment]
This issue tracker is dedicated to the git-scm.com website.

The issue you have raised is related to the git program and its manual pages. If you think there is a bug in this, please, send your issue to the git mailing list git@vger.kernel.org

If you need help with using git, you can ask the [community](https://git-scm.com/community)

**Comment by StingyJack** [comment]
The page i was on linked here

**Comment by peff** [comment]
Right, but all of the pages under docs/ are a wholesale mirror of manpages from the upstream project. So any changes have to go there first, and then they get pulled in automatically to the site.

**Comment by StingyJack** [comment]
Got it. This is for problems with the host platform and not for the content. I came here from google trying to find an example of where to type the commit message for an interactive squash, and saw the link at the bottom and was on  "...the _git-scm.com website_".  

You may want to consider a reworded issue template, because I'm sure there are many idiots like myself who make the same assumption or don't know what a "man" page is (or that some pages are a mirror) that have been bugging you needlessly

**Comment by peff** [comment]
Thanks for the suggestion. We definitely have had problems with people reporting upstream git problems, and the issue template is new-ish to deal with that. I agree it might be worth clarifying which content comes from where based on URLs on the site, which is what people actually see.

/cc @sxlijin

**Comment by pedrorijo91** [comment]
@peff just to clarify, which "sources" does the website contains?

- the book (https://git-scm.com/book/en/v2)
- the man pages (https://git-scm.com/docs)
- website content itself

and any other?

**Comment by peff** [comment]
@pedrorijo91 I think that covers it. The book content is actually all of `/book`, really.
