### ISSUE TITLE
Link to old version of Pro Git still exists

### ISSUE THREAD

**Issue by sxlijin** [git/git-scm.com#964]
On the [documentation page](https://git-scm.com/doc), if you click "Book information and downloads" in the Book section, you get pointed to what I can only assume is [Pro Git v1](https://github.s3.amazonaws.com/media/progit.en.pdf) (image taken from https://git-scm.com/images/pro-git-298x398.jpg):

![image](https://cloud.githubusercontent.com/assets/512410/23099101/8beebf5e-f624-11e6-9f5c-2a9e9351df5b.png)

The issue is in the [`doc/index.html.erb` view](https://github.com/git/git-scm.com/blob/805d1d7bc432bb403f3ae20f6386a502dcbbffac/app/views/doc/index.html.erb#L32-L98); unfortunately I've had been busy lately and still haven't gotten around to setting up my local env to build the website.

The [`doc/book.html.erb` view](https://github.com/git/git-scm.com/blob/805d1d7bc432bb403f3ae20f6386a502dcbbffac/app/views/doc/book.html.erb) may be of interest to whoever decides to take this up.

cc @peff @jnavila

**Comment by sxlijin** [comment]
The [SCSS](https://github.com/git/git-scm.com/blob/805d1d7bc432bb403f3ae20f6386a502dcbbffac/app/assets/stylesheets/book.scss#L85) that brings the cover as a background-image will also need to be fixed.

**Comment by jnavila** [comment]
Doh! I wasn't even aware of this link and the associated animation!

**Comment by jnavila** [comment]
Well thinking back, even the proposed patch is only part of the story, because the links in the text are outdated. Gosh, this site is full of copies of lists of links... :sob:

**Comment by peff** [comment]
As nifty as that little put-the-information-inside-the-picture-of-the-book thing is, maybe the sensible thing would be to have that link just send people to `/book`? It has all of the same information, plus an expanded table of contents so you can start reading immediately.

**Comment by jnavila** [comment]
OK, I can change the URL pointed by link, but I have no idea what could be stripped from the different files when this feature is removed.

**Comment by peff** [comment]
Hmm. I actually think the whole `book-container` div could go away in favor of just having a short blurb about the book and a link to the main `/book` page. And then all of `FlippyBook` in `site.js` could go away, too. It's cute, I guess, but I don't think it's helping the usability of the page.

(And I didn't even realize there was an animation because it doesn't do anything in Firefox.)
