### ISSUE TITLE
Please update the outdated information

### ISSUE THREAD

**Issue by Explorare** [git/git-scm.com#978]
For https://git-scm.com/book/gr/v2/Git-Tools-Credential-Storage

>If you’re using Windows, you can install a helper called “winstore.” This is similar to the “osxkeychain” helper described above, but uses the Windows Credential Store to control sensitive information. It can be found at https://gitcredentialstore.codeplex.com.

The project "Windows Credential Store" is no longer maintained and has been replaced by [Microsoft/Git-Credential-Manager-for-Windows: Secure Git credential storage for Windows.](https://github.com/Microsoft/Git-Credential-Manager-for-Windows).

**Comment by pedrorijo91** [comment]
Hey @Explorare, thanks for the info! Nevertheless, the content you refer to, is extracted from the [progit/progit2](https://github.com/progit/progit2/issues) repository. Could you raise the issue there? 

This repository aggregates info from several sources. To better understand to which source the content refers to, you can start by having a look at our [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md) at let us know if you need any help

**Comment by Explorare** [comment]
@pedrorijo91 Oh, sorry for this. I've read the template but still made the mistake :)
Please close this issue. Sry for bothering you.
