### ISSUE TITLE
git-scm.com is now served via cloudflare

### ISSUE THREAD

**Issue by peff** [git/git-scm.com#980]
Since yesterday morning, all git-scm.com traffic has been served through Cloudflare. I set this up to try to relieve some of the load on the Heroku setup, and also because it increases our flexibility for hosting the backend (e.g., if we do switch to a GH Pages site, then we'd probably need some kind of CDN in front of it anyway, at the very least for custom-domain SSL). The folks at Cloudflare were kind enough to give us a complimentary Business domain, so we shouldn't run into any limitations on scale or features.

Here's what it looks like from Cloudflare's side:

![cloudflare](https://cloud.githubusercontent.com/assets/45925/23789631/a7b75fdc-0549-11e7-8037-723e0a905453.png)

Unsurprisingly (since it's a static site), the vast majority of requests are served out of cache.

On the Heroku side, you can see the drop in requests as the caches filled (the cut-over was at Thursday ~1am):

![throughput](https://cloud.githubusercontent.com/assets/45925/23789752/339c5728-054a-11e7-993a-4b553f14f5aa.png)

The response time on Heroku jumped, but I think it's an artifact of the measurement. The 95th percentile went up because all of the _easy_ requests are now served from Cloudflare, so the long requests are a much larger fraction. Here's the graph:

![response-time](https://cloud.githubusercontent.com/assets/45925/23789869/a728c2f8-054a-11e7-9891-f5e689906cff.png)

I was hoping that the dyno load on Heroku would lower, but I don't see a meaningful drop:

![dyno-load](https://cloud.githubusercontent.com/assets/45925/23789892/c99faa90-054a-11e7-83d1-670672839630.png)

So my hypothesis is that the "easy" requests were already being served pretty quickly due to mem-caching on the Heroku side. If we're going to stick with a Rails app, there's probably some optimization that can be done. I played around with the Scout add-on, and it identified some N+1 queries that resulted in slow renderings (e.g., separate queries to load the section slugs for each book chapter). I don't have a lot of ActiveRecord experience, but my impression is that some well-placed `includes()` should make these go away.

As for the Cloudflare setup, it's fairly vanilla. I'm using one of their universal certs for the SSL now. That means that clients need to support SNI to connect that way. But it was the same on Heroku. We do have a cert for git-scm.com that's good through the end of the year. But if nobody is complaining about SNI, it seems easier to just stick with what's there.

If there are other Cloudflare settings that people think ought to be tweaked, let me know.

**Comment by jnavila** [comment]
So what's left that is served without caching by CloudFlare? The HTML content? It seems that caching should also be active for most of the doc content (46c62fa).

**Comment by sxlijin** [comment]
Do ES queries hit the CF caches?

**Comment by peff** [comment]
Everything goes through the CF caches, and it decides what to cache. I think its rules are by file-extension, and it doesn't cache the HTML by default. That would explain the hit-rates I'm seeing on Heroku, which are roughly proportional to the unique-visitors count (so somebody hits an HTML page, and that goes to Heroku but the rest of the assets are served statically).

I just tweaked the settings a bit to try to cache everything. I'll see what that does.

The ES queries should go be going through CF, too, though I suspect they were mostly not-cached until the tweak I just did. They should be OK cached because CF respects the query strings. I don't think search requests make up a large portion of the requests, though.

**Comment by jnavila** [comment]
At least, now, the header for the html content are:

```
Cache-Control: public, max-age:14400
```

So the caching at the end point (the browser) is activated. But, I guess that CF can use such header because the internal policy is identical. So, this boils down to comparing the number of requests concerning HTML that reach Heroku to the one at CF. If they are still the same, then the caching is not active in CF, but only in the browsers.

**Comment by peff** [comment]
The cache-control you're seeing comes from CF. The one from heroku is only 600 seconds, but I've instructed CF to use a blanket 1-hour ttl.

If you want to hit the heroku servers directly, you can do something like (or just stick an entry in your /etc/hosts for one of the heroku IPs that the herokudns name resolves to).

```
curl -v --connect-to git-scm.com:443:git-scm.com.herokudns.com:443 https://git-scm.com
```

**Comment by peff** [comment]
The other thing you can check is the "CF" headers when the request goes through Cloudflare. So for example:

```
$ curl -v https://git-scm.com 2>&1 >/dev/null | grep CF-
< CF-Cache-Status: HIT
< CF-RAY: 33df0e1459a0576b-IAD
```

show that it was served out of cache.

**Comment by peff** [comment]
It's been about 26 hours since I flipped the "cache everything" switch on Cloudflare. Here's what it looks like from Heroku's side:

![throughput](https://cloud.githubusercontent.com/assets/45925/23831599/429ba67c-06fb-11e7-84ca-5d3ae42f9f3c.png)

The switch close the v501 deploy (the deploy didn't do it; that just happened to be when I was working on the site yesterday morning). The requests drop off naturally on the weekend, as you can see, but they shrink quite a bit more after the deploy.

Here's the dyno load during the corresponding period:

![dyno-load](https://cloud.githubusercontent.com/assets/45925/23831612/77063670-06fb-11e7-987d-46e7aa871bda.png)

So those look pretty promising. I've scaled back to a single dyno for now (from three), and I'll keep an eye on it over the course of today (Sunday) to make sure it is keeping up with load. And then the real test will be how it behaves on a weekday.

**Comment by peff** [comment]
This has been scaled back to one dyno for the past week. It seems fine, I think. That dyno stays reasonably busy, and the 95th percentile response times at Heroku sometimes hit a few hundred milliseconds. But those are a tiny fraction of all requests, as cloudflare is handling 95% of the requests straight from cache already, so it's effectively 99.75th percentile.

So I think I'll leave it like this indefinitely. I'm going to close this issue. There was never really any task to accomplish; I mostly just wanted to let people know of the ongoing experiments. I'll make a post to the mailing list, too, but there are a few other loose ends I want to tie up first.
