### ISSUE TITLE
file names are considered case insensitive in same folder.

### ISSUE THREAD

**Issue by vishy16** [git/git-scm.com#988]
- [ ] Git 2.10.1 on Apple mac is treating different(uppercase/lowercase) files as same name(e.g ABCD.py and abcd.py)
     -  In a project where file name is same but case is different, either ABCD.py or abcd.py. There is always one of these files is modified.
     - Below is the git version on my mac.
     `snappy:myproject$ git version`
     `git version 2.10.1 (Apple Git-78)`

     - Where as git 2.7.4 on Linux Ubuntu xenial is treating ABCD.py and abcd.py as different files.

> To reproduce the issue on mac. Clone a project that has two files in same directory with same name but different case. ClassTest.py and classtest.py

**Comment by pedrorijo91** [comment]
Hey @vishy16,

The issue you are reporting seems to be related with git itself. This repository (and its issue tracker) is for the website and its content. For more details on issues that fit on this issue tracker, have a look at the [issue template](https://github.com/git/git-scm.com/blob/master/.github/ISSUE_TEMPLATE.md)

I recommend you to report this problem with the [community](https://git-scm.com/community).

Also, I think it's possible that it's a file system behaviour, and git is not responsible for that, but it's better to confirm with the community, as I said previously.

**Comment by vishy16** [comment]
Thanks Pedro, I did it in hurry. I will open the issue with community. closing this one.
