### ISSUE TITLE
Documentation from Documentation/technical/ not hosted

### ISSUE THREAD

**Issue by sxlijin** [git/git-scm.com#994]
The Git man pages make occasional references to information in [`technical/`](https://github.com/git/git/tree/master/Documentation/technical); however, this documentation is not hosted anywhere on the site, so the link 302's to the home page for the docs.

[kernel.org](https://www.kernel.org/pub/software/scm/git/docs/technical/) does host them FWIW.

@peff thoughts?

**Comment by peff** [comment]
In ye olden days when git-scm.com was first written, the pages in `technical/` did not even build to HTML. And since there's so rarely referenced by the main documentation, nobody ever noticed or added it. I suspect it would just need some tweaks to the rake task that pulls in the pages. Patches definitely welcome.

**Comment by jnavila** [comment]
@sxlijin Can you point to where the 302 happens?

**Comment by sxlijin** [comment]
@jnavila see #512

```
$ curl -is http://git-scm.com/docs/technical/api-credentials.html | head -n 1
HTTP/1.1 301 Moved Permanently
```

**Comment by peff** [comment]
The 301 is to redirect you to https, and then you get the 302 (curl doesn't follow the redirects by default, but if you add in `-L` you can see it switching to HTTP/2. Neat!).

I'm not sure about the 307. It's obviously accomplishing the same thng, but it's interesting that the server generates a different code. This is all Cloudflare, so they may tailor the response based on user-agent sniffing.

Anyway, that's all orthogonal to the actual problem that we don't import the `technical/` docs.
