### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by elisokal** [git/git-scm.com#995]
Hello. I would like to know where I can learn about the git documentation conventions. In particular, the diff page at https://git-scm.com/docs/git-diff uses \<commit\> its syntax description. But I am unable to find a document that explains what forms \<commit\> can take. I had to go to stackoverflow to learn that \<commit\> can be a branch name. Thanks in advance to point me at that documentation!

**Comment by sxlijin** [comment]
Hey, so this isn't the right place for this. As the issue template says, this repo is **not** for issues about

     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).

That being said, it sounds like you want something like `gitglossary(7)`.
