### ISSUE TITLE
Git.exe crashes on WinSshFs - unhandled exception

### ISSUE THREAD

**Issue by ambrt** [git/git-scm.com#996]
Hello

I'm running a guest  VMWare Workstation with Ubuntu Linux on Windows 10 host.
To edit files inside of guest  i use [WinSshFs](https://github.com/Foreveryone-cz/win-sshfs/) application [v1.6.0.14](https://github.com/Foreveryone-cz/win-sshfs/releases/download/1.6.1/previous.release-1.6.0-rc3.zip).
The files are shown correctly in new drive and i can edit them.

The problem is when i try to run hosts Windows Git (ie. git status) on folder that is inside guest git crashes with debug info:
`An unhandled win32 exception occurred in git.exe`

After that error text different numbers occur like  [18104] , [3760],[14748] etc (not sure what they are).

For projects that are on Windows host drive same installation of git works correctly.

**Comment by sxlijin** [comment]
This is not where issues re Git for Windows should be raised.

Did you not read the issue template?

- [ ] This is **not** an issue about 
     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).
