### ISSUE TITLE
 Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped

### ISSUE THREAD

**Issue by sakufo** [git/git-scm.com#997]
Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped
How does this tip suggest? How do I reset the "MAX_RECORD_SIZE" value?

thank you very much!

**Comment by sxlijin** [comment]
Hi - this is not the right place to ask this. It's also very unclear what you're asking about.

Please read the issue template that you ignored:

- [ ] This is **not** an issue about 
     - the Git documentation (a.k.a. man/help pages, i.e. anything with a URL starting with `https://git-scm.com/docs`), which should be raised with the [community](https://git-scm.com/community),
     - the contents of the Pro Git book (i.e. anything with a URL starting with `https://git-scm.com/book` or its PDF versions), which should be raised at [progit/progit2](https://github.com/progit/progit2/issues).
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or
     - Git for Windows, which should be raised at [git-for-windows/git](https://github.com/git-for-windows/git).
     - and is actually about the website itself (e.g. website-specific content, JS, or CSS that doesn't seem to be doing its job correctly).
