### ISSUE TITLE
Bug report: Git Stash; spelling mistake of stash followed by a yes prints character 'y' infinite times.

### ISSUE THREAD

**Issue by rpai1** [git/git-scm.com#999]
Hi,
I am a corporate user of git. I noticed that when you switch between the branches and do a git stash ( I miss spelled it as git stahs). Git asked if i meant git stash. and i entered yes. and git printed the character y infinite times.

Below are the steps to reproduce.
1. create a local branch and make some code changes in the same branch.
2. now checkout another branch. git says Your local changes to the following files would be overwritten by checkout.
3. Now do git stahs ( spelling mistake )
4. Now git says git: 'stahs' is not a git command. See 'git --help'.
Did you mean this?

stash

5. Now types yes. and you will see character 'y' getting printed infinite times!.

Though this is not a major bug, I thought notifying this would be a good idea. The above mentioned issue is reproducible in Mac Yosemite in git version 2.4.5

**Comment by tgummerer** [comment]
Before opening an issue, please read the issue template next time.  Specifically:

- [ ] This is **not** an issue about 
[...]
     - Git itself, which should also be raised with the [community](https://git-scm.com/community), or

**Comment by jnavila** [comment]
Just to help you:

The question was not meant to request an answer from you. It was more an help with respect to spelling mistakes. Obviously, you did not interpret as that, which could be described as (yet another) user interface bug in Git suite.

As for the "y", when you replied with "yes", in fact you invoked the command "yes" that prints "y"s on the lines and is used in pipes to autoreply questions of other commandes, e.g.

```shell
 $ yes | rm a_file
```
 use `man yes` for further information.
